import {nativeAuthorshipDisclosure} from './proceduralStageAuthoring';
import {captureAuthoredControls} from './proceduralAuthoringControls';
import {installStageAuthoredDriverEditor,type StageAuthoredDriverHost,type NativeAuthoredDriverIntent,type StageAuthoredDriverObservation} from './proceduralStageAuthoredDrivers';
import {installStageLifecycleEditor,type NativeLifecycleIntent,type StageLifecycleObservation} from './proceduralStageLifecycle';
import {installStageDriverEditor,type StageDriverEditorIntent} from './proceduralStageDrivers';
import {installStageConstructionEditor,validateSceneOutputs,validateSequenceHolds,retainedMaterialChoice} from './proceduralStageConstruction';
import {installStageBootstrapEditor} from './proceduralStageBootstrapEditor';
import {isStageBootstrapRefusalObservation,type StageSourceBootstrapIntent,type StageSourceBootstrapOutcome} from './proceduralStageBootstrap';
/** Normal application Stage surface. The existing Studio owns target scope,
 * native operation review, scalar authoring, scene flow and restoration. This
 * extension owns DOM/form intent only; all source/compiler/conduct calls reach
 * that same serialized native Workspace. There is no runtime/store/timer here. */
import {clone} from './model';
import {installProceduralStudio,studioBasis,addressLabel,type ProceduralStudio,type ProceduralStudioHost,type StudioSnapshot,type ProcedurePreview} from './proceduralStudio';
import {sameNative,type Scope,type Operation} from './proceduralProtocol';
import {retention,type SourceBasis} from './proceduralRetention';
import {retainedProcedureAuthorship,validateProcedureAuthorship,stageForceParameters,stageForceChoice,stageForceCommandTarget,stageAtlasCommandTarget,type NativeSceneSource,type StageSourceReading,type StageLibrary,type StageLibraryIntent,type ProcedureAuthorship,type LibraryChoice,type NativeLibraryDescriptor} from './proceduralStageSource';
import {type StagePreparation,createProceduralStageProvider,type StageWorkspacePort,type ProceduralStageProvider,type StageRuntimeIntent,type StageRuntimeResult} from './proceduralStageProvider';

export interface ProceduralStageHost extends ProceduralStudioHost {workspace:StageWorkspacePort;openDriverEditor?:(intent:StageDriverEditorIntent)=>Promise<void>;authoredDrivers?:Omit<StageAuthoredDriverHost,'snapshot'|'scope'|'report'>;}
export interface ProceduralStage extends ProceduralStudio {
 readonly provider:ProceduralStageProvider;
 acceptPrepared(operation:Operation):Promise<void>;
 /** Original typed form intent only; native issuer/journal remains authority. */
 retainedPreparation():StageLibraryIntent|null;
 /** Agent and human callers use these exact typed routes, not DOM actions. */
 prepareLibrary(intent:StageLibraryIntent):Promise<StagePreparation>;
 conduct(intent:StageRuntimeIntent):Promise<StageRuntimeResult>;
 bootstrapSource(intent:StageSourceBootstrapIntent):Promise<StageSourceBootstrapOutcome>;
 retainedSourceIntent():StageSourceBootstrapIntent|null;
 lifecycle(intent:NativeLifecycleIntent):Promise<StageLifecycleObservation>;
 retainedLifecycleIntent():NativeLifecycleIntent|null;
 authoredDriver(intent:NativeAuthoredDriverIntent):Promise<StageAuthoredDriverObservation>;
 retryAuthoredDriver():Promise<StageAuthoredDriverObservation>;
 retainedAuthoredDriver():NativeAuthoredDriverIntent|null;
}
function el<K extends keyof HTMLElementTagNameMap>(tag:K,text?:string):HTMLElementTagNameMap[K]{const result=document.createElement(tag);if(text!==undefined)result.textContent=text;return result;}
function note(text:string){const result=el('p',text);result.className='control-note';return result;}
function label(text:string,input:HTMLElement){const result=el('label');result.className='control';result.append(el('span',text),input);return result;}
function section(title:string){const root=el('details');root.open=true;const content=el('div');root.append(el('summary',title),content);return {root,content};}
function select(title:string){const result=el('select');result.setAttribute('aria-label',title);return result;}
function input(title:string,type='text'){const result=el('input');result.type=type;result.setAttribute('aria-label',title);if(type==='number')result.step='any';return result;}
function options(element:HTMLSelectElement,rows:readonly (readonly [string,string])[],empty:string){const value=element.value;const next=[['',empty] as const,...rows];if(element.options.length!==next.length||[...element.options].some((o,i)=>o.value!==next[i][0]||o.textContent!==next[i][1]))element.replaceChildren(...next.map(([v,t])=>{const option=el('option',t);option.value=v;return option;}));if(next.some(([v])=>v===value))element.value=value;}
function enums(title:string,rows:readonly string[]){const result=select(title);options(result,rows.map(value=>[value,value.replaceAll('_',' ')]),'Choose explicitly');return result;}
function text(value:unknown):string {if(value===null)return 'none';if(typeof value==='string'||typeof value==='number'||typeof value==='boolean')return String(value);if(Array.isArray(value))return value.map(text).join(' · ');if(value&&typeof value==='object')return Object.entries(value).map(([key,item])=>`${key.replaceAll('_',' ')}: ${text(item)}`).join('; ');return 'unavailable';}
const mint=()=>`operation:stage-${crypto.randomUUID()}`;
const TRIGGERS=['state_changed','musical_gesture','physical_gesture','source_changed','scene_entered','scene_left','sequence_transition','explicit'] as const;
const BUDGETS=[['max_evaluations',4096],['max_operations',4096],['max_expansion_depth',64],['max_active_instances',2048],['max_queue',4096]] as const;

export function installProceduralStage(host:ProceduralStageHost):ProceduralStage {
 const provider=createProceduralStageProvider(host.workspace);
 let disposed=false,active=false,busy=false,readGeneration=0,scope:Scope|null=null,sourceReading:StageSourceReading|null=null,sceneSource:NativeSceneSource|null=null,sourceProfile:SourceBasis|null=null,library:StageLibrary|null=null,authored:ProcedureAuthorship|null=null,draftBasis:ReturnType<typeof studioBasis>|null=null,draftScope:Scope|null=null,selectedDefinitionRef='',sourceRequestBasis='',compiledIntent:StageLibraryIntent|null=null;
 // Scope is the exact request produced by the existing Studio. It is never
 // independently inferred from display names, selection array indices or DOM.
 const studio=installProceduralStudio({...host,subscribe:host.subscribe?listener=>host.subscribe!(()=>{listener();refresh();}):undefined,owner:{async procedural(request){const result=await host.owner.procedural(request);if(request.operation==='read'){scope=clone(request.scope);void readSources();}return result;}}});
 const sourceSection=section('Current native Source · manifestation'),librarySection=section('Construct a procedural passage'),ruleSection=section('Native rule reception');
 const status=note('Open the existing Stage scope and read its native Source.'),sourceFacts=el('div'),sourceActions=el('div'),profiles=select('Actual native source profile'),profileFacts=note('Declared profile readings come from the current accepted native Scene. Live Source context and consumers remain separately qualified.'),sceneSourceFacts=el('div'),libraryChoice=select('Native construction'),libraryFacts=note('Read the running native library to choose a supported construction.'),procedureChoice=select('Source-owned procedure'),authorshipFacts=el('div'),form=el('div'),choiceForm=el('div'),previewFacts=el('div'),runtimeChoice=select('Retained native procedure'),runtimeFacts=el('div'),runtimeActions=el('div');
 status.setAttribute('role','status');status.setAttribute('aria-live','polite');
 sourceSection.content.append(status,sourceActions,sourceFacts);
 librarySection.content.append(label('Source profile',profiles),profileFacts,sceneSourceFacts,label('Construction',libraryChoice),libraryFacts,label('Authored procedure',procedureChoice),authorshipFacts,form,choiceForm,previewFacts);
 ruleSection.content.append(label('Procedure',runtimeChoice),runtimeFacts,runtimeActions);
 studio.panel.append(sourceSection.root,librarySection.root,ruleSection.root);
 const lifecycleEditor=installStageLifecycleEditor({snapshot:host.snapshot,capability:(action)=>provider.lifecycleAvailability(action),submit:async intent=>{const result=await provider.lifecycle(intent);if(result.operation?.status==='prepared')await acceptPrepared(result.operation);return result;},retry:intent=>provider.retryLifecycle(intent),settled:intent=>provider.settledLifecycle(intent)},message=>say(message));
 const driverEditor=installStageDriverEditor({snapshot:host.snapshot,open:host.openDriverEditor,report:message=>say(message)});const authoredDriverEditor=installStageAuthoredDriverEditor({...host.authoredDrivers,snapshot:host.snapshot,scope:()=>{if(!scope)throw Error('Choose the exact existing Studio scope before a driver Source read');return clone(scope);},actor:host.authoredDrivers?.actor??'',report:message=>say(message)});studio.panel.append(lifecycleEditor.panel,driverEditor.panel,authoredDriverEditor.panel);
 function say(message:string){status.textContent=message;host.report?.(message);}
 async function run(action:()=>Promise<void>){if(busy||disposed)return;busy=true;refreshAvailability();try{await action();}catch(error){say(error instanceof Error?error.message:String(error));}finally{busy=false;refreshAvailability();}}
 function button(title:string,action:()=>void){const result=el('button',title);result.type='button';result.addEventListener('click',action);return result;}
 function sourceButton(source:SourceBasis){return button(`${source.ref} · ${source.revision} · ${source.availability}`,()=>host.openSource(clone(source)));}
 function current():StudioSnapshot {const snapshot=host.snapshot();if(!snapshot)throw Error('Open or save a native Expression before constructing a passage');return snapshot;}
 function original(){const snapshot=current();if(!draftBasis||!draftScope||!sameNative(studioBasis(snapshot),draftBasis))throw Error('The original procedure Source/Scene/revision changed. Your form is retained; read its current basis and explicitly reload the authored procedure.');return snapshot;}
 const bootstrapEditor=installStageBootstrapEditor({retainWorldSource:(actor,recover)=>provider.retainSelectedSceneSource(actor,recover),pendingWorldSource:()=>provider.pendingSelectedSceneSource(),sourceRetentionReason:()=>provider.selectedSceneSourceRetentionReason(),openWorld:recover=>provider.openSelectedScene(recover),abandonWorld:()=>provider.abandonSelectedScene(),openingReason:()=>provider.selectedSceneOpeningReason(),pendingOpening:()=>provider.pendingSelectedScene(),captureBasis:()=>provider.captureSourceBasis(),authored:actor=>provider.sourceAuthorship(actor),authoringReading:()=>provider.authoringReading('source_authorship'),subjects:()=>sourceReading?.current_readings.map(row=>row.subject)??[],submit:bootstrapSource,availability(){const snapshot=host.snapshot();if(!snapshot)return 'Open the current native Expression';return provider.sourceBootstrapReason();},run:action=>void run(action),report:say});sourceSection.content.append(bootstrapEditor.panel);
 async function bootstrapSource(value:StageSourceBootstrapIntent){const result=await provider.bootstrapSource(value);sceneSource=null;sourceProfile=null;sourceReading=null;sourceFacts.replaceChildren(note(isStageBootstrapRefusalObservation(result)?`Source refused at actual Document ${result.document_receipt.document.revision}; original intent remains retained. Explicitly inspect and requalify before library use.`:result.source_current?'Current native Source issued; read its exact current Scene/profile for library use.':'Binding adoption changed the Document. The original Source revision is retained; read and requalify the current Scene before library use.'));return result;}
 function capabilities(){const snapshot=host.snapshot();if(!snapshot)return null;const basis=studioBasis(snapshot);return Object.fromEntries((['library','prepare','authorship','conduct','retire'] as const).map(name=>{try{return [name,provider.capability(name,basis)];}catch(error){return [name,{state:'unavailable' as const,reason:error instanceof Error?error.message:String(error)}];}}));}
 function refreshAvailability(){
  const snapshot=host.snapshot(),caps=capabilities(),changed=!!snapshot&&!!draftBasis&&!sameNative(studioBasis(snapshot),draftBasis);
  for(const row of guardedButtons){const capability=caps?.[row.capability];row.button.disabled=busy||!snapshot||capability?.state!=='available'||(row.original&&(!authored||changed));row.button.title=capability?.state==='unavailable'?capability.reason:changed?'The original native basis changed; your form is retained.':'';}
  const reasons=caps?Object.entries(caps).filter(([,value])=>value.state==='unavailable').map(([key,value])=>`${key}: ${value.state==='unavailable'?value.reason:''}`):['No current native Expression is open.'];
  libraryFacts.textContent=[library?.standing??'Read the running native library to choose a supported construction.',...reasons,changed?'Current native basis advanced. The full uncommitted intent remains on its original basis.':''].filter(Boolean).join(' ');
 }
 const guardedButtons:Array<{button:HTMLButtonElement;capability:'library'|'prepare'|'authorship'|'conduct'|'retire';original:boolean}>=[];
 function guarded(title:string,capability:'library'|'prepare'|'authorship'|'conduct'|'retire',original:boolean,action:()=>Promise<void>){const result=button(title,()=>void run(action));guardedButtons.push({button:result,capability,original});return result;}
 sourceActions.append(button('Read this scope’s native Source',()=>void run(readSources)),button('Read running native library',()=>void run(async()=>{const snapshot=current();library=await provider.discover(snapshot);options(libraryChoice,library.recipes.map(recipe=>[recipe.recipe,recipe.label]),'Choose native construction');refresh();})),button('Read current scene material',()=>void run(readSceneSource)));
 const useSource=button('Read native authored C′ and timing',()=>void run(async()=>{if(!sceneSource)throw Error('Read the exact current native Scene material first');const snapshot=current(),originalControls=captureAuthoredControls([librarySection.root]),value=await provider.authorship(snapshot,sceneSource);if(disposed||!originalControls())throw Error('Native procedure authorship returned while your typed procedure controls changed. They remain retained; explicitly load the current native authoring intent again.');loadAuthorship(value,snapshot);const reading=provider.authoringReading('procedure_authorship');if(reading)authorshipFacts.append(note(nativeAuthorshipDisclosure(reading)));}));
 const reload=button('Reload this saved procedure on current basis',()=>void run(async()=>{const snapshot=current(),retained=snapshot.journey.scenes.flatMap(scene=>retention(scene).procedures).find(row=>row.procedure_ref===procedureChoice.value);if(!retained)throw Error('Choose a source-owned retained definition');loadAuthorship(retainedProcedureAuthorship(retained.definition),snapshot);}));
 librarySection.content.insertBefore(el('div'),authorshipFacts);authorshipFacts.before(useSource,reload);
 const procedureRef=input('Procedure identity'),revision=input('Procedure revision'),seed=input('Retained procedure seed'),trigger=enums('Native rule trigger',TRIGGERS),triggerMode=enums('Native trigger behaviour',['edge','level']),membership=enums('Target membership',['frozen','sustained']),membershipPolicy=enums('Membership change policy',['admit_and_record','retain_existing','reject_change']),removal=enums('Generated removal policy',['retire_unedited_detach_edited','conflict_on_edited']),failure=enums('Rule failure policy',['stop_affected_and_checkpoint','hold_last_admitted_and_report']),continuation=enums('Continuation policy',['continue','hold','checkpoint_and_release']),selectorChoice=enums('Native membership selector',['all','occurrences','subject','tag']),selectorValue=select('Exact native selector value'),selectorFacts=note('Read the selected scope before choosing native membership.');
 const budgets=new Map<string,HTMLInputElement>(),parameters=new Map<string,HTMLInputElement>();
 const outputSlot=input('Stable contribution output slot'),forceTarget=select('Actual force property'),forceValue=input('Force value in authored units','number'),atlasTarget=select('Existing native place'),atlasAction=enums('Existing place operation',['focus','scene_reorder']);
 const construction=installStageConstructionEditor(say);
 function renderAuthorship(){
  form.replaceChildren();authorshipFacts.replaceChildren();parameters.clear();budgets.clear();
  if(!authored){authorshipFacts.append(note('Choose a full saved procedure definition or its current native authored C′ provider. A missing graph, timing binding or source profile is not supplied by this screen.'));return;}
  procedureRef.value=authored.procedure_ref;revision.value=authored.revision;seed.value=authored.seed;trigger.value=authored.trigger.kind;triggerMode.value=authored.trigger.mode;membership.value=authored.membership_mode;membershipPolicy.value=authored.membership_change_policy;removal.value=authored.removal_policy;failure.value=authored.failure_policy;continuation.value=authored.continuation_policy;selectorChoice.value=String(authored.selector.selector);
  form.append(label('Procedure identity',procedureRef),label('Source revision',revision),label('Retained seed',seed),label('Trigger',trigger),label('Trigger behaviour',triggerMode),label('Selector',selectorChoice),label('Selector value',selectorValue),selectorFacts,label('Membership',membership),label('Membership changes',membershipPolicy),label('Removed generated material',removal),label('Failure',failure),label('Continuation',continuation));
  for(const [key,maximum]of BUDGETS){const value=input(key.replaceAll('_',' '),'number');value.step='1';value.min='1';value.max=String(maximum);value.value=String(authored.budgets[key]);budgets.set(key,value);form.append(label(key.replaceAll('_',' '),value));}
  for(const [key,value]of Object.entries(authored.recipe_parameters)){
   if(!['string','number','boolean'].includes(typeof value)){form.append(note(`Retained native parameter ${key}: ${text(value)}`));continue;}
   const field=input(`Recipe parameter ${key}`,typeof value==='number'?'number':typeof value==='boolean'?'checkbox':'text');if(field.type==='checkbox')field.checked=value===true;else field.value=String(value);parameters.set(key,field);form.append(label(`Recipe parameter · ${key}`,field));
  }
  const composition=authored.composition;authorshipFacts.append(note(`Full authored C′ · actor ${text(composition.actor)} · direction ${text(composition.direction)} · whole ${text(composition.whole)} · resolution ${text(composition.resolvePath)}`),note(`Native timing · ${authored.timing.owner_ref} · ${authored.timing.domain} · epoch ${authored.timing.epoch_ref} · requested position ${authored.timing.requested_cursor} · mapping ${authored.timing.time_mapping_ref??'none'}`));
  for(const ref of composition.sources as string[]){const actual=current().currentSources?.find(row=>row.ref===ref);if(actual)authorshipFacts.append(sourceButton(actual));else authorshipFacts.append(note(`Authored source · ${ref} · current revision and availability unobserved`));}
  renderSelector(true);renderConditions();form.append(conditionBox);
 }
 const conditionBox=section('Rule conditions').root,conditionRows=el('div'),conditionProperty=input('Native condition property'),conditionMinimum=input('Condition minimum','number'),conditionMaximum=input('Condition maximum','number');
 conditionBox.append(conditionRows,label('Native property',conditionProperty),label('Minimum',conditionMinimum),label('Maximum',conditionMaximum),button('Add bounded scalar condition',()=>void run(async()=>{collectAuthorship();const minimum=Number(conditionMinimum.value),maximum=Number(conditionMaximum.value);if(!conditionProperty.value.trim()||!conditionMinimum.value.trim()||!conditionMaximum.value.trim()||!Number.isFinite(minimum)||!Number.isFinite(maximum)||minimum>maximum)throw Error('Enter an explicit native property and finite ordered bounds');if(authored!.conditions.length>=64)throw Error('The native condition budget is full');authored!.conditions.push({condition:'scalar_range',property:conditionProperty.value,minimum,maximum});renderConditions();})));
 function renderConditions(){conditionRows.replaceChildren();for(const [index,condition]of authored?.conditions.entries()??[]){const row=el('div');row.append(note(`Condition ${index+1} · ${text(condition)}`),button(`Remove condition ${index+1}`,()=>void run(async()=>{collectAuthorship();authored!.conditions.splice(index,1);renderConditions();})));conditionRows.append(row);}}
 function loadAuthorship(value:ProcedureAuthorship,snapshot:StudioSnapshot){validateProcedureAuthorship(value);if(!scope)throw Error('Read the existing Studio’s actual native scope first');authored=clone(value);draftBasis=studioBasis(snapshot);draftScope=clone(scope);selectedDefinitionRef=value.procedure_ref;compiledIntent=null;renderAuthorship();renderChoice();refreshAvailability();say('Full native authored procedure loaded. Edits remain on this original Source/Document basis until preparation.');}
 function selectorRows(){const rows=sourceReading?.current_readings??[];if(selectorChoice.value==='subject')return [...new Set(rows.map(row=>row.subject.subject_ref))].map(ref=>[ref,ref] as const);if(selectorChoice.value==='tag')return [...new Map(rows.flatMap(row=>row.tags.map(tag=>[JSON.stringify([tag.value,tag.origin,tag.scope_ref]),[JSON.stringify([tag.value,tag.origin,tag.scope_ref]),`${tag.value} · ${tag.origin} · ${tag.scope_ref}`] as const]))).values()];const occurrences=new Map<string,string[]>();for(const row of rows)occurrences.set(row.occurrence_ref,[...(occurrences.get(row.occurrence_ref)??[]),addressLabel(row.address)]);return [...occurrences].map(([ref,addresses])=>[ref,`${ref} · ${addresses.join(' · ')}`] as const);}
 function renderSelector(seed=false){const old=selectorValue.value,rows=selectorRows();if(!seed&&old&&!rows.some(([value])=>value===old))rows.push([old,`${old} · no longer reported; intent retained`] as const);options(selectorValue,rows,'Choose exact reported value');if(seed&&authored&&selectorChoice.value===String(authored.selector.selector)){const s=authored.selector;let saved='';if(s.selector==='subject')saved=String(s.subject_ref);if(s.selector==='tag')saved=JSON.stringify([s.value,s.origin,s.scope_ref]);if(s.selector==='occurrences'&&Array.isArray(s.refs)&&s.refs.length===1)saved=String(s.refs[0]);if(saved&&!rows.some(([value])=>value===saved)){const option=el('option',`${saved} · saved membership; current availability unobserved`);option.value=saved;selectorValue.append(option);}selectorValue.value=saved;}else selectorValue.value=old;selectorValue.parentElement!.hidden=selectorChoice.value==='all';selectorFacts.textContent=selectorChoice.value==='occurrences'?`Retained membership · ${text(authored?.selector.refs??[])}. Selecting a reported occurrence explicitly replaces that membership with this one target.`:'Selector values preserve native subject or tag origin and scope.';}
 selectorChoice.addEventListener('change',()=>{selectorValue.value='';renderSelector(true);});
 function collectAuthorship(commandSelector?:Record<string,unknown>):ProcedureAuthorship {
  if(!authored)throw Error('A full source-owned authored procedure is required');
  const next=clone(authored);next.procedure_ref=procedureRef.value;next.revision=revision.value;next.seed=seed.value;next.trigger={kind:trigger.value,mode:triggerMode.value as 'edge'|'level'};next.membership_mode=membership.value as ProcedureAuthorship['membership_mode'];next.membership_change_policy=membershipPolicy.value as ProcedureAuthorship['membership_change_policy'];next.removal_policy=removal.value as ProcedureAuthorship['removal_policy'];next.failure_policy=failure.value as ProcedureAuthorship['failure_policy'];next.continuation_policy=continuation.value as ProcedureAuthorship['continuation_policy'];
  for(const [key,field]of budgets){if(!field.value.trim())throw Error('Retain every explicit native rule budget');next.budgets[key as keyof ProcedureAuthorship['budgets']]=Number(field.value);}
  for(const [key,field]of parameters){const original=next.recipe_parameters[key];if(typeof original==='number'&&(!field.value.trim()||!Number.isFinite(Number(field.value))))throw Error(`Recipe parameter ${key} needs a finite explicit value`);next.recipe_parameters[key]=typeof original==='boolean'?field.checked:typeof original==='number'?Number(field.value):field.value;}
  if(commandSelector)next.selector=clone(commandSelector);else {const kind=selectorChoice.value;if(kind!=='all'&&selectorValue.value&&!selectorRows().some(([value])=>value===selectorValue.value))throw Error('The original native selector value is no longer reported in this scope; its uncommitted intent is retained');if(kind==='all')next.selector={selector:'all'};else if(kind==='occurrences'){if(selectorValue.value)next.selector={selector:'occurrences',refs:[selectorValue.value]};else if(authored.selector.selector!=='occurrences')throw Error('Choose an actual reported occurrence');}else if(kind==='subject'){if(!selectorValue.value)throw Error('Choose an actual native subject');next.selector={selector:'subject',subject_ref:selectorValue.value};}else if(kind==='tag'){if(!selectorValue.value)throw Error('Choose an actual tag origin and scope');const [value,origin,scope_ref]=JSON.parse(selectorValue.value);next.selector={selector:'tag',value,origin,scope_ref};}else throw Error('Choose a native membership selector');}
  validateProcedureAuthorship(next);authored=next;return clone(next);
 }
 function descriptor():NativeLibraryDescriptor {const result=library?.recipes.find(recipe=>recipe.recipe===libraryChoice.value);if(!result)throw Error('Read and choose an actual running native construction');return result;}
 function renderChoice(){
  choiceForm.replaceChildren();const snapshot=host.snapshot(),recipe=library?.recipes.find(row=>row.recipe===libraryChoice.value);if(!snapshot||!recipe)return;
  choiceForm.append(note(`${recipe.label} · ${recipe.native_operations.join(', ')}`),note(recipe.required_source??recipe.domain_owner??''));
  if(recipe.recipe==='scene_material'||recipe.recipe==='sequence_material'){construction.refresh(snapshot,recipe.recipe==='sequence_material');choiceForm.append(construction.panel);}
  if(recipe.recipe==='force_parameters'){
   const rows=scope?stageForceParameters(snapshot,recipe,scope):[];options(forceTarget,rows.map(row=>[row.target,`${addressLabel(row.address)} · ${row.units}`]),'Choose actual property');choiceForm.append(label('Force property',forceTarget),label('Authored value',forceValue),label('Stable output slot',outputSlot));showForceDomain();
  }
  if(recipe.recipe==='atlas_passage'){options(atlasTarget,snapshot.view.document.scenes.map(scene=>[scene.scene_ref,scene.title]),'Choose current native place');choiceForm.append(label('Existing operation',atlasAction),label('Existing place',atlasTarget),note('Focus preserves the current native occurrence. Reorder moves the chosen existing scene first; no place is recreated.'));}
 }
 function showForceDomain(){if(!scope||!host.snapshot())return;const recipe=library?.recipes.find(row=>row.recipe===libraryChoice.value);if(!recipe)return;const row=stageForceParameters(current(),recipe,scope).find(row=>row.target===forceTarget.value);if(!row)return;forceValue.min=String(row.minimum);forceValue.max=String(row.maximum);forceValue.title=`${row.minimum}…${row.maximum} ${row.units}; native conversion factor ${row.factor}`;}
 forceTarget.addEventListener('change',showForceDomain);libraryChoice.addEventListener('change',renderChoice);
 function collectChoice(snapshot:StudioSnapshot,action:'prepare'|'regenerate'):LibraryChoice {
  const recipe=descriptor();if(recipe.recipe==='scene_material'||recipe.recipe==='sequence_material'){
   if(!authored)throw Error('Load the full actual native procedure before constructing outputs');
   const outputs=validateSceneOutputs(snapshot,construction.outputs(),{max_active_instances:authored.budgets.max_active_instances,procedure_ref:authored.procedure_ref,action});
   return recipe.recipe==='scene_material'?{recipe:'scene_material',outputs}:{recipe:'sequence_material',outputs,holds:validateSequenceHolds(snapshot,construction.holds())};
  }
  if(recipe.recipe==='force_parameters'){if(!forceValue.value.trim()||!draftScope)throw Error('Enter the authored property value on its original scope');return stageForceChoice(snapshot,recipe,draftScope,forceTarget.value,Number(forceValue.value),outputSlot.value);}
  if(!atlasTarget.value||!atlasAction.value)throw Error('Choose an exact existing native place and action');const refs=snapshot.view.document.scenes.map(scene=>scene.scene_ref);if(!refs.includes(atlasTarget.value))throw Error('The selected native place is no longer present');return {recipe:'atlas_passage',changes:atlasAction.value==='focus'?[{change:'focus',scene_ref:atlasTarget.value,entity_ref:null}]:[{change:'scene_reorder',scene_refs:[atlasTarget.value,...refs.filter(ref=>ref!==atlasTarget.value)]}]};
 }
 async function intent(action:'prepare'|'regenerate'):Promise<StageLibraryIntent> {
  const snapshot=original();if(!sceneSource||!sourceProfile||sceneSource.document_revision!==draftBasis!.document_revision)throw Error('Read the actual original native Scene material and source profile');const choice=collectChoice(snapshot,action),source=clone(sceneSource),profile=clone(sourceProfile),basis=clone(draftBasis!);
  let commandScope=clone(draftScope!),commandSelector:Record<string,unknown>|undefined;
  if(choice.recipe==='atlas_passage'){const target=stageAtlasCommandTarget(snapshot,draftScope!);commandSelector=target.selector;commandScope=target.scope;selectorFacts.textContent='The flow passage targets this continuing whole Expression. Its actual native Selection and scene order remain the authored basis.';}
  // Capture existing full authored fields before the native read. The actual
  // scalar membership is assigned only from its genuine current Source reply;
  // no Entity authority or browser-issued occurrence replaces that receipt.
  const value=collectAuthorship(choice.recipe==='force_parameters'?clone(authored!.selector):commandSelector);
  if(choice.recipe==='force_parameters'){const target=stageForceCommandTarget(snapshot,descriptor(),draftScope!,forceTarget.value);commandScope=target.scope;const reading=await provider.readSource(snapshot,target.scope,null,target.property_keys);original();value.selector={selector:'occurrences',refs:reading.current_readings.map(row=>row.occurrence_ref)};validateProcedureAuthorship(value);selectorFacts.textContent=`Force passage retains only ${text(target.scope)}. Membership uses ${reading.current_readings.length} exact native Source-issued scalar occurrences; sibling properties remain outside this command.`;}
  return {basis,operation_ref:mint(),source,profile,authored:value,choice,scope:commandScope,action};
 }
 async function acceptPrepared(operation:Operation){const receiving=studio as ProceduralStudio&{acceptPrepared?:(operation:Operation)=>Promise<void>};if(!receiving.acceptPrepared)throw Error('The existing native operation review receiver is not paired. Native prepared intent remains retained in its Workspace journal.');await receiving.acceptPrepared(operation);}
 async function prepareLibrary(value:StageLibraryIntent){const result=await provider.prepare(value);if('outcome' in result){previewFacts.replaceChildren(note(result.source_current?'Native Source and retained construction are unchanged. No material edit or preparation was issued.':'Original native no-change history retained. Current Source needs explicit requalification before a new authored operation.'));say(result.source_current?'Native construction is unchanged.':'Original readonly outcome; current Source unqualified.');return result;}await acceptPrepared(result.operation);previewFacts.replaceChildren(...result.changes.map(change=>note(`${change.kind} · ${change.label}${change.address?` · ${addressLabel(change.address)}`:''}`)));say('Native procedure prepared. Inspect and apply the operation through the existing Studio review.');return result;}
 const loadOutputs=button('Load original saved output slots and holds',()=>void run(async()=>{const snapshot=current(),retained=snapshot.journey.scenes.flatMap(scene=>retention(scene).procedures).find(row=>row.procedure_ref===procedureChoice.value);if(!retained)throw Error('Choose an actual saved native definition');const choice=retainedMaterialChoice(retained.definition);if(!library?.recipes.some(row=>row.recipe===choice.recipe))throw Error('Read the actual native library supporting this original construction');construction.load(choice);libraryChoice.value=choice.recipe;renderChoice();say('Original saved output intent loaded explicitly. Current Source/CAS and stable ownership still require native preparation.');}));
 const libraryActions=el('div');libraryActions.append(guarded('Preview native construction','library',true,async()=>{const value=await intent('prepare');compiledIntent=clone(value);const result=await provider.build(original(),value);previewFacts.replaceChildren(note(`Native definition · ${result.procedure.procedure_ref} · ${result.source_scene_ref} · Source ${result.source_material_fingerprint}`),note(result.standing),note('Definition compiled. Live preparation still requires the native graph/currentness/ThreadPlan and the same Workspace admission.'));}),guarded('Prepare current construction','prepare',true,async()=>{const value=await intent('prepare');compiledIntent=clone(value);await prepareLibrary(value);}),guarded('Prepare regeneration','prepare',true,async()=>{const value=await intent('regenerate');compiledIntent=clone(value);await prepareLibrary(value);}),button('Retry the retained preparation',()=>void run(async()=>{if(!compiledIntent)throw Error('There is no original retained typed preparation to retry');await prepareLibrary(clone(compiledIntent));})));librarySection.content.append(loadOutputs,libraryActions);
 libraryActions.prepend(button('Read this construction’s native operands',()=>void run(async()=>{const snapshot=original(),recipe=descriptor();if(recipe.recipe==='force_parameters'){const selected=stageForceParameters(snapshot,recipe,draftScope!).find(row=>row.target===forceTarget.value);if(!selected)throw Error('Choose an actual force property inside the original scope');const target=stageForceCommandTarget(snapshot,recipe,draftScope!,forceTarget.value),reading=await provider.readSource(snapshot,target.scope,null,[selected.parameter]);previewFacts.replaceChildren(note(`Native original ${selected.parameter} · ${text(reading.current_readings[0].properties[selected.parameter])} · native Parameter units. Authored controls use ${selected.units}; conversion ${selected.factor}.`));}else if(recipe.recipe==='atlas_passage'){const target=stageAtlasCommandTarget(snapshot,draftScope!),reading=await provider.readSource(snapshot,target.scope,null,['native_atlas_state']);previewFacts.replaceChildren(note(`Actual continuing Expression flow · ${text(reading.current_readings[0].properties.native_atlas_state)}`));}else{await readSceneSource();previewFacts.replaceChildren(note('The construction basis is the whole currently admitted native Scene material, including its retained source and sequence coordinates.'));}})));
 procedureChoice.addEventListener('change',()=>void run(async()=>{const snapshot=current(),retained=snapshot.journey.scenes.flatMap(scene=>retention(scene).procedures).find(row=>row.procedure_ref===procedureChoice.value);if(!retained)throw Error('Choose a full saved source-owned procedure');loadAuthorship(retainedProcedureAuthorship(retained.definition),snapshot);}));
 profiles.addEventListener('change',()=>{sceneSource=null;sourceProfile=null;sceneSourceFacts.replaceChildren();profileFacts.textContent='The chosen profile changed. Read the current scene material before preparation.';});
 async function readSceneSource(){const snapshot=current(),basis=studioBasis(snapshot),profile=snapshot.currentSources?.find(row=>JSON.stringify([row.ref,row.revision])===profiles.value);if(!profile)throw Error('Choose an actual current native profile');const address={expression_ref:basis.expression_ref,scene_ref:basis.scene_ref,entity_ref:null,component:'scene' as const,constituent_ref:null,property:null};const result=await provider.readSource(snapshot,{kind:'addresses',addresses:[address]},profile);if(result.scene_sources.length!==1)throw Error('The actual source owner did not supply exactly this bound Scene material');sceneSource=result.scene_sources[0];sourceProfile=clone(profile);profileFacts.textContent=`${sceneSource.principal.subject_ref} · ${sceneSource.contributors.length} contributors · ${sceneSource.locus_ref} · ${sceneSource.source_basis.revision} · material ${sceneSource.material_fingerprint}`;sceneSourceFacts.replaceChildren();for(const [role,subject]of [['Principal',sceneSource.principal] as const,...sceneSource.contributors.map(subject=>['Contributor',subject] as const)]){const card=section(`${role} · ${subject.subject_ref}`);card.content.append(note(`${subject.native_owner} · ${subject.presentation_role}`));for(const source of [...subject.sources,...subject.readings])card.content.append(sourceButton(source));for(const action of subject.actions)card.content.append(note(`Native action · ${action.action_ref} · ${action.target_ref} · ${action.authority_requirement}`));sceneSourceFacts.append(card.root);}sceneSourceFacts.append(note(`Continuing occurrence · ${sceneSource.expression_ref} · ${sceneSource.scene_ref} · document ${sceneSource.document_revision}`),note(`Source-qualified place · ${sceneSource.locus_ref} · ${sceneSource.locus_revision}`));say('Current native Scene source admitted for inspection. Live production remains subject to its native currentness preparation.');}
 async function readSources(){if(disposed||!active||!scope)return;const generation=++readGeneration;try{const snapshot=current(),requested=clone(scope),signature=JSON.stringify([studioBasis(snapshot),requested]);const result=await provider.readSource(snapshot,requested);if(disposed||generation!==readGeneration||JSON.stringify([studioBasis(current()),scope])!==signature)return;sourceReading=result;sourceRequestBasis=signature;renderSources();if(authored)renderSelector();}catch(error){if(generation===readGeneration){sourceReading=null;sourceFacts.replaceChildren(note(error instanceof Error?error.message:String(error)));}}}
 function renderSources(){
  sourceFacts.replaceChildren();if(!sourceReading){sourceFacts.append(note('Current native Source is unobserved. Use the native read in this exact scope.'));return;}
  sourceFacts.append(note(`${sourceReading.expression_ref} · document ${sourceReading.document_revision} · ${sourceReading.current_readings.length} qualified native occurrences`));
  for(const row of sourceReading.current_readings){const card=section(`${row.occurrence_ref} · ${row.subject.presentation_role}`);card.content.append(note(addressLabel(row.address)),note(`Principal · ${row.subject.subject_ref} · ${row.subject.native_owner} · native revision ${row.revision}`));if(!row.subject.sources.length&&!row.subject.readings.length)card.content.append(note('This native subject declares no Source readings. No source availability or procedural graph is inferred.'));for(const source of row.subject.sources)card.content.append(sourceButton(source));for(const reading of row.subject.readings)card.content.append(sourceButton(reading));for(const action of row.subject.actions)card.content.append(note(`Native action · ${action.action_ref} · target ${action.target_ref} · ${action.authority_requirement}`));for(const tag of row.tags)card.content.append(note(`Tag · ${tag.value} · ${tag.origin} · ${tag.scope_ref} · ${tag.basis.source_ref} ${tag.basis.revision}`));sourceFacts.append(card.root);}
 }
 async function conduct(value:StageRuntimeIntent){const result=await provider.conduct(value);runtimeFacts.append(note(result.standing));say(`Native rule ${value.action}: ${result.standing}`);return result;}
 function runtimeIntent(action:StageRuntimeIntent['action']):StageRuntimeIntent {const snapshot=current(),retained=snapshot.journey.scenes.flatMap(scene=>retention(scene).procedures).find(row=>row.procedure_ref===runtimeChoice.value);if(!retained)throw Error('Choose an actual retained native procedure');return {basis:studioBasis(snapshot),procedure_ref:retained.procedure_ref,expected_recipe_revision:retained.revision,action,observed_rule_cursor:retained.cursor};}
 for(const [action,title]of [['read','Read native rule'],['pause','Hold native rule'],['resume','Continue native rule'],['cancel','Interrupt native rule'],['checkpoint','Checkpoint through native owner']] as const)runtimeActions.append(guarded(title,'conduct',false,async()=>{await conduct(runtimeIntent(action));}));
 function showRuntime(){runtimeFacts.replaceChildren();const retained=host.snapshot()?.journey.scenes.flatMap(scene=>retention(scene).procedures).find(row=>row.procedure_ref===runtimeChoice.value);if(!retained){runtimeFacts.append(note('No saved native procedure selected. A saved definition alone does not establish a running held-host instance.'));return;}runtimeFacts.append(note(`${retained.procedure_ref} · saved ${retained.state} · rule event position ${retained.cursor} · source revision ${retained.revision}`),note(`${retained.resolved_targets.length} retained native targets · ${retained.membership_events.length} membership changes`));for(const source of retained.source_basis)runtimeFacts.append(sourceButton(source));}
 runtimeChoice.addEventListener('change',showRuntime);
 function refresh(){
  if(disposed)return;studio.refresh();const snapshot=host.snapshot();if(!snapshot){refreshAvailability();return;}
  const basis=studioBasis(snapshot),signature=scope?JSON.stringify([basis,scope]):'';
  if(sourceReading&&sourceRequestBasis!==signature){sourceReading=null;sourceFacts.replaceChildren(note('The native Source basis changed. Retained form intent still names its original basis; read the current scope explicitly.'));}
  options(profiles,(snapshot.currentSources??[]).map(source=>[JSON.stringify([source.ref,source.revision]),`${source.ref} · ${source.revision} · ${source.availability}`]),'Choose current native profile');
  const procedures=snapshot.journey.scenes.flatMap(scene=>retention(scene).procedures);options(procedureChoice,procedures.map(row=>[row.procedure_ref,`${row.procedure_ref} · ${row.revision}`]),'Choose saved full native definition');options(runtimeChoice,procedures.map(row=>[row.procedure_ref,`${row.procedure_ref} · ${row.state}`]),'Choose native rule');if(selectedDefinitionRef&&!procedureChoice.value)procedureChoice.value=selectedDefinitionRef;
  construction.refresh(snapshot,libraryChoice.value==='sequence_material');refreshAvailability();showRuntime();bootstrapEditor.refresh();lifecycleEditor.refresh();driverEditor.refresh();authoredDriverEditor.refresh();
 }
 // Existing Studio's subscription is the only pulse registration. Inputs and
 // their original full intent are not reconstructed during native pulses.
 const originalSetActive=studio.setActive.bind(studio);
 renderAuthorship();refresh();
 return {panel:studio.panel,provider,attach:mount=>studio.attach(mount),setActive(next){if(disposed||active===next)return;active=next;readGeneration++;originalSetActive(next);if(next)refresh();},refresh,async read(){await studio.read();await readSources();},acceptPrepared,retainedPreparation:()=>clone(compiledIntent),prepareLibrary,conduct,bootstrapSource,retainedSourceIntent:()=>bootstrapEditor.retainedIntent(),lifecycle:intent=>lifecycleEditor.submit(intent),retainedLifecycleIntent:()=>lifecycleEditor.retainedIntent(),authoredDriver:intent=>authoredDriverEditor.submit(intent),retryAuthoredDriver:()=>authoredDriverEditor.retry(),retainedAuthoredDriver:()=>authoredDriverEditor.retainedIntent(),dispose(){if(disposed)return;disposed=true;readGeneration++;construction.dispose();bootstrapEditor.dispose();lifecycleEditor.dispose();driverEditor.dispose();authoredDriverEditor.dispose();studio.dispose();authored=null;sceneSource=null;sourceReading=null;compiledIntent=null;}};
}
