import {nativeAuthorshipDisclosure,type NativeAuthorshipReading} from './proceduralStageAuthoring';
import {captureAuthoredControls} from './proceduralAuthoringControls';
import type {PendingNativeSelectedSceneSource,SelectedSceneSourceReply} from './proceduralSelectedSceneSource';
import type {PendingNativeSelectedScene,SelectedSceneOpening} from './proceduralSelectedScene';
/** Source authoring controls in the existing Stage. Nodes and original intent
 * stay mounted through native pulses; this has no second store/clock/runtime. */
import {clone} from './model';
import type {StudioBasis} from './proceduralStudio';
import type {FullNativeSubject} from './proceduralStageSource';
import {STAGE_PROFILE_AXES,validateStageSourceAuthorship,isStageBootstrapRefusalObservation,type StageSourceAuthorship,type StageSourceBootstrapIntent,type StageSourceBootstrapOutcome} from './proceduralStageBootstrap';
export interface StageBootstrapEditorHost {
 captureBasis():Promise<StudioBasis>;
 retainWorldSource(actor:string,recover?:boolean):Promise<SelectedSceneSourceReply>;
 pendingWorldSource():PendingNativeSelectedSceneSource|null;
 sourceRetentionReason():string|null;
 openWorld(recover?:boolean):Promise<SelectedSceneOpening>;
 abandonWorld():Promise<unknown>;
 openingReason():string|null;
 pendingOpening():PendingNativeSelectedScene|null;
 authored(actor:string):Promise<StageSourceAuthorship>;
 authoringReading?():NativeAuthorshipReading|null;
 subjects():readonly FullNativeSubject[];
 submit(intent:StageSourceBootstrapIntent):Promise<StageSourceBootstrapOutcome>;
 availability():string|null;
 run(action:()=>Promise<void>):void;
 report(message:string):void;
}
export interface StageBootstrapEditor {panel:HTMLElement;refresh():void;retainedIntent():StageSourceBootstrapIntent|null;dispose():void;}
const node=<K extends keyof HTMLElementTagNameMap>(tag:K,text?:string)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
function note(text:string){const n=node('p',text);n.className='control-note';return n;}
function field(title:string,type='text'){const n=node('input');n.type=type;n.setAttribute('aria-label',title);if(type==='number')n.step='1';return n;}
function label(title:string,n:HTMLElement){const l=node('label');l.className='control';l.append(node('span',title),n);return l;}
function choice(title:string,values:readonly string[]){const n=node('select');n.setAttribute('aria-label',title);const blank=node('option','Choose explicitly');blank.value='';n.append(blank,...values.map(value=>{const o=node('option',value);o.value=value;return o;}));return n;}
function action(title:string,fn:()=>void){const n=node('button',title);n.type='button';n.addEventListener('click',fn);return n;}
const list=(text:string)=>text.split('\n').map(value=>value.trim()).filter(Boolean);
function lines(title:string){const n=node('textarea');n.rows=2;n.setAttribute('aria-label',title);return n;}
type RowField={title:string;type?:'number'|'list'|'optional'};
function table(title:string,fields:Record<string,RowField>){
 const root=node('details');root.open=false;const body=node('div'),rows:{panel:HTMLElement;fields:Map<string,HTMLInputElement|HTMLTextAreaElement>}[]=[];root.append(node('summary',title),body);
 function add(values:Record<string,unknown>={}){const panel=node('fieldset'),map=new Map<string,HTMLInputElement|HTMLTextAreaElement>();for(const [key,definition]of Object.entries(fields)){const f=definition.type==='list'?lines(`${title}: ${definition.title}`):field(`${title}: ${definition.title}`,definition.type==='number'?'number':'text');f.value=Array.isArray(values[key])?(values[key] as unknown[]).join('\n'):values[key]===null||values[key]===undefined?'':String(values[key]);map.set(key,f);panel.append(label(definition.title,f));}const row={panel,fields:map};panel.append(action('Remove this row',()=>{panel.remove();rows.splice(rows.indexOf(row),1);}));rows.push(row);body.append(panel);}
 root.append(action(`Add ${title.toLowerCase()} row`,()=>add()));
 return {root,load(values:Record<string,unknown>[]){body.replaceChildren();rows.length=0;values.forEach(add);},collect(){return rows.map(row=>Object.fromEntries([...row.fields].map(([key,f])=>{const definition=fields[key];if(definition.type==='number'&&!f.value.trim())throw Error(`Enter ${title}: ${definition.title}`);return [key,definition.type==='list'?list(f.value):definition.type==='number'?Number(f.value):definition.type==='optional'?(f.value.trim()||null):f.value];})));}};
}
export function installStageBootstrapEditor(host:StageBootstrapEditorHost):StageBootstrapEditor {
 let disposed=false,basis:StudioBasis|null=null,intent:StageSourceBootstrapIntent|null=null,loaded:StageSourceAuthorship|null=null,readyForNewIntent=false;
 const panel=node('details');panel.open=false;panel.dataset.stageSourceBootstrap='';panel.append(node('summary','Author the current native Stage Source'));
 const availabilityNote=note('The protected native Source bootstrap owner is unobserved.');
 const status=note('Capture the accepted Scene basis, then enter or load every original Source authoring field. Native Source owns the held principal, graph, currentness and timing.');status.setAttribute('role','status');status.setAttribute('aria-live','polite');panel.append(status,availabilityNote);
 const required=new Map<string,HTMLInputElement>();for(const [key,title]of [['actor_ref','Actor ref'],['standing_ref','Authored standing ref'],['category','Source category'],['ground_ref','Canonical place ref'],['ground_face','Place face'],['resolve_path','Resolve path'],['context_resolution','Context resolution'],['authority','Authority ref · empty means absent']] as const){const f=field(title);required.set(key,f);panel.append(label(title,f));}
 const role=choice('Principal presentation role',['being','thing']);panel.append(label('Principal presentation role',role),note('The principal identity comes from the actual held native subject. Its presentation role is explicit authorship.'));
 const frameFields=new Map<string,HTMLInputElement>(),frame=node('fieldset');frame.append(node('legend','Native context frame'));for(const key of ['id','lens','basis','face','positions']){const f=field(`Context frame ${key}`);frameFields.set(key,f);frame.append(label(key,f));}panel.append(frame);
 const profiles=new Map<string,HTMLSelectElement>(),profile=node('fieldset');profile.append(node('legend','Original C′ profile'));for(const [key,values]of Object.entries(STAGE_PROFILE_AXES)){const f=choice(key,values);profiles.set(key,f);profile.append(label(key,f));}panel.append(profile);
 const language=choice('Existing full language binding',['absent','retain_original']);panel.append(label('Language binding',language),note('An existing full native language binding can be retained from loaded authorship. This form does not infer a language reading.'));
 const contributors=node('details'),contributorRows=node('div'),selected=new Map<string,FullNativeSubject>(),contributorNodes=new Map<string,{subject:FullNativeSubject;checkbox:HTMLInputElement;label:HTMLElement}>(),contributorNotice=note('');contributorRows.append(contributorNotice);contributors.append(node('summary','Source contributors'),contributorRows);panel.append(contributors);
 const members=table('Structural members',{subject_ref:{title:'Subject ref'},position:{title:'Position',type:'number'},face:{title:'Face'}}),returns=table('Source returns',{from_ref:{title:'From subject ref'},anchor_ref:{title:'Expression anchor ref'},ground_ref:{title:'Canonical place ref'},face:{title:'Face'},kind:{title:'Return kind'}}),relations=table('Source relations',{row_position:{title:'Row position',type:'number'},row_face:{title:'Row face'},column_position:{title:'Column position',type:'number'},column_face:{title:'Column face'},relation_ref:{title:'Relation Source ref'},evidence:{title:'Evidence refs · one per line',type:'list'}}),legs=table('Thread legs',{unit_ref:{title:'Unit ref'},subject_ref:{title:'Subject ref'},scope_ref:{title:'Scope ref'},input_refs:{title:'Original input refs · one per line',type:'list'},result_ref:{title:'Result ref'},after:{title:'Predecessor unit refs · one per line',type:'list'},parent:{title:'Parent unit ref · empty means absent',type:'optional'}});
 panel.append(members.root,returns.root,relations.root,legs.root);
 const threadFields=new Map<string,HTMLInputElement>();for(const key of ['aggregation_ref','continuation_ref','stop_condition_ref']){const f=field(key);threadFields.set(key,f);panel.append(label(`${key.replaceAll('_',' ')} · empty means absent`,f));}
 const openWorld=action('Open this selected Scene’s native World',()=>host.run(async()=>{const opened=await host.openWorld();status.textContent=`Native World admitted for ${opened.selected_scene.scene_ref} at Document ${opened.selected_scene.document_revision}. Procedural Source remains pending. Capture this accepted Scene basis and submit the complete original authorship. Typed fields remain unchanged.`;}));
 const recoverWorld=action('Recover the original native opening',()=>host.run(async()=>{const opened=await host.openWorld(true);status.textContent=`Original unconsumed native opening recovered for ${opened.selected_scene.scene_ref}. Capture its accepted Source basis explicitly; no Source or physical/audio acceptance was inferred.`;}));
 const abandonWorld=action('Abandon the original unresolved opening',()=>host.run(async()=>{await host.abandonWorld();status.textContent='The native owner acknowledged closure of the original opening. Typed Source fields and original Source intent remain retained.';}));
 const openingNote=note('');panel.append(openWorld,recoverWorld,abandonWorld,openingNote);
 const retainWorldSource=action('Save this native World source',()=>host.run(async()=>{const actor=required.get('actor_ref')!.value;if(!actor.trim())throw Error('Enter the original actor ref before saving this World source');const r=await host.retainWorldSource(actor);status.textContent=`Native World source saved at Document ${r.selected_scene.document_revision}. Capture this accepted Source basis; your original authored fields are unchanged.`;}));
 const recoverWorldSource=action('Recover the original World source save',()=>host.run(async()=>{const pending=host.pendingWorldSource();if(!pending)throw Error('No original World source request is retained');const r=await host.retainWorldSource(pending.actor,true);status.textContent=`The actual owner recovered the original source save at Document ${r.selected_scene.document_revision}. No getter, Edit, body or sound replay occurred.`;}));
 panel.append(retainWorldSource,recoverWorldSource);
 const capture=action('Capture the current accepted Scene basis',()=>host.run(async()=>{basis=clone(await host.captureBasis());readyForNewIntent=true;status.textContent=`Original intent · ${basis.expression_ref} · ${basis.scene_ref} · Document ${basis.document_revision}. Typed fields remain unchanged.`;}));
 const load=action('Load original native Source authorship',()=>host.run(async()=>{const originalControls=captureAuthoredControls([panel]);const actor=required.get('actor_ref')!.value;if(!actor.trim())throw Error('Enter the requesting actor before reading the original native Source authoring intent');const next=validateStageSourceAuthorship(await host.authored(actor));if(disposed||!originalControls())throw Error('Source authorship returned while your original typed fields changed. They remain retained; explicitly read again before loading the native authoring intent.');loaded=clone(next);for(const [key,f]of required)f.value=String(next[key as keyof StageSourceAuthorship]??'');role.value=next.principal_role;for(const [key,f]of frameFields)f.value=next.frame[key as keyof typeof next.frame];for(const [key,f]of profiles)f.value=next.profile[key as keyof typeof next.profile];language.value=next.language===null?'absent':'retain_original';selected.clear();next.contributors.forEach(row=>selected.set(row.subject_ref,clone(row)));members.load(next.members.map(row=>({subject_ref:row.subject_ref,...row.coordinate})));returns.load(next.source_returns.map(row=>({...row})));relations.load(next.relations.map(row=>({row_position:row.row.position,row_face:row.row.face,column_position:row.column.position,column_face:row.column.face,relation_ref:row.relation_ref,evidence:row.evidence})));legs.load(next.thread_plan.legs.map(row=>({...row})));for(const [key,f]of threadFields)f.value=next.thread_plan[key as keyof typeof next.thread_plan] as string??'';refreshContributors();const reading=host.authoringReading?.();status.textContent=reading?nativeAuthorshipDisclosure(reading):'Native authoring fields loaded explicitly; current Source/consumer qualification remains unobserved. Capture the current accepted Scene basis before submission.';}));
 function collect():StageSourceAuthorship {if(!language.value)throw Error('Choose explicit absence or retain an actual original full language binding');if(language.value==='retain_original'&&!loaded?.language)throw Error('Load an actual original full native language binding before retaining it');return validateStageSourceAuthorship({...Object.fromEntries([...required].map(([key,f])=>[key,key==='authority'?(f.value.trim()||null):f.value])),principal_role:role.value,contributors:[...selected.values()].map(clone),members:members.collect().map(row=>({subject_ref:row.subject_ref,coordinate:{position:row.position,face:row.face}})),source_returns:returns.collect(),relations:relations.collect().map(row=>({row:{position:row.row_position,face:row.row_face},column:{position:row.column_position,face:row.column_face},relation_ref:row.relation_ref,evidence:row.evidence})),frame:Object.fromEntries([...frameFields].map(([key,f])=>[key,f.value])),language:language.value==='absent'?null:clone(loaded!.language),profile:Object.fromEntries([...profiles].map(([key,f])=>[key,f.value])),thread_plan:{legs:legs.collect(),...Object.fromEntries([...threadFields].map(([key,f])=>[key,f.value.trim()||null]))}});}
 function describe(receipt:StageSourceBootstrapOutcome){if(isStageBootstrapRefusalObservation(receipt)){const document=receipt.document_receipt.document,reply=receipt.native_reply;status.textContent=`Native Source ${reply.state} · actual Document ${document.expression_ref} revision ${document.revision}. ${typeof reply.reason==='string'?reply.reason:'The source owner refused this original request.'} Original operation, authorship and typed fields remain retained. Read and requalify this actual Scene through its current native owner before a new operation.`;host.report(status.textContent);return;}const a=receipt.binding_adoption,timing=receipt.source.timing as Record<string,unknown>,position=receipt.source.native_position;const boundary=timing.domain==='native_samples'?`Performance body cursor ${position.samples_elapsed} · admission horizon ${timing.requested_cursor} · owner ${timing.owner_ref}. `:`Field cursor ${position.samples_elapsed} · owner ${timing.owner_ref}. `;status.textContent=boundary+(receipt.source_current?`Current native Source · ${receipt.source.native_scene_source.principal.subject_ref} · ${receipt.source.scene_ref} · Document ${receipt.source.document_revision}. Native graph/profile and timing were issued by this owner. Body, GPU and sound reception require their own observations.`:`Source issued at Document ${receipt.source.document_revision}; ${a.state} binding at Document ${a.document_revision_after}. ${receipt.qualification==='historical_unqualified'?'This historical retry grants no current Source.':'Read and requalify the actual current Scene through the same owner.'} The original intent is retained.`);host.report(status.textContent);}
 const submit=action('Bootstrap this original native Source',()=>host.run(async()=>{if(!basis||!readyForNewIntent)throw Error(intent?'The original Source intent is retained. Retry it or explicitly read/requalify before submitting another operation.':'Capture the current accepted Scene basis before submitting the original Source');const authored=collect();intent={basis:clone(basis),operation_ref:`operation:stage-source-${crypto.randomUUID()}`,authorship:authored};readyForNewIntent=false;describe(await host.submit(clone(intent)));}));
 const retry=action('Retry the original Source intent',()=>host.run(async()=>{if(!intent)throw Error('There is no original Source intent to retry');describe(await host.submit(clone(intent)));}));
 const requalify=action('Read and requalify the current Scene',()=>host.run(async()=>{if(!intent)throw Error('Retain a complete original authorship before requalification');const current=await host.captureBasis();basis=clone(current);readyForNewIntent=false;intent={basis:clone(current),operation_ref:`operation:stage-source-${crypto.randomUUID()}`,authorship:clone(intent.authorship)};describe(await host.submit(clone(intent)));}));
 panel.append(capture,load,submit,retry,requalify);
 function refreshContributors(){
  const actual=new Map(host.subjects().map(row=>[row.subject_ref,row])),visible=new Map([...actual,...selected]);
  for(const [ref,row]of contributorNodes)if(document.activeElement===row.checkbox&&!visible.has(ref))visible.set(ref,row.subject);
  for(const [ref,subject]of visible){
   let row=contributorNodes.get(ref);
   if(!row){
    const checkbox=field(`Contributor ${ref}`,'checkbox');checkbox.dataset.stageNativeContributor=ref;
    const wrapper=label('',checkbox);row={subject:clone(subject),checkbox,label:wrapper};contributorNodes.set(ref,row);contributorRows.append(wrapper);
    checkbox.addEventListener('change',()=>{
     if(checkbox.checked){const current=host.subjects().find(subject=>subject.subject_ref===ref);if(!current){checkbox.checked=selected.has(ref);host.report('This contributor no longer has a current native Source read. Its original retained identity was not replaced.');return;}selected.set(ref,clone(current));}
     else selected.delete(ref);
    });
    checkbox.addEventListener('blur',()=>refreshContributors());
   }
   row.checkbox.checked=selected.has(ref);
   const text=`${ref} · ${subject.native_owner} · ${subject.presentation_role}${actual.has(ref)?'':' · current Source unobserved'}`;
   if(row.label.firstElementChild?.textContent!==text)row.label.firstElementChild!.textContent=text;
  }
  for(const [ref,row]of contributorNodes)if(!visible.has(ref)){row.label.remove();contributorNodes.delete(ref);}
  contributorNotice.textContent=actual.size?'Choose contributors from the current full native Source read.':'Read the actual Stage scope to select full native contributors. None are inferred from display names.';
 }

 function refresh(){if(disposed)return;const sourceReason=host.sourceRetentionReason();retainWorldSource.disabled=!!sourceReason||!!host.pendingWorldSource();retainWorldSource.title=sourceReason??'Save the actual current native World source through this same owner.';recoverWorldSource.disabled=!host.pendingWorldSource();const opening=host.openingReason(),pending=host.pendingOpening();openWorld.disabled=!!opening;openWorld.title=opening??'Request the exact selected Scene/Document from its native owner.';recoverWorld.disabled=!pending;abandonWorld.disabled=!pending;openingNote.textContent=pending?'The complete original native opening is retained. Recovery queries that same owner; abandonment requires its actual closed receipt.':opening??'The retained current native World source is ready for an opening request; native qualification remains required.';const reason=host.availability();availabilityNote.textContent=reason??'The admitted selected-Scene owner is ready to receive the authored Source request. Every request still requires actual private Source/lease/original CAS qualification.';submit.disabled=!!reason;requalify.disabled=!!reason;submit.title=reason??'';requalify.title=reason??'';retry.disabled=!intent;retry.title=intent?'Retry preserves the exact original operation ID and authorship. Historical receipt grants no current Source.':'No original Source intent';refreshContributors();}
 refresh();return {panel,refresh,retainedIntent:()=>clone(intent),dispose(){disposed=true;selected.clear();contributorNodes.clear();loaded=null;}};
}
