import {createRequire} from 'node:module';import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require('../../../desktop/cradle/node_modules/playwright');const evidence=new URL('../evidence/',import.meta.url).pathname;
const fixture=JSON.parse(await readFile(evidence+'modulation-native-result.json','utf8'));
const palaceFixture=JSON.parse(await readFile(evidence+'native-result.json','utf8'));
async function inspect(ref=fixture.expression_ref){const data=await fetch('http://127.0.0.1:4186/op',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({op:'expression',request:{operation:'inspect',expression_ref:ref}})}).then(response=>response.json());assert.equal(data.ok,true);return data.outcome.data.document;}
const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[];page.on('pageerror',error=>errors.push(String(error)));
try{
 await page.goto('http://127.0.0.1:4298/?bridge=http://127.0.0.1:4186',{waitUntil:'domcontentloaded',timeout:120000});
 await page.getByRole('button',{name:'Modulation',exact:true}).click();await page.getByRole('textbox',{name:'Modulation rate',exact:true}).waitFor({timeout:25000});
 await page.locator('.editor-workbench').evaluate(element=>{element.style.width='440px';element.style.height='320px';});
 const rate=page.getByRole('textbox',{name:'Modulation rate',exact:true});await rate.fill('-');
 await page.getByRole('button',{name:'Expand Modulation',exact:true}).click();assert.equal(await rate.inputValue(),'-');
 await page.getByRole('button',{name:'Fold Modulation',exact:true}).click();await page.getByRole('button',{name:'Reopen Modulation',exact:true}).click();assert.equal(await rate.inputValue(),'-');
 const pinnedBefore=await inspect();const foreignScene=pinnedBefore.scenes.find(scene=>scene.scene_ref!==fixture.scene_ref);assert.ok(foreignScene.presentation.scene.automation.some(lane=>lane.id==='native-source'),'The second native Scene intentionally has the same lane ID.');
 await page.getByRole('button',{name:'Journey',exact:true}).click();await page.getByRole('group',{name:'Native scene sequence',exact:true}).getByRole('button',{name:'2. Second passage',exact:true}).click();
 await page.getByRole('button',{name:'Modulation',exact:true}).click();await page.getByText('Select the pinned native Scene to continue this Modulation edit.',{exact:false}).waitFor({timeout:15000});assert.equal(await rate.inputValue(),'-');assert.equal(await rate.isDisabled(),true);assert.equal(await page.getByRole('button',{name:'Apply',exact:true}).isDisabled(),true);const foreignAfter=await inspect();assert.deepEqual(foreignAfter.scenes.find(scene=>scene.scene_ref===foreignScene.scene_ref).presentation.scene.automation,foreignScene.presentation.scene.automation);
 await page.getByRole('button',{name:'Journey',exact:true}).click();await page.getByRole('group',{name:'Native scene sequence',exact:true}).getByRole('button').first().click();await page.getByRole('button',{name:'Modulation',exact:true}).click();await page.waitForFunction(()=>{const input=document.querySelector('input[aria-label="Modulation rate"]');return input&&!input.closest('fieldset[disabled]');});assert.equal(await rate.isDisabled(),false);assert.equal(await rate.inputValue(),'-');
 await page.getByRole('button',{name:'Cancel input',exact:true}).click();await page.getByRole('button',{name:'Compact Modulation',exact:true}).click();
 const before=await inspect(),nextRate=before.scenes.find(scene=>scene.scene_ref===fixture.scene_ref).presentation.scene.automation[0].rate===.875?.6875:.875;await rate.fill(String(nextRate));await page.getByRole('button',{name:'Apply',exact:true}).click();await page.getByText('Native modulation source readback confirmed.',{exact:true}).waitFor({timeout:20000});const after=await inspect();assert.equal(after.revision,before.revision+1);assert.equal(after.scenes.find(scene=>scene.scene_ref===fixture.scene_ref).presentation.scene.automation[0].rate,nextRate);
 await page.screenshot({path:evidence+'modulation-compact.png'});await page.getByRole('button',{name:'Expand Modulation',exact:true}).click();await page.locator('.editor-workbench').evaluate(element=>{element.style.width='1160px';element.style.height='780px';});const rangeBefore=await inspect(),linked=rangeBefore.scenes.find(scene=>scene.scene_ref===fixture.scene_ref).presentation.scene.automation.find(lane=>lane.id==='native-linked'),rangeMin=(linked.min+linked.max)/2;await page.getByRole('textbox',{name:'native-linked min',exact:true}).fill(String(rangeMin));await page.getByRole('button',{name:'Apply range',exact:true}).click();await page.getByText('Native target range readback confirmed.',{exact:true}).waitFor({timeout:20000});const rangeAfter=await inspect(),rangeLanes=rangeAfter.scenes.find(scene=>scene.scene_ref===fixture.scene_ref).presentation.scene.automation;assert.equal(rangeLanes.find(lane=>lane.id==='native-linked').min,rangeMin);assert.equal(rangeLanes.find(lane=>lane.id==='native-linked').syncWith,'native-source');assert.equal(rangeLanes.find(lane=>lane.id==='native-source').rate,nextRate);await page.screenshot({path:evidence+'modulation-full.png'});
 await page.getByRole('button',{name:'Journey',exact:true}).click();await page.getByRole('group',{name:'Native scene sequence',exact:true}).waitFor();await page.getByRole('button',{name:'Expand Journey',exact:true}).click();await page.getByRole('region',{name:'Glyph Sequence editor',exact:true}).waitFor({timeout:10000});const phraseBefore=await inspect(),nativeSceneBefore=phraseBefore.scenes.find(scene=>scene.scene_ref===fixture.scene_ref),entity=Object.values(nativeSceneBefore.presentation.scene.entities??{}).find(value=>value.sequence?.steps?.length===3)??nativeSceneBefore.presentation.scene.entities?.find?.(value=>value.sequence?.steps?.length===3);const states=entity?.sequence?.steps;assert.ok(states,'The fixture must disclose its real three-state phrase.');
 const nextHold=states[0].hold===1.375?1.625:1.375;const hold=page.getByRole('textbox',{name:'Hold · s',exact:true});await hold.fill(String(nextHold));await hold.press('Enter');let phraseAfter;for(let attempt=0;attempt<100;attempt++){phraseAfter=await inspect();const row=Object.values(phraseAfter.scenes.find(scene=>scene.scene_ref===fixture.scene_ref).presentation.scene.entities??{}).find(value=>value.id===entity.id);if(row?.sequence.steps[0].hold===nextHold)break;await new Promise(resolve=>setTimeout(resolve,200));};const afterEntity=Object.values(phraseAfter.scenes.find(scene=>scene.scene_ref===fixture.scene_ref).presentation.scene.entities??{}).find(value=>value.id===entity.id);assert.deepEqual(afterEntity.sequence.steps.map(step=>step.id),states.map(step=>step.id));assert.equal(afterEntity.sequence.steps[0].hold,nextHold);
 const glyphText=page.getByRole('textbox',{name:'State glyph content',exact:true});
 const retainedText='Retained source '+phraseAfter.revision;
 await glyphText.fill(retainedText+' initial');await page.getByRole('listbox',{name:'Glyph states',exact:true}).getByRole('option').nth(1).click();
 await page.getByText('Retained draft · '+states[0].id,{exact:true}).waitFor({timeout:15000});await glyphText.fill(retainedText);await page.getByRole('button',{name:'Replace glyph',exact:true}).click();
 let textAfter;for(let attempt=0;attempt<100;attempt++){textAfter=await inspect();const row=Object.values(textAfter.scenes.find(scene=>scene.scene_ref===fixture.scene_ref).presentation.scene.entities??{}).find(value=>value.id===entity.id);if(row?.sequence.steps[0].text===retainedText)break;await new Promise(resolve=>setTimeout(resolve,200));}
 const textEntity=Object.values(textAfter.scenes.find(scene=>scene.scene_ref===fixture.scene_ref).presentation.scene.entities??{}).find(value=>value.id===entity.id);assert.equal(textEntity.sequence.steps[0].text,retainedText);assert.equal(textEntity.sequence.steps[1].text,states[1].text);assert.deepEqual(textEntity.sequence.steps.map(step=>step.id),states.map(step=>step.id));await page.waitForFunction(()=>{const enabled=document.querySelector('button[aria-label="Glyph sequence enabled"]');return enabled&&!enabled.disabled;},{},{timeout:30000});await page.getByText('Retained draft · '+states[0].id,{exact:true}).waitFor({state:'hidden'});assert.equal(await glyphText.inputValue(),states[1].text);assert.equal(await page.getByRole('button',{name:'Replace glyph',exact:true}).isDisabled(),true);

 await page.screenshot({path:evidence+'journey-full.png'});await page.getByRole('button',{name:'Compact Journey',exact:true}).click();await page.locator('.editor-workbench').evaluate(element=>{element.style.width='500px';element.style.height='430px';});await page.screenshot({path:evidence+'journey-compact.png'});
 await page.getByRole('button',{name:'Palace',exact:true}).click();await page.getByRole('button',{name:'Expand Palace',exact:true}).click();await page.getByRole('textbox',{name:'New room name',exact:true}).waitFor({timeout:10000});await page.locator('.editor-workbench').evaluate(element=>{element.style.width='1160px';element.style.height='760px';});const palaceBefore=await inspect(palaceFixture.expression_ref);while(await page.getByRole('button',{name:'Remove room',exact:true}).count())await page.getByRole('button',{name:'Remove room',exact:true}).first().click();
 const sourceName='Source room '+palaceBefore.revision,composedName='Composed room '+palaceBefore.revision;for(const name of [sourceName,composedName]){await page.getByRole('textbox',{name:'New room name',exact:true}).fill(name);await page.getByRole('button',{name:'Add room',exact:true}).click();}
 const constituent=page.getByRole('combobox',{name:'Constituent for '+sourceName,exact:true});await constituent.selectOption(palaceFixture.member_ref);const sourceRef=await page.locator('.palace-composition article').filter({has:page.getByRole('button',{name:'1. '+sourceName,exact:true})}).locator('code').first().innerText(),composedRef=await page.locator('.palace-composition article').filter({has:page.getByRole('button',{name:'2. '+composedName,exact:true})}).locator('code').first().innerText();await page.getByRole('button',{name:'Save composition',exact:true}).click();await page.getByText(/Saved and read back at revision/).waitFor({timeout:20000});const palaceAfter=await inspect(palaceFixture.expression_ref);assert.ok(palaceAfter.revision>palaceBefore.revision);const sourceRoom=palaceAfter.scenes.find(scene=>scene.scene_ref===sourceRef);assert.ok(sourceRoom);assert.equal(sourceRoom.body.subject_ref,palaceFixture.member_ref);assert.ok(palaceAfter.scenes.some(scene=>scene.scene_ref===composedRef));await page.screenshot({path:evidence+'palace-full.png'});await page.getByRole('button',{name:'Compact Palace',exact:true}).click();await page.locator('.editor-workbench').evaluate(element=>{element.style.width='520px';element.style.height='350px';});await page.screenshot({path:evidence+'palace-compact.png'});
 const palaceJournal=await fetch('http://127.0.0.1:4186/op',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({op:'expression_recovery',request:{operation:'read',scope:'expressions',kind:'checkpoint',id:palaceFixture.checkpoint_id}})}).then(response=>response.json());assert.equal(palaceJournal.ok,true);assert.deepEqual(palaceJournal.outcome.data.record.value.view.document,palaceAfter,'The acknowledged Palace is recoverable through the current native journal');
 await writeFile(evidence+'native-browser-result.json',JSON.stringify({expression_ref:fixture.expression_ref,scene_ref:fixture.scene_ref,palace_expression_ref:palaceFixture.expression_ref,palace_revision:palaceAfter.revision,palace_source_scene:sourceRef,phrase_hold:nextHold,phrase_state_ids:states.map(step=>step.id),before_revision:before.revision,after_revision:after.revision,native_rate:nextRate,errors,confirmed:['native DocumentStore/NativeWorking receiving entrance','compact native modulation write and independent readback','following target range edited in full without replacing its source','uncommitted incomplete value across full/fold/reopen','pinned modulation input survives same-lane-ID foreign Scene without a foreign edit','rich native Glyph Sequence component reused inside Journey','same native phrase compact/full','stable glyph state IDs and native hold edit','pending glyph source retains its original state across selection and typing','two native Palace rooms with exact constituent and independent native readback','Palace native journal exactly matches acknowledged composition'],unverified:['native processing telemetry','native fullscreen/popout','Timeline/Places source renderer acceptance']},null,2));
 console.log(JSON.stringify({errors,body:(await page.locator('main').innerText()).slice(0,5000)}));assert.deepEqual(errors,[]);
}catch(error){await page.screenshot({path:evidence+'native-browser-failure.png'}).catch(()=>{});console.error('Browser body:',(await page.locator('body').innerText().catch(()=>'' )).slice(0,6000));throw error;}finally{await browser.close();}
