import test from 'node:test';import assert from 'node:assert/strict';
import {InstrumentPresentation} from '../src/frame/presentation.ts';
const constraints={compact:{width:400,height:220,minWidth:280,minHeight:170},full:{width:1000,height:700,minWidth:640,minHeight:440},aspect:'free',resize:'viewport',focusTargets:['canvas'],placements:['rack','dock','focused','popout']};
const target={ownerRef:'oi',subjectRef:'expression:editor-proof',instanceRef:'instrument:editor-proof',label:'Proof',sceneRef:'expression:editor-proof:scene:main'};
test('fold/reopen retains editor depth, native binding, geometry and pending input',()=>{const p=new InstrumentPresentation(target,constraints);p.setDepth('full');p.resize({x:90,y:80,width:1000,height:720});p.updateView({text:'Uncommitted'});p.setDraft(true);p.setDepth('folded');p.unfold();assert.equal(p.snapshot().depth,'full');assert.equal(p.snapshot().target.subjectRef,target.subjectRef);assert.equal(p.snapshot().view.text,'Uncommitted');assert.equal(p.snapshot().geometry.x,90);assert.equal(p.hasDraft,true);});
test('focus/selection cannot retarget an edit; explicit transfer clears only the admitted old view',()=>{const p=new InstrumentPresentation(target,constraints);p.setFollowSelection(true);p.setDraft(true);const next={...target,subjectRef:'expression:other'};const before=p.snapshot();assert.equal(p.selection(next),false);assert.notEqual(p.snapshot(),before,'standing changes notify React through a new snapshot');assert.equal(p.snapshot().target.subjectRef,target.subjectRef);assert.throws(()=>p.transfer(next),/Finish or cancel/);p.setDraft(false);p.transfer(next);assert.equal(p.snapshot().target.subjectRef,next.subjectRef);assert.deepEqual(p.snapshot().view,{});});
test('view recovery rejects foreign binding and keeps the current owner source revision',()=>{const p=new InstrumentPresentation({...target,sourceRevision:'r3'},constraints);p.updateView({text:'Retained'});const saved=p.checkpoint();saved.target.sourceRevision='r2';const restored=new InstrumentPresentation({...target,sourceRevision:'r3'},constraints,undefined,saved);assert.equal(restored.snapshot().target.sourceRevision,'r3');assert.equal(restored.snapshot().view.text,'Retained');saved.target.subjectRef='expression:foreign';assert.throws(()=>restored.restore(saved),/another native binding/);});
test('unavailable Surface relocation is refused without altering binding or geometry',async()=>{const p=new InstrumentPresentation(target,constraints);const before=p.checkpoint();await assert.rejects(p.relocate('popout'),/Surface relocation adapter/);assert.deepEqual(p.checkpoint(),before);});
test('native size constraints and malformed geometry are enforced',()=>{const p=new InstrumentPresentation(target,constraints);p.setDepth('full');p.resize({x:0,y:0,width:50,height:20});assert.equal(p.snapshot().geometry.width,640);assert.equal(p.snapshot().geometry.height,440);assert.throws(()=>p.resize({x:NaN,y:0,width:900,height:800}),/Invalid/);});

test('folded workspace recovery reopens the retained full editor and uncommitted input',()=>{const p=new InstrumentPresentation(target,constraints);p.setDepth('full');p.updateView({timing:'-'});p.setDepth('folded');const restarted=new InstrumentPresentation(target,constraints,undefined,p.checkpoint());restarted.unfold();assert.equal(restarted.snapshot().depth,'full');assert.equal(restarted.snapshot().view.timing,'-');});
test('independent nested draft owners cannot clear another editor edit',()=>{const p=new InstrumentPresentation(target,constraints);p.setFollowSelection(true);p.setDraft(true,'composition');p.setDraft(true,'integral');p.setDraft(false,'integral');assert.equal(p.hasDraft,true);assert.equal(p.selection({...target,subjectRef:'expression:other'}),false);p.setDraft(false,'composition');assert.equal(p.selection({...target,subjectRef:'expression:other'}),true);});
test('hidden presentation updates cannot reactivate graphics while native binding remains retained',()=>{const p=new InstrumentPresentation(target,constraints);p.setVisible(false);p.setDepth('full');p.updateView({text:'Hidden retained input'});p.resize({x:0,y:0,width:900,height:700});p.setFollowSelection(true);assert.equal(p.visible,false);assert.equal(p.snapshot().target.subjectRef,target.subjectRef);p.setVisible(true);assert.equal(p.visible,true);p.setDepth('folded');assert.equal(p.visible,false);p.unfold();assert.equal(p.visible,true);assert.equal(p.snapshot().view.text,'Hidden retained input');});
