import test from 'node:test';import assert from 'node:assert/strict';
import {receiveResearchHost} from '../src/research/receiver.ts';import {ResearchOperations} from '../src/research/operations.ts';
// Negative-only receiving fixtures: no successful native writes or owner
// acknowledgements are simulated. A returning stale read must never publish.
const setup=()=>{let view={document:{expression_ref:'expression:retained',revision:7,entities:{},scenes:[{scene_ref:'expression:retained:scene:one'}]},bindings:{one:{scene_ref:'expression:retained:scene:one',member_refs:[]}}};let calls=0,publish=0;let resolve;const source={nativeView:()=>view,sceneId:()=> 'one',read:()=>{calls++;return new Promise(done=>resolve=done);}};const receiver=receiveResearchHost(source,'one',{},new ResearchOperations(()=>{}),()=>publish++);return {receiver,get calls(){return calls;},get published(){return publish;},advance:()=>view={...view,document:{...view.document,revision:8}},return:value=>resolve(value)};};
const request={expression_ref:'expression:retained',revision:7,scene_ref:'expression:retained:scene:one'};
test('returning native publication is rejected after revision advances',async()=>{const scope=setup(),result=scope.receiver.read(request);scope.advance();scope.return({});await assert.rejects(result,/changed/);assert.equal(scope.published,0);});
test('foreign address is refused before invoking native read',async()=>{const scope=setup();await assert.rejects(scope.receiver.read({...request,scene_ref:'expression:retained:scene:other'}),/different Scene/);assert.equal(scope.calls,0);assert.equal(scope.published,0);});
test('host-wide unrelated subject cannot lend facets to this bound Scene',async()=>{const scope=setup(),result=scope.receiver.read(request);scope.return({contract:'ql.techne/v1',reading_ref:'reading:other',subject:{subject_ref:'subject:other',native_owner:'wiki'},disclosure:{instruments:[]}});await assert.rejects(result,/No source reading is bound/);assert.equal(scope.published,0);});
test('pinned source opening refuses another active owner Scene instead of borrowing its context',()=>{let opened=0;const source={nativeView:()=>({document:{expression_ref:'expression:retained',revision:7},bindings:{one:{scene_ref:request.scene_ref}}}),sceneId:()=> 'other',openSubject:()=>opened++};const errors=[];const receiver=receiveResearchHost(source,'one',{},new ResearchOperations(()=>{}),()=>{},message=>errors.push(message));receiver.openSubject('source:proof');assert.equal(opened,0);assert.match(errors[0],/pinned Scene/);});
