import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {NativeWorking} from '../../../desktop/cradle/expressions-app/field-studies-journeys/src/nativeWorking.ts';
import {openNativeWorkbench} from '../dev/nativeRecovery.ts';
const root=new URL(process.env.OI_EDITOR_EVIDENCE_URL??'../evidence/',import.meta.url),bridge=process.env.OI_EDITOR_TEST_BRIDGE??'http://127.0.0.1:4186';
const mode=process.argv[2],basisPath='/tmp/oi-instrument-editor-restart-basis.json';
async function call(op){const result=await fetch(bridge+'/op',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(op),signal:AbortSignal.timeout(30000)}).then(response=>response.json());assert.equal(result.ok,true,result.error);return result.outcome.data;}
async function json(file){return JSON.parse(await readFile(new URL(file,root),'utf8'));}
function digest(value){return createHash('sha256').update(JSON.stringify(value)).digest('hex');}
async function ownerProcess(){const {stdout}=await promisify(execFile)('lsof',['-t','-iTCP:'+new URL(bridge).port,'-sTCP:LISTEN']);const ids=[...new Set(stdout.trim().split(/\s+/))];assert.equal(ids.length,1);return Number(ids[0]);}
if(mode==='reopen'){
 const before=JSON.parse(await readFile(basisPath,'utf8')),reopened=[];
 for(const document of before.documents){const ref=document.expression_ref,record=(await call({op:'expression_recovery',request:{operation:'read',scope:'expressions',kind:'checkpoint',id:ref}})).record;assert.ok(record);assert.deepEqual(record.value.view.document,document,'The isolated journal must hold the same acknowledged native document');const work=new NativeWorking({expression:request=>call({op:'expression',request}),file:request=>call({op:'expression_file',request}),mint:()=>ref,checkpoint:async()=>{throw Error('Exact transferred recovery must not rewrite its journal');}});await openNativeWorkbench(work,ref,async()=>record.value,async()=>{throw Error('Open from the actual isolated journal before inspection');});assert.deepEqual((await call({op:'expression',request:{operation:'inspect',expression_ref:ref}})).document,document);reopened.push({expression_ref:ref,revision:document.revision,sha256:digest(document)});}
 await writeFile(new URL('isolation-reopen-result.json',root),JSON.stringify({reopened,confirmed:['six transferred native documents reopen exactly from actual isolated journals']},null,2));console.log(JSON.stringify({mode,reopened:reopened.length}));
}else if(mode==='capture'){
 const fixtures=[await json('native-result.json'),await json('modulation-native-result.json'),await json('recovery-native-result.json'),await json('workbench-native-result.json')];
 for(const file of ['research-browser-result.json','native-browser-result.json'])try{fixtures.push(await json(file));}catch(error){if(error.code!=='ENOENT')throw error;}
 const refs=new Set();
 function visit(value){if(typeof value==='string'&&/^expression:(modulation-editor|instrument-editor|instrument-member|research-editor)-[a-f0-9-]+$/.test(value))refs.add(value);else if(Array.isArray(value))value.forEach(visit);else if(value&&typeof value==='object')Object.values(value).forEach(visit);}
 fixtures.forEach(visit);assert.ok(refs.size>=3);
 const documents=[],checkpoints=[];for(const ref of refs){const result=await call({op:'expression',request:{operation:'inspect',expression_ref:ref}});assert.equal(result.document.expression_ref,ref);documents.push(result.document);const recovered=await call({op:'expression_recovery',request:{operation:'read',scope:'expressions',kind:'checkpoint',id:ref}});assert.ok(recovered.record,'Every accepted document needs its actual native journal');assert.deepEqual(recovered.record.value.view.document,result.document,'Do not restart with an unjournalled acknowledged native edit');checkpoints.push(recovered.record);}
 assert.ok(checkpoints.some(record=>record.value.pending),'Acceptance includes actual retained refused input');const process=await ownerProcess();await writeFile(basisPath,JSON.stringify({process,documents,checkpoints},null,2));console.log(JSON.stringify({mode,process,documents:documents.length,checkpoints:checkpoints.length}));
}else if(mode==='verify'){
 const before=JSON.parse(await readFile(basisPath,'utf8')),documents=[],checkpoints=[],process=await ownerProcess();assert.notEqual(process,before.process,'Acceptance requires an actual owner process restart');
 for(const document of before.documents){const ref=document.expression_ref,record=before.checkpoints.find(record=>record.id===ref);assert.ok(record);const closed=await fetch(bridge+'/op',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({op:'expression',request:{operation:'inspect',expression_ref:ref}})}).then(response=>response.json());assert.equal(closed.ok,false,'This work must be absent from the fresh process before native recovery');assert.match(closed.error,/Expression is not open/);
  const requests=[],work=new NativeWorking({expression:request=>{requests.push(request.operation);return call({op:'expression',request});},file:request=>call({op:'expression_file',request}),mint:()=>ref,checkpoint:async()=>{throw Error('Exact recovery must not rewrite the acknowledged native journal');}});
  const opened=await openNativeWorkbench(work,ref,async()=>(await call({op:'expression_recovery',request:{operation:'read',scope:'expressions',kind:'checkpoint',id:ref}})).record?.value,async()=>{throw Error('The native journal must reopen this work before inspection');});assert.deepEqual(requests,['open'],'Recovery cannot replay pending native edits');const pending=record.value.pending;assert.deepEqual(work.state.pending,pending);if(pending?.kind==='edit'||pending?.kind==='create')assert.deepEqual(opened.journey,pending.submitted.journey,'Retain submitted input across the real process restart');
  const actual=(await call({op:'expression',request:{operation:'inspect',expression_ref:ref}})).document;assert.deepEqual(actual,document,'Native document changed across process restart');documents.push({expression_ref:actual.expression_ref,revision:actual.revision,sha256:digest(actual),...(pending?{pending_kind:pending.kind,retained_input_sha256:digest(opened.journey)}:{})});}
 for(const record of before.checkpoints){const actual=(await call({op:'expression_recovery',request:{operation:'read',scope:'expressions',kind:'checkpoint',id:record.id}})).record;assert.deepEqual(actual,record,'Native recovery record changed across process restart');checkpoints.push({id:actual.id,revision:actual.revision,sha256:digest(actual)});}
 const result={bridge,previous_process:before.process,replacement_process:process,documents,checkpoints,confirmed:['native Expressions initially absent from fresh process','actual NativeWorking reopen from native disk journals before inspection','exact native documents after actual bridge process restart','exact acknowledged native recovery journal after restart','actual pending submitted input retained without replay after process restart'],unverified:['native detached window restoration','component-local unsaved glyph source text after process restart']};await writeFile(new URL('restart-result.json',root),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}else throw Error('Use reopen for transferred journals, capture before isolated restart, and verify after restart.');
