import {createRequire} from 'node:module';import {readFile,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require('../../../desktop/cradle/node_modules/playwright'),evidence=new URL('../evidence/',import.meta.url).pathname;
const modulation=JSON.parse(await readFile(evidence+'modulation-native-result.json','utf8')),palace=JSON.parse(await readFile(evidence+'native-result.json','utf8'));
async function call(op){const packet=await fetch('http://127.0.0.1:4186/op',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(op)}).then(response=>response.json());assert.equal(packet.ok,true,packet.error);return packet.outcome.data;}
async function captured(){const rows=[];for(const ref of [modulation.expression_ref,palace.expression_ref])rows.push({document:(await call({op:'expression',request:{operation:'inspect',expression_ref:ref}})).document,journal:(await call({op:'expression_recovery',request:{operation:'read',scope:'expressions',kind:'checkpoint',id:ref}})).record});return rows;}
const before=await captured(),browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[];page.on('pageerror',error=>errors.push(String(error)));
try{
 await page.goto('http://127.0.0.1:4298/?bridge=http://127.0.0.1:4186',{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'Modulation',exact:true}).click();await page.getByRole('textbox',{name:'Modulation rate',exact:true}).waitFor({timeout:30000});const rate=before[0].document.scenes.find(scene=>scene.scene_ref===modulation.scene_ref).presentation.scene.automation.find(row=>row.id==='native-source').rate;assert.equal(Number(await page.getByRole('textbox',{name:'Modulation rate',exact:true}).inputValue()),rate);
 await page.getByRole('button',{name:'Palace',exact:true}).click();await page.getByText('2 rooms',{exact:true}).waitFor({timeout:30000});await page.getByRole('button',{name:'Expand Palace',exact:true}).click();await page.getByRole('textbox',{name:'New room name',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Remove room',exact:true}).count(),2);assert.equal(await page.getByRole('button',{name:'Save composition',exact:true}).isDisabled(),true);await page.screenshot({path:evidence+'restart-native-workbench.png'});
 assert.deepEqual(await captured(),before,'Opening retained editors after native restart cannot edit native work or replay a pending journal');assert.deepEqual(errors,[]);const result={errors,confirmed:['actual receiving entrance opens journals after owner process restart','effective modulation source shown','both acknowledged Palace rooms restored','no native document/journal change while reopening components'],unverified:['native detached/fullscreen window restoration','component-local source text after restart']};await writeFile(evidence+'restart-browser-result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}finally{await browser.close();}
