import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {writeFile} from 'node:fs/promises';
import {NativeWorking} from '../../../desktop/cradle/expressions-app/field-studies-journeys/src/nativeWorking.ts';
import {DocumentStore} from '../../../desktop/cradle/expressions-app/field-studies-journeys/src/store.ts';
import {entity} from '../../../desktop/cradle/expressions-app/field-studies-journeys/src/model.ts';
import {nativeWorkbench} from '../dev/nativeWorkbench.ts';import {nativeWorkbenchJournal} from '../dev/nativeRecovery.ts';
const bridge=process.env.OI_EDITOR_TEST_BRIDGE??'http://127.0.0.1:4186';
async function call(op){const packet=await fetch(bridge+'/op',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(op),signal:AbortSignal.timeout(30000)}).then(response=>response.json());assert.equal(packet.ok,true,packet.error);return packet.outcome.data;}
test('actual receiving aperture keeps exact restored selection and owns one operation through overlapping read/refusals',async()=>{
 const ref='expression:instrument-editor-'+randomUUID(),expression=request=>call({op:'expression',request}),recovery=request=>call({op:'expression_recovery',request});
 await expression({operation:'create',expression_ref:ref,title:'Actual receiving overlap',actor:'agent:instrument-editor-native-test'});
 const journal=await nativeWorkbenchJournal(ref,recovery),work=new NativeWorking({expression,file:request=>call({op:'expression_file',request}),mint:()=>ref,checkpoint:journal.checkpoint}),view=await work.adopt((await expression({operation:'inspect',expression_ref:ref})).document),store=new DocumentStore(view.journey);
 store.change(document=>document.scenes[0].entities.push(entity('First native phrase','first'),entity('Second native phrase','second')));await work.commit({journey:store.document,sceneId:view.startSceneId,entityId:null});
 const second=store.document.scenes[0].entities.filter(value=>value.kind==='formation').at(-1),occurrence=work.state.view.bindings[view.startSceneId].occurrences.find(value=>value.view_entity_id===second.id),sceneRef=work.state.view.bindings[view.startSceneId].scene_ref;await work.select({scene_ref:sceneRef,entity_ref:occurrence.entity_ref});
 const receiver=await nativeWorkbench({kind:'bridge',url:bridge},ref,()=>{},()=>{}),initial=receiver.receiver.read();assert.deepEqual(initial.selection.entity_ids,[second.id],'Reopening retains the acknowledged second occurrence, not the first formation');
 const composing=receiver.palaceHost.composeExpression({expression_ref:ref,expected_revision:initial.basis.revision,changes:[{change:'scene_rename',scene_ref:sceneRef,title:'A real composed whole'}]});
 assert.equal(receiver.receiver.read().standing.pending,true);
 const read=receiver.request({operation:'read'}),refused=receiver.request({operation:'undo',basis:initial.basis}),history=assert.rejects(receiver.receiver.history('redo'),/awaiting acknowledgement/),select=assert.rejects(receiver.selectScene(sceneRef),/awaiting acknowledgement/),edit=receiver.edit(initial.basis,'unavailable-source',{rate:2});
 const [reading,rejection,, ,editReply]=await Promise.all([read,refused,history,select,edit]);assert.equal(reading.ok,true);assert.equal(reading.reading.standing.pending,true,'Read cannot release the active native composition');assert.equal(rejection.ok,false);assert.match(rejection.error,/awaiting acknowledgement/);assert.equal(editReply.ok,false);assert.match(editReply.error,/awaiting acknowledgement/);
 const ack=await composing;assert.equal(ack.ok,true);assert.equal(receiver.receiver.read().standing.pending,false);assert.deepEqual(receiver.receiver.read().selection.entity_ids,[second.id]);
 const native=(await expression({operation:'inspect',expression_ref:ref})).document;assert.equal(native.revision,initial.basis.revision+1);assert.deepEqual((await recovery({operation:'read',scope:'expressions',kind:'checkpoint',id:ref})).record.value.view.document,native);
 receiver.store.begin();await assert.rejects(receiver.palaceHost.composeExpression({expression_ref:ref,expected_revision:native.revision,changes:[{change:'scene_rename',scene_ref:sceneRef,title:'Forbidden during gesture'}]}),/Finish the retained native work/);receiver.store.finish();assert.deepEqual((await expression({operation:'inspect',expression_ref:ref})).document,native);
 const unsupported=await receiver.request({operation:'scene',basis:receiver.receiver.read().basis,action:'play'});assert.equal(unsupported.ok,false);assert.match(unsupported.error,/no Scene transport receiver/,'An unavailable native operation cannot return success');
 const field=await receiver.request({operation:'select-field',basis:receiver.receiver.read().basis});assert.equal(field.ok,true,field.error);assert.deepEqual(field.reading.selection.entity_ids,[]);const final=(await expression({operation:'inspect',expression_ref:ref})).document;assert.equal(final.selection.entity_ref,null);assert.equal(final.revision,native.revision+1);assert.deepEqual((await recovery({operation:'read',scope:'expressions',kind:'checkpoint',id:ref})).record.value.view.document,final);
 await writeFile(process.env.OI_EDITOR_EVIDENCE_DIR+'/workbench-native-result.json',JSON.stringify({expression_ref:ref,checkpoint_id:ref,revision:final.revision,selected_entity:occurrence.entity_ref,confirmed:['second native occurrence restored from actual journal','read and refused requests cannot clear another operation lease','history, Scene opening and modulation refuse overlapping native composition','one exact native composition and matching native journal','open gesture refuses before native dispatch','unavailable Scene transport refused instead of falsely acknowledged','Field selection actually clears native focus and advances its journal']},null,2));
});
