import type {JourneyReading, JourneySummaryReading, ProjectReading, RunReading} from "./run-reading"
import {runMapNodes, runOutcome, titleCase} from "./run-reading"

export function FactoryRunList({project,journeys,runReadings,selectedRun,pendingRun,onSelectRun}:{project:ProjectReading;journeys:Record<string,JourneyReading|undefined>;runReadings:Record<string,RunReading|undefined>;selectedRun?:string;pendingRun?:string;onSelectRun:(runRef:string)=>void}) {
 return <aside className="factory-run-list" aria-label="Factory Runs"><div className="factory-run-list-heading"><span>Runs</span><small>{project.journeys.reduce((total,journey)=>total+journey.runRefs.length,0)} published</small></div>{project.journeys.length===0&&<p>No Journeys are published for this Project.</p>}{project.journeys.map(journey=><JourneyRuns key={journey.journeyRef} journey={journey} detail={journeys[journey.journeyRef]} runReadings={runReadings} selectedRun={selectedRun} pendingRun={pendingRun} onSelectRun={onSelectRun}/>)}</aside>
}
function JourneyRuns({journey,detail,runReadings,selectedRun,pendingRun,onSelectRun}:{journey:JourneySummaryReading;detail?:JourneyReading;runReadings:Record<string,RunReading|undefined>;selectedRun?:string;pendingRun?:string;onSelectRun:(runRef:string)=>void}) {
 const runs=detail?.runRefs??journey.runRefs
 return <section className="factory-journey-row"><div className="factory-journey-context"><strong>{detail?.commission.purpose??journey.frontier??"Factory journey"}</strong><span>{titleCase(detail?.status??journey.status??"unknown")}</span></div>{runs.length===0&&<p>No Runs are named by this Journey.</p>}{runs.map((runRef,index)=>{const outcome=runOutcome(detail,runRef), run=runReadings[runRef]; return <button key={runRef} type="button" className={"factory-run-choice"+(selectedRun===runRef?" is-selected":"")} aria-pressed={selectedRun===runRef} onClick={()=>onSelectRun(runRef)}><span>{run?.destination??"Run "+(index+1)}</span><small>{pendingRun===runRef?"Loading…":outcome??(run?titleCase(run.lifecycle):"Details not read")}</small></button>})}<details className="factory-technical-detail"><summary>Source details</summary><code>{journey.journeyRef}</code>{detail?.commission.commission_ref&&<code>{detail.commission.commission_ref}</code>}</details></section>
}
export function FactorySelectedRunSummary({reading,journey,compact=false}:{reading:RunReading;journey?:JourneyReading;compact?:boolean}) {
 const nodes=runMapNodes(reading), outcome=runOutcome(journey,reading.runRef), workflow=nodes.filter(node=>node.kind==="work")
 return <section className={"factory-run-summary"+(compact?" is-compact":"")} aria-label="Selected Run summary"><div className="factory-run-summary-copy">{!compact&&<><p className="factory-run-kicker">{titleCase(reading.lifecycle)}</p><h2>{reading.destination}</h2>{journey?.commission.purpose&&<p>{journey.commission.purpose}</p>}</>}{outcome?<p className="factory-run-outcome"><strong>Returned outcome</strong>{outcome}</p>:<p className="factory-run-outcome">No returned outcome is recorded for this Run.</p>}</div><dl className="factory-run-facts"><div><dt>Workflow</dt><dd>{workflow.length?workflow.length+" work "+(workflow.length===1?"item":"items"):"No work items recorded"}</dd></div><div><dt>Map</dt><dd>{nodes.length?nodes.length+" "+(nodes.length===1?"node":"nodes"):"No nodes recorded"}</dd></div></dl>{!compact&&<details className="factory-technical-detail"><summary>Source details</summary><code>{reading.runRef}</code><code>{reading.projectRef}</code></details>}</section>
}
