import {useEffect,useState} from "react";
import {useKernel} from "../kernel/KernelProvider";
import type {CentralLocation} from "../kernel/types";
import {readFile,fileOperation,type FileHistory as History,type FilePreview} from "./client";
import {Loading} from "../shared/Loading";
/** Active-subject history plane. Every comparison is read through Central. */
export function FileHistory({location}:{location:CentralLocation}) {
 const {transport}=useKernel();const [history,setHistory]=useState<History>();const [preview,setPreview]=useState<FilePreview>();const [pending,setPending]=useState(true);const [error,setError]=useState<string>();const [available,setAvailable]=useState(false);
 useEffect(()=>{let live=true;void readFile(transport,location).then(async reading=>{if(!live)return;if(!reading.operations?.history.available){setAvailable(false);return;}setAvailable(true);const value=await fileOperation<History>(transport,location,{action:"history",limit:30});if(live)setHistory(value);}).catch(error=>{if(live)setError(String(error));}).finally(()=>{if(live)setPending(false);});return()=>{live=false;};},[location.ref]);
 const compare=async(revision:string)=>{setPending(true);setError(undefined);try{const current=await readFile(transport,location);setPreview(await fileOperation<FilePreview>(transport,location,{action:"recovery_preview",expected_revision:current.revision,revision}));}catch(error){setError(String(error));}finally{setPending(false);}};
 return <section aria-label="Central file history">{pending&&<Loading label="Reading file history…"/>}{error&&<p role="alert">{error}</p>}{!pending&&!available&&!error&&<p>No history operation is available for this subject.</p>}{history?.entries.length===0&&<p>No changes recorded by Central.</p>}{history?.entries.map(entry=><div key={entry.cursor}><p>{entry.actor} · {entry.actor_kind}</p><button disabled={pending} onClick={()=>void compare(entry.previous_revision)}>Before change {entry.cursor}</button><button disabled={pending} onClick={()=>void compare(entry.revision)}>After change {entry.cursor}</button></div>)}{history?.more&&<button disabled={pending} onClick={()=>{setPending(true);void fileOperation<History>(transport,location,{action:"history",limit:30,before:history.next_before??undefined}).then(next=>setHistory({...next,entries:[...history.entries,...next.entries]})).catch(error=>setError(String(error))).finally(()=>setPending(false));}}>Earlier changes</button>}{preview&&<><h3>Current</h3><pre className="file-history-content">{preview.current_content}</pre><h3>Selected revision</h3><pre className="file-history-content">{preview.content}</pre></>}</section>;
}
