import {kernelOp} from "../kernel/bridge";
import type {KnowledgeAddress,KnowledgeReading,KnowledgeRelations,KernelTransportStatus} from "../kernel/types";
import type {Change,ExpressionDocument,ExpressionRequest,ExpressionResult,ReadingRef,SubjectBinding} from "../expression/types";
import type {GraphNode} from "./graph";
export const KNOWLEDGE_EXPRESSION_LIMIT=10;
export type ParticipationForm="constellation"|"pair"|"triad"|"whole"|"direct-conjugate";
export interface OwnerParticipation {contract:"ql-mef/wiki-participation/v1";participation_ref:string;revision:number;form:ParticipationForm;members:{role:"member"|"direct"|"conjugate";canonical_ref:string;source_identity:string}[];provenance:{source_ref:string;source_revision?:string}[]}
export interface LocalMember {node:GraphNode;reading:KnowledgeReading}
export interface LocalWhole {locus:string;members:LocalMember[];edges:KnowledgeRelations["edges"];truncated:boolean;warnings:string[];pinned:string[];grammar:{state:"applied";participation:OwnerParticipation}|{state:"unavailable"|"stale";detail:string};relationBindingsUnavailable:number}
export type ProjectionOutcome={state:"ready";document:ExpressionDocument;whole:LocalWhole}|{state:"revision_conflict";whole:LocalWhole;result:ExpressionResult}|{state:"unavailable";whole?:LocalWhole;detail:string};
async function digest(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(v=>v.toString(16).padStart(2,"0")).join("").slice(0,32);}
export async function knowledgeExpressionRef(surface:string){return `expression:knowledge-${await digest(surface)}`;}
export async function knowledgeEntityRef(expressionRef:string,subjectRef:string){return `${expressionRef}:entity:k-${await digest(subjectRef)}`;}
function address(node:GraphNode):KnowledgeAddress|undefined{return node.kind==="wiki-node"||node.kind==="wiki-space"?{kind:"wiki",value:node.ref}:node.kind==="file"?{kind:"source",value:node.ref}:undefined;}
async function knowledge<T>(transport:KernelTransportStatus,project:string|undefined,request:import("../kernel/types").KnowledgeRequest){const r=await kernelOp(transport,{op:"knowledge",project,request});if(r.error||r.outcome?.result!=="knowledge")throw new Error(r.error??"Native knowledge owner unavailable");return r.outcome.data as T;}
export function validateParticipation(participation:OwnerParticipation|undefined,members:LocalMember[]):LocalWhole["grammar"]{
 if(!participation)return {state:"unavailable",detail:"The current owner reading disclosed no QL participation grammar."};
 if(participation.contract!=="ql-mef/wiki-participation/v1"||!Number.isInteger(participation.revision)||participation.revision<1||!(["constellation","pair","triad","whole","direct-conjugate"] as string[]).includes(participation.form)||participation.members.some(m=>!m.source_identity||!m.source_identity.includes(m.canonical_ref)||!/@[^@]+$/.test(m.source_identity)))return {state:"stale",detail:"Owner participation contract, revision, form, or source identity is invalid."};
 const refs=participation.members.map(m=>m.canonical_ref),unique=new Set(refs),actual=new Set(members.map(m=>m.node.ref));
 const cardinality=participation.form==="pair"||participation.form==="direct-conjugate"?refs.length===2:participation.form==="triad"?refs.length===3:participation.form==="constellation"?refs.length>=2:refs.length>=1;
 const roles=participation.form==="direct-conjugate"?participation.members.filter(m=>m.role==="direct").length===1&&participation.members.filter(m=>m.role==="conjugate").length===1:participation.members.every(m=>m.role==="member");
 const sources=participation.provenance.length>0&&participation.provenance.every(p=>p.source_ref&&p.source_revision&&members.some(m=>m.reading.evidence.includes(p.source_ref)&&m.reading.revision===p.source_revision));
 return unique.size===refs.length&&unique.size===actual.size&&refs.every(ref=>actual.has(ref))&&cardinality&&roles&&sources?{state:"applied",participation}:{state:"stale",detail:"Owner participation does not match the exact unique members, roles, cardinality, and source revisions of this local whole."};
}
/** Pull the owner's bounded relations first, then read every admitted member. */
export async function readLocalWhole(transport:KernelTransportStatus,project:string|undefined,locus:GraphNode,pins:GraphNode[]=[],participation?:OwnerParticipation,rootAddress?:KnowledgeAddress):Promise<LocalWhole>{
 const root=rootAddress??address(locus);if(!root)throw new Error(`Native relations are unavailable for ${locus.kind}: ${locus.ref}`);
 const relations=await knowledge<KnowledgeRelations>(transport,project,{action:"relations",address:root});const graphNodes=new Map([locus,...pins].map(n=>[n.ref,n]));
 for(const row of relations.nodes)if(!graphNodes.has(row.resource))graphNodes.set(row.resource,{ref:row.resource,label:row.label,kind:row.kind as GraphNode["kind"],native_owner:locus.native_owner,provenance:locus.provenance,actions:[]});
 const admitted=[locus.ref,...pins.map(n=>n.ref),...relations.nodes.map(n=>n.resource)].filter((ref,i,a)=>a.indexOf(ref)===i).slice(0,KNOWLEDGE_EXPRESSION_LIMIT),members:LocalMember[]=[];
 for(const ref of admitted){const node=graphNodes.get(ref),a=ref===locus.ref?root:node&&address(node);if(node&&a){const reading=await knowledge<KnowledgeReading>(transport,project,{action:"read",address:a});members.push({node:{...node,native_owner:reading.provider,provenance:{source:reading.authority,revision:reading.revision,detail:reading.evidence}},reading});}}
 const refs=new Set(members.map(m=>m.node.ref)),edges=relations.edges.filter(e=>refs.has(e.from)&&refs.has(e.to));
 if(!members.some(member=>member.node.ref===locus.ref))throw new Error(`Native local whole did not return a readable locus: ${locus.ref}`);
 return {locus:locus.ref,members,edges,truncated:relations.truncated||relations.nodes.length>members.length,warnings:relations.warnings,pinned:pins.map(n=>n.ref).filter(ref=>refs.has(ref)),grammar:validateParticipation(participation,members),relationBindingsUnavailable:edges.length};
}
function rr(member:LocalMember,ref=member.reading.resource):ReadingRef{return {ref,revision:member.reading.revision??"revision-unavailable",availability:member.reading.revision?"available":"unavailable"};}
function binding(member:LocalMember):SubjectBinding{return {subject_ref:member.node.ref,native_owner:member.reading.provider,presentation_role:"thing",sources:member.reading.evidence.length?member.reading.evidence.map(ref=>rr(member,ref)):[rr(member)],readings:[rr(member)],actions:[]};}
function glyph(member:LocalMember,whole:LocalWhole){if(whole.grammar.state==="applied"){const role=whole.grammar.participation.members.find(m=>m.canonical_ref===member.node.ref)?.role;if(role==="direct")return "◐";if(role==="conjugate")return "◑";return whole.grammar.participation.form==="pair"?"◒":whole.grammar.participation.form==="triad"?"△":whole.grammar.participation.form==="whole"?"◎":"✦";}return member.node.kind.startsWith("wiki")?"○":member.node.kind==="file"?"□":"·";}
export async function projectionChanges(document:ExpressionDocument,whole:LocalWhole){
 const expressionRef=document.expression_ref,sceneRef=`${expressionRef}:scene:knowledge`,prefix=`${expressionRef}:entity:k-`,ids=new Map<string,string>();for(const member of whole.members){const id=await knowledgeEntityRef(expressionRef,member.node.ref);if([...ids.values()].includes(id))throw new Error("Knowledge member identity collision");ids.set(member.node.ref,id);}
 const changes:Change[]=[];const scene=document.scenes.find(s=>s.scene_ref===sceneRef);if(!scene)changes.push({change:"scene_create",scene_ref:sceneRef,title:"Knowledge"});const wanted=new Set(ids.values());for(const entity of Object.values(document.entities))if(entity.entity_ref.startsWith(prefix)&&!wanted.has(entity.entity_ref)){if(document.scenes.some(s=>s.scene_ref!==sceneRef&&s.entity_refs.includes(entity.entity_ref)))throw new Error("Managed knowledge member is reused outside its bounded scene");changes.push({change:"entity_remove",entity_ref:entity.entity_ref});}
 whole.members.forEach((member,index)=>{const entity_ref=ids.get(member.node.ref)!,existing=document.entities[entity_ref];if(existing&&existing.subject?.subject_ref!==member.node.ref)throw new Error("Managed knowledge member changed outside its source binding");if(!existing)changes.push({change:"entity_add",scene_ref:sceneRef,entity_ref,title:member.node.label});const next=binding(member);if(!existing||JSON.stringify(existing.subject)!==JSON.stringify(next))changes.push({change:"subject_bind",entity_ref,binding:next});const angle=index*Math.PI*2/Math.max(1,whole.members.length),values={glyph:glyph(member,whole),x:Math.cos(angle)*500,y:Math.sin(angle)*350,z:0,scale:member.node.ref===whole.locus?1.4:.8,share:member.node.ref===whole.locus?1:.65};for(const [parameter,value] of Object.entries(values))if(!existing)changes.push({change:"parameter_set",entity_ref,parameter,value});});const ordered=[...whole.members.map(m=>ids.get(m.node.ref)!),...(scene?.entity_refs??[]).filter(ref=>!ref.startsWith(prefix))];if(!scene||JSON.stringify(scene.entity_refs)!==JSON.stringify(ordered))changes.push({change:"scene_compose",scene_ref:sceneRef,entity_refs:ordered});const focus=ids.get(whole.locus)!;if(document.selection.scene_ref!==sceneRef||document.selection.entity_ref!==focus)changes.push({change:"focus",scene_ref:sceneRef,entity_ref:focus});return changes;
}
async function expression(transport:KernelTransportStatus,request:ExpressionRequest){const r=await kernelOp(transport,{op:"expression",request});if(r.error||r.outcome?.result!=="expression")throw new Error(r.error??"Expression application unavailable");return r.outcome.data;}
export async function projectLocalWhole(transport:KernelTransportStatus,project:string|undefined,surface:string,locus:GraphNode,pins:GraphNode[]=[],participation?:OwnerParticipation,rootAddress?:KnowledgeAddress):Promise<ProjectionOutcome>{let whole:LocalWhole;try{whole=await readLocalWhole(transport,project,locus,pins,participation,rootAddress);}catch(e){return {state:"unavailable",detail:String(e)};}try{const expression_ref=await knowledgeExpressionRef(surface);let result:ExpressionResult;try{result=await expression(transport,{operation:"inspect",expression_ref});}catch{result=await expression(transport,{operation:"create",expression_ref,title:`Knowledge · ${locus.label}`,actor:"human:knowledge-expression"});}if(!result.document)return {state:"unavailable",whole,detail:"Expression application returned no document."};const changes=await projectionChanges(result.document,whole);if(changes.length===0)return {state:"ready",document:result.document,whole};result=await expression(transport,{operation:"edit",expression_ref,expected_revision:result.document.revision,actor:"human:knowledge-expression",changes});if(result.state==="revision_conflict")return {state:"revision_conflict",whole,result};return result.document?{state:"ready",document:result.document,whole}:{state:"unavailable",whole,detail:`Expression projection refused: ${result.state??"no result"}`};}catch(e){return {state:"unavailable",whole,detail:String(e)};}}
