import {useEffect,useRef,useState} from "react";
import {useKernel} from "../kernel/KernelProvider";
import {useExpressionStage,type StagePresentation} from "../stage/ExpressionStage";
import {expressionConfig} from "../expression/engineProjection";
import type {KnowledgeAddress} from "../kernel/types";
import type {GraphNode} from "./graph";
import {projectLocalWhole,type ProjectionOutcome} from "./expressionProjection";
export function KnowledgeExpression({surface,project,address,locus,pins,follow}:{surface:string;project?:string;address?:KnowledgeAddress;locus:GraphNode;pins:GraphNode[];follow:boolean}){
 const {transport}=useKernel(),stage=useExpressionStage();const [outcome,setOutcome]=useState<ProjectionOutcome>(),[busy,setBusy]=useState(false),[visible,setVisible]=useState(false),[stageError,setStageError]=useState("");const presentation=useRef<StagePresentation|null>(null),host=useRef<HTMLDivElement>(null),generation=useRef(0),alive=useRef(true);
 const close=()=>{generation.current++;presentation.current?.release();presentation.current=null;setVisible(false);setOutcome(undefined);setStageError("");};
 const projectWhole=async()=>{const current=++generation.current;setBusy(true);setStageError("");const next=await projectLocalWhole(transport,project,surface,locus,pins,undefined,address);if(!alive.current||current!==generation.current)return;setOutcome(next);setBusy(false);if(next.state!=="ready")return;try{const config=expressionConfig(next.document);let active=presentation.current;if(!active){active=stage.present({id:`knowledge-expression:${surface}`,plane:"overlay",recipe:"",config,sceneRef:next.document.selection.scene_ref});if(!active)throw new Error(stage.error??"The Expression stage refused this presentation");presentation.current=active;}active.setContainer(host.current);active.updateConfig(config,next.document.selection.scene_ref,next.document.selection.entity_ref?[next.document.selection.entity_ref]:[]);setVisible(true);}catch(e){presentation.current?.release();presentation.current=null;setVisible(false);setStageError(String(e));}};
 useEffect(()=>{if(follow&&presentation.current)void projectWhole();},[locus.ref,address?.kind,address?.value,pins.map(p=>p.ref).join("\0"),follow]);useEffect(()=>()=>{alive.current=false;generation.current++;presentation.current?.release();},[]);
 return <section className="knowledge-expression-controls" aria-label="Knowledge Expression"><div ref={host} className="knowledge-expression-host" data-active={visible}/><div className="knowledge-expression-actions"><button disabled={busy} onClick={()=>void projectWhole()}>{busy?"Projecting…":"Express local whole"}</button>{visible&&<button onClick={close}>Return to knowledge</button>}</div>{outcome?.state==="ready"&&<span role="status">{outcome.whole.members.length} subjects · {outcome.whole.edges.length} typed relations · Expression r{outcome.document.revision}{outcome.whole.truncated?" · owner result truncated":""}</span>}{outcome?.state==="ready"&&outcome.whole.grammar.state!=="applied"&&<span role="status">QL grammar unavailable</span>}{outcome?.state==="ready"&&outcome.whole.relationBindingsUnavailable>0&&<span role="status">Relation identity unavailable for {outcome.whole.relationBindingsUnavailable} owner edges</span>}{stageError&&<span role="alert">{stageError}</span>}{outcome?.state!=="ready"&&outcome&&<span role="alert">{outcome.state==="unavailable"?outcome.detail:"The Expression changed; project again from its current revision."}</span>}</section>;
}
