import {useEffect,useRef,useState} from 'react';
import type {KernelTransportStatus} from '../kernel/types';
import type {TechneTemporalFacet,TechneTemporalKind,TechneTemporalPrecision,TechnePlaceFacet} from '../techne/contract';
import {newRef,type NativeMember} from './construction';
import type {DraftMember} from './constructionDraft';
import {readParticipationEvidence} from './participationEvidence';
const kinds:TechneTemporalKind[]=['occurrence','receipt','valid','source-created','source-modified','day','now','session','run','generation','presentation'];
const precisions:TechneTemporalPrecision[]=['millennium','century','decade','year','month','day','hour','minute','second','subsecond'];
/** Draft inputs only. The enclosing constellation save retains its exact
 * pending operation and invokes the native frame CAS, as for role edits. */
export function ParticipationFacts({member,basis,transport,onChange}:{member:DraftMember;basis?:NativeMember;transport:KernelTransportStatus;onChange:(member:DraftMember)=>void}){
 const latest=useRef({member,onChange}),alive=useRef(true);latest.current={member,onChange};useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const [path,setPath]=useState(''),[reading,setReading]=useState(false),[error,setError]=useState('');
 const times=member.temporal??[],places=member.places??[],sources=member.facet_sources??[];
 const time=(index:number,patch:Partial<TechneTemporalFacet>)=>onChange({...member,temporal:times.map((row,i)=>i===index?{...row,...patch}:row)});
 const place=(index:number,patch:Partial<TechnePlaceFacet>)=>onChange({...member,places:places.map((row,i)=>i===index?{...row,...patch}:row)});
 const sourceControl=(value:string|null|undefined,onSelect:(source:string)=>void)=><label>Evidence source<select value={value??''} onChange={event=>onSelect(event.target.value)}><option value="">Choose a read evidence file…</option>{value&&!sources.some(row=>row.source_ref===value)&&<option value={value}>Saved evidence · read its file to change this fact</option>}{sources.map(row=><option key={row.source_ref} value={row.source_ref}>{row.title??row.location.path}</option>)}</select></label>;
 const read=async()=>{setReading(true);setError('');try{const source=await readParticipationEvidence(transport,path);if(alive.current&&latest.current.member.participation_ref===member.participation_ref){const current=latest.current.member;latest.current.onChange({...current,facet_sources:[...(current.facet_sources??[]).filter(row=>row.source_ref!==source.source_ref),source]});}}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setReading(false);}};
 const coord=(index:number,axis:0|1,value:string)=>{const current=places[index],xy=Array.isArray(current.geometry?.coordinates)?[...current.geometry.coordinates]:[null,null];xy[axis]=value.trim()?Number(value):null;place(index,{geometry:{type:'point',coordinates:xy},precision:current.precision==='unlocated'?'approximate':current.precision});};
 return <details className="wiki-participation-facts"><summary>Time and place · this participation</summary>
  <p>These facts describe this member in this constellation. They do not date the whole constellation or change other uses of its source. Save with “Save constellation”.</p>
  <label>Evidence file in this World<input value={path} onChange={event=>setPath(event.target.value)} placeholder="Work/Project/notes.md"/></label><button type="button" className="oi-action" disabled={reading||!path.trim()} onClick={()=>void read()}>{reading?'Reading evidence…':'Read evidence file'}</button>{sources.length>0&&<p role="status">{sources.length} evidence file{sources.length===1?'':'s'} read. Native revisions are checked again on save.</p>}{error&&<p role="alert">{error}</p>}
  <h4>Time</h4><p>Keep the source’s precision, such as year or century. Dates include a timezone. Historical dates use astronomical years: 0000 is 1 BCE; −000027 is 28 BCE (enter a plain minus sign).</p>{times.map((fact,index)=><fieldset key={fact.facet_ref??index}><legend>Time fact {index+1}</legend>
   <label>Meaning<select value={fact.kind} onChange={event=>time(index,{kind:event.target.value as TechneTemporalKind})}>{kinds.map(kind=><option key={kind} value={kind}>{kind.replaceAll('-',' ')}</option>)}</select></label>
   {fact.interval?<><label>From · date and time with timezone<input value={fact.interval.from??''} placeholder="2026-09-24T12:00:00Z" onChange={event=>time(index,{interval:{...fact.interval,from:event.target.value}})}/></label><label>Until · optional<input value={fact.interval.to??''} onChange={event=>time(index,{interval:{...fact.interval,to:event.target.value||null}})}/></label><label>Precision<select value={fact.interval.from_precision??'day'} onChange={event=>time(index,{interval:{...fact.interval,from_precision:event.target.value as TechneTemporalPrecision}})}>{precisions.map(value=><option key={value}>{value}</option>)}</select></label></>:<><label>At · date and time with timezone<input value={fact.instant??''} placeholder="2026-09-24T12:00:00Z" onChange={event=>time(index,{instant:event.target.value||undefined})}/></label><label>Precision<select value={fact.precision??'day'} onChange={event=>time(index,{precision:event.target.value as TechneTemporalPrecision})}>{precisions.map(value=><option key={value}>{value}</option>)}</select></label></>}
   {(['day_ref','now_ref','session_ref','run_ref'] as const).filter(key=>fact[key]!==undefined).map(key=><label key={key}>{key.replace('_ref','')} reference<input value={fact[key]??''} onChange={event=>time(index,{[key]:event.target.value||undefined})}/></label>)}
   {sourceControl(fact.source_ref,value=>time(index,{source_ref:value}))}<label>Uncertainty or qualification<input value={fact.uncertainty??''} onChange={event=>time(index,{uncertainty:event.target.value||null})}/></label><button type="button" className="oi-action" onClick={()=>onChange({...member,temporal:times.filter((_,i)=>i!==index)})}>Remove time fact {index+1}</button>
  </fieldset>)}
  <button type="button" className="oi-action" onClick={()=>onChange({...member,temporal:[...times,{facet_ref:newRef('wiki:temporal'),kind:'occurrence',instant:'',precision:'day',source_ref:sources[0]?.source_ref}]})}>Add time</button><button type="button" className="oi-action" onClick={()=>onChange({...member,temporal:[...times,{facet_ref:newRef('wiki:temporal'),kind:'valid',interval:{from:'',from_precision:'day'},source_ref:sources[0]?.source_ref}]})}>Add time range</button>
  <h4>Place</h4>{places.map((fact,index)=><fieldset key={fact.place_ref}><legend>Place fact {index+1}</legend><label>Name<input value={fact.identity?.names?.[0]?.name??''} onChange={event=>place(index,{identity:{...fact.identity,names:[{...fact.identity?.names?.[0],name:event.target.value},...(fact.identity?.names?.slice(1)??[])]}})}/></label><label>Precision<select value={fact.precision} onChange={event=>place(index,{precision:event.target.value as TechnePlaceFacet['precision']})}>{['exact','approximate','region','unlocated'].map(value=><option key={value}>{value}</option>)}</select></label>
   {fact.geometry?.type==='polygon'?<p>The saved region geometry is preserved; this form changes its name, precision and evidence.</p>:<><label>Longitude<input type="number" min={-180} max={180} step="any" value={Array.isArray(fact.geometry?.coordinates)?(fact.geometry.coordinates[0]??''):''} onChange={event=>coord(index,0,event.target.value)}/></label><label>Latitude<input type="number" min={-90} max={90} step="any" value={Array.isArray(fact.geometry?.coordinates)?(fact.geometry.coordinates[1]??''):''} onChange={event=>coord(index,1,event.target.value)}/></label>{fact.geometry&&<button type="button" className="oi-action" onClick={()=>place(index,{geometry:undefined,precision:'unlocated'})}>Remove coordinates</button>}</>}
   {sourceControl(fact.source_ref,value=>place(index,{source_ref:value}))}<label>Uncertainty or qualification<input value={fact.uncertainty??''} onChange={event=>place(index,{uncertainty:event.target.value||null})}/></label><button type="button" className="oi-action" onClick={()=>onChange({...member,places:places.filter((_,i)=>i!==index)})}>Remove place fact {index+1}</button>
  </fieldset>)}<button type="button" className="oi-action" onClick={()=>onChange({...member,places:[...places,{place_ref:newRef('wiki:place'),precision:'unlocated',identity:{names:[{name:''}]},source_ref:sources[0]?.source_ref}]})}>Add place</button>
  <button type="button" className="oi-action" onClick={()=>onChange({...member,temporal:structuredClone(basis?.['aikit.techne-facet/v1']?.temporal??[]),places:structuredClone(basis?.['aikit.techne-facet/v1']?.spatial??[])})}>Reset time and place to saved values</button>
 </details>;
}
