import {useEffect,useRef,useState} from 'react';
import type {TechneReading,TechneActionRoute,TechneInstrument,TechneExpressionBinding} from '../../../../desktop/cradle/src/techne/contract';
import {assertReading,resolveActionRoute} from '../../../../desktop/cradle/src/techne/m0m5/adapter';
import {palaceTraversal,palaceBasis,type PalaceComposition} from '../../../../desktop/cradle/src/techne/m0m5/palace/palace-state';
import {regionArchaeology,type PalaceRegionEntry,type PalaceRegionKey} from '../../../../desktop/cradle/src/techne/m0m5/palace/regions';
import {palaceReturnRoute,returnCrossing} from '../../../../desktop/cradle/src/techne/m0m5/palace/return';
import {restoreIntegralComposition,integralMove} from './integralState';
import {integralEntryAt,integralEntryContext,integralBookmark,integralBookmarkPosition} from './entryContext';
import type {InstrumentPresentation} from '../frame/presentation';
/** Execution acknowledgement is separate from the native routing receipt. */
export interface PalaceIntegralHost{
 reading:TechneReading;
 open(entry:PalaceRegionEntry,context:{readingRef:string;subjectRef:string;expressionBinding?:TechneExpressionBinding}):Promise<void>;
 executeReturn?(route:TechneActionRoute):Promise<{accepted:boolean;receipt:unknown;reason?:string}>;
 cross?(instrument:TechneInstrument):Promise<void>;
}
export function IntegralPalace(props:{host:PalaceIntegralHost;presentation:InstrumentPresentation;depth:'compact'|'full'}){
 assertReading(props.host.reading);
 return <IntegralBody key={palaceBasis(props.host.reading)} {...props}/>;
}
function IntegralBody({host,presentation,depth}:{host:PalaceIntegralHost;presentation:InstrumentPresentation;depth:'compact'|'full'}){
 const reading=host.reading,retained=presentation.snapshot().view.integral as {composition?:PalaceComposition;walk?:number;start?:string;selected?:string;selectedRegion?:PalaceRegionKey;selectedOccurrence?:number;intent?:string}|undefined;
 const [composition,setComposition]=useState(()=>restoreIntegralComposition(reading,retained?.composition));
 const [walk,setWalk]=useState(Number.isInteger(retained?.walk)?retained!.walk!:0),[start,setStart]=useState(retained?.start??'');
 const [selected,setSelected]=useState(retained?.selected??''),[selectedRegion,setSelectedRegion]=useState<PalaceRegionKey|undefined>(retained?.selectedRegion),[selectedOccurrence,setSelectedOccurrence]=useState(Number.isInteger(retained?.selectedOccurrence)?retained!.selectedOccurrence!:0),[intent,setIntent]=useState(retained?.intent??'');
 const [receipt,setReceipt]=useState<unknown>(),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const steps=palaceTraversal(composition),active=steps.length?steps[((walk%steps.length)+steps.length)%steps.length]:undefined;
 const focused=selected?(selectedRegion?composition.regions.find(region=>region.key===selectedRegion)?.entries:composition.regions.flatMap(region=>region.entries))?.filter(entry=>entry.ref===selected)[selectedOccurrence]:undefined;
 const focusedPlacement=selectedRegion?(composition.placements[selectedRegion]??[]).filter(position=>position.ref===selected)[selectedOccurrence]:undefined;
 const positionKey=(step:typeof steps[number])=>JSON.stringify([step.region,step.ref,step.locus]);
 const focusedContext:ReturnType<typeof integralEntryContext>=focused&&selectedRegion?integralEntryContext(reading,selectedRegion,focused.ref,selectedOccurrence):{};
 useEffect(()=>{presentation.updateView({...presentation.snapshot().view,integral:{composition,walk,start,selected,selectedRegion,selectedOccurrence,intent}});},[composition,walk,start,selected,selectedRegion,selectedOccurrence,intent,presentation]);
 useEffect(()=>{presentation.setDraft(Boolean(intent)||busy,'palace-integral');},[intent,busy,presentation]);
 const choose=(entry:PalaceRegionEntry,region:PalaceRegionKey,occurrence:number,locus:unknown)=>{setSelected(entry.ref);setSelectedRegion(region);setSelectedOccurrence(occurrence);const index=steps.findIndex(step=>step.region===region&&step.ref===entry.ref&&JSON.stringify(step.locus)===JSON.stringify(locus));if(index>=0)setWalk(index);};
 const open=async(entry:PalaceRegionEntry,context=focusedContext)=>{if(busy)return;presentation.setDraft(true,'palace-integral');setBusy(true);try{await host.open(entry,{readingRef:reading.reading_ref,subjectRef:reading.subject.subject_ref,...context});}catch(error){if(alive.current)setNotice(String(error));}finally{if(alive.current)setBusy(false);}};
 const submit=async()=>{if(busy)return;const route=palaceReturnRoute(reading,{...composition,bound:true});if(!route){setNotice('This reading has no disclosed governed Return route or attributable material.');return;}
  const routing=resolveActionRoute(reading,route);if(!routing.routed){setReceipt(routing);return;}
  if(!host.executeReturn){setReceipt(routing);setNotice('The owner execution adapter is unavailable. This routing receipt has not submitted a proposal.');return;}
  setBusy(true);presentation.setDraft(true,'palace-integral');
  try{const outcome=await host.executeReturn({...route,input:{...(route.input as object),intent}});if(!alive.current)return;setReceipt(outcome.receipt);if(!outcome.accepted){setNotice(outcome.reason??'The native owner refused this Return; the arrangement is retained.');return;}setNotice('The native owner acknowledged the Return proposal. Human acceptance follows its own owner route.');const crossing=returnCrossing(reading);if(crossing&&host.cross)await host.cross(crossing.instrument);}
  catch(error){if(alive.current)setNotice(String(error));}finally{if(alive.current)setBusy(false);}
 };
 return <section className="palace-integral" aria-label="Integral Palace">
 <div className="instrument-toolbar"><strong>Whole and constituents</strong><span>{steps.length} native positions</span><button disabled={!steps.length||busy} onClick={()=>setWalk(index=>index-1)}>Previous</button><button disabled={!steps.length||busy} onClick={()=>setWalk(index=>index+1)}>Next</button><label>Start<select aria-label="Palace named start" value={steps.some(step=>positionKey(step)===start)?start:''} onChange={event=>{setStart(event.target.value);setWalk(Math.max(0,steps.findIndex(step=>positionKey(step)===event.target.value)));}}><option value="">Choose a native position</option>{steps.map((step,index)=><option key={`${step.region}:${step.ref}:${index}`} value={positionKey(step)}>{step.region} · {step.ref} · locus {((step.locus.room.row*3+step.locus.room.column)*4+step.locus.locus)+1}</option>)}</select></label>{active&&<output>{active.region} · {active.ref}</output>}</div>
 <div className="palace-integral-board" data-depth={depth}>{composition.regions.map(region=><section key={region.key} className="palace-integral-region"><h3>{region.office.replace('Project / ground','Project / Graph')}</h3><p className="palace-standing">{regionArchaeology(reading,region)}</p><div className="palace-loci">{Array.from({length:24},(_,slot)=>{const here=composition.placements[region.key]?.filter(placement=>((placement.locus.room.row*3+placement.locus.room.column)*4+placement.locus.locus)===slot)??[];return <div key={slot} className="palace-locus" aria-label={`${region.office} locus ${slot+1}`} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();if(busy)return;try{const value=JSON.parse(event.dataTransfer.getData('application/x-oi-palace-locus'));if(value.basis!==composition.basis||value.region!==region.key)throw Error('A locus move must stay on the disclosed region and reading.');setComposition(integralMove(composition,region.key,value.ref,slot));}catch(error){setNotice(String(error));}}}>{here.map((placement,positionIndex)=>{const {entry,occurrence}=integralEntryAt(composition,region.key,placement);const context=integralEntryContext(reading,region.key,entry.ref,occurrence);return <button key={`${entry.ref}:${positionIndex}`} draggable={!busy&&region.entries.filter(value=>value.ref===entry.ref).length===1} data-focused={active?.ref===entry.ref&&active.region===region.key&&JSON.stringify(active.locus)===JSON.stringify(placement.locus)} title={entry.ref} onClick={()=>choose(entry,region.key,occurrence,placement.locus)} onDoubleClick={()=>void open(entry,context)} onDragStart={event=>event.dataTransfer.setData('application/x-oi-palace-locus',JSON.stringify({basis:composition.basis,region:region.key,ref:entry.ref}))} onKeyDown={event=>{if(!busy&&region.entries.filter(value=>value.ref===entry.ref).length===1&&event.altKey&&['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();setComposition(integralMove(composition,region.key,entry.ref,Math.max(0,Math.min(23,slot+(event.key==='ArrowRight'?1:-1)))));}}}>{entry.label}<small>{context.expressionBinding?.scene_ref??entry.ref}</small></button>;})}</div>;})}</div></section>)}</div>
 {depth==='full'&&<aside className="palace-integral-inspector">{focused?<><h3>{focused.label}</h3><code>{focused.ref}</code>{focusedContext.expressionBinding&&<p>Scene {focusedContext.expressionBinding.scene_ref} · revision {focusedContext.expressionBinding.revision??'not disclosed'}</p>}{focused.revision&&<p>Source revision {focused.revision}</p>}{focused.source&&<p>Source {focused.source}</p>}{focused.note&&<p>{focused.note}</p>}<button disabled={busy} onClick={()=>void open(focused)}>Open constituent</button><button disabled={!focusedPlacement||!selectedRegion||busy} onClick={()=>{if(focusedPlacement&&selectedRegion)setComposition(integralBookmark(composition,selectedRegion,focusedPlacement));}}>{composition.bookmarks.some(mark=>mark.ref===focused.ref&&mark.region===selectedRegion&&JSON.stringify(mark.locus)===JSON.stringify(focusedPlacement?.locus))?'Remove bookmark':'Bookmark position'}</button></>:<p>Select a constituent to inspect its native source and position.</p>}{composition.bookmarks.map(mark=><button key={mark.ref} onClick={()=>{try{const {entry,occurrence,placement}=integralBookmarkPosition(composition,mark);choose(entry,mark.region,occurrence,placement.locus);}catch(error){setNotice(String(error));}}}>{mark.region} · {mark.ref}</button>)}<label>Return intent<textarea aria-label="Palace Return intent" value={intent} onChange={event=>{presentation.setDraft(Boolean(event.target.value),'palace-integral');setIntent(event.target.value);}} maxLength={8192}/></label><button disabled={busy||!intent.trim()||!steps.length} onClick={()=>void submit()}>Return proposal</button><button disabled={busy||!intent} onClick={()=>{setIntent('');presentation.setDraft(false,'palace-integral');}}>Clear intent</button><p>Attributable proposal · await human acceptance at the native owner</p></aside>}
 {notice&&<p role="status">{notice}</p>}{receipt!==undefined&&<details open><summary>Native Return receipt</summary><pre>{JSON.stringify(receipt,null,2)}</pre></details>}
 </section>;
}
