import {useEffect,useRef,useState} from 'react';
import {regionSceneRef,type PalaceDocumentSnapshot,type PalaceRegionSpec} from '../../../../desktop/cradle/src/techne/m0m5/palace/composition';
import type {PalaceInstrumentHost,PalaceComposeResult,PalaceKernelExpression} from '../../../../desktop/cradle/expressions-app/field-studies-journeys/src/palaceInstrument';
import type {InstrumentPresentation} from '../frame/presentation';
import {planPalaceEdits,restorePalaceDraft,discoverPalaceRegions,type PalaceEditorChange} from './nativePlan';
import {IntegralPalace,type PalaceIntegralHost} from './IntegralPalace';
import './palace.css';
export interface PalaceEditorHost extends Omit<PalaceInstrumentHost,'composeExpression'>{composeExpression:(input:{expression_ref:string;expected_revision:number;changes:PalaceEditorChange[]})=>Promise<PalaceComposeResult>}

type Document=PalaceDocumentSnapshot&{title:string};
export interface PalaceEditorProps {host:PalaceEditorHost;expressionRef:string;depth:'compact'|'full';visible?:boolean;revision?:number|string;presentation:InstrumentPresentation;onSelectRoom?:(sceneRef:string)=>void;integral?:PalaceIntegralHost}
/** Reuses the native Palace composition law: one region is one real Scene,
 * its member is the Scene body and its entrance a Portal. No marker store. */
export function PalaceEditor(props:PalaceEditorProps){return <PalaceBody key={props.expressionRef} {...props}/>;}
function PalaceBody({host,expressionRef,depth,visible=true,revision,presentation,onSelectRoom,integral}:PalaceEditorProps){
 const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const initial=presentation.snapshot().view;const restored=restorePalaceDraft(initial,expressionRef);
 const [authoredRevision,setAuthoredRevision]=useState<number|undefined>(typeof initial.authoredRevision==='number'&&Number.isSafeInteger(initial.authoredRevision)?initial.authoredRevision:undefined);
 const [basis,setBasis]=useState<Document|undefined>(restored?.basis);const [regions,setRegions]=useState<PalaceRegionSpec[]>(restored?.regions??[]);
 const [removed,setRemoved]=useState<string[]>(restored?.removed??[]);
 const [selected,setSelected]=useState(typeof initial.selected==='string'?initial.selected:'');
 const [eligible,setEligible]=useState<PalaceKernelExpression[]>([]);const [newName,setNewName]=useState(typeof initial.newName==='string'?initial.newName:'');const [dirty,setDirty]=useState(restored?.dirty??false);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [changed,setChanged]=useState(false);
 const state=useRef({dirty,regions,newName});state.current={dirty,regions,newName};
 const update=(next:PalaceRegionSpec[])=>{if(busy)return;setRegions(next);setDirty(true);presentation.setDraft(true);};
 useEffect(()=>{let alive=true;if(!visible)return;const authored=host.authoredRevision();void host.readExpression(expressionRef).then(doc=>{if(!alive)return;if(doc.expression_ref!==expressionRef)throw Error('The native owner returned another Palace.');
 if(state.current.dirty||Boolean(state.current.newName)){if(doc.revision!==basis?.revision||host.authoredRevision()!==authoredRevision)setChanged(true);return;}setBasis(doc);setAuthoredRevision(host.authoredRevision()===authored?authored:undefined);setRegions(discoverPalaceRegions(doc));setChanged(false);
 }).catch(e=>{if(alive)setNotice(String(e));});void host.listExpressions().then(list=>{if(alive)setEligible(list.filter(row=>row.expression_ref!==expressionRef));}).catch(e=>{if(alive)setNotice(String(e));});return()=>{alive=false;};},[host,expressionRef,revision,visible]);
 useEffect(()=>{presentation.setDraft(dirty||busy||Boolean(newName));presentation.updateView({...presentation.snapshot().view,regions,removed,selected,basis,newName,authoredRevision});},[regions,removed,selected,basis,newName,authoredRevision,dirty,busy,presentation]);
 const select=(region:PalaceRegionSpec)=>{if(busy)return;setSelected(region.name);if(region.scene_ref)onSelectRoom?.(region.scene_ref);};
 const move=(name:string,delta:number)=>{const index=regions.findIndex(row=>row.name===name),to=index+delta;if(index<0||to<0||to>=regions.length)return;const next=[...regions];[next[index],next[to]]=[next[to],next[index]];update(next);};
 async function save(){if(busy||!basis||basis.expression_ref!==expressionRef)return;presentation.setDraft(true);setBusy(true);setNotice('');try{
 if(!host.canCompose()||host.authoredRevision()!==authoredRevision)throw Error('The native author has changed or has pending work. This Palace draft is retained; review and Revert only when you intend to discard it.');
 const fresh=await host.readExpression(expressionRef);if(!host.canCompose()||host.authoredRevision()!==authoredRevision)throw Error('The native author changed while reading the Palace. The composition draft is retained.');if(fresh.expression_ref!==expressionRef||fresh.revision!==basis.revision)throw Error('The Palace changed elsewhere. Your composition is retained; compare the current source before saving.');
 const changes=planPalaceEdits(basis,regions,removed);if(!changes){if(!mounted.current)return;setDirty(false);setNotice('The native composition already matches.');return;}
 const result=await host.composeExpression({expression_ref:expressionRef,expected_revision:basis.revision,changes});if(!result.ok)throw Error(result.reason);
 const readback=await host.readExpression(expressionRef);if(readback.expression_ref!==expressionRef)throw Error('Readback addressed another native Palace.');const actual=discoverPalaceRegions(readback);if(!mounted.current)return;
 const matches=actual.length===regions.length&&actual.every((region,index)=>region.name===regions[index].name&&region.scene_ref===(regions[index].scene_ref??regionSceneRef(expressionRef,regions[index].name))&&(region.member?.expression_ref??null)===(regions[index].member?.expression_ref??null)&&(!regions[index].member?.revision||region.member?.revision===regions[index].member?.revision));
 if(!matches)throw Error('The native readback differs from this composition. The draft is retained for review; do not repeat the save blindly.');
 setBasis(readback);setAuthoredRevision(host.authoredRevision());setRegions(actual);setRemoved([]);setDirty(false);setChanged(false);setNotice(`Saved and read back at revision ${readback.revision}.`);
 }catch(e){if(mounted.current)setNotice(String(e));}finally{if(mounted.current)setBusy(false);}}
 async function revert(){if(busy)return;presentation.setDraft(true);setBusy(true);try{const authored=host.authoredRevision();const doc=await host.readExpression(expressionRef);if(doc.expression_ref!==expressionRef)throw Error('The native owner returned another Palace.');if(!mounted.current)return;setBasis(doc);setAuthoredRevision(host.authoredRevision()===authored?authored:undefined);setRegions(discoverPalaceRegions(doc));setRemoved([]);setNewName('');setDirty(false);setChanged(false);setNotice('Draft reverted to the current native composition.');}catch(e){if(mounted.current)setNotice(String(e));}finally{if(mounted.current)setBusy(false);}}
 return <section className="instrument-palace" data-depth={depth} hidden={!visible} aria-label="Palace editor" aria-busy={busy}>
 <div className="instrument-toolbar"><strong>{basis?.title??'Palace'}</strong><span>{regions.length} rooms</span>{basis&&<span>r{basis.revision}</span>}<button disabled={busy||!dirty||!basis||basis.expression_ref!==expressionRef} onClick={()=>void save()}>Save composition</button>{(dirty||Boolean(newName))&&<button disabled={busy} onClick={()=>void revert()}>Revert draft</button>}{depth==='compact'&&<button onClick={()=>presentation.setDepth('full')}>Compose</button>}</div>
 {integral&&<IntegralPalace host={integral} depth={depth} presentation={presentation}/>}
 {changed&&<p role="status">The native or authored source has advanced. This draft remains on revision {basis?.revision}.</p>}{notice&&<p role="status">{notice}</p>}
 <svg className="palace-miniature" viewBox={`0 0 ${Math.max(320,regions.length*150)} 140`} role="group" aria-label="Rooms and guided path">{regions.map((region,index)=><g key={region.name} tabIndex={0} role="button" aria-label={`Open room ${region.name}`} onClick={()=>select(region)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();select(region);}}}>{index>0&&<path d={`M${index*150-30} 60h30`} stroke="currentColor"/>}<rect x={index*150+8} y={20} width={112} height={80} rx={2} fill={selected===region.name?'#716138':'#45484e'} stroke={selected===region.name?'#ffbe00':'#868990'}/><text x={index*150+16} y={45}>{index+1}. {region.name.slice(0,15)}</text><text x={index*150+16} y={68}>{region.member?.title?.slice(0,15)??(region.member?'Native work':'Empty room')}</text></g>)}</svg>
 {depth==='compact'&&selected&&<div className="instrument-toolbar"><span>{selected}</span><button disabled={regions[0]?.name===selected} onClick={()=>move(selected,-1)}>Earlier</button><button disabled={regions.at(-1)?.name===selected} onClick={()=>move(selected,1)}>Later</button>{regions.find(r=>r.name===selected)?.member&&<button onClick={()=>host.openExpression(regions.find(r=>r.name===selected)!.member!.expression_ref)}>Open work</button>}</div>}
 <fieldset className="palace-composition" disabled={busy||!basis||basis.expression_ref!==expressionRef} hidden={depth!=='full'}><section><h3>Rooms and constituents</h3>{regions.map((region,index)=><article key={region.name} data-selected={selected===region.name}><button onClick={()=>select(region)}>{index+1}. {region.name}</button><code>{region.scene_ref}</code><div className="instrument-toolbar"><button disabled={index===0} onClick={()=>move(region.name,-1)}>↑</button><button disabled={index===regions.length-1} onClick={()=>move(region.name,1)}>↓</button><button onClick={()=>{update(regions.filter(r=>r.name!==region.name));if(region.scene_ref&&basis?.scenes.some(scene=>scene.scene_ref===region.scene_ref))setRemoved(current=>[...current,region.scene_ref!]);}}>Remove room</button></div>{region.member?<div><strong>{region.member.title}</strong><code>{region.member.expression_ref}</code><button onClick={()=>host.openExpression(region.member!.expression_ref)}>Open constituent</button><button onClick={()=>update(regions.map(r=>r.name===region.name?{...r,member:null}:r))}>Detach constituent</button></div>:<select aria-label={`Constituent for ${region.name}`} value="" onChange={event=>{const member=eligible.find(row=>row.expression_ref===event.target.value);if(member)update(regions.map(r=>r.name===region.name?{...r,member:{expression_ref:member.expression_ref,title:member.title,revision:String(member.revision)}}:r));}}><option value="">Choose native Expression…</option>{eligible.map(row=><option key={row.expression_ref} value={row.expression_ref}>{row.title}</option>)}</select>}</article>)}<form onSubmit={event=>{event.preventDefault();const name=newName.trim();if(!basis||!name||regions.some(r=>r.name===name))return;const sceneRef=regionSceneRef(expressionRef,name);setRemoved(current=>current.filter(ref=>ref!==sceneRef));update([...regions,{name,scene_ref:sceneRef,member:null}]);setNewName('');}}><label>New room<input aria-label="New room name" value={newName} maxLength={80} onChange={e=>{presentation.setDraft(true);setNewName(e.target.value);}}/></label><button disabled={!newName.trim()||regions.some(r=>r.name===newName.trim())}>Add room</button></form></section><aside><h3>Native composition</h3><code>{expressionRef}</code><p>Each room holds one native Expression. Opening a constituent returns to its own work.</p>{basis&&<details><summary>Source basis</summary><pre>{JSON.stringify(basis,null,2)}</pre></details>}</aside></fieldset>
 </section>;
}
