import type { PanelContext } from '../shell/panels'
import { getPanels } from '../shell/panels'
import { displayDeviceName, type SetDocument } from '../shell/document'
import type { SetSelection } from './SessionView'
import { Icon } from './Icon'
export type DetailMode = 'clip' | 'device'
function Value({ label, value }: { label: string; value?: string }) {
  return <label className="clip-value"><span>{label}</span><input readOnly value={value ?? '—'} aria-label={label} title={value === undefined ? 'Value not disclosed by the document owner' : `${label} · read-only native document value`} /></label>
}
export function DeviceChainPanel({ ctx, document, selection, mode }: { ctx: PanelContext; document: SetDocument | null; selection: SetSelection; mode: DetailMode }) {
  const track = ctx.set?.tracks[selection.track]
  const deep = document?.tracks[selection.track]
  const clip = selection.clip === undefined ? undefined : deep?.arrangementClips[selection.clip]
  const sessionClip = selection.scene === null ? null : deep?.sessionSlots[String(selection.scene)]
  const name = clip?.name ?? sessionClip
  return <section className="chain" aria-label="Detail panel">
    {mode === 'clip' ? !name && !clip ? <div className="detail-no-selection">No clip selected.</div> : <><aside className="clip-inspector"><div className="clip-section-title"><span className="clip-color-chip" />{name || 'Clip'}</div><details open><summary>Clip</summary><div className="clip-values-pair"><Value label="Start" value={clip?.start.toString()} /><Value label="End" value={clip?.end.toString()} /></div><button disabled title="Duplicate requires the document editing owner">Duplicate</button><button disabled title="Loop writing requires native document editing">▣ Loop</button><div className="clip-values-pair"><Value label="Position" value={clip?.start.toString()} /><Value label="Length" value={clip ? (clip.end - clip.start).toString() : undefined} /></div><div className="clip-values-pair"><Value label="Signature" /><Value label="Groove" /></div><span className="clip-subheading">Scale</span><div className="clip-values-pair"><Value label="Root" /><Value label="Mode" /></div></details><details><summary>Launch</summary><Value label="Launch mode" /></details><details open><summary>Pitch &amp; Time</summary><button disabled title="Note editing requires native clip notes">Fit to Scale</button><button disabled title="Note editing requires native clip notes">Invert</button><Value label="Transpose" /><div className="clip-values-pair"><button disabled>×2</button><button disabled>÷2</button></div></details></aside>
      <div className="note-editor"><div className="note-toolbar"><button disabled>Fold</button><button disabled>Scale</button><label><input type="checkbox" disabled />Highlight Scale</label><span>{clip?.kind === 'audio' ? 'Audio' : 'Notes'}</span><output>{track?.name}</output></div><div className="note-ruler">{Array.from({ length: 20 }, (_, i) => <span key={i}>{Math.floor((clip?.start ?? 0) / 4) + i + 1}</span>)}</div><div className="note-grid"><div className="note-keyboard">{['C5', 'C4', 'C3', 'C2', 'C1', 'C0', 'C−1', 'C−2'].map(note => <span key={note}>{note}</span>)}</div><div className="note-grid-body" title="Note and waveform contents are not yet disclosed by the document owner" /></div><div className="velocity-lane"><span>Velocity</span><div /></div></div></>
      : <><div className="device-chain-surface">{track?.devices.map((name, i) => { const device = deep?.devices[i]; return <section key={i} className="device-tile"><div className="device-title"><span className="device-power" title="Device enable state not disclosed">●</span><Icon name="device" size={12} />{displayDeviceName(name)}<span>▾</span></div><div className="device-parameters">{device?.params.map(parameter => <label key={parameter.id} className="device-parameter" title={`${parameter.id}${parameter.min === undefined ? '' : ` · range ${parameter.min}–${parameter.max}`}`}><span>{parameter.id.replaceAll('/', ' › ')}</span><input aria-label={`${displayDeviceName(name)} ${parameter.id}`} value={parameter.value} readOnly title="Lossless document reading · parameter editing awaits native owner" /></label>)}{!device?.params.length && <div className="device-empty" title="No parameters disclosed by the native document">—</div>}</div></section> })}{track && !track.devices.length && <div className="detail-no-selection">No devices on this track.</div>}</div></>}
    {getPanels('bottom').map(panel => { const Panel = panel.component; return <div className="chain-side" key={panel.id}><Panel {...ctx} /></div> })}
  </section>
}
