import {useEffect,useRef,useState} from "react";
import {EditorButton,EditorFrame,useTextContextMenu} from "../editor/EditorChrome";
import {useKernel} from "../kernel/KernelProvider";
import type {SurfaceBinding} from "../surface/types";
import {flow} from "./client";
import "./flow.css";

export function FlowSurface({binding}:{binding:SurfaceBinding}){
 const kernel=useKernel();const input=useRef<HTMLTextAreaElement>(null);const textRef=useRef("");const [text,setText]=useState("");const [saved,setSaved]=useState("");const [revision,setRevision]=useState("");const [error,setError]=useState<string>();const [busy,setBusy]=useState(false);const [loaded,setLoaded]=useState(false);
 const key=`oi-flow-draft:${binding.flow?.flowRef}`;
 useEffect(()=>{let live=true;setLoaded(false);setError(undefined);void flow(kernel.transport,{action:"flow_read",project:binding.project!,flow_ref:binding.flow!.flowRef}).then(read=>{if(!live)return;setSaved(read.content??"");let draft:{text:string;revision:string}|undefined;let recoveryNotice:string|undefined;try{const raw=localStorage.getItem(key);if(raw){const parsed:unknown=JSON.parse(raw);if(parsed&&typeof parsed==="object"&&typeof (parsed as {text?:unknown}).text==="string"&&typeof (parsed as {revision?:unknown}).revision==="string")draft=parsed as {text:string;revision:string};else recoveryNotice="The saved local Flow draft has an unsupported shape. Its original recovery data was retained.";}}catch{recoveryNotice="The saved local Flow draft could not be read. Its original recovery data was retained.";}const content=draft?.text??read.content??"";textRef.current=content;setText(content);setRevision(draft?.revision??read.flow.current_revision);setLoaded(true);if(draft&&draft.revision!==read.flow.current_revision)setError("This Flow changed since your draft. Your writing is retained; saving will require resolving that revision.");else if(recoveryNotice)setError(recoveryNotice);}).catch(reason=>{if(live)setError(String(reason));});return()=>{live=false;};},[binding.id]);
 const change=(value:string)=>{textRef.current=value;setText(value);try{localStorage.setItem(key,JSON.stringify({text:value,revision}));}catch{setError("Draft recovery storage is unavailable; save your writing to Central.");}};
 const save=async()=>{if(!loaded||!revision||busy)return;const content=text;setBusy(true);setError(undefined);try{const read=await flow(kernel.transport,{action:"flow_write",project:binding.project!,flow_ref:binding.flow!.flowRef,expected_revision:revision,content,actor:"desktop-user",actor_kind:"human"});const nextRevision=read.flow.current_revision;setSaved(content);setRevision(nextRevision);try{if(textRef.current===content)localStorage.removeItem(key);else localStorage.setItem(key,JSON.stringify({text:textRef.current,revision:nextRevision}));}catch{setError("Your Flow was saved, but newer writing could not be kept in local recovery storage.");}}catch(reason){setError(String(reason));}finally{setBusy(false);}};
 const attach=()=>{const el=input.current;if(!el)return;const start=el.selectionStart,end=el.selectionEnd;const selected=end>start?text.slice(start,end):text;if(!selected.trim())return;window.dispatchEvent(new CustomEvent("oi:context-candidate",{detail:{bindingId:binding.id,kind:"text",text:selected,start:end>start?start:0,end:end>start?end:text.length,sourceRef:binding.ref,revision,workingCopy:text!==saved}}));};
 const selectionMenu=useTextContextMenu(binding,input,loaded&&!busy,change,attach);
 const wrap=(prefix:string,suffix=prefix)=>{const el=input.current;if(!el)return;const start=el.selectionStart,end=el.selectionEnd;el.focus();document.execCommand("insertText",false,prefix+text.slice(start,end)+suffix);};
 const status=!loaded?(error?"Unavailable":"Loading…"):busy?"Saving…":error?"Needs attention":text===saved?"Saved":"Unsaved";
 return <EditorFrame className="flow-surface" label="Flow editor"
  toolbar={<><EditorButton disabled={!loaded||busy} onMouseDown={e=>e.preventDefault()} onClick={()=>wrap("**")}>Bold</EditorButton><EditorButton disabled={!loaded||busy} onMouseDown={e=>e.preventDefault()} onClick={()=>wrap("_")}>Italic</EditorButton><EditorButton disabled={!loaded||busy} onMouseDown={e=>e.preventDefault()} onClick={()=>wrap("## ","")}>Heading</EditorButton><EditorButton disabled={!loaded||busy} onMouseDown={e=>e.preventDefault()} onClick={()=>wrap("- ","")}>List</EditorButton><EditorButton disabled={!loaded||busy} onMouseDown={e=>e.preventDefault()} onClick={()=>wrap("[","](https://)")}>Link</EditorButton><EditorButton disabled={!loaded||busy} onMouseDown={e=>e.preventDefault()} onClick={attach}>Attach selection @</EditorButton></>}
  footer={<><span className="editor-path" title={`${binding.ref}\n${binding.flow?.flowRef}`}>{binding.project} / {binding.flow?.path}</span><span role="status">{status}</span><button disabled={!loaded||busy||!revision||text===saved} onClick={()=>void save()}>Save · ⌘S</button></>}
 >
  {error&&<p role="alert" className="flow-error">{error}</p>}
  <textarea ref={input} disabled={!loaded} className="flow-writing" aria-label="Writing in Flow.md" placeholder={loaded?"Start writing…":"Loading Flow…"} value={text} onChange={e=>change(e.target.value)} onContextMenu={selectionMenu.onContextMenu} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==="s"){e.preventDefault();void save();}if((e.metaKey||e.ctrlKey)&&e.shiftKey&&e.key==="2"){e.preventDefault();attach();}}}/>
  {selectionMenu.menuNode}
 </EditorFrame>;
}
