import { useEffect, useState } from "react";
import { useKernel } from "../../kernel/KernelProvider";
import { EncounterList, type EncounterRow } from "../../encounter/EncounterList";
import "./agents.css";
import { readAgentRoster, proposeAgentProfile, type AgentProfileProposal, type AgentRoster } from "./client";
import { SessionSpaceControls } from "./SessionSpaceControls";
export interface AgentRosterSurfaceProps { project: string; projectRef: string; onOpenEncounter?: (row: EncounterRow) => Promise<void>; }
export function AgentRosterSurface({ project, projectRef, onOpenEncounter }: AgentRosterSurfaceProps) {
  const kernel = useKernel(); const [roster, setRoster] = useState<AgentRoster>(); const [error, setError] = useState<string>(); const [loading, setLoading] = useState(true); const [tick, setTick] = useState(0); const [form, setForm] = useState<AgentProfileProposal>({ profile_ref: "", agent_ref: "", revision: "", world_ref: "", intent_expression: "" }); const [proposal, setProposal] = useState<unknown>(); const [busy, setBusy] = useState(false);
  useEffect(() => { let live = true; setLoading(true); setError(undefined); setRoster(undefined); void readAgentRoster(kernel.transport, project, projectRef).then(v => { if (live) setRoster(v); }).catch(x => { if (live) setError(String(x)); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, [kernel.transport, project, projectRef, tick]);
  const required = ["profile_ref","agent_ref","revision","world_ref","intent_expression"] as const; const incomplete = required.some(name => !form[name].trim()); const propose = async () => { if (incomplete) return; setBusy(true); setError(undefined); try { setProposal(await proposeAgentProfile(kernel.transport, project, projectRef, form)); setForm(value => ({ ...value, intent_expression: "" })); } catch (x) { setError(String(x)); } finally { setBusy(false); } };
  const field = (name: keyof AgentProfileProposal, label: string) => <label>{label}<input value={form[name] ?? ""} onChange={event => setForm(value => ({ ...value, [name]: event.target.value }))} /></label>;
  return <section className="agents-roster" aria-label="Project Agents"><header><div><h2>Agents</h2><p>Durable project profiles and teams</p></div><button onClick={() => setTick(x => x + 1)} disabled={loading}>Refresh</button></header>{error && <p role="alert">{error}</p>}{loading && <p role="status">Reading Central Agents…</p>}<section><h3>Profiles</h3>{roster?.profiles.length ? <ul>{roster.profiles.map((p, i) => <li key={String(p.profile_ref ?? p.agent_ref ?? i)}><strong>{String(p.agent_ref ?? p.profile_ref ?? "Unnamed Agent")}</strong><span>{String(p.purpose ?? "Profile source")}</span><small>{String(p.revision ?? "revision unavailable")}</small></li>)}</ul> : roster && <p>No project AgentProfiles are authored.</p>}</section><section><h3>AgentSets</h3>{roster?.sets.length ? <ul>{roster.sets.map((s, i) => <li key={String(s.ref ?? i)}><strong>{String(s.ref ?? "Unnamed AgentSet")}</strong><span>{Array.isArray(s.members) ? `${s.members.length} declared members` : "Declared membership unavailable"}</span><small>{s.orchestrator_agent_ref ? `orchestrated by ${s.orchestrator_agent_ref}` : String(s.revision ?? "revision unavailable")}</small></li>)}</ul> : roster && <p>No project AgentSets are authored.</p>}</section><section><h3>Current sessions</h3>{onOpenEncounter ? <EncounterList project={project} onOpen={onOpenEncounter} /> : <p>Session controls are supplied by the canonical AIKit encounter Surface.</p>}</section><SessionSpaceControls project={project} projectRef={projectRef} /><details><summary>Propose a project AgentProfile</summary><p>This creates a Central proposal and leaves recognition to the owner.</p>{field("profile_ref", "Profile ref")}{field("agent_ref", "Agent ref")}{field("revision", "Revision")}{field("world_ref", "World ref")}{field("intent_expression", "Intent")}{field("purpose", "Purpose")}{field("role", "Role")}<button onClick={() => void propose()} disabled={busy || incomplete}>{busy ? "Proposing…" : "Propose profile"}</button>{proposal !== undefined && <pre data-proposal-standing="generated-proposal-unrecognised">{JSON.stringify(proposal, null, 2)}</pre>}</details></section>;
}
