import { kernelOp } from "../../kernel/bridge";
import type { ActionDispatch, KernelTransportStatus } from "../../kernel/types";
export type AgentProfile = Record<string, unknown> & { profile_ref?: string; agent_ref?: string; revision?: string; purpose?: string };
export type AgentSet = Record<string, unknown> & { ref?: string; revision?: string; members?: string[]; orchestrator_agent_ref?: string | null };
export type AgentRoster = { profiles: AgentProfile[]; sets: AgentSet[]; observed_at_unix_ms: number };
async function call(t: KernelTransportStatus,p:string,a:string,target:string,input:Record<string,unknown>):Promise<ActionDispatch>{const r=await kernelOp(t,{op:"invoke_action",project:p,invocation:{action:a,target_ref:target,input}});if(r.error)throw new Error(r.error);if(r.outcome?.result!=="action_dispatched")throw new Error("Central returned no Action dispatch result");return r.outcome.dispatch;}
export async function readAgentRoster(t:KernelTransportStatus,project:string,projectRef:string):Promise<AgentRoster>{const [p,s]=await Promise.all([call(t,project,"agent-profile.list",projectRef,{scope:"project",project}),call(t,project,"central.agent-set.list",projectRef,{scope:"project",project})]);if(p.state!=="invoked")throw new Error("AgentProfile listing unavailable");if(s.state!=="invoked")throw new Error("AgentSet listing unavailable");if(!p.data||typeof p.data!=="object"||!Array.isArray((p.data as Record<string,unknown>).profiles))throw new Error("Central returned an invalid AgentProfile list");if(!s.data||typeof s.data!=="object"||!Array.isArray((s.data as Record<string,unknown>).records))throw new Error("Central returned an invalid AgentSet list");return{profiles:(p.data as {profiles:AgentProfile[]}).profiles,sets:(s.data as {records:AgentSet[]}).records,observed_at_unix_ms:Date.now()};}
export interface AgentProfileProposal { profile_ref: string; agent_ref: string; revision: string; world_ref: string; intent_expression: string; role?: string; purpose?: string; }
export async function proposeAgentProfile(t:KernelTransportStatus,project:string,projectRef:string,input:AgentProfileProposal):Promise<unknown>{const r=await call(t,project,"agent-profile.propose",projectRef,{scope:"project",project,...input});if(r.state!=="invoked")throw new Error("Central did not accept the AgentProfile proposal");return r.data;}
export type SessionSpaceRequest = { action: "discover"; project: string } | { action: "project_context" } | { action: "create"; id: string; label?: string } | { action: "stage"; space?: string; intent: unknown } | { action: "apply"; preview: unknown } | { action: "open"; space: string } | { action: "resolve_working"; space: string; agent_session: string; surface?: string };
export async function sessionSpace(t: KernelTransportStatus, project: string, request: SessionSpaceRequest): Promise<unknown> { const result = await kernelOp(t, { op: "session_space", project, request }); if (result.error) throw new Error(result.error); if (result.outcome?.result !== "session_space_reading") throw new Error("AIKit did not return a SessionSpace reading"); return result.outcome.data; }
