/**
 * The Expression verso — the back of ONE Expression (ES2), rendered over the
 * same identity the front's engine body presents. This component renders the
 * generated verso reading (`verso.mjs`): bound subjects with their sources
 * and disclosed Actions, relation bindings, available representations and
 * provenance — refs and availability only, never a source body, never front
 * material state.
 *
 * It is a reading, not a second inspector shell and not a fixed
 * database-property panel: it renders what the document actually carries and
 * stays sparse when the document is sparse. Every semantic address rides on
 * the element as data, so the human reading and a structured Agent reading
 * name the same refs. The front's stage presentation stays alive (suspended)
 * underneath the flip; nothing here remints, releases or re-opens identity.
 */
import {useMemo} from "react";
import {versoReading} from "./verso.mjs";
import type {ExpressionDocument} from "./types";

/** The verso reading's shape (generated by verso.mjs, refs only). */
interface VersoReading {
  schema: string;
  expression_ref: string;
  revision: number;
  title: string;
  selected_scene_ref: string | null;
  selected_entity_ref: string | null;
  scenes: {scene_ref: string; title: string; entity_count: number}[];
  subjects: {ref: string; native_owner: string; presentation_role: "being" | "thing"; entities: string[];
    sources: {ref: string; revision: string; availability: string}[];
    actions: {action_ref: string; target_ref: string; authority_requirement: string}[]}[];
  relations: {binding_ref: string; relation: {ref: string; revision: string; availability: string}; from_entity_ref: string; to_entity_ref: string}[];
  representations: {kind: string; ref: string; revision: string; availability: string}[];
  provenance: {ref: string; revision: string}[];
}

export function ExpressionVerso({document,onInvokeAction,onOpenRef}:{document:ExpressionDocument;onInvokeAction?:(entityRef:string,actionRef:string)=>void;onOpenRef?:(ref:string)=>void}) {
  const verso=useMemo<VersoReading>(()=>versoReading(document) as VersoReading,[document]);
  return <article className="expression-verso" aria-label={`Verso of ${verso.title||verso.expression_ref}`}
    data-expression-ref={verso.expression_ref} data-expression-revision={verso.revision}
    data-verso-schema={verso.schema}
    data-subject-count={verso.subjects.length} data-relation-count={verso.relations.length}
    data-representation-count={verso.representations.length}>
    <header className="expression-verso__head">
      <div className="world-component__eyebrow">Verso · the same Expression, read</div>
      <h3>{verso.title||verso.expression_ref}</h3>
      <small><span className="oi-ref">{verso.expression_ref}</span> · revision {verso.revision}{verso.selected_scene_ref?<> · scene <span className="oi-ref">{verso.selected_scene_ref}</span></>:null}</small>
    </header>
    {verso.subjects.length>0&&<section className="expression-verso__region" aria-label="Bound subjects" data-region="subjects">
      <h4>Bound subjects · {verso.subjects.length}</h4>
      {verso.subjects.map(subject=><article key={subject.ref} className="expression-verso__subject" data-subject-ref={subject.ref} data-native-owner={subject.native_owner} data-presentation-role={subject.presentation_role}>
        <header><strong>{subject.ref}</strong><span className="oi-state">{subject.presentation_role} · {subject.native_owner||"native owner"}</span></header>
        {subject.entities.map(ref=><button key={ref} type="button" className="oi-ref expression-verso__entity" title="Focus this entity on the front" onClick={()=>onOpenRef?.(ref)}>{ref}</button>)}
        {subject.sources.length>0&&<dl className="expression-verso__sources">{subject.sources.map(source=><div key={`${source.ref}@${source.revision}`} data-source-ref={source.ref} data-source-availability={source.availability}><dt><code>{source.ref}</code></dt><dd>{source.availability}{source.revision?` · ${source.revision}`:""}</dd></div>)}</dl>}
        {subject.actions.length>0&&<div className="expression-verso__actions" data-action-count={subject.actions.length}><span className="oi-eyebrow">Disclosed Actions · {subject.native_owner}</span><div className="oi-action-group">{subject.actions.map(action=><button key={action.action_ref} type="button" className="oi-action" title={action.authority_requirement||"authority per caller"} onClick={()=>onInvokeAction?.(subject.entities[0],action.action_ref)}>{action.action_ref}</button>)}</div></div>}
      </article>)}
    </section>}
    {verso.relations.length>0&&<section className="expression-verso__region" aria-label="Relation bindings" data-region="relations">
      <h4>Relations · {verso.relations.length}</h4>
      <ul className="expression-verso__relations">{verso.relations.map(relation=><li key={relation.binding_ref} data-binding-ref={relation.binding_ref} data-relation-ref={relation.relation.ref}>
        <button type="button" className="oi-ref" onClick={()=>onOpenRef?.(relation.relation.ref)}>{relation.relation.ref}</button>
        <span>{relation.from_entity_ref} → {relation.to_entity_ref}{relation.relation.revision?` · ${relation.relation.revision}`:""}</span>
      </li>)}</ul>
    </section>}
    {verso.representations.length>0&&<section className="expression-verso__region" aria-label="Available representations" data-region="representations">
      <h4>Representations · {verso.representations.length}</h4>
      <ul className="expression-verso__representations">{verso.representations.map(representation=><li key={`${representation.kind}:${representation.ref}`} data-representation-kind={representation.kind} data-availability={representation.availability}>
        {representation.kind} · {representation.ref}{representation.revision?` · ${representation.revision}`:""} · {representation.availability}
      </li>)}</ul>
      <p className="oi-note">The live renderer presents on the front. Captures and pages render where their own renderers are admitted; availability is disclosed, never silently substituted.</p>
    </section>}
    {verso.subjects.length===0&&verso.relations.length===0&&verso.representations.length===0&&verso.provenance.length===0&&
      <p className="oi-note expression-verso__sparse" data-sparse="true">This Expression carries no bound subjects, relations, representations or provenance yet. The verso stays as sparse as the thing itself.</p>}
    {verso.provenance.length>0&&<details className="expression-verso__provenance oi-disclosure" data-region="provenance">
      <summary>Provenance · {verso.provenance.length}</summary>
      <ul>{verso.provenance.map(reading=><li key={`${reading.ref}@${reading.revision}`}><code>{reading.ref}</code>{reading.revision?` · ${reading.revision}`:""}</li>)}</ul>
    </details>}
  </article>;
}
