/**
 * The Expression verso — the back of ONE subject (ES2 + owner Wayfinder
 * §10), rendered over the same identity the face presents. Two readings
 * compose here over the SAME subject, never two objects:
 *
 *  - the generated verso reading (`verso.mjs`) when an `oi.expression/v1`
 *    document stands: bound subjects with their sources and disclosed
 *    Actions, relation bindings, available representations, provenance —
 *    refs and availability only, never a source body, never front material
 *    state;
 *  - the account depth (`versoAccount.ts`, owner Wayfinder §10) when the
 *    host supplies an account: World/Project/ProjectCentral identity, the
 *    position in the ONE wiki projection state, the exact source files with
 *    real open paths, the actual page content through the owners (honest
 *    states, never invented), saved Expression editions where the owner
 *    supplies them, the scene breakdown as list/tree/bounded graph, eligible
 *    Actions, and the Return trail where the host carries one.
 *
 * It is a reading, not a second inspector shell and not a fixed
 * database-property panel: it renders what the owners actually disclose and
 * stays sparse when the subject is sparse. Every semantic address rides on
 * the element as data, so the human reading and a structured Agent reading
 * name the same refs.
 *
 * IDENTITY PRESERVATION (face ↔ verso): the verso performs no write, no
 * kernel edit and no selection change — opening it cannot move the field,
 * and closing it returns to the exact position it opened from. The root
 * carries the subject's full address (data-subject-ref, data-scene-ref,
 * data-entity-ref, data-expression-ref, data-register-key) plus the
 * open-time position snapshot (data-open-scene-ref / data-open-entity-ref),
 * so a walk can prove nothing moved.
 */
import {useMemo, useState} from "react";
import {versoReading} from "./verso.mjs";
import type {ExpressionDocument} from "./types";
import {useWikiProjectionState, wikiRegisterOwning, wikiProjectionOf, wikiDocumentOf} from "../techne/wikiProjectionStore";
import type {VersoAccountReading} from "./versoAccount";
import "./verso.css";

/** The verso reading's shape (generated by verso.mjs, refs only). */
interface VersoReading {
  schema: string;
  expression_ref: string;
  revision: number;
  title: string;
  selected_scene_ref: string | null;
  selected_entity_ref: string | null;
  scenes: {scene_ref: string; title: string; entity_count: number}[];
  subjects: {ref: string; native_owner: string; presentation_role: "being" | "thing"; entities: string[];
    sources: {ref: string; revision: string; availability: string}[];
    actions: {action_ref: string; target_ref: string; authority_requirement: string}[]}[];
  relations: {binding_ref: string; relation: {ref: string; revision: string; availability: string}; from_entity_ref: string; to_entity_ref: string}[];
  representations: {kind: string; ref: string; revision: string; availability: string}[];
  provenance: {ref: string; revision: string}[];
}

type Aperture = "list" | "tree" | "graph";

export function ExpressionVerso({document, account, onInvokeAction, onOpenRef, onClose, onOpenSourceRef, onOpenPage}: {
  /** The face's own Expression document, when the face is an Expression. */
  document?: ExpressionDocument;
  /** The subject's account depth (versoAccount.ts), when the host supplies one. */
  account?: VersoAccountReading;
  onInvokeAction?: (entityRef: string, actionRef: string) => void;
  onOpenRef?: (ref: string) => void;
  onClose?: () => void;
  /** Open one exact source ref — resolved through the files seam by the host before it opens. */
  onOpenSourceRef?: (sourceRef: string) => void;
  /** Open the subject's wiki page through the frame's knowledge path. */
  onOpenPage?: (ref: string, title?: string) => void;
}) {
  const versoDocument = document ?? (account?.state === "ready" ? account.account.document : undefined);
  const verso = useMemo<VersoReading | null>(() => {
    if (!versoDocument || versoDocument.schema !== "oi.expression/v1" || !versoDocument.expression_ref.startsWith("expression:")) return null;
    try { return versoReading(versoDocument) as VersoReading; } catch { return null; }
  }, [versoDocument]);
  const subject = account && (account.state === "reading" || account.state === "unavailable") ? account.subject
    : account?.state === "ready" ? account.account.subject : undefined;
  const ready = account?.state === "ready" ? account.account : undefined;
  const title = verso?.title ?? ready?.subject.title ?? subject?.title ?? subject?.ref ?? "the current subject";

  return <article className="expression-verso expression-verso--depth" aria-label={`Verso of ${title}`}
    data-expression-ref={verso?.expression_ref ?? (versoDocument?.expression_ref)}
    data-expression-revision={verso?.revision}
    data-verso-schema={verso?.schema}
    data-subject-ref={subject?.ref}
    data-scene-ref={subject?.sceneRef ?? undefined}
    data-entity-ref={subject?.entityRef ?? undefined}
    data-register-key={ready?.web.registerKey ?? undefined}
    data-open-scene-ref={subject?.sceneRef ?? undefined}
    data-open-entity-ref={subject?.entityRef ?? undefined}
    data-subject-count={verso?.subjects.length ?? 0} data-relation-count={verso?.relations.length ?? 0}
    data-representation-count={verso?.representations.length ?? 0}
    data-account-state={account?.state}>
    <header className="expression-verso__head">
      <div className="world-component__eyebrow">Verso · the same subject, read</div>
      <h3>{title}</h3>
      <small>
        {subject && <span className="oi-ref">{subject.ref}</span>}
        {verso && <> · revision {verso.revision}</>}
        {verso?.selected_scene_ref ? <> · scene <span className="oi-ref">{verso.selected_scene_ref}</span></> : null}
        {ready?.savedFile && <> · saved at <span className="oi-ref">{ready.savedFile.ref}</span> @ {ready.savedFile.revision}</>}
      </small>
      {onClose && <button type="button" className="oi-action expression-verso__close" onClick={onClose}
        title="Close the verso — the face stands exactly where it was" aria-label="Close the verso">Return to the face</button>}
    </header>

    {account?.state === "no-subject" && <p className="oi-note expression-verso__sparse" data-account-state="no-subject" role="status">
      No subject stands. Nothing is selected in the field yet, so the verso has nothing to read — select a subject on the face, in the Library or in the wiki map first.</p>}
    {account?.state === "unavailable" && <p className="oi-refusal expression-verso__sparse" data-account-state="unavailable" role="status">
      The account read did not resolve: {account.reason}</p>}
    {account?.state === "reading" && <p className="oi-note" data-account-state="reading" role="status">Reading the subject's account…</p>}

    {ready && <>
      <AccountIdentity account={ready}/>
      <AccountWebPosition account={ready}/>
      <AccountScenes account={ready}/>
      <AccountSources account={ready} onOpenSourceRef={onOpenSourceRef}/>
      <AccountPage account={ready} onOpenPage={onOpenPage}/>
      <AccountSourceFile account={ready}/>
      {ready.editions.length > 0 && <section className="expression-verso__region" aria-label="Saved editions" data-region="editions">
        <h4>Editions · {ready.editions.length}</h4>
        <ul className="expression-verso__relations">{ready.editions.map(edition => <li key={edition} data-edition-ref={edition}>{edition}</li>)}</ul>
      </section>}
      {ready.actions.length > 0 && <section className="expression-verso__region" aria-label="Eligible Actions" data-region="actions">
        <h4>Eligible Actions · {ready.actions.length}</h4>
        <div className="expression-verso__actions oi-action-group">{ready.actions.map(action =>
          <button key={`${action.entityRef ?? ""}:${action.actionRef}`} type="button" className="oi-action"
            title={action.authorityRequirement ? `authority: ${action.authorityRequirement}` : "authority per caller"}
            data-action-ref={action.actionRef}
            onClick={() => { if (action.entityRef) onInvokeAction?.(action.entityRef, action.actionRef); }}>
            {action.actionRef}</button>)}</div>
      </section>}
      {ready.returnTrail && ready.returnTrail.length > 0 && <section className="expression-verso__region" aria-label="Return position" data-region="return">
        <h4>Return · {ready.returnTrail.length}</h4>
        <ul className="expression-verso__relations">{ready.returnTrail.slice(-4).map((stop, index) =>
          <li key={`${stop.mode}:${stop.label}:${index}`} data-return-mode={stop.mode}>{stop.label} <span className="oi-state">{stop.mode}</span></li>)}</ul>
        <p className="oi-note">Closing the verso returns to the exact field position — the verso changes nothing.</p>
      </section>}
      {ready.notices.length > 0 && <div className="expression-verso__notices" role="status" data-region="notices">
        {ready.notices.map(notice => <p key={notice} className="oi-note">{notice}</p>)}
      </div>}
    </>}

    {verso && <>
      {verso.subjects.length > 0 && <section className="expression-verso__region" aria-label="Bound subjects" data-region="subjects">
        <h4>Bound subjects · {verso.subjects.length}</h4>
        {verso.subjects.map(subject => <article key={subject.ref} className="expression-verso__subject" data-subject-ref={subject.ref} data-native-owner={subject.native_owner} data-presentation-role={subject.presentation_role}>
          <header><strong>{subject.ref}</strong><span className="oi-state">{subject.presentation_role} · {subject.native_owner || "native owner"}</span></header>
          {subject.entities.map(ref => <button key={ref} type="button" className="oi-ref expression-verso__entity" title="Focus this entity on the front" onClick={() => onOpenRef?.(ref)}>{ref}</button>)}
          {subject.sources.length > 0 && <dl className="expression-verso__sources">{subject.sources.map(source => <div key={`${source.ref}@${source.revision}`} data-source-ref={source.ref} data-source-availability={source.availability}><dt><code>{source.ref}</code></dt><dd>{source.availability}{source.revision ? ` · ${source.revision}` : ""}</dd></div>)}</dl>}
          {subject.actions.length > 0 && <div className="expression-verso__actions" data-action-count={subject.actions.length}><span className="oi-eyebrow">Disclosed Actions · {subject.native_owner}</span><div className="oi-action-group">{subject.actions.map(action => <button key={action.action_ref} type="button" className="oi-action" title={action.authority_requirement || "authority per caller"} onClick={() => onInvokeAction?.(subject.entities[0], action.action_ref)}>{action.action_ref}</button>)}</div></div>}
        </article>)}
      </section>}
      {verso.relations.length > 0 && <section className="expression-verso__region" aria-label="Relation bindings" data-region="relations">
        <h4>Relations · {verso.relations.length}</h4>
        <ul className="expression-verso__relations">{verso.relations.map(relation => <li key={relation.binding_ref} data-binding-ref={relation.binding_ref} data-relation-ref={relation.relation.ref}>
          <button type="button" className="oi-ref" onClick={() => onOpenRef?.(relation.relation.ref)}>{relation.relation.ref}</button>
          <span>{relation.from_entity_ref} → {relation.to_entity_ref}{relation.relation.revision ? ` · ${relation.relation.revision}` : ""}</span>
        </li>)}</ul>
      </section>}
      {verso.representations.length > 0 && <section className="expression-verso__region" aria-label="Available representations" data-region="representations">
        <h4>Representations · {verso.representations.length}</h4>
        <ul className="expression-verso__representations">{verso.representations.map(representation => <li key={`${representation.kind}:${representation.ref}`} data-representation-kind={representation.kind} data-availability={representation.availability}>
          {representation.kind} · {representation.ref}{representation.revision ? ` · ${representation.revision}` : ""} · {representation.availability}
        </li>)}</ul>
        <p className="oi-note">The live renderer presents on the front. Captures and pages render where their own renderers are admitted; availability is disclosed, never silently substituted.</p>
      </section>}
      <details className="expression-verso__provenance oi-disclosure" data-region="provenance">
        <summary>Provenance · {verso.provenance.length}</summary>
        <ul>{verso.provenance.map(reading => <li key={`${reading.ref}@${reading.revision}`}><code>{reading.ref}</code>{reading.revision ? ` · ${reading.revision}` : ""}</li>)}</ul>
      </details>
    </>}

    {!verso && !account && <p className="oi-note expression-verso__sparse" data-sparse="true" role="status">
      This verso has no document and no account to read yet.</p>}
    {verso && verso.subjects.length === 0 && verso.relations.length === 0 && verso.representations.length === 0 && verso.provenance.length === 0 && !account &&
      <p className="oi-note expression-verso__sparse" data-sparse="true">This Expression carries no bound subjects, relations, representations or provenance yet. The verso stays as sparse as the thing itself.</p>}
  </article>;
}

/** World / Project / ProjectCentral identity — the kernel navigator's own
 * reading, verbatim. */
function AccountIdentity({account}: {account: NonNullable<Extract<VersoAccountReading, {state: "ready"}>["account"]>}) {
  const {identity} = account;
  const hasAny = identity.worldRoot || identity.projectName || identity.projectCentralWikiSpace;
  if (!hasAny) return <section className="expression-verso__region" aria-label="World identity" data-region="identity">
    <h4>World / Project</h4>
    <p className="oi-note">The world reading carries no identity for this subject yet.</p>
  </section>;
  return <section className="expression-verso__region" aria-label="World identity" data-region="identity"
    data-world-root={identity.worldRoot} data-project={identity.projectName} data-wiki-space={identity.projectCentralWikiSpace}>
    <h4>World / Project</h4>
    <dl className="expression-verso__sources expression-verso__identity">
      {identity.worldRoot && <div><dt>World root</dt><dd><span className="oi-ref">{identity.worldRoot}</span></dd></div>}
      {identity.projectName && <div><dt>Project</dt><dd>{identity.projectName}{identity.projectPath ? <span className="oi-ref"> · {identity.projectPath}</span> : null}</dd></div>}
      {identity.projectCentralWikiSpace && <div><dt>ProjectCentral wiki</dt><dd><span className="oi-ref">{identity.projectCentralWikiSpace}</span>{identity.projectCentralState ? ` · ${identity.projectCentralState}` : ""}</dd></div>}
    </dl>
  </section>;
}

/** The face's position in the ONE wiki projection state — read-only, the
 * same selection every aperture shows. */
function AccountWebPosition({account}: {account: NonNullable<Extract<VersoAccountReading, {state: "ready"}>["account"]>}) {
  const {web} = account;
  const hasAny = web.registerKey || web.expressionRef || web.subjectRef;
  if (!hasAny) return null;
  return <section className="expression-verso__region" aria-label="Position in the web" data-region="web-position">
    <h4>Position in the web</h4>
    <dl className="expression-verso__sources expression-verso__identity">
      {web.registerKey && <div><dt>Register</dt><dd data-web-register={web.registerKey}>{web.registerKey}</dd></div>}
      {web.expressionRef && <div><dt>Web Expression</dt><dd><span className="oi-ref">{web.expressionRef}</span></dd></div>}
      {web.sceneRef && <div><dt>Scene</dt><dd><span className="oi-ref">{web.sceneRef}</span></dd></div>}
      {web.entityRef && <div><dt>Entity</dt><dd><span className="oi-ref">{web.entityRef}</span></dd></div>}
      {web.subjectRef && <div><dt>Subject</dt><dd data-web-subject={web.subjectRef}><span className="oi-ref">{web.subjectRef}</span></dd></div>}
    </dl>
  </section>;
}

/** The scene breakdown — the same subject's scenes as list, tree and a
 * bounded graph, over the SAME document the face presents (the wiki
 * projection's standing document where one stands). Mirrors the wiki map's
 * aperture shapes; no second reading, no invented structure. */
function AccountScenes({account}: {account: NonNullable<Extract<VersoAccountReading, {state: "ready"}>["account"]>}) {
  const store = useWikiProjectionState();
  const [aperture, setAperture] = useState<Aperture>("list");
  const doc = account.document ?? undefined;
  // The standing projection that owns this subject: by the document's own
  // expression identity, else by the web position's register.
  const owningKey = doc ? wikiRegisterOwning(doc.expression_ref) : (account.web.registerKey && store.standings[account.web.registerKey] ? account.web.registerKey : null);
  const standing = owningKey ? store.standings[owningKey] : undefined;
  const projection = wikiProjectionOf(standing);
  const standingDoc = wikiDocumentOf(standing);
  const document = standingDoc ?? doc;
  if (!document || document.scenes.length === 0) {
    return <section className="expression-verso__region" aria-label="Scene breakdown" data-region="scenes">
      <h4>Scenes</h4>
      <p className="oi-note">{doc ? "The face's Expression carries no scenes yet." : "No scene structure is disclosed for this subject."}</p>
    </section>;
  }
  const constellations = projection?.constellations;
  return <section className="expression-verso__region" aria-label="Scene breakdown" data-region="scenes" data-aperture={aperture}
    data-scene-count={document.scenes.length} data-expression-ref={document.expression_ref}>
    <h4>Scenes · {document.scenes.length}{projection ? " · the standing projection" : ""}</h4>
    <div className="expression-verso__apertures" role="tablist" aria-label="Scene breakdown aperture">
      {(["list", "tree", "graph"] as const).map(choice => <button key={choice} type="button" role="tab"
        aria-selected={aperture === choice} data-aperture-choice={choice}
        title={choice === "list" ? "Flat index of the scenes" : choice === "tree" ? "Scenes and their entities, nested" : "The current scene drawn from the document itself — same positions, bound relations only"}
        onClick={() => setAperture(choice)}>{choice === "list" ? "List" : choice === "tree" ? "Tree" : "Graph"}</button>)}
    </div>
    {aperture === "list" && <ul className="expression-verso__scene-list">
      {document.scenes.map(scene => <li key={scene.scene_ref} data-scene-ref={scene.scene_ref}>
        <span className="expression-verso__scene-title">{scene.title}</span>
        <span className="oi-state">{scene.entity_refs.length} · {constellations?.some(entry => entry.sceneRef === scene.scene_ref) ? (constellations.find(entry => entry.sceneRef === scene.scene_ref)?.scheme === "ql-constellation" ? "warranted shape" : "radial") : "scene"}</span>
      </li>)}
    </ul>}
    {aperture === "tree" && <div className="expression-verso__scene-tree">
      {document.scenes.map(scene => <details key={scene.scene_ref} className="expression-verso__scene-branch" data-scene-ref={scene.scene_ref}>
        <summary>{scene.title} <span className="oi-state">{scene.entity_refs.length}</span></summary>
        <ul>{scene.entity_refs.map(ref => {
          const entity = document.entities[ref];
          if (!entity) return null;
          return <li key={ref} data-entity-ref={ref} data-subject-ref={entity.subject?.subject_ref ?? undefined}>
            {entity.title}{entity.subject ? <span className="oi-state"> · {entity.subject.subject_ref}</span> : null}
          </li>;
        })}</ul>
      </details>)}
    </div>}
    {aperture === "graph" && <SceneGraph document={document}/>}
  </section>;
}

/** The bounded graph: the selected scene drawn from the document's own
 * positions and bound relations — the wiki map's GRAPH shape, nothing
 * invented. */
function SceneGraph({document}: {document: ExpressionDocument}) {
  const scene = document.scenes.find(entry => entry.scene_ref === document.selection.scene_ref) ?? document.scenes[0];
  const placed = scene.entity_refs.map(ref => document.entities[ref]).filter(entity => !!entity);
  const at = (entity: NonNullable<(typeof placed)[number]>) => ({
    x: Number(entity.parameters?.x?.value ?? 0),
    y: Number(entity.parameters?.y?.value ?? 0),
  });
  const relations = Object.values(document.relations).filter(relation =>
    scene.entity_refs.includes(relation.from_entity_ref) && scene.entity_refs.includes(relation.to_entity_ref));
  return <figure className="expression-verso__scene-graph" data-scene-ref={scene.scene_ref}>
    <svg viewBox="-0.62 -0.62 1.24 1.24" role="img" aria-label={`${scene.title} — the document's own drawing`}>
      {relations.map(relation => {
        const from = document.entities[relation.from_entity_ref], to = document.entities[relation.to_entity_ref];
        if (!from || !to) return null;
        const a = at(from), b = at(to);
        return <line key={relation.binding_ref} className="expression-verso__graph-relation" x1={a.x} y1={a.y} x2={b.x} y2={b.y}/>;
      })}
      {placed.map(entity => {
        const position = at(entity);
        return <g key={entity.entity_ref} className="expression-verso__graph-node" data-entity-ref={entity.entity_ref}
          data-subject-ref={entity.subject?.subject_ref ?? undefined}>
          <title>{entity.title}{entity.subject ? ` — ${entity.subject.subject_ref}` : ""}</title>
          <circle cx={position.x} cy={position.y} r={0.055}/>
          <text x={position.x} y={position.y + 0.02} textAnchor="middle">{String(entity.parameters?.glyph?.value ?? "·")}</text>
        </g>;
      })}
    </svg>
    <figcaption className="oi-note">{scene.title} — the document's own positions and bound relations</figcaption>
  </figure>;
}

/** Exact sources with real open paths. The host resolves the ref through
 * the files seam before anything opens — an unresolvable ref is the host's
 * named refusal, never a guess. */
function AccountSources({account, onOpenSourceRef}: {account: NonNullable<Extract<VersoAccountReading, {state: "ready"}>["account"]>; onOpenSourceRef?: (ref: string) => void}) {
  const seen = new Set<string>();
  const sources = account.sources.filter(source => !seen.has(source.ref) && seen.add(source.ref));
  return <section className="expression-verso__region" aria-label="Exact sources" data-region="sources" data-source-count={sources.length}>
    <h4>Exact sources · {sources.length}</h4>
    {sources.length === 0 && <p className="oi-note">No exact source is disclosed for this subject.</p>}
    <dl className="expression-verso__sources">{sources.map(source => <div key={source.ref} data-source-ref={source.ref} data-source-availability={source.availability ?? "available"}>
      <dt>{onOpenSourceRef
        ? <button type="button" className="oi-ref expression-verso__source-open" title={`Open ${source.ref} — resolved through the files seam before it opens`} onClick={() => onOpenSourceRef(source.ref)}>{source.ref}</button>
        : <code>{source.ref}</code>}</dt>
      <dd>{source.availability ?? "available"}{source.revision ? ` · ${source.revision}` : ""}</dd>
    </div>)}</dl>
  </section>;
}

/** The actual page content through the knowledge client — verbatim, bounded,
 * with the provider/authority/revision the read discloses. */
function AccountPage({account, onOpenPage}: {account: NonNullable<Extract<VersoAccountReading, {state: "ready"}>["account"]>; onOpenPage?: (ref: string, title?: string) => void}) {
  const page = account.page;
  return <section className="expression-verso__region" aria-label="Page content" data-region="page" data-page-present={page ? "true" : "false"}>
    <h4>Page</h4>
    {page ? <>
      <p className="oi-note">{page.provider} · {page.authority}{page.revision ? ` · ${page.revision}` : ""}</p>
      {page.content
        ? <pre className="expression-verso__page-body">{page.content}</pre>
        : <p className="oi-note" data-page-content="absent">The read disclosed no page body — the resource exists but carries no content through this reading.</p>}
      {onOpenPage && <button type="button" className="oi-action" onClick={() => onOpenPage(account.subject.ref, account.subject.title)}>Open the page in a centre surface</button>}
    </> : <p className="oi-note" data-page-present="absent">
      {account.subject.ref.startsWith("expression:")
        ? "The subject is an Expression, not a wiki page; its content lives in its document and its sources."
        : "The page read did not resolve — the notice above names why."}</p>}
  </section>;
}

/** The subject's exact source file, when the face carries one — actual
 * content, verbatim and bounded. */
function AccountSourceFile({account}: {account: NonNullable<Extract<VersoAccountReading, {state: "ready"}>["account"]>}) {
  const file = account.sourceFile;
  return <section className="expression-verso__region" aria-label="Source file" data-region="source-file" data-source-file-present={file ? "true" : "false"}>
    <h4>Source file</h4>
    {file ? <>
      <p className="oi-note"><span className="oi-ref">{file.location.path ?? file.location.ref}</span> · revision {file.revision}</p>
      <pre className="expression-verso__page-body">{file.content}</pre>
    </> : <p className="oi-note" data-source-file-present="absent">No exact source file stands under this subject.</p>}
  </section>;
}
