/** Actual production Glyph material and original durable draft owner.
 * Native effects stay closed; no fabricated native replies or pixel claim. */
import test,{beforeEach} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {register} from 'node:module';import {tmpdir} from 'node:os';import {resolve,sep} from 'node:path';
const storageArg=process.execArgv.find(a=>a.startsWith('--localstorage-file='));assert.ok(storageArg,'Use an owned OS temporary real WebStorage file');assert.ok(resolve(storageArg.slice('--localstorage-file='.length)).startsWith(resolve(tmpdir())+sep));assert.equal(localStorage.constructor.name,'Storage');beforeEach(()=>localStorage.clear());
const root=new URL('../../../../',import.meta.url),compiler=new URL('desktop/cradle/node_modules/typescript/lib/typescript.js',root).href;
const parameters=new URL('packages/expressions-boundary/src/parameters.ts',root).href;
const loader=`data:text/javascript,${encodeURIComponent(`import ts from ${JSON.stringify(compiler)};import {readFile} from 'node:fs/promises';export async function resolve(s,c,n){if(s==='@epilogos/expressions-boundary/parameters')return n(${JSON.stringify(parameters)},c);try{return await n(s,c)}catch(e){if(!s.startsWith('.'))throw e;if(s.endsWith('.js')){try{return await n(s.slice(0,-3)+'.ts',c)}catch{}}for(const suffix of ['.ts','.tsx']){try{return await n(s+suffix,c)}catch{}}throw e}}export async function load(u,c,n){if(u.endsWith('?raw'))return {format:'module',shortCircuit:true,source:'export default '+JSON.stringify(await readFile(new URL(u.split('?')[0]),'utf8'))};if(u.endsWith('.css'))return {format:'module',shortCircuit:true,source:'export {}'};if(!u.endsWith('.ts')&&!u.endsWith('.tsx'))return n(u,c);return {format:'module',shortCircuit:true,source:ts.transpileModule(await readFile(new URL(u),'utf8'),{fileName:new URL(u).pathname,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX}}).outputText}}`)}`;
register(loader,import.meta.url);
const author=new URL('desktop/cradle/expressions-app/field-studies-journeys/src/',root);
const [{createNativeInputContinuity,nativeInputTargetKey},{glyphInputMaterial},{privateNativeInputChanges},{kernelDocumentToJourney},{DocumentStore},{createRetainedNativeEditor},{applyNativeGlyphChanges},frame,tsModule]=await Promise.all([
 import('../src/continuity/nativeInputs.ts'),import('../src/continuity/glyphInputMaterial.ts'),import('../src/continuity/nativeInputRecovery.ts'),import(new URL('kernelDocumentBridge.ts',author)),import(new URL('store.ts',author)),import(new URL('hostEditor.ts',author)),import(new URL('hostEditor.ts',author)),import(new URL('desktop/cradle/src/document/frame.ts',root)),import(compiler)]);
const receiptPath='/Users/admin/Central/Work/reverse-engineering/2026-10-07-techne-instrument-re/new-shell/evidence/native/material-verification-c79dab7c-8de3-4b69-87cb-ee11cce28c9f/rich-artifact-inspection-3a33a7f6-94e9-445d-b2ec-7e7f25950935.json',archive=JSON.parse(await readFile(receiptPath,'utf8'));assert.deepEqual(archive.before.document,archive.after.document);
const closed=()=>{throw Error('Native effects remain closed in this source verification')};
function source(){const view=kernelDocumentToJourney(archive.after.document),store=new DocumentStore(view.journey),scene=store.document.scenes[0],entity=scene.entities[0],step=entity.sequence.steps[0],editor=createRetainedNativeEditor({store,sceneId:()=>scene.id,selection:()=>({entity_ids:[entity.id],step_id:step.id}),nativeView:()=>view,nativeSelect:closed,commit:closed,change:closed,afterHistory:closed,selectLocal:closed,openEditor:closed,standing:()=>({busy:false,notice:null}),telemetry:()=>undefined,fieldPaused:()=>false});return {view,store,scene,entity,step,reading:editor.read()}}
const scope={owner:'central',world:'control:root',workcell:'workcell:mac',accessEpoch:'glyph-custody-source',workspace_id:'glyph-custody-source',surface_id:'glyph-custody-source'};
const ts=tsModule.default,glyphText=await readFile(new URL('packages/live-shell/ui/src/components/GlyphSequenceEditor.tsx',root),'utf8'),providerText=await readFile(new URL('packages/live-shell/ui/src/components/NativeInputRetention.tsx',root),'utf8');
const ast=ts.createSourceFile('GlyphSequenceEditor.tsx',glyphText,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),providerAst=ts.createSourceFile('NativeInputRetention.tsx',providerText,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
const find=(node,predicate)=>{const out=[];const visit=n=>{if(predicate(n))out.push(n);ts.forEachChild(n,visit)};visit(node);assert.equal(out.length,1);return out[0]},component=find(ast,n=>ts.isFunctionDeclaration(n)&&n.name?.text==='GlyphSequenceEditor');
const fn=name=>find(component,n=>ts.isFunctionDeclaration(n)&&n.name?.text===name).getText(ast);
const execute=(body,bindings)=>new Function(...Object.keys(bindings),ts.transpileModule('const selected='+body,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText+';return selected')(...Object.values(bindings));
function aperture(owner=createNativeInputContinuity(scope)){const failures={current:new Map()},effects=[],change=()=>{},definition=find(providerAst,n=>ts.isVariableDeclaration(n)&&n.name.getText(providerAst)==='failure').initializer.getText(providerAst),failure=execute(definition,{failures,changed:change});return {owner,current:()=>true,changed:change,failure,failures,effects}}

test('actual rich Compound state and spatial layers retain complete source bodies through native edit material',()=>{
 const r=source(),step=r.entity.sequence.steps.find(step=>step.objectState);assert.ok(step,'Archived rich native state has actual body overrides');
 const before=structuredClone(r.store.document),state=glyphInputMaterial(r.reading,r.entity,step,'Width','Width',String(step.objectState.size.x+.1),String(step.objectState.size.x));assert.equal(state.input.kind,'gesture');const change=state.input.changes[0];assert.deepEqual(change.values,{...step.objectState,size:{...step.objectState.size,x:step.objectState.size.x+.1}});
 const layerStep=r.entity.sequence.steps.find(step=>(step.layers??r.entity.layers??[]).some(row=>row.source?.kind==='image'));assert.ok(layerStep,'Archived rich native image layer exists');const layers=layerStep.layers??r.entity.layers,layer=layers[0],material=glyphInputMaterial({...r.reading,selection:{...r.reading.selection,step_id:layerStep.id}},r.entity,layerStep,'Depth',`${layer.id}:depth`,String(layer.z+.1),String(layer.z));
 assert.deepEqual(material.input.changes[0].layers,layers.map(row=>row.id===layer.id?{...row,z:layer.z+.1}:row));assert.ok(material.input.changes[0].layers.some(row=>row.source?.kind==='image'));assert.deepEqual(r.store.document,before);
 const owner=createNativeInputContinuity(scope),receipt=owner.retain(material,()=>true);assert.deepEqual(owner.read().copies[0].copy.input,material.input);
 const selection={...r.reading,selection:{...r.reading.selection,step_id:layerStep.id}},changed=applyNativeGlyphChanges(before,r.scene.id,privateNativeInputChanges(receipt.copy,selection));assert.deepEqual(changed.scenes[0].entities[0].sequence.steps.find(row=>row.id===layerStep.id).layers,material.input.changes[0].layers);
});
test('unfinished numeric text remains exact durable material with original basis and refuses native decoding',()=>{
 const r=source(),owner=createNativeInputContinuity(scope),material=glyphInputMaterial(r.reading,r.entity,r.step,'Hold · s','Hold · s',' 2.45e-\nλ ',String(r.step.hold));assert.equal(material.input.kind,'text');const receipt=owner.retain(material,()=>true);
 assert.equal(receipt.copy.input.text,' 2.45e-\nλ ');assert.deepEqual(receipt.copy.basis,r.reading.basis);assert.throws(()=>privateNativeInputChanges(receipt.copy,r.reading),/finite exact parameter/);assert.equal(r.store.undoStack.length,0);
});
test('actual ExactValue changing shared compact/full draft keeps its first factory, native step and original basis',()=>{
 const r=source(),inputAperture=aperture(),values=new Map(),faults=[],context={scope:'actual-glyph-cut',values,changed:()=>{},capture:(label,identity,initial)=>text=>glyphInputMaterial(r.reading,r.entity,r.step,label,identity,text,initial)},id=context.scope+':Hold · s';
 context.retain=execute(fn('retainInput'),{inputAperture,nativeInputTargetKey,setFault:v=>faults.push(v)});
 const control=find(ast,n=>ts.isFunctionDeclaration(n)&&n.name?.text==='ExactValue'),handler=find(control,n=>ts.isJsxAttribute(n)&&n.name.getText(ast)==='onChange').initializer.expression.getText(ast),receive=execute(handler,{context,id,label:'Hold · s',identity:'Hold · s',value:r.step.hold,onCommit:closed,setDraft:()=>{},min:0,max:3600});
 receive({target:{value:'2.45'}});const first=values.get(id),firstBasis=first.inputReceipt.copy.basis;
 context.capture=()=>()=>{throw Error('New runtime context must not retarget captured human input')};receive({target:{value:'2.45e-'}});const later=values.get(id);assert.equal(later.materialFactory,first.materialFactory);assert.equal(later.numericCommit,first.numericCommit);assert.deepEqual(later.inputReceipt.copy.basis,firstBasis);assert.equal(later.inputReceipt.copy.target.step_id,r.step.id);assert.equal(later.inputReceipt.copy.input.text,'2.45e-');assert.equal(inputAperture.owner.read().copies.length,1);assert.deepEqual(faults,[]);
});
test('genuine stale owner receipt leaves latest raw local draft and blocks the actual binding checkpoint',async()=>{
 const r=source(),inputAperture=aperture(),faults=[],factory=text=>glyphInputMaterial(r.reading,r.entity,r.step,'Hold · s','Hold · s',text,String(r.step.hold)),retain=execute(fn('retainInput'),{inputAperture,nativeInputTargetKey,setFault:v=>faults.push(v)}),first={label:'Hold · s',value:'2.45',materialFactory:factory,commit:closed};retain(first);
 inputAperture.owner.retain({...factory('2.55'),refusal:'Separate actual same-owner callback retained newer bytes'},()=>true,first.inputReceipt);
 const next={label:'Hold · s',value:'2.65',materialFactory:factory,commit:closed};retain(next,first);assert.equal(next.value,'2.65');assert.equal(next.inputReceipt,undefined);assert.equal(inputAperture.owner.read().copies[0].copy.input.gesture.text,'2.55');assert.ok(inputAperture.failures.current.size);assert.match(faults.at(-1),/recovery failed/);
 const call=find(providerAst,n=>ts.isCallExpression(n)&&n.expression.getText(providerAst)==='registerDocumentCheckpoint'),task=execute(call.arguments[1].getText(providerAst),{failures:inputAperture.failures,owner:inputAperture.owner,current:inputAperture.current}),stop=frame.registerDocumentCheckpoint(scope.surface_id,task);
 try{await assert.rejects(frame.checkpointDocuments([scope.surface_id]),/Unretained native input/)}finally{stop()}
});
test('malformed actual storage bytes refuse Glyph retention without deleting winning records',()=>{
 const r=source(),inputAperture=aperture(),material=glyphInputMaterial(r.reading,r.entity,r.step,'Hold · s','Hold · s','2.45',String(r.step.hold)),first=inputAperture.owner.retain(material,()=>true),key='oi-cradle.draft.v1:'+first.ref,raw='{broken original';localStorage.setItem(key,raw);
 const faults=[],retain=execute(fn('retainInput'),{inputAperture,nativeInputTargetKey,setFault:v=>faults.push(v)}),previous={inputReceipt:first},next={value:'2.55',materialFactory:text=>glyphInputMaterial(r.reading,r.entity,r.step,'Hold · s','Hold · s',text,String(r.step.hold)),commit:closed};retain(next,previous);assert.equal(localStorage.getItem(key),raw);assert.equal(next.inputReceipt,undefined);assert.ok(inputAperture.failures.current.size);assert.ok(faults.length);
});
test('closed native submission coalesces Enter and blur and preserves exact acknowledged custody',async()=>{
 const r=source(),inputAperture=aperture(),entry={label:'Hold · s',value:'2.45',materialFactory:text=>glyphInputMaterial(r.reading,r.entity,r.step,'Hold · s','Hold · s',text,String(r.step.hold)),commit:closed};execute(fn('retainInput'),{inputAperture,nativeInputTargetKey,setFault:()=>{}})(entry);
 const submitFn=find(ast,n=>ts.isFunctionDeclaration(n)&&n.name?.text==='submitInput').getText(ast),submissions=new WeakMap(),submitInput=execute(submitFn,{submissions});let calls=0,release;
 const submit=execute(fn('submitCapturedInput'),{submitInput,inputAperture,apply:()=>{calls++;return new Promise((_yes,no)=>{release=no})},privateNativeInputChanges,r:r.reading,discardInput:closed,shown:()=>true,setFault:()=>{}}),first=submit(entry),second=submit(entry);assert.equal(first,second);await Promise.resolve();assert.equal(calls,1);release(Error('Actual native effects stay closed'));assert.equal(await first,false);assert.equal(inputAperture.owner.read().copies.length,1);
});
test('REGRESSION: failed durable retention must refuse submission before the closed native boundary',async()=>{
 const r=source(),inputAperture=aperture();inputAperture.current=()=>false;let nativeAttempts=0;const entry={label:'Hold · s',value:'2.45',materialFactory:text=>glyphInputMaterial(r.reading,r.entity,r.step,'Hold · s','Hold · s',text,String(r.step.hold)),commit:async()=>{nativeAttempts++;closed()}};
 execute(fn('retainInput'),{inputAperture,nativeInputTargetKey,setFault:()=>{}})(entry);assert.equal(entry.inputReceipt,undefined);
 const submitFn=find(ast,n=>ts.isFunctionDeclaration(n)&&n.name?.text==='submitInput').getText(ast),submitInput=execute(submitFn,{submissions:new WeakMap()}),receive=execute(fn('submitCapturedInput'),{submitInput,inputAperture,shown:()=>true,setFault:()=>{}});
 try{await receive(entry)}catch{}assert.equal(nativeAttempts,0,'Unacknowledged private custody must not fall back to commit');
});
test('REGRESSION: timing pointer movement/cancel must durably retain changed geometry before end',()=>{
 const r=source(),inputAperture=aperture(),epoch=3,drag={current:{pointerId:7,inputId:crypto.randomUUID(),epoch,entity_id:r.entity.id,entity_ref:r.reading.entityOccurrences[r.entity.id],step:r.step,region:'hold',start:100,basis:r.reading.basis,pixelsPerSecond:80,value:2,hold:2,transition:.5,preview:{id:r.step.id,hold:2,transition:.5}}},draftValues=new Map(),before=structuredClone(r.store.document),bindings={drag,lifetime:{current:{epoch}},shown:()=>true,isPresented:()=>true,setTimingDraft:()=>{},inputAperture,draftValues,apply:closed,draftChanged:()=>{}};bindings.retainInput=execute(fn('retainInput'),{inputAperture,nativeInputTargetKey,setFault:()=>{}});bindings.retainTimingInput=execute(fn('retainTimingInput'),bindings);
 execute(fn('updateTiming'),bindings)({pointerId:7,clientX:140});execute(fn('cancelTiming'),bindings)({pointerId:7,currentTarget:{hasPointerCapture:()=>false}});assert.equal(drag.current,null);assert.deepEqual(r.store.document,before);assert.equal(inputAperture.owner.read().copies.length,1);const copy=inputAperture.owner.read().copies[0].copy;assert.equal(copy.input.gesture.value,2.5);assert.deepEqual(copy.basis,r.reading.basis);assert.equal(copy.target.entity_ref,r.reading.entityOccurrences[r.entity.id]);assert.equal(draftValues.size,1);
});
test('actual discard cannot clear a stale submitted receipt or newer winning private bytes',()=>{
 const r=source(),inputAperture=aperture(),material=glyphInputMaterial(r.reading,r.entity,r.step,'Hold · s','Hold · s','2.45',String(r.step.hold)),receipt=inputAperture.owner.retain(material,()=>true),entry={value:'2.45',inputReceipt:receipt,materialFactory:text=>glyphInputMaterial(r.reading,r.entity,r.step,'Hold · s','Hold · s',text,String(r.step.hold))},winner=inputAperture.owner.retain(entry.materialFactory('2.55'),()=>true,receipt),faults=[];
 execute(fn('discardInput'),{inputAperture,nativeInputTargetKey,setFault:value=>faults.push(value)})(entry);assert.match(faults.at(-1),/Newer private input/);assert.deepEqual(inputAperture.owner.read().copies[0].copy,winner.copy);
});
test('current raw numeric source keeps text input and explicit decimal keyboard without browser numeric coercion',()=>{
 const control=find(ast,n=>ts.isFunctionDeclaration(n)&&n.name?.text==='ExactValue'),input=find(control,n=>ts.isJsxSelfClosingElement(n)&&n.tagName.getText(ast)==='input'),type=find(input,n=>ts.isJsxAttribute(n)&&n.name.getText(ast)==='type'),mode=find(input,n=>ts.isJsxAttribute(n)&&n.name.getText(ast)==='inputMode');assert.equal(type.initializer.text,'text');assert.equal(mode.initializer.text,'decimal');
});
test('durable rich layer recovery refuses changed stable state and native entity occurrence before decoding',()=>{
 const r=source(),layers=r.step.layers??r.entity.layers;assert.ok(layers.length);const layer=layers[0],owner=createNativeInputContinuity(scope),material=glyphInputMaterial(r.reading,r.entity,r.step,'Depth',`${layer.id}:depth`,String(layer.z+.1),String(layer.z)),receipt=owner.retain(material,()=>true);
 for(const reading of [{...r.reading,selection:{...r.reading.selection,step_id:'unselected-state'}},{...r.reading,entityOccurrences:{...r.reading.entityOccurrences,[r.entity.id]:'another-native-occurrence'}}])assert.throws(()=>privateNativeInputChanges(receipt.copy,reading),/no longer selected/);assert.deepEqual(owner.read().copies[0].copy,receipt.copy);
});
test('actual native Glyph validator refuses out-of-range retained timing while full rich input remains durable',()=>{
 const r=source(),before=structuredClone(r.store.document),owner=createNativeInputContinuity(scope),material=glyphInputMaterial(r.reading,r.entity,r.step,'Hold · s','Hold · s','5000',String(r.step.hold)),receipt=owner.retain(material,()=>true);
 assert.throws(()=>applyNativeGlyphChanges(r.store.document,r.scene.id,privateNativeInputChanges(receipt.copy,r.reading)),/Hold/);assert.deepEqual(r.store.document,before);assert.equal(owner.read().copies[0].copy.input.gesture.text,'5000');assert.equal(r.store.undoStack.length,0);
});
test('direct live timing route supports an unselected stable member but recovery retains strict selection and occurrence',()=>{
 const r=source(),step=r.entity.sequence.steps.find(row=>row.id!==r.step.id);assert.ok(step);const inputAperture=aperture(),draftValues=new Map(),bindings={draftValues,draftChanged:()=>{},apply:closed};bindings.retainInput=execute(fn('retainInput'),{inputAperture,nativeInputTargetKey,setFault:()=>{}});
 const entry=execute(fn('retainTimingInput'),bindings)({inputId:crypto.randomUUID(),pointerId:7,entity_id:r.entity.id,entity_ref:r.reading.entityOccurrences[r.entity.id],step,region:'hold',basis:r.reading.basis,hold:step.hold,transition:step.transition,value:2.45}).entry;
 assert.throws(()=>privateNativeInputChanges(entry.inputReceipt.copy,r.reading),/no longer selected/);const changes=privateNativeInputChanges(entry.inputReceipt.copy,r.reading,false);assert.equal(changes[0].kind,'step-timing');assert.equal(changes[0].step_id,step.id);
 const changed=applyNativeGlyphChanges(r.store.document,r.scene.id,changes);assert.equal(changed.scenes[0].entities[0].sequence.steps.find(row=>row.id===step.id).hold,2.45);
 const wrong={...r.reading,entityOccurrences:{...r.reading.entityOccurrences,[r.entity.id]:'another-native-instance'}};assert.throws(()=>privateNativeInputChanges(entry.inputReceipt.copy,wrong,false),/no longer selected/);assert.equal(inputAperture.owner.read().copies.length,1);
});
test('REGRESSION: live unselected-state timing qualification must refuse another kind of native state change',()=>{
 const r=source(),step=r.entity.sequence.steps.find(row=>row.id!==r.step.id);assert.ok(step);const owner=createNativeInputContinuity(scope),material=glyphInputMaterial(r.reading,r.entity,step,'Hold · s','Hold · s','2.45',String(step.hold));material.target.family='glyph:pointer-hold';material.input.changes=[{kind:'step-layers',entity_id:r.entity.id,step_id:step.id,layers:step.layers??r.entity.layers}];const receipt=owner.retain(material,()=>true);
 assert.throws(()=>privateNativeInputChanges(receipt.copy,r.reading,false),/timing/i);assert.equal(owner.read().copies.length,1);
});
