import {useEffect,useMemo,useState} from "react";
import type {SharedFieldSnapshot} from "../knowledge/shared-field";
import {useKernel} from "../kernel/KernelProvider";
import {kernelOp} from "../kernel/bridge";
import {summonExpression} from "../expression/summon";
// @ts-ignore -- language-neutral SharedField projection, covered by node tests.
import {beingEncounter,invocationStanding} from "./being.mjs";

export function BeingEncounter({participantRef,snapshot,onOpenRef}:{participantRef:string;snapshot:SharedFieldSnapshot;onOpenRef:(ref:string)=>void}) {
 const encounter:any=useMemo(()=>beingEncounter(snapshot,participantRef),[snapshot,participantRef]);
 const kernel=useKernel();const [standing,setStanding]=useState<any>();const [instruction,setInstruction]=useState("");const [result,setResult]=useState<any>();const [pending,setPending]=useState(false);const [error,setError]=useState<string>();
 useEffect(()=>{if(encounter.state!=="available"||encounter.identity.kind!=="agent"||!encounter.agency){setStanding(undefined);return;}let live=true;void kernelOp(kernel.transport,{op:"being_encounter",request:{operation:"standing",agent_ref:encounter.identity.ref,target_agency_ref:encounter.agency.ref}}).then(reply=>{if(live)setStanding(reply.outcome?.result==="being_encounter"?reply.outcome.data:{state:"unavailable",detail:reply.error??"Native gateway reading unavailable"});});return()=>{live=false;};},[kernel.transport,encounter.state,encounter.identity?.ref,encounter.agency?.ref]);
 if(encounter.state!=="available")return <p role="status" className="explore-absent">{encounter.reason}</p>;
 const invocation=invocationStanding(encounter,standing);
 const openNativeExpression=async()=>{setError(undefined);const reply=await kernelOp(kernel.transport,{op:"expression",request:{operation:"inspect",expression_ref:encounter.expressionRef}});if(reply.error||reply.outcome?.result!=="expression")throw new Error(reply.error??"The native Expression owner is unavailable in this world");const document=(reply.outcome.data as any)?.document;if(!document||document.revision!==encounter.expressionRevision)throw new Error(`Projected Expression revision ${encounter.expressionRevision} differs from the native owner${document?` at revision ${document.revision}`:""}.`);summonExpression(encounter.expressionRef);};
 const invoke=async()=>{if(!invocation.available||!encounter.expressionRef||!encounter.expressionRevision||!encounter.expressionComposition)return;setPending(true);setError(undefined);try{const invocationRef=`invocation:shared-field:${crypto.randomUUID()}`,returnRef=`return:shared-field:${crypto.randomUUID()}`;const reply=await kernelOp(kernel.transport,{op:"being_encounter",request:{operation:"invoke",agent_ref:encounter.identity.ref,target_agency_ref:encounter.agency.ref,subject_ref:encounter.participant.participant_ref,source_refs:encounter.sourceRefs,expression_ref:encounter.expressionRef,expression_revision:encounter.expressionRevision,composition:encounter.expressionComposition,instruction,invocation_ref:invocationRef,return_ref:returnRef}});if(reply.error||reply.outcome?.result!=="being_encounter")throw new Error(reply.error??"Native Agent invocation unavailable");setResult(reply.outcome.data);}catch(cause){setError(String(cause));}finally{setPending(false);}};
 return <article className="world-presentation world-presentation--being being-encounter" data-being-ref={encounter.participant.participant_ref} data-identity-kind={encounter.identity.kind} data-invocation={invocation.available?"available":"unavailable"}>
  <header className="world-presentation__masthead"><div><div className="world-component__eyebrow">Being · {encounter.identity.kind}</div><h1>{encounter.label}</h1></div><div className="world-presentation__revision">{encounter.participant.participant_ref}</div>{encounter.profile&&<p>{encounter.profile}</p>}</header>
  <section className="world-region"><div className="world-region__label">Presence and identity</div><div className="world-region__components"><article className="world-component world-component--text">
   <dl className="world-component__meta"><div><dt>Identity</dt><dd><code>{encounter.identity.ref}</code></dd></div><div><dt>Field</dt><dd><button type="button" onClick={()=>onOpenRef(encounter.participant.field_ref)}>{encounter.participant.field_ref}</button></dd></div><div><dt>Presence</dt><dd>{encounter.presence??"not disclosed"}</dd></div><div><dt>Your membership</dt><dd>{encounter.membership.length?encounter.membership.map((row:{role:string})=>row.role).join(", "):"none"}</dd></div></dl>
   <p className="explore-muted">Presence, membership, addressing, invocation authority and attention remain separate. Opening this Being starts no AgentSession and shares nothing with your personal Agent.</p>
  </article></div></section>
  <section className="world-region"><div className="world-region__label">Relations · Activity · Method</div><div className="world-region__components">
   <div className="world-component__collection">{encounter.relations.map((row:{relation:string;origin:string;direction:string;other:string},index:number)=><button type="button" key={`${row.relation}:${row.other}:${index}`} onClick={()=>onOpenRef(row.other)}><strong>{row.relation}</strong><span>{row.direction} · {row.other} · {row.origin}</span></button>)}{!encounter.relations.length&&<span className="explore-muted">No disclosed relations.</span>}</div>
   {encounter.activity?<article className="being-activity" data-activity-ref={encounter.activity.activity_ref}><strong>{encounter.activity.semantic_summary}</strong><span>{encounter.activity.phase} · {encounter.activity.native_owner}</span><code>{encounter.activity.activity_ref}</code></article>:<p className="explore-muted">No attributable Activity disclosed.</p>}
   {encounter.methods.length?<div className="world-component__refs">{encounter.methods.map((ref:string)=><button type="button" key={ref} onClick={()=>onOpenRef(ref)}>{ref}</button>)}</div>:<p className="explore-muted">No Method disclosed.</p>}
  </div></section>
  <section className="world-region"><div className="world-region__label">Address and act</div><div className="being-address"><span>To:</span><code>{encounter.address.to[0].address}</code><small>{encounter.address.to[0].kind} · {encounter.address.to[0].participant}</small></div>
   <p className="explore-muted">This typed address names the participant only. It grants no membership, invocation authority or attention standing.</p>
   {encounter.expressionRef&&encounter.expressionRevision&&<><button type="button" className="being-expression" onClick={()=>onOpenRef(encounter.expressionRef)}>Open projected Expression r{encounter.expressionRevision}</button><button type="button" className="being-expression" onClick={()=>void openNativeExpression().catch(cause=>setError(String(cause)))}>Open native owner for review</button></>}
   {encounter.identity.kind==="agent"&&<label className="being-instruction">Exact request<textarea aria-label={`Request for ${encounter.label}`} value={instruction} onChange={event=>setInstruction(event.target.value)} placeholder="Ask for one bounded refinement of this projected Expression."/></label>}
   <button type="button" className="being-invoke" disabled={!invocation.available||!instruction.trim()||!encounter.expressionRevision||!encounter.expressionComposition||pending} title={!encounter.expressionComposition?"The Projection discloses no structured Expression composition.":invocation.available?"Invoke through the native Actuation Gateway":invocation.reason} onClick={()=>void invoke()}>{pending?"Invoking…":"Invoke Agent"}</button>
   {!invocation.available&&<p role="status" className="being-refusal">Agent invocation unavailable: {invocation.reason}</p>}
   {error&&<p role="alert" className="being-refusal">{error}</p>}{result&&<details className="being-invocation-result" open><summary>{result.state} · {result.owner_operation}</summary><pre>{JSON.stringify(result,null,2)}</pre></details>}
  </section>
 </article>;
}
