import {useMemo,useState} from "react";
import type {KernelTransportStatus} from "../kernel/types";
import {receiving,type DocumentReading,type ReturnReading} from "../receiving/client";
import {sharedField,slug,type HostedContribution,type SharedFieldContributionResult,type SharedFieldReading} from "../knowledge/shared-field";
// @ts-ignore -- renderer-neutral SharedField contract, covered by node tests.
import {contributionBody,createAttachedContribution,nativeReturnSubmission} from "../../../../shared-field/contribution-return.mjs";

type HostedReading=Extract<SharedFieldReading,{state:"hosted"}>;
type Kind="prose"|"relation-proposal"|"source-proposal"|"thing"|"expression-revision"|"expression-scene"|"file"|"reference"|"method";
const labels:Record<Kind,string>={prose:"Response","relation-proposal":"Relation proposal","source-proposal":"Source / Wiki proposal",thing:"Thing / artifact","expression-revision":"Expression revision","expression-scene":"Expression scene",file:"File",reference:"Reference",method:"Method / sequence"};
function presentationBasis(reading:HostedReading){const projection=reading.projections.find(p=>p.projection_ref===(reading.entry.meta?.projection_ref as string|undefined))??reading.projections[0];if(!projection)return undefined;const representation=projection.representation as {kind?:string;payload?:{presentation_ref?:string;revision?:number;regions?:{bindings?:{portable_renderer?:string;component_ref?:string;props?:{expression?:{expression_ref:string;expression_revision:number}}}[]}[]}}|undefined;const presentation=representation?.kind==="oi.world-presentation/v1"?representation.payload:undefined;const expression=presentation?.regions?.flatMap(region=>region.bindings??[]).find(binding=>(binding.portable_renderer??binding.component_ref)==="oi.presentation/expression/v1")?.props?.expression;return {source_ref:projection.source.ref??projection.subject.ref,source_revision:projection.source.revision,projection_ref:projection.projection_ref,projection_revision:projection.projection_revision,...(presentation?.presentation_ref&&presentation.revision?{world_presentation_ref:presentation.presentation_ref,world_presentation_revision:presentation.revision}:{}),...(expression?{expression_ref:expression.expression_ref,expression_revision:expression.expression_revision}:{})};}
const bodyText=(row:HostedContribution)=>{try{const body=contributionBody(row.contract);return typeof body.content==="string"?body.content:JSON.stringify(body.content);}catch{return "Unsupported contributed material";}};

export function ContributionPanel({transport,reading,onChanged}:{transport:KernelTransportStatus;reading:HostedReading;onChanged:()=>void}){
 const [open,setOpen]=useState(false),[kind,setKind]=useState<Kind>("prose"),[content,setContent]=useState(""),[replyTo,setReplyTo]=useState<string>(),[busy,setBusy]=useState(false),[message,setMessage]=useState<string>(),[error,setError]=useState<string>();
 const [returnState,setReturnState]=useState<{contribution_ref:string;reading:ReturnReading;document:DocumentReading}>();
 const authority=reading.my_authority.find(a=>a.field_ref===reading.field_ref&&!a.revoked&&a.role==="contributor");const basis=useMemo(()=>presentationBasis(reading),[reading]);const contributions=reading.contributions.filter(row=>row.contract?.schema==="oi.contribution/v1");
 const submit=async()=>{if(!authority||!basis||!reading.field_ref||!content.trim())return;setBusy(true);setError(undefined);setMessage(undefined);try{let parsed:unknown=content.trim();if(kind!=="prose")parsed=JSON.parse(content);const nonce=crypto.randomUUID();const contribution=createAttachedContribution({contribution_ref:`contribution:${slug(authority.participant_ref)}:${nonce}`,field_ref:reading.field_ref,contributor_participant_ref:authority.participant_ref,created_at:new Date().toISOString(),target:replyTo?{kind:"oi.contribution",ref:replyTo}:{kind:reading.entry.kind,ref:reading.entry.ref,revision:basis.source_revision},body:{kind,basis,content:parsed,attachments:[]},provenance:[{kind:"projection-encounter",ref:basis.projection_ref,source_system:"o-i",revision:String(basis.projection_revision)}]});const result=await sharedField<SharedFieldContributionResult>(transport,{kind:"contribute",contribution,transport_message_id:nonce});setMessage(`Contribution ${result.state}; its receiving owner decides admission.`);setContent("");setReplyTo(undefined);onChanged();}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}};
 const beginReturn=async(row:HostedContribution)=>{if(!basis)return;setBusy(true);setError(undefined);setMessage(undefined);try{const documentId=reading.entry.meta?.document_id;if(typeof documentId!=="string"||!documentId)throw new Error("The Projection does not disclose a native document_id, so Return is unavailable for this subject.");const project=typeof reading.entry.meta?.project==="string"?reading.entry.meta.project:null;const document=await receiving<DocumentReading>(transport,project,{kind:"document",source_ref:basis.source_ref,document_id:documentId});const request=nativeReturnSubmission(row.contract,{source_ref:basis.source_ref,source_revision:document.revision.revision,projection_ref:basis.projection_ref,projection_revision:basis.projection_revision,world_presentation_ref:basis.world_presentation_ref,world_presentation_revision:basis.world_presentation_revision,expression_ref:basis.expression_ref,expression_revision:basis.expression_revision},{project,document_id:documentId});const submitted=await receiving<ReturnReading>(transport,project,{kind:"submit",...request.input});setReturnState({contribution_ref:row.contribution_ref,reading:submitted,document});setMessage("Returned to the native owner for review.");}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}};
 const decide=async(disposition:"accepted"|"rejected")=>{if(!returnState)return;setBusy(true);setError(undefined);try{const meta=reading.entry.meta??{},project=typeof meta.project==="string"?meta.project:null;const reviewed=await receiving<ReturnReading>(transport,project,{kind:"review",return_ref:returnState.reading.return_ref,expected_return_revision:returnState.reading.revision,disposition,...(disposition==="accepted"?{expected_source_revision:returnState.document.revision.revision}:{})});if(disposition==="accepted"){const included=await receiving<ReturnReading>(transport,project,{kind:"include",return_ref:reviewed.return_ref,expected_return_revision:reviewed.revision,expected_source_revision:returnState.document.revision.revision});setReturnState({...returnState,reading:included});setMessage(`Native owner included ${returnState.contribution_ref}.`);}else{setReturnState({...returnState,reading:reviewed});setMessage(`Native owner refused ${returnState.contribution_ref}.`);}onChanged();}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}};
 return <aside className="explore-contributions" aria-label="Contributions" data-contribution-count={contributions.length}><header><strong>Contributions</strong><button type="button" onClick={()=>setOpen(value=>!value)} disabled={!authority||!basis}>{open?"Close":"Contribute"}</button></header>{!authority&&<p className="explore-muted">Contribution is unavailable for this participant.</p>}{open&&<div className="contribution-composer"><label>Kind<select value={kind} onChange={event=>setKind(event.target.value as Kind)}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{replyTo&&<p>Responding to <code>{replyTo}</code> <button type="button" onClick={()=>setReplyTo(undefined)}>Clear</button></p>}<textarea aria-label="Contributed material" rows={4} value={content} onChange={event=>setContent(event.target.value)} placeholder={kind==="prose"?"Add a response attached to this work…":"Enter the admitted JSON body…"}/><button type="button" disabled={busy||!content.trim()} onClick={()=>void submit()}>Submit Contribution</button></div>}{(message||error)&&<p role={error?"alert":"status"}>{error??message}</p>}<ol className="contribution-stack">{contributions.map(row=><li key={row.contribution_ref} data-contribution-ref={row.contribution_ref}><small>{row.contract.mode} · {row.contract.contributor_participant_ref}</small><p>{bodyText(row)}</p><div><button type="button" onClick={()=>{setReplyTo(row.contribution_ref);setOpen(true);}}>Respond</button><button type="button" disabled={busy} onClick={()=>void beginReturn(row)}>Return to source</button></div></li>)}</ol>{returnState&&!['included','rejected'].includes(returnState.reading.record.status)&&<div className="contribution-review"><p>Inspect the returned difference against source <code>{returnState.document.revision.revision}</code>.</p><button type="button" disabled={busy} onClick={()=>void decide("accepted")}>Accept and include</button><button type="button" disabled={busy} onClick={()=>void decide("rejected")}>Refuse</button></div>}</aside>;
}
