import {useEffect,useMemo,useRef,useState,type ReactNode} from "react";
import {useKernel} from "../kernel/KernelProvider";
import {useExpressionStage,type StagePresentation} from "../stage/ExpressionStage";
import {expressionConfig} from "../expression/engineProjection";
import {projectProvidedLocalWhole,type LocalWhole,type ProjectionOutcome} from "../knowledge/expressionProjection";
// @ts-ignore -- renderer-neutral SF2 contract, tested under shared-field.
import {createKnowledgeEncounter} from "../../../../shared-field/knowledge-encounter.mjs";

type Node={ref:string;kind:string;world_ref:string;label:string;summary?:string;revision?:string;availability?:string;meta?:{ql?:unknown};provenance:{kind:string;ref:string;source_system:string;revision?:string}[]};
type Edge={from:string;to:string;relation:string;origin:string;direction?:string;provenance:{kind:string;ref:string;source_system:string;revision?:string}[]};
type Encounter={state:"available"|"degraded";focus:string;resource:Node;detail?:string;nodes:Node[];edges:Edge[];truncated?:boolean;presentations:string[];actions:string[];sources?:{ref:string;revision?:string}};
type Mode="graph"|"tree"|"list"|"page"|"expression";

function relationLabel(value:string){const parts=value.split(/[/.]/).filter(Boolean);return (parts[parts.length-1]??value).replace(/-/g," ");}
function initialPins(){try{const value=JSON.parse(localStorage.getItem("oi-cradle.explore-knowledge-pins.v1")??"[]");return Array.isArray(value)?value.filter(item=>typeof item==="string"):[];}catch{return [];}}
function initialFollow(){try{return localStorage.getItem("oi-cradle.explore-knowledge-follow.v1")!=="false";}catch{return true;}}

export function KnowledgeEncounter({opened,page,onOpenRef}:{opened:unknown;page:ReactNode;onOpenRef:(ref:string)=>void}) {
  const {transport}=useKernel();const stage=useExpressionStage();
  const encounter=useMemo(()=>createKnowledgeEncounter(opened) as Encounter,[opened]);
  const [mode,setMode]=useState<Mode>(encounter.state==="available"?"graph":"page");
  const [pins,setPins]=useState<string[]>(initialPins);
  const [follow,setFollow]=useState(initialFollow);
  const [heldLocus,setHeldLocus]=useState(encounter.focus);
  const [expressionOutcome,setExpressionOutcome]=useState<ProjectionOutcome>();const [expressionBusy,setExpressionBusy]=useState(false);const [expressionError,setExpressionError]=useState("");
  const expressionHost=useRef<HTMLDivElement>(null),stagePresentation=useRef<StagePresentation|null>(null);
  const focus=encounter.nodes.find(node=>node.ref===encounter.focus)??encounter.resource;
  const togglePin=()=>setPins(current=>{const next=current.includes(encounter.focus)?current.filter(ref=>ref!==encounter.focus):[...current,encounter.focus];try{localStorage.setItem("oi-cradle.explore-knowledge-pins.v1",JSON.stringify(next));}catch{/* storage failure does not change semantic state */}return next;});
  const selectedMode=encounter.presentations.includes(mode)?mode:"page";
  const visualLocus=follow?encounter.focus:(encounter.nodes.some(node=>node.ref===heldLocus)?heldLocus:encounter.focus);
  const open=(ref:string)=>{const node=encounter.nodes.find(item=>item.ref===ref);if(node&&node.availability!=="unavailable")onOpenRef(ref);};
  const neighbours=encounter.edges.map(edge=>({edge,ref:edge.from===encounter.focus?edge.to:edge.from})).filter(({ref},index,all)=>all.findIndex(candidate=>candidate.ref===ref)===index);
  const whole=useMemo<LocalWhole>(()=>({locus:encounter.focus,members:encounter.nodes.filter(node=>node.availability!=="unavailable").map(node=>({node:{ref:node.ref,label:node.label,kind:node.kind as "wiki-node",native_owner:node.provenance[0]?.source_system??"shared-field",provenance:{source:node.provenance[0]?.kind??"projection",revision:node.revision,detail:node.provenance.map(row=>row.ref)},actions:[]},reading:{resource:node.ref,provider:node.provenance[0]?.source_system??"shared-field",revision:node.revision,authority:node.provenance[0]?.kind??"projection",evidence:node.provenance.map(row=>row.ref),why_selected:node.ref===encounter.focus?"locus":"typed relation",content:node.summary??node.label}})),edges:encounter.edges.filter(edge=>encounter.nodes.every(node=>node.availability!=="unavailable"||node.ref!==edge.from&&node.ref!==edge.to)).map(edge=>({from:edge.from,to:edge.to,relation:edge.relation})),truncated:Boolean(encounter.truncated),warnings:[],pinned:pins.filter(ref=>encounter.nodes.some(node=>node.ref===ref&&node.availability!=="unavailable")),grammar:{state:"unavailable",detail:"The hosted Projection disclosed no source-backed QL participation contract."},relationBindingsUnavailable:0}),[encounter,pins]);
  const express=async()=>{setExpressionBusy(true);setExpressionError("");stagePresentation.current?.release();stagePresentation.current=null;try{const outcome=await projectProvidedLocalWhole(transport,`explore:${encounter.resource.world_ref}:${encounter.focus}`,focus.label,whole);setExpressionOutcome(outcome);if(outcome.state!=="ready")throw new Error(outcome.state==="unavailable"?outcome.detail:"The Expression revision changed; project again.");const active=stage.present({id:`explore-knowledge-expression:${encounter.focus}`,plane:"overlay",recipe:"",config:expressionConfig(outcome.document),sceneRef:outcome.document.selection.scene_ref});if(!active)throw new Error(stage.error??"The Expression stage refused this knowledge presentation");stagePresentation.current=active;active.setContainer(expressionHost.current);active.updateConfig(expressionConfig(outcome.document),outcome.document.selection.scene_ref,outcome.document.selection.entity_ref?[outcome.document.selection.entity_ref]:[]);setMode("expression");}catch(error){setExpressionError(String(error instanceof Error?error.message:error));}finally{setExpressionBusy(false);}};
  useEffect(()=>()=>stagePresentation.current?.release(),[]);
  return <section className="knowledge-encounter" aria-label="Projected knowledge local whole" data-knowledge-state={encounter.state} data-focus-ref={encounter.focus} data-node-count={encounter.nodes.length} data-relation-count={encounter.edges.length}>
    <header className="knowledge-encounter__header"><div><span>Wiki / M0 local whole</span><h1>{focus.label}</h1><code>{encounter.focus}{focus.revision?` @ ${focus.revision}`:""}</code></div><div className="knowledge-encounter__travel" role="group" aria-label="Knowledge travel"><button type="button" aria-pressed={pins.includes(encounter.focus)} onClick={togglePin}>{pins.includes(encounter.focus)?"Pinned":"Pin"}</button><button type="button" aria-pressed={follow} onClick={()=>setFollow(value=>{const next=!value;if(!next)setHeldLocus(encounter.focus);try{localStorage.setItem("oi-cradle.explore-knowledge-follow.v1",String(next));}catch{/* view state remains usable */}return next;})}>{follow?"Following locus":"Follow locus"}</button></div></header>
    {encounter.state==="degraded"&&<div className="knowledge-encounter__degraded" role="status"><strong>Relations unavailable</strong><p>{encounter.detail}</p><p>The projected page and exact source identity remain available.</p></div>}
    <nav className="knowledge-encounter__modes" aria-label="Knowledge presentation">{(["graph","tree","list","page"] as Mode[]).map(candidate=><button key={candidate} type="button" aria-pressed={selectedMode===candidate} disabled={!encounter.presentations.includes(candidate)} onClick={()=>setMode(candidate)}>{candidate}</button>)}<button type="button" aria-pressed={selectedMode==="expression"} disabled={encounter.state!=="available"||expressionBusy} onClick={()=>void express()}>{expressionBusy?"Expressing…":"Expression"}</button></nav>
    {pins.length>0&&<div className="knowledge-encounter__pins" aria-label="Pinned knowledge subjects">{pins.map(ref=><button key={ref} type="button" disabled={!encounter.nodes.some(node=>node.ref===ref&&node.availability!=="unavailable")} onClick={()=>open(ref)}>{ref}</button>)}</div>}
    {selectedMode==="graph"&&<Graph encounter={encounter} visualLocus={visualLocus} onOpen={open}/>} 
    {selectedMode==="tree"&&<div className="knowledge-encounter__tree"><article><span>Focus</span><strong>{focus.label}</strong><code>{focus.ref}</code></article><ol>{neighbours.map(({edge,ref})=>{const node=encounter.nodes.find(item=>item.ref===ref)!;return <li key={`${edge.from}:${edge.relation}:${edge.to}`}><button type="button" onClick={()=>open(ref)}><small>{relationLabel(edge.relation)} · {edge.origin}</small><strong>{node.label}</strong><code>{node.ref}</code></button></li>;})}</ol></div>}
    {selectedMode==="list"&&<ol className="knowledge-encounter__list">{encounter.nodes.map(node=><li key={node.ref}><button type="button" aria-current={node.ref===encounter.focus?"true":undefined} onClick={()=>open(node.ref)}><span>{node.kind}</span><strong>{node.label}</strong><code>{node.ref}{node.revision?` @ ${node.revision}`:""}</code></button></li>)}</ol>}
    {selectedMode==="page"&&<div className="knowledge-encounter__page" data-knowledge-presentation="page">{page}</div>}
    <div ref={expressionHost} className="knowledge-encounter__expression" data-active={selectedMode==="expression"&&expressionOutcome?.state==="ready"}/>
    {selectedMode==="expression"&&expressionOutcome?.state==="ready"&&<p role="status">{expressionOutcome.whole.members.length} subjects · {expressionOutcome.whole.edges.length} typed relations · Expression r{expressionOutcome.document.revision}</p>}
    {expressionError&&<p role="alert">{expressionError}</p>}
    <footer><span>{encounter.nodes.length} subjects · {encounter.edges.length} typed relations{encounter.truncated?" · bounded at owner budget":""}</span><span>Actions: {encounter.actions.length?encounter.actions.join(" · "):"none disclosed"}</span></footer>
  </section>;
}

function Graph({encounter,visualLocus,onOpen}:{encounter:Encounter;visualLocus:string;onOpen:(ref:string)=>void}) {
  const positioned=encounter.nodes.map(node=>{if(node.ref===visualLocus)return {...node,x:400,y:215};const others=Math.max(1,encounter.nodes.length-1),slot=encounter.nodes.filter(item=>item.ref!==visualLocus).findIndex(item=>item.ref===node.ref),angle=(Math.PI*2*slot)/others-Math.PI/2;return {...node,x:400+Math.cos(angle)*260,y:215+Math.sin(angle)*145};});
  const byRef=new Map(positioned.map(node=>[node.ref,node]));
  return <svg className="knowledge-encounter__graph" viewBox="0 0 800 430" role="img" aria-label="Bounded typed knowledge constellation" data-visual-locus={visualLocus}>{encounter.edges.map((edge,index)=>{const from=byRef.get(edge.from),to=byRef.get(edge.to);return from&&to?<g key={`${edge.from}:${edge.relation}:${edge.to}:${index}`}><line x1={from.x} y1={from.y} x2={to.x} y2={to.y}/><text x={(from.x+to.x)/2} y={(from.y+to.y)/2-6}>{relationLabel(edge.relation)}</text><title>{edge.relation} · {edge.origin} · {edge.provenance.map(row=>`${row.ref}@${row.revision??"unrevisioned"}`).join(", ")}</title></g>:null;})}{positioned.map(node=><g key={node.ref} className={`${node.ref===encounter.focus?"is-focus":""}${node.availability==="unavailable"?" is-unavailable":""}`} data-knowledge-ref={node.ref} transform={`translate(${node.x},${node.y})`} role="button" aria-disabled={node.availability==="unavailable"} tabIndex={node.availability==="unavailable"?-1:0} onClick={()=>onOpen(node.ref)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();onOpen(node.ref);}}}><circle r={node.ref===encounter.focus?34:22}/><text y={node.ref===encounter.focus?52:39}>{node.label}</text><title>{node.ref}{node.revision?` @ ${node.revision}`:""}{node.availability==="unavailable"?" · unavailable":""}</title></g>)}</svg>;
}
