// Exercise the local presentation model. These are not product-integration receipts.
export default async function run({page,baseUrl,check,shot}) {
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const control=name=>page.getByRole('button',{name,exact:true});
 await page.goto(`${baseUrl}/?study=chat`);await page.getByRole('tab',{name:'Designing the desktop',exact:true}).waitFor();
 check(await page.getByRole('complementary',{name:'Central sidebar'}).count()===1 && await page.locator('.s-rail').count()===0,'One Central sidebar replaces the duplicated left rails');
 check(await page.locator('.w-project-modes').first().getByRole('button').count()===3,'Projects expose exactly three compact view controls');
 check(await control('O-I: chats and tasks').getAttribute('aria-pressed')==='true','Project navigation defaults to chats and tasks');
 await control('Open agent as chat tab').click();
 check(await page.getByRole('tab',{name:'Designing the desktop',exact:true}).count()===1,'Agent access focuses the existing encounter instead of duplicating it');
 await page.getByLabel('Message in a').fill('Keep this session draft across presentations.');
 await control('O-I: files').click();
 check(await page.getByLabel('Message in a').inputValue()==='Keep this session draft across presentations.','Changing the sidebar lens leaves the active chat and draft intact');
 await control('Research: files').click();
 check(await page.getByLabel('Message in a').isVisible(),'Browsing another project does not silently switch the canvas');
 await control('O-I: wiki').click();
 check(await page.getByLabel('O-I contextual graph').isVisible(),'Project wiki opens from its contextual sidebar control');
 check(await page.locator('.s-segments,.s-view-switch').count()===0,'Graph has no redundant scope tabs or graph/list controls');
 await page.getByRole('tab',{name:'Designing the desktop',exact:true}).click();
 check(await control('O-I: wiki').getAttribute('aria-pressed')==='true','Activating a chat preserves the project’s remembered sidebar lens');
 await page.getByLabel('Active workspace').selectOption('Research');
 await control('Open agent as chat tab').click();
 check(await page.getByRole('tab',{name:'Questions worth keeping',exact:true}).count()===1 && await page.getByRole('tab').count()===1,'Agent access reuses the Research encounter after workspace restore');
 check(await control('O-I: chats and tasks').getAttribute('aria-pressed')==='true','Sidebar lenses are scoped to workspace and project');
 await page.getByLabel('Active workspace').selectOption('Central');
 check(await control('O-I: wiki').getAttribute('aria-pressed')==='true','Returning to workspace restores its project lens');
 await page.reload();await page.getByLabel('Message in a').waitFor();
 check(await page.getByLabel('Message in a').inputValue()==='Keep this session draft across presentations.','Reload preserves the encounter draft and active surface');
 await control('O-I: files').click();await shot('chat-files');
 await page.goto(`${baseUrl}/?study=tiled`);await page.getByLabel('O-I contextual graph').waitFor();
 check(await page.locator('.w-pane').count()===3,'Tiled preset presents three independent window groups');
 check(await page.getByRole('tablist').count()===3,'Every group has its own tab bar');
 await page.getByLabel('Edit shell-direction.md').fill('Held source writing survives window moves.');
 await page.getByLabel('Message in c').fill('Same session, larger surface.');
 await control('Maximize conversation c').click();
 check(await page.locator('.w-pane').count()===1 && await page.getByRole('complementary',{name:'Central sidebar'}).isVisible(),'Full conversation masks other groups and retains Central navigation');
 check(await page.getByLabel('Message in c').inputValue()==='Same session, larger surface.','Maximization retains the same session draft');
 await shot('full-chat');
 await page.keyboard.press('Escape');
 check(await page.locator('.w-pane').count()===3 && await page.getByLabel('Edit shell-direction.md').inputValue()==='Held source writing survives window moves.','Escape restores exact tiled source and conversation state');
 const divider=page.getByRole('separator',{name:'Resize tiled groups'});await divider.focus();await page.keyboard.press('ArrowLeft');
 check(await divider.getAttribute('aria-valuenow')==='53','Tiling divider resizes from the keyboard');
 await control('Window menu c').click();await page.getByRole('menuitem',{name:'Move to group 2 (b)',exact:true}).click();
 check(await page.getByLabel('Message in b').inputValue()==='Same session, larger surface.' && await page.getByRole('tab',{name:'Designing the desktop',exact:true}).count()===1,'Context menu moves one encounter binding and its draft between groups');
 await page.getByRole('tab',{name:'Designing the desktop',exact:true}).click({button:'right'});await page.getByRole('menuitem',{name:'Move into a new split',exact:true}).click();
 check(await page.getByLabel('Message in c').inputValue()==='Same session, larger surface.','Split action reuses the empty group without duplicating session');
 await control('Arrange columns').click();
 check(await page.locator('.w-pane').count()===2 && await page.getByRole('tab').count()===4,'Changing arrangement consolidates tabs without losing surfaces');
 await page.reload();await page.getByRole('tab',{name:'Designing the desktop',exact:true}).waitFor();
 check(await page.locator('.w-pane').count()===2,'Reload restores the saved pane arrangement');
 await control('Arrange studio').click();await control('Open agent as chat tab').click();await control('Window menu a').click();await page.getByRole('menuitem',{name:'Move to group 2 (c)',exact:true}).click();
 await page.getByRole('tab',{name:'O-I wiki',exact:true}).click();await control('O-I: files').click();await shot('tiled-files');
 await page.locator('.w-tab-shell').filter({has:page.getByRole('tab',{name:'intent.md',exact:true})}).dragTo(page.locator('.w-pane').first());
 check(await page.getByRole('tablist',{name:'Tabs in a'}).getByRole('tab',{name:'intent.md',exact:true}).count()===1,'Pointer drag moves the tab into the targeted window group');
 await control('Shared Field 2').click();
 check(await page.getByRole('button',{name:'Select node Design commons',exact:true}).isVisible(),'Field opens an admitted neighbourhood with its distinct entry');
 check(await page.getByRole('button',{name:'Select node Design guidance',exact:true}).count()===0,'Shared Field omits private local graph subjects');
 await control('Open Central wiki').click();
 check(await page.getByLabel('Central contextual graph').isVisible(),'Central wiki remains the containing local graph');
 await page.setViewportSize({width:900,height:760});
 check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Smaller desktop has no page-level horizontal overflow');
 check(errors.length===0,`No renderer exceptions (${errors.join('; ')})`);
}
