import {docText, waitForDoc} from '../editor-doc.mjs';
import {setup} from './files.mjs';
import {readFileSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
export {setup};
export default async function run({page,baseUrl,check,shot,channel,provision:p}) {
 await page.goto(baseUrl);await channel('info');
 const nav=page.getByRole('complementary',{name:'World navigator'});
 await nav.locator('[data-project-path="Work/Other"]').click();
 await nav.getByRole('button',{name:'Other: files',exact:true}).click();
 await nav.getByRole('button',{name:'Expand folder src',exact:true}).click();
 await nav.locator(`[data-file-path="${p.path}"]`).click();
 const file=page.getByRole('region',{name:'File ordinary.ts',exact:true});
 const editor=file.getByRole('textbox',{name:'Editing ordinary.ts',exact:true});await editor.waitFor();
 check(await docText(page,'.cm-content')===p.content,'Editable ordinary file begins with exact owner bytes');
 const first='First native ordinary edit.\n';await editor.fill(first);
 await editor.press('Home');await editor.press('ArrowRight');await editor.press('Shift+ArrowRight');
 const caret=async()=>(await page.locator('.editor-footer').allTextContents()).join(' ').match(/Ln \d+, Col \d+/)?.[0];
 const selection=await caret();
 await page.keyboard.press('Meta+w');await page.keyboard.press('Meta+Shift+t');await editor.waitFor();
 await page.waitForFunction(expected=>[...document.querySelectorAll('.editor-footer')].map(f=>f.textContent).join(' ').includes(expected),selection);
 check(true,'Close and reopen retains ordinary-file caret and selection');
 await page.reload();await editor.waitFor();
 check(await docText(page,'.cm-content')===first,'Unsaved ordinary draft survives reload');
 check(readFileSync(join(p.root,p.path),'utf8')===p.content,'Retaining a draft does not write the source');
 await file.getByRole('button',{name:'Save',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.source-clean-marker')?.textContent==='Saved');
 check(readFileSync(join(p.root,p.path),'utf8')===first,'Explicit Save writes actual bytes through Central');
 const mine='My conflicting draft.\n',theirs='External writer.\n';await editor.fill(mine);writeFileSync(join(p.root,p.path),theirs);
 await file.getByRole('button',{name:'Save',exact:true}).click();
 await file.getByRole('region',{name:'File conflict'}).waitFor();
 check(await docText(page,'.cm-content')===mine&&readFileSync(join(p.root,p.path),'utf8')===theirs,'CAS conflict preserves both actual source and held typing');
 check(await file.getByRole('textbox',{name:'Current file',exact:true}).inputValue()===theirs,'Conflict comparison reads the actual current owner revision');
 await file.getByRole('button',{name:'Use current revision as draft basis'}).click();
 await file.getByRole('button',{name:'Save',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.source-clean-marker')?.textContent==='Saved');
 check(readFileSync(join(p.root,p.path),'utf8')===mine,'Explicit reconciliation then Save uses the current native basis');
 await file.getByRole('button',{name:'History',exact:true}).click();
 await file.getByRole('button',{name:/^Compare before change /}).last().click();
 const preview=file.getByRole('region',{name:'File recovery preview'});await preview.waitFor();
 check(readFileSync(join(p.root,p.path),'utf8')===mine,'Recovery preview performs no source mutation');
 check(await preview.getByRole('textbox',{name:'Recovery content',exact:true}).inputValue()===p.content,'Recovery preview contains exact retained original bytes');
 await preview.getByRole('button',{name:'Restore this revision'}).click();
 await page.waitForFunction(()=>!document.querySelector('.file-recovery'));
 check(readFileSync(join(p.root,p.path),'utf8')===p.content&&await docText(page,'.cm-content')===p.content,'Explicit Restore updates native source and visible reading together');
 await shot('ordinary-native-cas-history-restore');
}
