import {docText, waitForDoc, openChrome} from '../editor-doc.mjs';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
export { setup } from './editor.mjs';

export default async function run({ page, baseUrl, check, shot, channel, provision: p, log }) {
  page.on("response", async response => {
    if (!response.url().endsWith("/op")) return;
    try { const request=response.request().postDataJSON(); if (request.op === "source_history") log(`Native history response: ${await response.text()}`); } catch { /* the completed walk may close a response */ }
  });
  await page.goto(baseUrl); await channel('info');
  const source = p.sources[0];
  const ref = source.binding.ref;
  if (!await page.getByRole('complementary', {name:'World navigator'}).isVisible()) await page.keyboard.press('Meta+b');
  await page.locator('[data-project-path="Work/Editor"]').click();
  if(await page.getByRole('button',{name:'Editor: files',exact:true}).getAttribute('aria-pressed') !== 'true') await page.getByRole('button',{name:'Editor: files',exact:true}).click();
  await page.locator(`[data-file-path="Work/Editor/${p.sources[0].binding.path}"]`).click();
  const text = page.locator('.cm-content');
  await text.waitFor();
  await openChrome(page, '.source-editor');
  await page.locator('.source-editor').getByRole('button', { name: 'History', exact: true }).click();
  const history = page.getByRole('region', { name: 'Source history' });
  const rows = history.locator('li');
  const settled = () => page.waitForFunction(() => document.querySelector('.source-history')?.getAttribute('aria-busy') === 'false');
  await settled();
  const initialCount = await rows.count();
  const ownerRows = () => p.call('projectcentral.change.horizon', { project: 'Editor' }).changes.filter(c => c.source_ref === ref);
  check(initialCount === ownerRows().length, 'Initial history matches actual retained Central records');
  const original = p.call('projectcentral.source.read', { project: 'Editor', source_ref: ref });
  const human = 'Local writing to reconcile.\n';
  const external = 'Concurrent writing from another real Central caller.\n';
  await text.fill(human);
  const externalWrite = p.call('projectcentral.source.write', { project: 'Editor', source_ref: ref, expected_revision: original.revision.revision, content: external, actor: 'integration:concurrent-writer', actor_kind: 'human' });
  await page.keyboard.press('Meta+s');
  const conflict = page.locator('.source-conflict');
  await conflict.waitFor();
  check(await docText(page,'.cm-content') === human, 'Conflict preserves the exact local writing');
  check(await conflict.locator('[data-canonical]').textContent() === external, 'Conflict displays the exact concurrently saved canonical side');
  check(readFileSync(join(p.projectRoot, source.binding.path), 'utf8') === external, 'Failed CAS never overwrites the concurrent source');
  const current = externalWrite.receipt.revision.revision;
  check(await conflict.locator('[data-current]').getAttribute('data-current') === current, 'Conflict names the actual competing owner revision');
  check(ownerRows().length === initialCount + 1, 'A refused save adds no owner history record');
  await page.waitForFunction(count => document.querySelectorAll('.source-history-rows li').length === count, initialCount + 1);
  check(await rows.count() === initialCount + 1, 'Conflict refreshes history to include the competing owner write');
  await shot('both-sides');
  const merged = `${human}${external}`;
  await text.fill(merged);
  await conflict.getByRole('button').click();
  await conflict.waitFor({ state: 'detached' });
  check(await docText(page,'.cm-content') === merged, 'Explicit re-read preserves the reconciled writing');
  check(await page.locator('.source-revision').getAttribute('data-revision') === current, 'Re-read uses the resulting canonical revision as the CAS base');
  await text.focus(); await page.keyboard.press('Meta+s');
  await page.waitForFunction(() => document.querySelector('.source-editor')?.getAttribute('data-dirty') === 'false');
  await page.waitForFunction(count => document.querySelectorAll('.source-history-rows li').length === count, initialCount + 2);
  check(readFileSync(join(p.projectRoot, source.binding.path), 'utf8') === merged, 'Resolved save commits both reconciled contributions');
  check(await rows.count() === initialCount + 2, 'History increments exactly once for the resolved save');
  const owned = ownerRows().sort((a,b) => b.cursor-a.cursor);
  check(await rows.first().getAttribute('data-change-ref') === owned[0].change_ref, 'History uses the owner change ref without inventing identity');
  check((await rows.first().innerText()).includes('human:desktop'), 'History preserves the native write attribution');
  check((await rows.evaluateAll(nodes => nodes.map(n => n.getAttribute('data-source-ref')))).every(r => r === ref), 'History excludes every other source');
  await text.focus(); await page.keyboard.press('Meta+s');
  await channel('read.state');
  check(ownerRows().length === initialCount + 2, 'A no-change save creates no fabricated history row');
  await rows.first().getByText('Revision and provenance').click();
  await shot('resolved-history');
  await page.keyboard.press('Meta+w'); await page.keyboard.press('Meta+Shift+t');
  await text.waitFor();
  await openChrome(page, '.source-editor');
  await page.locator('.source-editor').getByRole('button', { name: 'History', exact: true }).click(); await settled();
  check(await rows.count() === initialCount + 2, 'Reopened source reads the durable owner history');
  check(await docText(page,'.cm-content') === merged, 'Reopening preserves the saved reconciliation');
}
