import { execFileSync } from 'node:child_process';
export default async function run({ page, baseUrl, check, metric, shot, channel }) {
  const owner = (action, input = {}) => {
    const args = ['--json'];
    if (process.env.OI_CENTRAL_ROOT) args.push('--root', process.env.OI_CENTRAL_ROOT);
    args.push('action', 'run', action, JSON.stringify(input));
    const result = JSON.parse(execFileSync(process.env.OI_CENTRAL_CTRL_BIN ?? 'ctrl', args, { encoding: 'utf8' }));
    if (!result.ok) throw new Error(JSON.stringify(result));
    return result.data;
  };
  const expected = owner('central.world');
  await page.goto(baseUrl);
  await channel('info');
  await page.getByRole('textbox', { name: 'Writing surface' }).fill('Keep this writing while I explore my world.');
  const started = Date.now();
  await page.keyboard.press('Meta+b');
  const nav = page.getByRole('complementary', { name: 'World navigator' });
  const settled = () => page.waitForFunction(() => document.querySelector('.world-navigator')?.getAttribute('aria-busy') === 'false');
  await nav.locator('[data-project-path]').first().waitFor(); await settled();
  metric('world_summon_ms', Date.now() - started);
  const paths = await nav.locator('[data-project-path]').evaluateAll(rows => rows.map(r => r.dataset.projectPath));
  check(JSON.stringify(paths) === JSON.stringify(expected.work.projects.map(p => p.path)), 'Every project row matches the real Central World map in owner order', paths);
  check(await page.locator('.canvas-surface').inputValue() === 'Keep this writing while I explore my world.', 'Summoning retains the original writing buffer');
  await nav.getByRole('searchbox').fill('O-I');
  check(await nav.locator('[data-project-path]').count() === expected.work.projects.filter(p => p.name.toLowerCase().includes('o-i')).length, 'Filter narrows only real projects');
  const project = expected.work.projects.find(p => p.name === 'O-I');
  if (!project) throw new Error('Real O-I project required');
  await nav.locator(`[data-project-path="${project.path}"]`).click();
  await nav.getByRole('heading', { name: 'O-I', exact: true }).waitFor(); await settled();
  const state = (await channel('read.state')).data;
  const snapshot = state.snapshot ?? state;
  const ground = owner('projectcentral.inspect', { project: 'O-I' });
  check(snapshot.navigator.project.project.path === project.path, 'Kernel holds the selected owner project reading');
  check(snapshot.navigator.project_ref === ground.manifest.project_id, 'Project ref is the owner manifest identity verbatim');
  check(snapshot.focus.project.ref === ground.manifest.project_id && snapshot.focus.subject.ref === ground.manifest.project_id, 'Global focus carries the selected project');
  check((await nav.locator('[data-ground-relations]').innerText()).includes(project.projectcentral.relations.path), 'Ground relations show their real owner location');
  await nav.locator('summary').filter({ hasText: 'Root wiki' }).click();
  const rootWiki = expected.control.agent_wiki.wiki;
  check(await nav.locator(`[data-wiki-ref="${rootWiki.space_ref}"]`).isVisible(), 'Root wiki identity is reachable from the project');
  await nav.locator('summary').filter({ hasText: 'Project wiki' }).click();
  check(await nav.locator(`[data-wiki-ref="${project.projectcentral.agent_wiki.wiki.space_ref}"]`).isVisible(), 'Distinct project wiki identity is preserved');
  check((await nav.locator('[data-federation]').innerText()).includes('is linked') === rootWiki.child_space_refs.includes(project.projectcentral.agent_wiki.wiki.space_ref), 'Federation statement agrees with real root wiki children');
  await shot('project-ground');
  await nav.getByRole('button', { name: /^Central / }).click(); await settled();
  const rootState = (await channel('read.state')).data;
  check(!rootState.navigator.project && !rootState.focus.project && !rootState.focus.subject, 'Selecting the root clears the old project selection and focus');
  await page.keyboard.press('Escape');
  check(await nav.count() === 0 && await page.locator('.canvas-surface').inputValue() === 'Keep this writing while I explore my world.', 'Escape dismisses to the same writing');
  await page.waitForFunction(() => document.activeElement === document.querySelector('.canvas-surface'), null, { timeout: 5000 });
  check(true, 'Dismiss restores writing caret');
  await page.locator('.agency-field').click({ button: 'right' });
  await page.getByRole('menuitem', { name: 'World (⌘B)' }).click();
  await nav.waitFor();
  check(await nav.isVisible(), 'Pointer context menu summons the same World surface');
  const unbound = expected.work.projects.find(p => p.projectcentral.state === 'absent');
  if (unbound) {
    await nav.getByRole('searchbox').fill(unbound.name);
    await nav.locator(`[data-project-path="${unbound.path}"]`).click();
    await nav.getByRole('heading', { name: unbound.name, exact: true }).waitFor(); await settled();
    check(await nav.getByText('Ordinary Work project · no ProjectCentral binding', { exact: true }).isVisible(), 'Ordinary Work project stays truthfully unbound');
    const current = (await channel('read.state')).data;
    const unboundState = current.snapshot ?? current;
    check(!unboundState.focus.project && !unboundState.focus.world && !unboundState.navigator.project_ref, 'Unbound project clears stale focus and fabricates no identity');
  }
  await nav.getByRole('button', { name: 'Close World navigator' }).click();
  check(await nav.count() === 0, 'Pointer close returns to rest');
  await page.waitForFunction(() => document.activeElement === document.querySelector('.canvas-surface'), null, { timeout: 5000 });
  check(true, 'Pointer summon and close restore the original caret rather than the removed menu item');
  const events = (await channel('read.events', [0])).data.receipts;
  check(events.every((e, i) => e.seq === i + 1), 'World event log is contiguous and ordered', events);
  check(events.some(e => e.event === 'world_changed') && events.some(e => e.event === 'focus_changed'), 'World and focus each publish state changes');
  await shot('restored-writing');
  await page.addInitScript(() => { delete window.__OI_KERNEL_BRIDGE__; });
  await page.reload(); await channel('info');
  await page.keyboard.press('Meta+b');
  await nav.getByRole('status').filter({ hasText: 'no kernel transport' }).waitFor();
  check(await nav.locator('[data-project-path]').count() === 0, 'Unavailable owner transport fabricates no project rows');
  check(await nav.getByRole('status').isVisible(), 'Unavailable transport is disclosed locally in the navigator');
}
