import {setup as sourceSetup} from './editor.mjs';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
export const setup=sourceSetup;
export default async function run({page,baseUrl,check,shot,channel,provision:p}){
 page.setDefaultTimeout(10000);await page.goto(baseUrl);await channel('info');
 const nav=page.getByRole('complementary',{name:'World navigator'});
 await nav.locator('[data-project-path="Work/Editor"]').click();await nav.getByRole('button',{name:'Editor: files',exact:true}).click();
 const source=p.sources[0];await nav.locator(`[data-file-path="Work/Editor/${source.binding.path}"]`).click();
 const editor=page.locator('.cm-content');await editor.waitFor();
 check(await page.getByRole('button',{name:'Text',exact:true}).count()===0&&await page.getByRole('button',{name:'Components',exact:true}).count()===0,'Pen and @ are the only mode selectors');
 check(await page.locator('.editor-command-line').getByRole('button',{name:'Bold',exact:true}).isVisible(),'Writing mode exposes its editing toolkit in the header');
 const writingMenu=async()=>{const box=await editor.locator('.cm-line').first().boundingBox();await page.mouse.click(box.x+35,box.y+8,{button:'right'});};
 await editor.fill('A real editing surface.\nSecond line.\n');
 await page.waitForFunction(()=>document.querySelector('.source-editor')?.dataset.dirty==='true');
 await editor.press('Meta+s');await page.waitForFunction(()=>document.querySelector('.source-editor')?.dataset.dirty==='false');
 check(readFileSync(join(p.projectRoot,source.binding.path),'utf8')==='A real editing surface.\nSecond line.\n','CodeMirror saves exact text through the real Central source owner');
 await editor.press('Meta+ArrowUp');await editor.press('Meta+Shift+ArrowRight');
 await writingMenu();await page.getByRole('menuitem',{name:'Highlight yellow',exact:true}).click();
 check(await page.locator('.text-highlight').count()>0,'Standard selection accepts a visual highlight');
 check(await page.locator('.source-editor').getAttribute('data-dirty')==='false','Highlighting does not modify the authored document');
 await writingMenu();await page.getByRole('menuitem',{name:'Bold',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.source-editor')?.dataset.dirty==='true');await editor.press('Meta+s');await page.waitForFunction(()=>document.querySelector('.source-editor')?.dataset.dirty==='false');
 check(readFileSync(join(p.projectRoot,source.binding.path),'utf8').startsWith('**A real editing surface.**'),'Markdown toolbar applies formatting to the actual selected range');
 await editor.press('Meta+z');await page.waitForFunction(()=>document.querySelector('.source-editor')?.dataset.dirty==='true');await editor.press('Meta+s');await page.waitForFunction(()=>document.querySelector('.source-editor')?.dataset.dirty==='false');
 check(readFileSync(join(p.projectRoot,source.binding.path),'utf8').startsWith('A real editing surface.'),'Undo restores real document content');
 await writingMenu();await page.getByRole('menuitem',{name:'Find / Replace',exact:true}).click();
 check(await page.locator('.cm-search').isVisible(),'Editor search and replace panel is available');await editor.press('Escape');
 const content=page.locator('.editor-content'),before=(await content.boundingBox()).height;
 await page.getByTitle('Hide editing tools',{exact:true}).click();await page.waitForTimeout(300);
 check((await content.boundingBox()).height>before+25,'Folding the toolbar yields its height to document content');
 check((await page.getByTitle('Show editing tools',{exact:true}).boundingBox()).height>=26,'Collapsed header keeps a usable reveal target');
 await page.getByTitle('Show editing tools',{exact:true}).focus();await page.getByTitle('Show editing tools',{exact:true}).click();
 const pane=page.locator('.pane.group.focused'),footer=pane.locator('.editor-footer');const pb=await pane.boundingBox();
 await page.mouse.move(pb.x+pb.width/2,pb.y+pb.height/2);await page.waitForTimeout(250);
 check((await footer.boundingBox()).height<=4,'Hovering pane content does not reveal its footer');
 const contentBefore=(await content.boundingBox()).height;
 const fb=await footer.boundingBox();await page.mouse.move(fb.x+fb.width/2,fb.y+1);await page.waitForTimeout(550);
 check((await footer.boundingBox()).height>=23,'Only the bottom edge reveals the pane footer');
 check((await content.boundingBox()).height<contentBefore-18,'Footer expansion gives up document height instead of overlaying it');
 await page.mouse.move(pb.x+pb.width/2,pb.y+80);
 const tab=page.locator('.tab').first();await tab.click({button:'right'});await page.getByRole('menuitem',{name:'Focus this tab',exact:true}).click();await page.waitForTimeout(300);
 check((await pane.locator('.tab-strip').boundingBox()).height<2,'Per-tab focus folds away the tab strip');await page.keyboard.press('Escape');
 await editor.click({button:'right'});check(await page.getByRole('menu',{name:'Writing commands'}).isVisible()&&await page.getByRole('menuitem',{name:'Focus this tab',exact:true}).count()===0,'Document right-click uses shared menu styling with writing-specific actions');await page.keyboard.press('Escape');
 const left=page.locator('[data-region="left"]');await page.getByRole('button',{name:'Toggle left region',exact:true}).click();await page.waitForTimeout(300);
 check((await left.boundingBox()).width<1,'Sidebar closes fully');await page.getByRole('button',{name:'Toggle left region',exact:true}).click();await page.waitForTimeout(300);
 const resize=page.getByRole('separator',{name:'Resize left region',exact:true});
 check(await resize.evaluate(el=>getComputedStyle(el,'::after').content)==='none','Resize affordance has no visible line');
 const rb=await resize.boundingBox(),old=(await left.boundingBox()).width;await page.mouse.move(rb.x+rb.width/2,rb.y+100);await page.mouse.down();await page.mouse.move(rb.x+rb.width/2+40,rb.y+100,{steps:8});await page.mouse.up();await page.waitForTimeout(250);
 check((await left.boundingBox()).width>old+30,'Dragging changes live sidebar geometry and retains final width');
 const edge=await page.locator('.workspace-footer-edge').boundingBox();await page.mouse.move(edge.x+edge.width-20,edge.y+1);await page.waitForTimeout(550);await page.getByRole('button',{name:'Pin workspace footer',exact:true}).click();
 check(await page.locator('.workspace-footer-edge').getAttribute('data-pinned')==='true','Workspace footer can be pinned');
 await page.getByRole('button',{name:'Unpin workspace footer',exact:true}).click();
 await page.getByRole('button',{name:'New tab',exact:true}).click();await page.getByRole('region',{name:'Fresh canvas'}).waitFor();
 check(await page.getByRole('button',{name:'Browse the web',exact:true}).count()===0,'Fresh canvas retains focused actions without Browse the web');
 check(await page.locator('.welcome-prompt h2').innerText()!=='','Welcome phrase component is integrated');
 await page.waitForTimeout(350);await shot('fresh-canvas-refined');
 await page.getByRole('button',{name:'Write',exact:true}).click();
 const flow=page.locator('.flow-surface');await page.waitForFunction(()=>document.querySelector('.flow-surface [role="status"]')?.textContent==='Saved');
 await flow.locator('.cm-content').fill('Flow writing with the real editor.');await flow.locator('.cm-content').press('Meta+s');
 await page.waitForFunction(()=>document.querySelector('.flow-surface [role="status"]')?.textContent==='Saved');
 const path=(await flow.locator('.editor-path').textContent()).split(' / ').slice(1).join(' / ');
 check(readFileSync(join(p.projectRoot,path),'utf8')==='Flow writing with the real editor.','Fresh Flow uses the same editor and saves to its real Central provenance');
 await page.locator('.tab').filter({hasText:source.binding.path.split('/').pop()}).click({button:'right'});await page.getByRole('menuitem',{name:'Split right',exact:true}).click();
 check(await page.locator('.pane.group').count()===2,'Tab split creates a second real pane');
 await page.locator('.tab').filter({hasText:source.binding.path.split('/').pop()}).click({button:'right'});
 await page.getByRole('menuitem',{name:/Move to pane/}).click();
 check(await page.locator('.pane.group').count()===1,'Per-tab move returns the selected tab and removes its emptied pane');
 await page.getByRole('button',{name:'Toggle right region',exact:true}).click();await page.waitForTimeout(300);
 const right=page.locator('[data-region="right"]');const rightWidth=(await right.boundingBox()).width;
 check(rightWidth>200,'Right sidebar opens with usable width');
 await page.getByRole('button',{name:'Full right region',exact:true}).click();await page.waitForTimeout(300);
 check((await right.boundingBox()).width>rightWidth+100,'Right sidebar expands across the central canvas');
 await page.getByRole('button',{name:'Restore right region',exact:true}).click();await page.waitForTimeout(300);
 check(Math.abs((await right.boundingBox()).width-rightWidth)<2,'Right sidebar restores its previous width');
 check(await page.getByRole('separator',{name:'Resize right region',exact:true}).evaluate(el=>getComputedStyle(el,'::after').content)==='none','Right resize affordance is cursor-only too');
 await page.getByRole('button',{name:'Toggle right region',exact:true}).click();await page.waitForTimeout(350);await shot('editor-and-chrome-refined');
 await page.setViewportSize({width:900,height:820});await page.waitForTimeout(300);
 const compactLeft=page.getByRole('separator',{name:'Resize left region',exact:true});const compactBox=await compactLeft.boundingBox();const compactWidth=(await left.boundingBox()).width;
 await page.mouse.move(compactBox.x+compactBox.width/2,compactBox.y+80);await page.mouse.down();await page.mouse.move(compactBox.x+compactBox.width/2-30,compactBox.y+80,{steps:6});await page.mouse.up();await page.waitForTimeout(300);
 check((await left.boundingBox()).width<compactWidth-20,'Compact-width sidebar dragging retains the chosen width');
 await page.setViewportSize({width:600,height:820});await page.waitForTimeout(300);await page.getByRole('button',{name:'Toggle right region',exact:true}).click();await page.waitForTimeout(300);
 const drawer=page.getByRole('separator',{name:'Resize right region',exact:true}),db=await drawer.boundingBox(),dw=(await right.boundingBox()).width;
 await page.mouse.move(db.x+db.width/2,db.y+80);await page.mouse.down();await page.mouse.move(db.x+db.width/2-50,db.y+80,{steps:6});await page.mouse.up();await page.waitForTimeout(300);
 check((await right.boundingBox()).width>dw+40,'Narrow overlay drawer resizes without snapping back');
 check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Narrow shell has no horizontal overflow');
}
