/** Frame operations over actual owner-backed sources, never synthetic tabs. */
export { setup } from './editor.mjs';
export default async function run({page,baseUrl,check,metric,shot,channel,provision:p}) {
  await page.goto(baseUrl); await channel('info');
  const nav=page.getByRole('complementary',{name:'World navigator'});
  await nav.locator('[data-project-path="Work/Editor"]').click();
  if(await page.getByRole('button',{name:'Editor: files',exact:true}).getAttribute('aria-pressed') !== 'true') await page.getByRole('button',{name:'Editor: files',exact:true}).click();
  const sources=p.sources.slice(0,5);
  const title=s=>s.binding.path.split('/').pop();
  const tab=s=>page.locator('.tab').filter({hasText:title(s)});
  const open=async s=>{await nav.locator(`[data-file-path="Work/Editor/${s.binding.path}"]`).click();await page.waitForFunction(ref=>document.querySelector('.pane.focused .source-textarea')?.dataset.sourceRef===ref,s.binding.ref);};
  const layout=async()=> (await channel('read.layout')).data.layout;
  const start=Date.now();
  for(const s of sources.slice(0,4)) await open(s);
  metric('open_4_tabs_ms',Date.now()-start);
  check(await page.locator('.tab').count()===4,'Four owner sources open as four unique bindings');
  check((await channel('read.focus')).data.subject.ref===sources[3].binding.ref,'Last opened source is the single kernel focus');
  await open(sources[0]);
  check(await page.locator('.tab').count()===4,'Opening an existing ref reuses its binding');
  await page.locator('.source-textarea').fill('Retained through all frame operations.\n');
  await open(sources[4]); await page.keyboard.press('Meta+w');
  check(await page.locator('.tab').count()===4,'Keyboard closes the focused source view');
  await page.keyboard.press('Meta+Shift+t');
  check(await page.locator('.tab').count()===5,'Keyboard reopens the same source binding');
  await tab(sources[4]).getByRole('button').click();
  check(await page.locator('.tab').count()===4,'Pointer close operates on the requested tab');
  await tab(sources[3]).click(); await page.keyboard.press('Meta+d');
  check(await page.locator('.pane.group').count()===2,'Keyboard splits the active source to the right');
  await page.waitForFunction(()=>document.activeElement?.closest('.pane.group')?.getAttribute('data-focused')==='true');
  check(true,'Keyboard split keeps the DOM caret in the semantically active pane');
  await page.keyboard.press('Alt+ArrowLeft');
  check(await page.locator('.pane.focused .tab').count()===3,'Keyboard focus moves to the neighbouring pane');
  await page.keyboard.press('Meta+Alt+ArrowRight');
  check(await page.locator('.pane.focused .tab').count()===2,'Keyboard moves the active binding into the neighbouring pane');
  await page.keyboard.press('Meta+Shift+d');
  check(await page.locator('.pane.group').count()===3,'Keyboard creates a vertical split');
  await page.keyboard.press('Meta+Alt+t');
  check(await page.locator('.pane.group').count()===4,'Keyboard tiles the four real sources');
  check(await page.locator('.source-textarea').count()===4,'Each tiled source has one editor');
  await shot('native-sources-tiled');
  await tab(sources[0]).click();
  check(await page.locator('.pane.focused .source-textarea').inputValue()==='Retained through all frame operations.\n','Tiling and movement retain dirty source writing');
  await tab(sources[0]).click({button:'right'});
  const actions=await page.locator('.ctx-item').evaluateAll(es=>es.map(e=>e.dataset.actionRef));
  check(JSON.stringify(actions)===JSON.stringify(['surface.close','surface.maximize','surface.split-right','surface.split-down','surface.pin']),'Source frame menu discloses exactly its operative frame actions');
  await page.getByRole('menuitem',{name:'Pin',exact:true}).click();
  check(await tab(sources[0]).getAttribute('data-pinned')==='true','Pointer menu pins the requested source');
  await page.keyboard.press('Meta+w');
  check(await tab(sources[0]).count()===1,'Pinned source refuses keyboard close');
  await tab(sources[0]).click({button:'right'});
  check(await page.getByRole('menuitem',{name:'Close (pinned — unpin first)',exact:true}).isDisabled(),'Pinned close is disclosed as disabled');
  await page.keyboard.press('Escape'); await page.keyboard.press('Alt+p');
  check(await tab(sources[0]).getAttribute('data-pinned')==='false','Keyboard unpins the same binding');
  await tab(sources[1]).dragTo(tab(sources[2]));
  check(await page.locator('.pane.group').count()===3,'Pointer drag moves a source and removes its empty pane');
  await tab(sources[1]).click({button:'right'});
  await page.getByRole('menuitem',{name:'Split right',exact:true}).click();
  check(await page.locator('.pane.group').count()===4,'Pointer menu splits the same real binding');
  await tab(sources[1]).click({button:'right'}); await page.keyboard.press('Enter');
  check(await tab(sources[1]).count()===0,'Keyboard menu activation closes the selected view');
  await page.keyboard.press('Meta+Shift+t');
  check(await tab(sources[1]).count()===1,'Closed binding reopens without a new source identity');
  const saved=await layout();
  await page.reload(); await channel('info');
  await page.waitForFunction(()=>document.querySelectorAll('.tab').length===4);
  check(JSON.stringify((await layout()).root)===JSON.stringify(saved.root),'Reload restores pane tree, active tabs, pins and weights exactly');
  await tab(sources[0]).click();
  await page.waitForFunction(()=>document.querySelector('.pane.focused .source-textarea')?.value==='Retained through all frame operations.\n');
  check(true,'Reload restores dirty writing through owner validation');
  const focusBefore=(await channel('read.focus')).data;
  const arrangement=JSON.stringify((await layout()).root);
  await nav.locator('[data-project-path="Work/Other"]').click();
  if(await page.getByRole('button',{name:'Other: files',exact:true}).getAttribute('aria-pressed') !== 'true') await page.getByRole('button',{name:'Other: files',exact:true}).click();
  check(JSON.stringify((await layout()).root)===arrangement,'Browsing another project never replaces open work');
  check(JSON.stringify((await channel('read.focus')).data)===JSON.stringify(focusBefore),'Browsing preserves the canonical focused source');
  const events=(await channel('read.events',[0])).data.receipts;
  check(events.every((e,i)=>e.seq===i+1),'Kernel receipts stay contiguous across frame operations');
  await shot('source-frame-menu');
}
