/** The personal instrument is source/occasion-bound, not another chatbot.
 * It operates native M4 records and the existing Central/Flow surfaces. */
import {useEffect,useRef,useState} from 'react';
import {useKernel} from '../../kernel/KernelProvider';
import {DayDieFace} from '../../receiving/DayDieFace';
import type {SurfaceBinding} from '../../surface/types';
import type {CentralLocation,NativeFileReading} from '../../kernel/types';
import {readFile} from '../../files/client';
import {listFlowInstances,readFlowInstance,writeFlowInstance,userFlowsArea,type FlowInstanceRow} from '../../flow/instances';
import {DOCUMENT_FORMS,resolveDocumentForm} from '../../flow/documentForms';
import {focusedInstrumentSources,focusedInstrumentSource} from '../../instrument/source';
import type {NaraRuntime} from '../runtime';
import {IdentityMaterialPanel} from './IdentityMaterialPanel';
import {endIdentity} from './identityHosts';
import {personalCall,PersonalController,readEnvelope,targetOf,object,text,type PersonalCapabilities,type PersonalRecord,type PersonalTarget} from './client';
import {identitySource,contextSource,nextPractice,sourceBasis,protectedSource,interpretOracle} from './operations';
import {previewDialogueReturn,acceptDialogueReturn,type ReturnPreview} from './flowReturn';
import {OwnWords} from './OwnWords';
import {SourcePicker} from './SourcePicker';
import './personal.css';
const labels:Record<string,string>={'birthdate-name':'Your name and birth information','natal-chart':'Natal chart','jungian-assessment':'Jungian assessment','gene-keys':'Gene Keys','human-design':'Human Design','archetypal-quintessence':'Archetypal quintessence'};
const hints:Record<string,string>={'birthdate-name':'Use your own words. Unknown birth date, time or place stays unknown; none is required to begin.','natal-chart':'Link an existing source-qualified chart. Do not substitute a guessed time or an automatically invented chart.','jungian-assessment':'A reported or assessed interpretation, not a permanent definition of you.','gene-keys':'An optional interpretive source. Leaving it unprovided does not block the personal field.','human-design':'An optional source with its own method and provenance; this interface does not infer a result.','archetypal-quintessence':'A source-backed synthesis offered for recognition, not an automatic summary authored on your behalf.'};
const sections=[['identity','Identity'],['embodied','Centres'],['oracle','Oracle'],['transformation','Practice'],['context','Perspectives'],['integration','Returns']] as const;
// Presentation-lifetime retention only. Native QL and Central keep durable work;
// no private drafts or records are copied into browser storage or diagnostics.
interface HeldPersonal {caps:PersonalCapabilities;host:string;controller:PersonalController;read:ReturnType<typeof personalCall>;source:NativeFileReading|null;candidate:Candidate|null;preview:ReturnPreview|null}
interface Candidate {label:string;mutation:Record<string,unknown>;revision:number;source:NativeFileReading|null}
const held=new Map<string,HeldPersonal>();
const rows=(value:unknown):Record<string,unknown>[]=>Array.isArray(value)?value.map(v=>object(v)):[];
export function PersonalWorkbench({binding,runtime}:{binding:SurfaceBinding;runtime?:NaraRuntime}){
 const kernel=useKernel(),transport=useRef(kernel.transport);transport.current=kernel.transport;
 const [entry,setEntry]=useState(held.get(binding.id)),[record,setRecord]=useState<PersonalRecord|null>(entry?.controller.snapshot.record??null);
 const [caps,setCaps]=useState<PersonalCapabilities>(entry?.caps as PersonalCapabilities),[targets,setTargets]=useState<{target:PersonalTarget;event_ref:string}[]>([]),[chosen,setChosen]=useState('');
 const [consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [tab,setTab]=useState('identity'),[source,setSource]=useState<NativeFileReading|null>(entry?.source??null),[candidate,setCandidate]=useState<Candidate|null>(entry?.candidate??null);
 const [slot,setSlot]=useState('birthdate-name'),[absence,setAbsence]=useState('Not supplied by me');
 const [day,setDay]=useState<{ref:string;revision:string;id:string;payload:unknown;fields:{id:string;label?:string;template_pointer?:string}[]}|null>(null);
 const [flows,setFlows]=useState<FlowInstanceRow[]>([]),[flowRef,setFlowRef]=useState(''),[returnPreview,setReturnPreview]=useState<ReturnPreview|null>(entry?.preview??null);
 const [centre,setCentre]=useState(0),[oracleSystem,setOracleSystem]=useState('tarot-rws'),[tradition,setTradition]=useState(''),[deck,setDeck]=useState(''),[draws,setDraws]=useState(1),[packet,setPacket]=useState('');
 const [confirmed,setConfirmed]=useState(false),[perspective,setPerspective]=useState('gebser'),[coordinate,setCoordinate]=useState('M4.4.0'),[model,setModel]=useState('');
 const [office,setOffice]=useState('integration-lab'),[retention,setRetention]=useState('');
 const [focusRef,setFocusRef]=useState(''),[efwa,setEfwa]=useState(['','','','']);
 const [,refresh]=useState(0);const mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 useEffect(()=>()=>{const previous=held.get(binding.id);if(previous?.host)void endIdentity(previous.host).catch(()=>{});},[binding.id]);
 useEffect(()=>runtime?.subscribe(()=>refresh(v=>v+1)),[runtime]);
 const incompatible=!!(record&&runtime&&(record.target.nara_ref!==runtime.binding.context.nara_ref||record.target.subject_ref!==runtime.binding.context.subject_ref));
 const run=async(work:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{await work();}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Personal operation failed');}finally{if(mounted.current){setBusy(false);if(entry)setRecord(entry.controller.snapshot.record);}}};
 const open=async(location:CentralLocation,_kind='file',_title='Source')=>{
  await readFile(transport.current,location);
  // Use the existing shell's exact native file-opening path. Dispatch is a
  // navigation request; its own UI shows returned errors. No success invented.
  window.dispatchEvent(new CustomEvent('oi:techne-open-file',{detail:{location}}));
 };
 const openDay=()=>run(async()=>{
  const reply=await kernel.dayOpen();if(reply?.result!=='source_opened')throw new Error('Central did not return the current Day; no replacement was created');
  const buffer=reply.buffer,document=object(JSON.parse(buffer.content),'Current Day document');
  if(document.schema!=='central.contribution-document/v1'||document.kind!=='day'||!document.template_payload||!Array.isArray(document.fields))throw new Error('The current Day does not supply the mapped native 4+2 document payload; open it through Today for its actual source form');
  setDay({ref:buffer.source_ref,revision:buffer.base_revision,id:text(document.document_id),payload:document.template_payload,fields:document.fields as {id:string;label?:string;template_pointer?:string}[]});
 });
 const chooseSource=(reading:NativeFileReading)=>{if(entry){entry.source=reading;entry.candidate=null;}setSource(reading);setCandidate(null);setNotice('Selected for review only. No identity or dialogue changed.');};
 const enable=()=>run(async()=>{
  if(!consent)throw new Error('Choose whether to open your private personal records first');
  const area=await userFlowsArea(transport.current),call=personalCall(()=>transport.current,binding.project);
  const reply=readEnvelope(await call({operation:'capabilities'}));
  if(!Array.isArray(reply.identity_slots)||!Array.isArray(reply.operations)||reply.public_export!==false||reply.centres_are_cymatic_stations!==false)throw new Error('Unsupported native personal capability reading');
  const c={actor_ref:area.baseRef,actor_kind:'human' as const,personal_data:true as const};
  const listing=readEnvelope(await call({operation:'list',consent:c}));
  const result=rows(listing.records).map(r=>({target:targetOf(r.target),event_ref:text(r.event_ref)})).filter(r=>!runtime||(r.target.nara_ref===runtime.binding.context.nara_ref&&r.target.subject_ref===runtime.binding.context.subject_ref));
  const next:HeldPersonal={caps:reply as unknown as PersonalCapabilities,host:"",controller:new PersonalController(call,c),read:call,source,candidate:null,preview:null};
  held.set(binding.id,next);setEntry(next);setCaps(reply as unknown as PersonalCapabilities);setTargets(result);setChosen('');setRecord(null);
 });
 const load=()=>run(async()=>{if(!entry)throw new Error('Open the personal field first');const target=targets.find(r=>r.target.record_ref===chosen)?.target;if(!target)throw new Error('Choose the existing personal occasion');await entry.controller.read(target);setRecord(entry.controller.snapshot.record);setCandidate(null);entry.candidate=null;});
 const propose=(label:string,mutation:Record<string,unknown>)=>{if(!entry||!record||incompatible)throw new Error('Select the matching native personal record');if(!caps?.operations.includes(String(mutation.kind)))throw new Error('This native operation is not available');if(entry.controller.snapshot.pending)throw new Error('Recover the original pending operation first');const next={label,mutation,revision:record.revision,source};entry.candidate=next;setCandidate(next);};
 const requireSource=()=>{if(!source)throw new Error('Choose one saved Central source first');return source;};
 const apply=()=>run(async()=>{if(!entry||!record||!candidate)throw new Error('No reviewed proposal');if(record.revision!==candidate.revision||incompatible)throw new Error('Personal basis changed; review again');if(candidate.source){const current=await readFile(transport.current,candidate.source.location);if(current.revision!==candidate.source.revision)throw new Error('The selected source changed; reselect it before applying');}await entry.controller.apply(candidate.mutation);entry.candidate=null;setCandidate(null);setNotice('The native owner confirmed the personal change. Central source was not rewritten.');});
 const openForm=(kind:string)=>run(async()=>{const chosenForm=DOCUMENT_FORMS.find(f=>f.kind===kind);if(!chosenForm)throw new Error('The original document is not registered');const location=await resolveDocumentForm(transport.current,chosenForm,kernel.snapshot.navigator?.root?.work.projects);await open(location,'file',chosenForm.label);});
 const create=()=>run(async()=>{
  if(!entry||!runtime||record)throw new Error('Attach the existing Nara encounter before continuing a new personal occasion');
  const native=focusedInstrumentSource(focusRef);if(!native)throw new Error('Select a current native focused instrument');
  const view=await native.read();const personal=object(view.focus.payload);
  if(!view.available||view.focus.focus!=='m4'||!view.focus.current||!view.personal_current||personal.schema!=='ql.nara-personal-field/v1'||personal.subject_id!==runtime.binding.context.subject_ref)throw new Error('The selected instrument has no matching current M4 reception; no replacement was generated');
  const e=efwa.map(v=>v.trim()?Number(v):NaN);if(e.some(v=>!Number.isFinite(v)))throw new Error('Supply the four explicit elemental values from the chosen source; absent values cannot be guessed');
  const selected=requireSource();const current=await readFile(transport.current,selected.location);if(current.revision!==selected.revision)throw new Error('Elemental source changed');
  await entry.controller.create({nara_ref:runtime.binding.context.nara_ref,personal,embodied:{elemental_efwa:{earth:e[0],fire:e[1],water:e[2],air:e[3]},elemental_source:sourceBasis(selected),elemental_standing:'reported',nadi_refs:[],sushumna_ref:null,temporal_astrology_refs:[],materia_refs:[],operation_refs:[],safety_intensity:null,contraindication_refs:[],response_refs:[],adjustment_refs:[]}});setRecord(entry.controller.snapshot.record);
 });
 const listFlows=()=>run(async()=>setFlows(await listFlowInstances(transport.current)));
 const previewReturn=(index:number)=>run(async()=>{if(!entry||!runtime)throw new Error('No actual native dialogue is attached');const row=runtime.getSnapshot().rows[index],flow=flows.find(f=>f.location.ref===flowRef);if(!row||!row.complete||!row.delivery_ref||row.role==='person'||!flow)throw new Error('Choose a complete native response and an existing Flow');const a=runtime.binding;const preview=await previewDialogueReturn(await readFlowInstance(transport.current,flow.location),{delivery_ref:row.delivery_ref,agent_session_ref:row.role==='epii'?a.epii!.agent_session:a.dialogue.agent_session,actor_ref:row.role==='epii'?a.epii!.agent_ref:a.constitution.agent_ref,role:row.role,subject_ref:a.context.subject_ref,text:row.text,complete:row.complete});entry.preview=preview;setReturnPreview(preview);});
 const returnToFlow=()=>run(async()=>{if(!entry||!returnPreview)throw new Error('Review a Flow return first');await acceptDialogueReturn(returnPreview,{read:location=>readFlowInstance(transport.current,location),write:(location,revision,html)=>writeFlowInstance(transport.current,location,revision,html)});entry.preview=null;setReturnPreview(null);setNotice('Attributed response saved in the existing Flow. Your entries, journal, notes and media were preserved.');});
 const identity=record?.domain.identity,centres=rows(record?.domain.embodied.centres),oracles=rows(record?.domain.oracle.records),phases=rows(record?.domain.transformation.phase_history&&object(record.domain.transformation.phase_history).phases),lastPhase=phases[phases.length-1];
 return <section className="nara-personal" aria-label="Personal field" data-private="true">
 <p className="nara-personal-intro">Your writing remains in Central. Nara’s personal field links your chosen sources, current reception and deliberate practice without defining you from a profile.</p>
 <OwnWords id={binding.id} transport={kernel.transport} onSaved={chooseSource}/>
 <SourcePicker transport={kernel.transport} onChoose={chooseSource} onOpen={location=>open(location)}/>
 <div className="nara-personal-actions"><button disabled={busy} onClick={openDay}>Open my current Day</button><button disabled={busy} onClick={()=>openForm('document-42')}>Open original Day form</button><button disabled={busy} onClick={()=>openForm('document-01')}>Open original Flow / Journal form</button><button disabled={busy} onClick={listFlows}>Browse my existing Flows</button></div>
 {day&&<section className="nara-personal-day" aria-label="Current native Day"><button onClick={()=>setDay(null)}>Close Day view</button><DayDieFace payload={(()=>{const buffer=kernel.snapshot.buffers[day.ref];if(buffer){try{return object(JSON.parse(buffer.content)).template_payload??day.payload;}catch{return day.payload;}}return day.payload;})()} revision={kernel.snapshot.buffers[day.ref]?.base_revision??day.revision} sourceRef={day.ref} documentId={day.id} fields={day.fields} project={null}/></section>}
 {flows.length>0&&<><label>Existing Flow<select aria-label="Existing Flow" value={flowRef} onChange={e=>{setFlowRef(e.target.value);setReturnPreview(null);if(entry)entry.preview=null;}}><option value="">Choose a Flow</option>{flows.map(f=><option key={f.location.ref} value={f.location.ref}>{f.name}</option>)}</select></label><button disabled={busy||!flowRef} onClick={()=>void run(async()=>{const f=flows.find(f=>f.location.ref===flowRef)!;await open(f.location,'file',f.name);})}>Open its existing HTML and Journal</button></>}
 {!entry?<><label><input type="checkbox" aria-label="Open private personal records" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Allow this view to read my private native personal records.</label><button type="button" disabled={busy||!consent} onClick={enable}>Open my personal field</button><p>No microphone, model, identity assessment or public sharing is started.</p></>:<>
 {!record&&<><label>Existing personal occasion<select aria-label="Personal occasion" value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">Choose an occasion</option>{targets.map(t=><option key={t.target.record_ref} value={t.target.record_ref}>{t.event_ref}</option>)}</select></label><button disabled={busy||!chosen} onClick={load}>Continue this occasion</button>{!targets.length&&<p>No matching personal occasion was returned. Your Central sources remain available below; no demo person has been created.</p>}
 {runtime&&<details><summary>Continue a new occasion from a real M4 reception</summary><p>This uses the current native seven-centre reception. Identity layers may stay unprovided. The explicit elemental reading is reported from your selected source, not inferred.</p><select aria-label="M4 reception source" value={focusRef} onChange={e=>setFocusRef(e.target.value)}><option value="">Choose native instrument</option>{focusedInstrumentSources().map(s=><option key={s.ref} value={s.ref}>{s.title}</option>)}</select><div className="nara-personal-fields">{['Earth','Fire','Water','Air'].map((name,i)=><label key={name}>{name}<input type="number" aria-label={`Reported ${name}`} value={efwa[i]} onChange={e=>setEfwa(values=>values.map((v,j)=>j===i?e.target.value:v))}/></label>)}</div><button disabled={busy||!source||!focusRef} onClick={create}>Create this source-bound occasion</button></details>}</>}

 {source&&<p role="status">Selected: <strong>{source.location.path}</strong> · revision {source.revision}. <button onClick={()=>{setSource(null);if(entry){entry.source=null;entry.candidate=null;}setCandidate(null);}}>Clear selection</button></p>}
 {incompatible&&<p role="alert">The current dialogue belongs to another Nara or personal subject. This personal field is not transferred to it.</p>}
 {record&&<><nav className="nara-personal-tabs" aria-label="Personal work">{sections.map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 <fieldset disabled={busy||incompatible||!!entry.controller.snapshot.pending}>
 {tab==='identity'&&<><h4>Identity in your own terms</h4><p>Use what you have; leave any layer unprovided. Source writing, an assessment, an interpretation and an accepted synthesis are different things.</p><label>Identity layer<select aria-label="Identity layer" value={slot} onChange={e=>setSlot(e.target.value)}>{(caps?.identity_slots??identity?.slots.map(s=>s.kind)??[]).map(k=><option key={k} value={k}>{labels[k]??k}</option>)}</select></label><p>{hints[slot]}</p>
 <p>Current: {identity?.slots.find(s=>s.kind===slot)?.protected_value_ref?.ref_id??identity?.slots.find(s=>s.kind===slot)?.absence_reason??'Unprovided'}.</p><button disabled={!source} onClick={()=>void run(async()=>propose('Link selected source to '+(labels[slot]??slot),identitySource(slot,requireSource())))}>Review this source for the layer</button><label>Reason to leave unprovided<input value={absence} onChange={e=>setAbsence(e.target.value)}/></label><button onClick={()=>void run(async()=>propose('Leave this layer unprovided',identitySource(slot,null,absence)))}>Review unprovided state</button>
 <IdentityMaterialPanel record={record} controller={entry.controller} call={entry.read} available={!!caps?.operations.includes('identity_material')&&caps.operations.includes('identity_seal')} readSource={location=>readFile(transport.current,location)} run={run} onHost={id=>{entry.host=id;}}/></>}
 {tab==='embodied'&&<><h4>Seven receiving centres</h4><p>These are the native personal reception readings—not station frequencies or inferred emotional/medical states.</p><label>Centre<select aria-label="Centre" value={centre} onChange={e=>setCentre(Number(e.target.value))}>{centres.map(c=><option key={Number(c.ordinal)} value={Number(c.ordinal)}>{String(c.label)}</option>)}</select></label><p>{String(centres.find(c=>c.ordinal===centre)?.safety??'No additional safety observation supplied')}</p><button disabled={!source} onClick={()=>void run(async()=>propose('Link selected feedback to this centre',{kind:'centre_feedback',ordinal:centre,feedback_ref:requireSource().location.ref}))}>Review feedback source</button><details><summary>Exact centre and EarthBody readings</summary><pre>{JSON.stringify(record.domain.embodied,null,2)}</pre></details></>}
 {tab==='oracle'&&<><h4>Oracle</h4><p>A cast is an explicit native operation with retained entropy and an immutable original. Interpretations do not rewrite the draw.</p><label>System<select value={oracleSystem} onChange={e=>setOracleSystem(e.target.value)}>{caps?.oracle_systems.map(s=><option key={s}>{s}</option>)}</select></label><label>Tradition source reference<input value={tradition} onChange={e=>setTradition(e.target.value)}/></label><label>Deck / method source reference<input value={deck} onChange={e=>setDeck(e.target.value)}/></label><label>Cards (Tarot only)<input type="number" min="1" max="78" value={draws} onChange={e=>setDraws(Number(e.target.value))}/></label><button disabled={!source||!tradition.trim()||!deck.trim()} onClick={()=>void run(async()=>propose('Perform one native cast using the selected query source',{kind:'oracle_cast',cast:{system:oracleSystem,tradition_ref:tradition,deck_or_method_ref:deck,spread_ref:null,query_ref:protectedSource(requireSource()),draw_count:draws,source_revisions:[sourceBasis(requireSource())],hygiene:'clear'}}))}>Review cast</button>{oracles.length>0&&<><label>Original packet to interpret<select aria-label="Original oracle packet" value={packet} onChange={e=>setPacket(e.target.value)}><option value="">Choose the retained original</option>{oracles.map(o=><option key={String(object(o.original).packet_ref)}>{String(object(o.original).packet_ref)}</option>)}</select></label><label>Interpretation model reference (only when supplied)<input value={model} onChange={e=>setModel(e.target.value)}/></label><button disabled={!source||!packet} onClick={()=>void run(async()=>propose('Record interpretation without changing the original cast',interpretOracle(packet,requireSource(),model)))}>Review interpretation source</button></>}{oracles.map(o=><details key={String(object(o.original).packet_ref)}><summary>Original cast · {String(object(o.original).packet_ref)}</summary><pre>{JSON.stringify(o,null,2)}</pre></details>)}</>}
 {tab==='transformation'&&<><h4>Practice</h4><p>Choose an actual protocol source and deliberately start. No practice, intensity or personal condition is inferred from the identity pattern.</p><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I have reviewed this protocol and choose to begin.</label><button disabled={!source||!confirmed} onClick={()=>void run(async()=>propose('Start the next native practice segment',nextPractice(record,requireSource(),confirmed)))}>Review start</button>{lastPhase&&lastPhase.closed_at_unix_ms==null&&<><p>Current segment {Number(lastPhase.storey)+1} / {Number(lastPhase.decan)+1} / {Number(lastPhase.stroke)+1}: {String(lastPhase.safety)}.</p>{['hold','resume','close'].map(command=><button key={command} disabled={!source} onClick={()=>void run(async()=>{const ref=requireSource().location.ref;propose(command+' the addressed practice',{kind:'practice_'+command,phase_ref:lastPhase.phase_ref,...(command==='hold'?{feedback_ref:ref}:command==='resume'?{safety_review_ref:ref}:{feedback_refs:[ref]})});})}>Review {command}</button>)}</>}<details><summary>Protocol and history</summary><pre>{JSON.stringify(record.domain.transformation,null,2)}</pre></details></>}
 {tab==='context'&&<><h4>Perspectives</h4><p>Retain a source-qualified reading without promoting it to observed truth about the person.</p><label>Perspective<select value={perspective} onChange={e=>{setPerspective(e.target.value);setCoordinate(`M4.4.${caps?.context_branches.indexOf(e.target.value)}`);}}>{caps?.context_branches.map(s=><option key={s}>{s}</option>)}</select></label><label>Exact native coordinate (including deeper branches)<input value={coordinate} onChange={e=>setCoordinate(e.target.value)}/></label><label>Method / model reference, when supplied<input value={model} onChange={e=>setModel(e.target.value)}/></label><button disabled={!source} onClick={()=>void run(async()=>propose('Retain this reported contextual reading',contextSource(perspective,coordinate,requireSource(),model)))}>Review reading</button><details><summary>All native contextual branches</summary><pre>{JSON.stringify(record.domain.context,null,2)}</pre></details></>}
 {tab==='integration'&&<><h4>Returns and writing</h4><p>Your notes and Journal remain in their existing Central files. Link a source, or review an actual Nara/Epii response for addition as an H entry—not as your own writing.</p><button disabled={!source} onClick={()=>void run(async()=>propose('Link the selected Central writing source',{kind:'journal_link',source:protectedSource(requireSource())}))}>Review writing-source link</button><label>Integration office<select value={office} onChange={e=>setOffice(e.target.value)}>{caps?.integration_offices.map(s=><option key={s}>{s}</option>)}</select></label><label>Selected retention policy reference<input value={retention} onChange={e=>setRetention(e.target.value)}/></label><button disabled={!source||!retention.trim()} onClick={()=>void run(async()=>propose('Retain a source-qualified integration Return',{kind:'integration_return',returned:{return_ref:`nara-return/${crypto.randomUUID()}`,office,input_refs:[record.target.record_ref],source_refs:[requireSource().location.ref],method_ref:null,output_ref:protectedSource(requireSource()),evidence_refs:[],human_response_ref:null,retention_policy_ref:retention,standing:'reported'}}))}>Review source Return</button>
 {runtime?.getSnapshot().rows.map((row,i)=>row.role!=='person'&&row.complete&&row.delivery_ref?<article key={row.delivery_ref}><p>{row.role==='nara'?'Nara':'Epii'}: {row.text.slice(0,200)}{row.text.length>200?'…':''}</p><button disabled={!flowRef} onClick={()=>previewReturn(i)}>Review response in selected Flow</button></article>:null)}
 <details><summary>Native source links and integration</summary><pre>{JSON.stringify({journal_refs:record.journal_refs,integration:record.domain.integration},null,2)}</pre></details></>}
 </fieldset>
 {candidate&&<section className="nara-personal-review" aria-label="Review personal change"><h4>{candidate.label}</h4><p>Based on personal revision {candidate.revision}{candidate.source?` and ${candidate.source.location.path} @ ${candidate.source.revision}`:''}. This changes QL’s personal working record, not your source writing or dialogue.</p><details><summary>Exact proposed operation</summary><pre>{JSON.stringify(candidate.mutation,null,2)}</pre></details><button disabled={busy||incompatible||!!entry.controller.snapshot.pending} onClick={apply}>Apply this reviewed change</button><button disabled={busy||!!entry.controller.snapshot.pending} onClick={()=>{entry.candidate=null;setCandidate(null);}}>Reject without mutation</button></section>}
 {returnPreview&&<section className="nara-personal-review" aria-label="Review Flow return"><h4>Add an attributed response to this existing Flow</h4><p>{returnPreview.location.path} @ {returnPreview.expected_revision}. Only a new H entry is added; no Journal, media or human entry is replaced.</p><pre>{returnPreview.entry.html}</pre><button disabled={busy} onClick={returnToFlow}>Save reviewed response to Flow</button><button disabled={busy} onClick={()=>{entry.preview=null;setReturnPreview(null);}}>Keep it out of my writing</button></section>}
 <details><summary>Personal provenance</summary><p>{record.target.subject_ref} · {record.target.nara_ref} · native revision {record.revision}</p><pre>{JSON.stringify(record.receipts,null,2)}</pre></details></>}
 {entry.controller.snapshot.pending&&<p role="alert">This native operation has no confirmed outcome. <button disabled={busy} onClick={()=>void run(async()=>{await entry.controller.recover();entry.candidate=null;setCandidate(null);setNotice('Recovered the original native operation by its unchanged idempotency key.');})}>Recover the same operation</button></p>}
 <button disabled={busy||!!entry.controller.snapshot.pending} onClick={()=>{void endIdentity(entry.host).catch(()=>{});held.delete(binding.id);setEntry(undefined);setRecord(null);setTargets([]);setSource(null);setCandidate(null);setReturnPreview(null);setConsent(false);}}>Close private personal view</button>
 </>}
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 </section>;
}
