import assert from 'node:assert/strict'; import test from 'node:test';
import {EXPRESSION_PRESENTATION_RENDERER, resolveExpressionPresentation, validateExpressionPresentation} from './expression-presentation.mjs';
const reading = (ref, availability='available') => ({ref, revision:'r1', availability});
function binding(overrides={}) { return {binding_ref:'binding:being-expression', component_ref:EXPRESSION_PRESENTATION_RENDERER, portable_renderer:EXPRESSION_PRESENTATION_RENDERER, subject_ref:'central:being:ada', props:{expression:{schema:'oi.expression-presentation/v1', expression_ref:'expression:ada', expression_revision:7, scene_ref:'expression:ada:scene:welcome', live_renderer_ref:'renderer:oi:expression-stage', live_availability:'available', subjects:[{...reading('central:being:ada'),sources:[]}], representations:[], ...overrides}}}; }
test('admits accepted live renderer and preserves identities',()=>{const result=resolveExpressionPresentation(binding(),{renderer_ref:'renderer:oi:expression-stage',available:true,focus:true,capture:true}); assert.equal(result.state,'live'); assert.equal(result.expression.expression_ref,'expression:ada'); assert.equal(result.expression.subjects[0].ref,'central:being:ada'); assert.equal(result.focus_available,true); assert.equal(result.capture_available,true);});
test('chooses first renderable authored capture when live admission is absent',()=>{const blank={kind:'image',representation:reading('capture:blank'),provenance:[reading('expression:ada')]},capture={kind:'image',representation:reading('capture:expression:ada:7'),provenance:[reading('expression:ada')],href:'./capture.png'}; const result=resolveExpressionPresentation(binding({representations:[blank,capture]}),{}); assert.equal(result.state,'fallback'); assert.equal(result.fallback.representation.ref,'capture:expression:ada:7'); assert.equal(result.expression.expression_revision,7);});
test('stale or withheld subjects and sources cannot be live truth',()=>{for(const availability of ['stale','withheld']){for(const subjects of [[{...reading('central:being:ada',availability),sources:[]}],[{...reading('central:being:ada'),sources:[reading('source:ada',availability)]}]]){const result=resolveExpressionPresentation(binding({subjects}),{renderer_ref:'renderer:oi:expression-stage',available:true}); assert.deepEqual({state:result.state,reason:result.reason},{state:'unavailable',reason:'subject_unavailable'});}}});
test('rejects identity drift and unsupported fallbacks',()=>{assert.throws(()=>resolveExpressionPresentation({...binding(),subject_ref:'central:being:other'},{}),/must be present/); assert.throws(()=>validateExpressionPresentation(binding({representations:[{kind:'embed',representation:reading('bad')}]}).props.expression),/image, video, or html/);});
test('rejects private runtime state, duplicate subjects and malformed provenance',()=>{assert.throws(()=>validateExpressionPresentation(binding({particle_buffer:[1,2,3]}).props.expression),/unsupported keys: particle_buffer/); assert.throws(()=>validateExpressionPresentation(binding({subjects:[{...reading('central:being:ada'),sources:[],session_state:{secret:true}}]}).props.expression),/unsupported keys: session_state/);assert.throws(()=>validateExpressionPresentation(binding({subjects:[{...reading('central:being:ada'),sources:[]},{...reading('central:being:ada'),sources:[]}]}).props.expression),/duplicate refs/);assert.throws(()=>validateExpressionPresentation(binding({representations:[{kind:'image',representation:reading('capture:x'),provenance:null,href:'x.png'}]}).props.expression),/provenance must/);});
