"""Checks only the supplied standalone control specimen, not the Cradle app."""
import json, os, shutil
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def check(name, condition):
    if not condition: raise AssertionError(name)
    checks.append({'check':name,'status':'passed'})
with sync_playwright() as p:
    executable=os.environ.get('SPECIMEN_BROWSER')
    if not executable and not Path(p.chromium.executable_path).exists():
        executable=shutil.which('chromium') or shutil.which('google-chrome')
    browser=p.chromium.launch(headless=True,executable_path=executable,args=['--no-sandbox'])
    page=browser.new_page(viewport={'width':1200,'height':1000},device_scale_factor=1)
    errors=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    # Render our generated, self-contained bytes; no external or private URL is read.
    page.set_content((ROOT/'control-specimen.html').read_text(), wait_until='load')
    check('explicit TEST SPECIMEN notice', 'TEST SPECIMEN' in page.locator('header.page').inner_text().upper())
    check('one creation trigger',page.get_by_role('button',name='Create agent or team',exact=True).count()==1)
    check('no standing New agent / New team buttons',not page.get_by_role('menu',name='Create',exact=True).is_visible())
    page.get_by_role('button',name='Create agent or team',exact=True).focus()
    page.keyboard.press('Enter')
    check('menu opens and focuses first item',page.evaluate("document.activeElement.textContent").strip()=='New agent…')
    page.screenshot(path=str(ROOT/'review/control-menu.png'),full_page=True)
    page.keyboard.press('ArrowDown')
    check('arrow moves to team',page.evaluate("document.activeElement.textContent").strip()=='New team…')
    page.keyboard.press('Escape')
    check('Escape restores plus',page.evaluate("document.activeElement.id")=='addBtn')
    page.keyboard.press('Enter');page.keyboard.press('Enter')
    check('new agent focuses intent',page.evaluate("document.activeElement.id")=='purpose')
    page.locator('#purpose').fill('Preserve the existing Context insert.')
    page.locator('#name').fill('Example draft')
    page.get_by_role('button',name='Review proposal',exact=True).click()
    check('specimen does not fake native creation','no native proposal is sent' in page.locator('#proposalResponse').inner_text())
    page.keyboard.press('Escape');page.wait_for_timeout(40)
    check('Escape from form restores trigger',page.evaluate("document.activeElement.id")=='addBtn')
    page.keyboard.press('Enter');page.keyboard.press('Enter')
    check('creation draft retained on reopen',page.locator('#purpose').input_value()=='Preserve the existing Context insert.')
    page.keyboard.press('Escape');page.wait_for_timeout(40)
    page.locator('[data-profile="Example engineer"]').click()
    check('card body opens detail without message action',page.locator('#drawerTitle').inner_text()=='Example engineer' and page.locator('#paneStatus').is_hidden())
    page.get_by_role('tab',name='Skills',exact=True).focus();page.keyboard.press('ArrowRight')
    check('drawer arrow selects Setup',page.get_by_role('tab',name='Setup',exact=True).get_attribute('aria-selected')=='true')
    page.screenshot(path=str(ROOT/'review/control-drawer.png'),full_page=True)
    page.keyboard.press('Escape');page.wait_for_timeout(40)
    check('drawer Escape restores original row',page.evaluate("document.activeElement.getAttribute('data-profile')")=='Example engineer')
    page.locator('#draft').fill('Retain this thought.')
    page.locator('#workmark summary').click();page.locator('#openActivity').click()
    check('workmark opens exact example event',page.locator('#tape').is_visible() and page.locator('#tape .event').count()==1)
    page.keyboard.press('Escape')
    check('activity Escape restores its invoker',page.evaluate("document.activeElement.id")=='openActivity')
    check('draft preserved during inspection',page.locator('#draft').input_value()=='Retain this thought.')
    page.locator('#searchBtn').click();page.locator('#search').fill('researcher');page.keyboard.press('Escape')
    check('Escape does not clear roster search',page.locator('#search').input_value()=='researcher')
    page.locator('#search').fill('');page.keyboard.press('Escape')
    check('empty search Escape returns to magnifier',page.evaluate("document.activeElement.id")=='searchBtn')
    check('no nested buttons',page.locator('button button').count()==0)
    check('zero deltas is one line with no controls',page.locator('.setting-study').inner_text().strip()=='No capability changes.' and page.locator('.setting-study button, .setting-study table').count()==0)
    page.set_viewport_size({'width':390,'height':844});page.locator('#addBtn').click()
    rect=page.locator('#createMenu').bounding_box()
    check('narrow menu stays in viewport',rect['x']>=8 and rect['x']+rect['width']<=382)
    check('narrow page has no horizontal overflow',page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'))
    page.screenshot(path=str(ROOT/'review/control-narrow.png'),full_page=True)
    page.keyboard.press('Escape')
    page.emulate_media(reduced_motion='reduce')
    page.locator('#addBtn').click();page.keyboard.press('Escape')
    check('reduced motion preserves menu interaction',page.evaluate("document.activeElement.id")=='addBtn')
    check('no browser exceptions',len(errors)==0)
    browser.close()
report={'kind':'standalone-control-specimen-only','checks':checks,'passed':len(checks),'browser_errors':errors,'browser_executable':executable or p.chromium.executable_path,'cradle_application_tests_run':False}
(ROOT/'review/specimen-validation.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps(report,indent=2))
