/** Native owner health and operations, adapted from Cradle ProductSection. */
import { useEffect, useRef, useState } from 'react'
import type { SettingsAdapter } from './adapter'
import type { DisclosedAction, SystemCompositionReading } from '../../../../../desktop/cradle/src/workspace/settings/types'
export function runnableProductAction(action:DisclosedAction):boolean {
  const path=(action as DisclosedAction&{native_path?:unknown}).native_path
  return action.availability==='disclosed'&&action.exposure?.ui!==false&&!action.args?.length&&typeof path==='string'&&!!path&&!/[<[]/.test(path)
}
export function ProductPreferences({adapter}:{adapter:SettingsAdapter}) {
  const [reading,setReading]=useState<SystemCompositionReading|null>(null),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[result,setResult]=useState<{product:string;action:string;ok:boolean;output:unknown;at:number}|null>(null)
  const generation=useRef(0),current=useRef(adapter);current.current=adapter
  const refresh=async()=>{if(!adapter.readProducts)return;const epoch=generation.current,source=adapter;setBusy('reading');setError(null);try{const answer=await source.readProducts!();if(epoch===generation.current&&source===current.current)setReading(answer)}catch(cause){if(epoch===generation.current)setError(cause instanceof Error?cause.message:String(cause))}finally{if(epoch===generation.current)setBusy(null)}}
  useEffect(()=>{++generation.current;setReading(null);setResult(null);if(adapter.readProducts)void refresh();return()=>{++generation.current}},[adapter,adapter.ownerEpoch])
  const run=async(product:string,action:DisclosedAction)=>{const invoke=adapter.invoke;if(!invoke||!runnableProductAction(action))return;const source=adapter,epoch=generation.current;setBusy(action.action_ref);setError(null);setResult(null);try{const answer=await invoke({op:'product_action_run',product_id:product,action_ref:action.action_ref});if(epoch!==generation.current||source!==current.current)return;if(answer.error||answer.outcome?.result!=='product_action_ran')throw new Error(answer.error??'The native owner did not acknowledge this operation.');const data=answer.outcome.data as {ok?:unknown;output?:unknown;ran_at_unix_ms?:unknown};if(typeof data?.ok!=='boolean'||typeof data.ran_at_unix_ms!=='number')throw new Error('The owner returned no qualified operation result.');setResult({product,action:action.action_ref,ok:data.ok,output:data.output,at:data.ran_at_unix_ms});if(source.readProducts){const refreshed=await source.readProducts();if(epoch===generation.current&&source===current.current)setReading(refreshed)}}catch(cause){if(epoch===generation.current)setError(cause instanceof Error?cause.message:String(cause))}finally{if(epoch===generation.current)setBusy(null)}}
  return <section className="owner-preferences" aria-label="Installed products and operations" tabIndex={-1}><h3 className="preference-group-title">Installed products</h3><p className="owner-note">Manage installed products and their available maintenance actions.</p>{!adapter.readProducts&&<p className="owner-note">Installed products are awaiting the application connection. No installation or update has been performed here.</p>}{reading?.owners.map(mount=><section className="preference-group" key={mount.product_id}><h3 className="preference-group-title">{mount.product_id}{mount.descriptor?.owner.owner_version?` · ${mount.descriptor.owner.owner_version}`:''}</h3><p className="owner-note">{mount.descriptor?.availability.state??mount.availability}{mount.reason?` · ${mount.reason}`:''}</p>{mount.descriptor?.about&&<p className="owner-note">{mount.descriptor.about}</p>}<div className="owner-actions">{mount.descriptor?.actions.filter(action=>action.exposure?.ui!==false).map(action=>runnableProductAction(action)?<button type="button" key={action.action_ref} disabled={!!busy||!adapter.invoke||mount.availability==='unavailable'} title={action.title} onClick={()=>void run(mount.product_id,action)}>{busy===action.action_ref?'Running…':action.title}</button>:<p className="owner-note" key={action.action_ref}>{action.title} · {action.availability==='disclosed'?'Choose its subject at the point of use.':action.unavailable_reason??'No native operation available.'}</p>)}</div><details className="preference-inspection"><summary>Health, provenance and known gaps</summary><p>Observed {new Date(mount.provenance.observed_at_unix_ms).toLocaleString()} · {mount.provenance.digest??'No digest reported'}</p>{mount.error&&<p>{mount.error}</p>}{mount.descriptor?.degradations?.map((value,i)=><p key={i}>{value.subject_ref} · {value.state} · {value.reason}</p>)}{mount.descriptor?.obligations?.map((value,i)=><p key={i}>{value}</p>)}</details></section>)}{busy==='reading'&&<p role="status">Reading installed products…</p>}{error&&<div className="settings-alert" role="alert">{error}<button type="button" disabled={!!busy} onClick={()=>void refresh()}>Read products again</button></div>}{result&&<div className={result.ok?'settings-notice':'settings-alert'} role="status">{result.action}: {result.ok?'the native owner reports success':'the native owner reports a problem'} · {new Date(result.at).toLocaleTimeString()}<details className="preference-inspection"><summary>Owner operation result</summary><pre>{JSON.stringify(result.output,null,2)}</pre></details></div>}</section>
}
