/** Adapted from Cradle ProfilesSection: sparse O:I profiles are distinct from
 * the AIKit profile setting. Use stages LOCAL drafts into the ordinary review. */
import { useEffect, useRef, useState } from 'react'
import type { ChangeRequest, SettingsAdapter } from './adapter'
import type { ProfileDocument } from '../../../../../desktop/cradle/src/configuration/contracts'
import { displayValue } from './model'

export function ProfilePreferences({adapter,drafts,onStage,isSensitive=()=>true}:{adapter:SettingsAdapter;drafts:ChangeRequest[];onStage:(requests:ChangeRequest[])=>Promise<void>;isSensitive?:(setting_ref:string)=>boolean}) {
  const [reading,setReading]=useState<{active_profile_ref:string|null;profiles:ProfileDocument[]}|null>(null)
  const [busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[note,setNote]=useState<string|null>(null)
  const [name,setName]=useState(''),[naming,setNaming]=useState(false)
  const file=useRef<HTMLInputElement>(null),generation=useRef(0),current=useRef(adapter);current.current=adapter
  const refresh=async()=>{if(!adapter.profiles)return;const epoch=generation.current,source=adapter;setBusy(true);setError(null);try{const value=await source.profiles!.listProfiles();if(epoch===generation.current&&source===current.current)setReading(value)}catch(cause){if(epoch===generation.current)setError(cause instanceof Error?cause.message:String(cause))}finally{if(epoch===generation.current)setBusy(false)}}
  useEffect(()=>{++generation.current;setReading(null);if(adapter.profiles)void refresh();return()=>{++generation.current}},[adapter,adapter.ownerEpoch])
  const run=async(work:(source:SettingsAdapter)=>Promise<string>)=>{const epoch=generation.current,source=adapter;setBusy(true);setError(null);setNote(null);try{const message=await work(source);if(epoch!==generation.current||source!==current.current)return;setNote(message);const refreshed=await source.profiles!.listProfiles();if(epoch===generation.current&&source===current.current)setReading(refreshed)}catch(cause){if(epoch===generation.current)setError(cause instanceof Error?cause.message:String(cause))}finally{if(epoch===generation.current)setBusy(false)}}
  const stage=(profile:ProfileDocument)=>void run(async source=>{const plan=await source.profiles!.profileUsePlan(profile.profile_ref);if(source!==current.current)throw new Error('The profile owner changed.');const requests=plan.entries.flatMap(entry=>entry.target?[{setting_ref:entry.setting_ref,scope:entry.scope,value:entry.target.value,secret_reference:entry.target.secret_reference??null}]:[]);await onStage(requests);return `Staged ${requests.length} local ${requests.length===1?'draft':'drafts'} from ${profile.title??profile.profile_ref}. Review the changes before applying.`})
  const save=()=>void run(async source=>{const title=name.trim(),ref=title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,48);if(!ref)throw new Error('Give the profile a name.');const created=await source.profiles!.createProfile(ref,title);try{if(drafts.length)await source.profiles!.saveProfile({...created,desired:drafts})}catch{throw new Error(`The owner created “${title}”, but did not acknowledge saving its draft entries. Read the profile before retrying.`)}setNaming(false);setName('');return `Profile saved by the native owner with ${drafts.length} valid draft entries. No settings were applied.`})
  const importFile=(picked:File)=>void run(async source=>{if(picked.size>1024*1024)throw new Error('Profile files must be under 1 MiB.');const value=JSON.parse(await picked.text()) as Partial<ProfileDocument>;if(value.schema!=='oi.profile/v1'||typeof value.profile_ref!=='string'||!value.profile_ref.trim()||!Array.isArray(value.desired))throw new Error('This file is not an O:I profile.');const created=await source.profiles!.createProfile(value.profile_ref,value.title??undefined);try{await source.profiles!.saveProfile({...created,title:value.title??created.title,description:value.description??created.description,desired:value.desired})}catch{throw new Error('The native owner created the profile but did not acknowledge its imported entries. Nothing was applied.')}return 'Profile import acknowledged by the native owner. Use it to stage changes for review.'})
  return <section className="owner-preferences" aria-label="Named settings profiles"><h3 className="preference-group-title">Named settings profiles</h3><p className="owner-note">A named sparse set of O:I settings. The AIKit profile selection below decides which agent composition to use; these saved sets stage ordinary settings drafts.</p>{!adapter.profiles&&<p className="owner-note">Saved profiles have not been read. Connect the retained O:I profile adapter.</p>}{reading?.profiles.map(profile=><div className="preference-row" key={profile.profile_ref}><div className="preference-label"><h3>{profile.title??profile.profile_ref}</h3><span className="preference-origin">{reading.active_profile_ref===profile.profile_ref?'Native active profile · ':''}{profile.desired.length} settings</span><details className="preference-inspection"><summary>Settings in this profile</summary>{profile.desired.map((entry,i)=><p key={i}>{entry.setting_ref} · {entry.scope.scope_kind}{entry.scope.scope_ref?` · ${entry.scope.scope_ref}`:''} · {entry.secret_reference?'Secret reference only':displayValue(entry.value,isSensitive(entry.setting_ref))}</p>)}</details></div><div className="preference-value"><button type="button" disabled={busy} onClick={()=>stage(profile)}>Use profile…</button></div></div>)}{reading&&!reading.profiles.length&&<p className="owner-note">The owner reports no saved profiles.</p>}{naming?<form className="owner-actions" onSubmit={e=>{e.preventDefault();save()}}><input aria-label="Profile name" value={name} onChange={e=>setName(e.target.value)} autoFocus/><button disabled={busy||!name.trim()} type="submit">Save profile</button><button type="button" disabled={busy} onClick={()=>setNaming(false)}>Cancel</button></form>:<div className="owner-actions"><button type="button" disabled={!adapter.profiles||busy} onClick={()=>setNaming(true)}>New profile from valid drafts…</button><button type="button" disabled={!adapter.profiles||busy} onClick={()=>file.current?.click()}>Import profile…</button><input ref={file} hidden type="file" accept="application/json,.json" aria-label="Import O:I profile" onChange={e=>{const picked=e.target.files?.[0];e.target.value='';if(picked)importFile(picked)}}/></div>}{busy&&<p role="status">Waiting for profile owner…</p>}{error&&<div className="settings-alert" role="alert">{error}<button type="button" disabled={busy} onClick={()=>void refresh()}>Read profiles again</button></div>}{note&&<p role="status" className="owner-note">{note}</p>}</section>
}
