import {useEffect,useState} from "react";
import {kernelOp} from "../kernel/bridge";
import {useKernel} from "../kernel/KernelProvider";
import {openRepositoryDiff} from "./object";
interface Repository {repo_root:string;head_branch?:string;head_sha?:string;worktrees:{path:string;branch?:string;dirty_files?:number;bare?:boolean;prunable?:boolean}[]}
export function RepositoryContext({project}:{project:string}){
 const {transport}=useKernel(),[repo,setRepo]=useState<Repository>(),[path,setPath]=useState(""),[basis,setBasis]=useState(""),[error,setError]=useState<string>(),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let live=true;setRepo(undefined);setError(undefined);void kernelOp(transport,{op:"git_repository_read",project}).then(result=>{if(!live)return;if(result.outcome?.result!=="git_repository_reading"){setError(result.error??"Repository unavailable");return;}const value=result.outcome.document as Repository;if(typeof value.repo_root!=="string"||!Array.isArray(value.worktrees)){setError("Central returned no repository paths");return;}setRepo(value);setPath(value.repo_root);}).catch(error=>{if(live)setError(error instanceof Error?error.message:String(error));});return()=>{live=false};},[project,attempt,transport]);
 const tree=repo?.worktrees.find(t=>t.path===path);
 return <section className="context-repository" aria-label="This repository"><h3>This repository</h3>{error?<p role="status">Couldn’t read git state: {error} <button className="oi-action" onClick={()=>setAttempt(v=>v+1)}>Retry</button></p>:repo?<><p>{tree?.branch??repo.head_branch??"Detached HEAD"}{typeof tree?.dirty_files==="number"?` · ${tree.dirty_files} changed files`:""}</p><label>Checkout<select aria-label="Repository checkout" value={path} onChange={e=>setPath(e.target.value)}>{repo.worktrees.filter(t=>!t.bare&&!t.prunable).map(t=><option key={t.path} value={t.path}>{t.path}</option>)}</select></label><label>Committed basis (optional)<input aria-label="Committed comparison basis" value={basis} onChange={e=>setBasis(e.target.value)} placeholder="Revision or branch" spellCheck={false}/></label><button className="oi-action" disabled={!path} onClick={()=>openRepositoryDiff({repo_root:path,from:basis.trim()||"HEAD",to:"working-tree"},project)}>{basis.trim()?"Open committed and working changes":"Open working changes"}</button></>:<p>Reading git state…</p>}</section>;
}
