import React,{useEffect,useState} from 'react';
import {scoreCounter,type NativeScoreEvent,type NativeScoreOperation,type NativeScorePort,type NativeScoreSnapshot} from './scoreProtocol.js';
const at=(event:NativeScoreEvent)=>event[4] as Record<string,unknown>;
const action=(event:NativeScoreEvent)=>typeof event[4]==='string'?event[4]:Object.keys(event[4])[0];
function kind(event:NativeScoreEvent){return({n:'Note on',o:'Note off',e:'Pressure',p:'Parameter',a:'Automation',s:'Sustain',f:'Force',b:'Body basis',c:'Receiving context',x:'All notes off'} as Record<string,string>)[action(event)]??'Native event';}
/** Edits the retained native Scene score. Callback recording and original
 * source/body/checkpoint receipts remain in their existing native owners. */
export function NativeScoreEditor({owner,report}:{owner:NativeScorePort;report:(error:unknown)=>void}){
 const [state,setState]=useState<NativeScoreSnapshot|null>(()=>owner.snapshot()),[dirty,setDirty]=useState(false),[pending,setPending]=useState(false),[page,setPage]=useState(0);
 const [selected,setSelected]=useState(''),[sample,setSample]=useState('0'),[velocity,setVelocity]=useState(1),[loopFrom,setLoopFrom]=useState('0'),[loopTo,setLoopTo]=useState('48000'),[position,setPosition]=useState('0'),[tempo,setTempo]=useState(120);
 const [target,setTarget]=useState(0),[route,setRoute]=useState(0),[amount,setAmount]=useState(1),[curveStart,setCurveStart]=useState('48000'),[curveEnd,setCurveEnd]=useState('96000'),[curveFrom,setCurveFrom]=useState(0),[curveTo,setCurveTo]=useState(1);
 useEffect(()=>owner.subscribe(()=>setDirty(true)),[owner]);
 const refresh=()=>{const next=owner.snapshot();setState(next);setDirty(false);return next;};
 const submit=async(operations:NativeScoreOperation[])=>{if(pending)return;setPending(true);try{const result=await owner.edit(operations);setState(result);setDirty(false);}catch(error){report(error);refresh();}finally{setPending(false);}};
 const perform=(make:()=>NativeScoreOperation[])=>{try{void submit(make());}catch(error){report(error);}};
 const events=state?.performance.pages.flatMap(p=>p.events)??[],pages=Math.max(1,Math.ceil(events.length/64)),shown=events.slice(Math.min(page,pages-1)*64,Math.min(page,pages-1)*64+64),event=events.find(e=>e[0]===selected),score=state?.performance;
 const choose=(event:NativeScoreEvent)=>{setSelected(event[0]);setSample(event[1]);const n=at(event)?.n;if(Array.isArray(n))setVelocity(Number(n[3]));};
 const edited=():NativeScoreEvent=>{if(!event)throw Error('Select a retained score event.');const replacement=structuredClone(event);replacement[1]=scoreCounter(sample);if(action(event)==='n'){const n=at(replacement).n as unknown[];if(!Number.isFinite(velocity)||velocity<0||velocity>1)throw Error('Velocity must be within 0 to 1.');n[3]=velocity;}return replacement;};
 const removeSelection=():NativeScoreOperation[]=>{
  if(!event)throw Error('Select a retained event to remove.');
  if(!['n','o','e'].includes(action(event)))return[{operation:'remove_event',sequence:scoreCounter(selected)}];
  const operand=at(event).n??at(event).o??at(event).e,touch=String(Array.isArray(operand)?operand[0]:operand);
  const passage=events.filter(e=>{const value=typeof e[4]==='object'?(at(e).n??at(e).o??at(e).e):null;return e[2]===event[2]&&e[3]===event[3]&&String(Array.isArray(value)?value[0]:value)===touch;});
  // Each ordinary native operation validates its full candidate. Remove
  // pressure first, release next and attack last so no orphan release is
  // admitted between operations; original performed receipts stay immutable.
  return [...passage.filter(e=>action(e)==='e'),...passage.filter(e=>action(e)==='o'),...passage.filter(e=>action(e)==='n')].map(e=>({operation:'remove_event',sequence:e[0]}));
 };
 const makeCurve=():NativeScoreOperation[]=>{
  if(!score||!score.routes[route])throw Error('Select an existing native route.');
  const from=scoreCounter(curveStart),to=scoreCounter(curveEnd);if(BigInt(to)<=BigInt(from))throw Error('Automation end must follow its start.');
  if(!Number.isFinite(curveFrom)||!Number.isFinite(curveTo))throw Error('Enter finite automation values.');
  let sequence=events.reduce((n,e)=>BigInt(e[0])>n?BigInt(e[0]):n,0n);const layer=event?.[2]??0,basis=event?.[3]??0;
  return[{operation:'automate',route_index:route,events:[[scoreCounter(String(++sequence)),from,layer,basis,{a:[route,curveFrom,null]}],[scoreCounter(String(++sequence)),to,layer,basis,{a:[route,curveTo,null]}]]}];
 };
 return <details className="performance-score" data-performance-score={score?.performance_ref??''} aria-busy={pending}><summary>Score · {events.length} events · {score?.layers.length??0} layers</summary>
  <div className="performance-actions"><button onClick={refresh} disabled={pending}>Refresh score{dirty?' · changed':''}</button><button data-performance="score-resolve" disabled={pending} onClick={()=>{setPending(true);void owner.resolve().then(value=>{setState(value);setDirty(false);}).catch(report).finally(()=>setPending(false));}}>Resolve interrupted edit</button><span>{state?`Revision ${state.document_revision}`:'No retained score'}</span></div>
  {state?.reason&&!state.playback_current&&<p role="status">{state.reason}</p>}
  {score&&<>
   <div className="performance-score-pages"><button disabled={!page||pending} onClick={()=>setPage(p=>p-1)}>Earlier</button><span>Page {Math.min(page,pages-1)+1} of {pages}</span><button disabled={page>=pages-1||pending} onClick={()=>setPage(p=>p+1)}>Later</button></div>
   <div className="performance-score-events" role="list" aria-label="Recorded native score events">{shown.map(e=><button key={e[0]} role="listitem" data-performance-event={e[0]} aria-pressed={selected===e[0]} onClick={()=>choose(e)}><span>{kind(e)}</span><span>Sample {e[1]} · layer {e[2]+1}</span></button>)}</div>
   <fieldset disabled={pending||!event}><legend>Edit selected event</legend><label>Sample<input aria-label="Event sample" inputMode="numeric" value={sample} onChange={e=>setSample(e.currentTarget.value)}/></label>{event&&action(event)==='n'&&<label>Velocity<input aria-label="Event velocity" type="number" min={0} max={1} step="any" value={velocity} onChange={e=>setVelocity(e.currentTarget.valueAsNumber)}/></label>}<button data-performance="edit-event" onClick={()=>perform(()=>[{operation:'edit_event',sequence:selected,replacement:edited()}])}>Apply event edit</button><button data-performance="remove-event" onClick={()=>perform(removeSelection)}>Remove selected passage</button></fieldset>
   <fieldset disabled={pending}><legend>Layers</legend>{score.layers.map((layer,index)=><div className="performance-score-layer" key={layer.layer_ref}><span>{layer.title}</span><label><input type="checkbox" checked={layer.enabled} onChange={e=>perform(()=>[{operation:'layer_set',index,layer:{...layer,enabled:e.currentTarget.checked}}])}/>Enabled</label><label><input type="checkbox" checked={layer.solo} onChange={e=>perform(()=>[{operation:'layer_set',index,layer:{...layer,solo:e.currentTarget.checked}}])}/>Solo</label></div>)}<button data-performance="layer-copy" disabled={!event} onClick={()=>perform(()=>{
    if(!event)throw Error('Select a recorded passage to layer.');
    const sameTouch=typeof event[4]==='object'&&(at(event).n??at(event).o??at(event).e),touch=Array.isArray(sameTouch)?String(sameTouch[0]):sameTouch===undefined?null:String(sameTouch);
    if(!touch)throw Error('Select a recorded note to layer its complete touch passage.');
    const passage=events.filter(e=>{const value=typeof e[4]==='object'&&(at(e).n??at(e).o??at(e).e);return e[2]===event[2]&&e[3]===event[3]&&String(Array.isArray(value)?value[0]:value)===touch;});
    if(!passage.some(e=>action(e)==='n')||!passage.some(e=>action(e)==='o'))throw Error('Release this recorded note before layering its complete passage.');
    let sequence=events.reduce((n,e)=>BigInt(e[0])>n?BigInt(e[0]):n,0n),token=events.reduce((n,e)=>{const value=typeof e[4]==='object'&&(at(e).n??at(e).o??at(e).e);const candidate=Array.isArray(value)?BigInt(String(value[0])):typeof value==='string'?BigInt(value):0n;return candidate>n?candidate:n;},0n)+1n;
    const member=events.reduce((n,e)=>{const note=typeof e[4]==='object'?at(e).n:null;const candidate=Array.isArray(note)?BigInt(String(note[1])):0n;return candidate>n?candidate:n;},0n)+1n;
    const copy=passage.map(e=>{const next=structuredClone(e);next[0]=scoreCounter(String(++sequence));const value=at(next);if(Array.isArray(value.n)){value.n[0]=scoreCounter(String(token));value.n[1]=scoreCounter(String(member));}else if(Array.isArray(value.e))value.e[0]=scoreCounter(String(token));else if(Object.hasOwn(value,'o'))value.o=scoreCounter(String(token));return next;});
    return[{operation:'overdub',layer:{layer_ref:`${score.performance_ref}/layer:${crypto.randomUUID()}`,title:`Layer ${score.layers.length+1}`,enabled:true,solo:false},events:copy}];
   })}>Layer selected passage</button></fieldset>
   <fieldset disabled={pending}><legend>Route and automate</legend><label>Destination<select aria-label="Automation destination" value={target} onChange={e=>setTarget(Number(e.currentTarget.value))}>{score.parameters.map((p,index)=><option key={p.target_ref} value={index}>{p.target_ref} · {p.unit}</option>)}</select></label><label>Amount<input aria-label="Automation route amount" type="number" step="any" value={amount} onChange={e=>setAmount(e.currentTarget.valueAsNumber)}/></label><button data-performance="route-create" disabled={!score.parameters.length} onClick={()=>perform(()=>{
    const destination=score.parameters[target];if(!destination||destination.scope==='note'||!Number.isFinite(amount))throw Error('Choose a finite instrument/body/context route; note scope requires its exact held touch.');
    return[{operation:'route_set',route:{route_ref:`${score.performance_ref}/route:${crypto.randomUUID()}`,source:{ref:score.performance_ref,revision:score.content_digest,availability:'available'},source_unit:'normalized',destination:structuredClone(destination),transfer:'add',amount,delay_samples:'0',feedback:false,enabled:true}}];
   })}>Route authored automation</button><label>Route<select aria-label="Retained automation route" value={route} onChange={e=>setRoute(Number(e.currentTarget.value))}>{score.routes.map((r,index)=><option key={r.route_ref} value={index}>{r.destination.target_ref}{r.enabled?'':' · disabled'}</option>)}</select></label><button data-performance="route-clear" disabled={!score.routes[route]} onClick={()=>perform(()=>[{operation:'route_clear',route_ref:score.routes[route].route_ref}])}>Disable route</button><div><label>Start sample<input aria-label="Automation start sample" value={curveStart} onChange={e=>setCurveStart(e.currentTarget.value)}/></label><label>Value<input aria-label="Automation start value" type="number" step="any" value={curveFrom} onChange={e=>setCurveFrom(e.currentTarget.valueAsNumber)}/></label><label>End sample<input aria-label="Automation end sample" value={curveEnd} onChange={e=>setCurveEnd(e.currentTarget.value)}/></label><label>Value<input aria-label="Automation end value" type="number" step="any" value={curveTo} onChange={e=>setCurveTo(e.currentTarget.valueAsNumber)}/></label></div><button data-performance="automate" disabled={!score.routes[route]} onClick={()=>perform(makeCurve)}>Add automation points</button></fieldset>
   <fieldset disabled={pending}><legend>Transport and tempo</legend><label>Position sample<input value={position} onChange={e=>setPosition(e.currentTarget.value)}/></label><button data-performance="score-seek" onClick={()=>perform(()=>[{operation:'seek',sample:scoreCounter(position)}])}>Set score position</button><label>Loop from<input value={loopFrom} onChange={e=>setLoopFrom(e.currentTarget.value)}/></label><label>Loop to<input value={loopTo} onChange={e=>setLoopTo(e.currentTarget.value)}/></label><button data-performance="score-loop" onClick={()=>perform(()=>[{operation:'loop',range:{from_sample:scoreCounter(loopFrom),to_sample:scoreCounter(loopTo)}}])}>Set loop</button><button onClick={()=>perform(()=>[{operation:'loop',range:null}])}>Clear loop</button><label>Tempo<input type="number" min={1} max={1000} value={tempo} onChange={e=>setTempo(e.currentTarget.valueAsNumber)}/></label><button data-performance="score-tempo" onClick={()=>perform(()=>{if(!Number.isFinite(tempo)||tempo<1||tempo>1000)throw Error('Tempo must be within 1 to 1000 beats per minute.');return[{operation:'tempo',segments:[{at_sample:'0',at_tick:'0',micros_per_quarter:Math.round(60000000/tempo)}]}];})}>Set tempo</button></fieldset>
  </>}
 </details>;
}
