import React,{useEffect,useState} from 'react';
import type {NativePerformanceClient} from './client.js';
import type {AuthoredFormOperation,AuthoredPhysicalMaterial,AuthoredMetricRecipe,NativePhysicalEditPort} from './physicalEdit.js';
/** Normal authored values. The native current Scene compiles the body, retains
 * both original replies and projects existing motion before play continues. */
export function NativePhysicalControls({owner,client,report}:{owner:NativePhysicalEditPort;client:NativePerformanceClient;report:(error:unknown)=>void}){
 const [snapshot,setSnapshot]=useState(()=>owner.snapshot()),[pending,setPending]=useState(false);
 const [material,setMaterial]=useState<AuthoredPhysicalMaterial|null>(snapshot?.material??null),[recipe,setRecipe]=useState<AuthoredMetricRecipe|null>(snapshot?.recipe??null);
 const [form,setForm]=useState(0),[line,setLine]=useState(1),[matrix,setMatrix]=useState(0),[pose,setPose]=useState(0),[aperture,setAperture]=useState(0),[steps,setSteps]=useState(1),[tick,setTick]=useState(0),[cycle,setCycle]=useState(0);
 const [angles,setAngles]=useState<[number,number,number]>([0,0,0]),[velocities,setVelocities]=useState<[number,number,number]>([0,0,0]);
 useEffect(()=>client.subscribe(()=>{const actual=owner.snapshot();setSnapshot(actual);if(actual&&actual.body_revision!==snapshot?.body_revision){setMaterial(actual.material);setRecipe(actual.recipe);}}),[client,owner,snapshot?.body_revision]);
 const current=!!snapshot?.current&&!pending;
 const apply=async(edit:Parameters<NativePhysicalEditPort['apply']>[0])=>{if(!current)return;setPending(true);try{await owner.apply(edit);const actual=owner.snapshot();setSnapshot(actual);if(actual){setMaterial(actual.material);setRecipe(actual.recipe);}}catch(error){report(error);}finally{setPending(false);}};
 const formEdit=(operation:AuthoredFormOperation)=>{const now=Date.now();void apply({kind:'form',actor_ref:'human:expressions-app',cause_ref:`physical-form:${crypto.randomUUID()}`,occurrence_unix_ms:now,receipt_unix_ms:now,operations:[operation]});};
 const provenance=()=>({reference:`physical-choice:${crypto.randomUUID()}`,revision:'1',source_ref:'human:expressions-app',standing:'source_authored' as const});
 const number=(label:string,value:number,set:(value:number)=>void,min?:number,max?:number,step:number|string='any')=><label>{label}<input type="number" value={value} min={min} max={max} step={step} disabled={!current} onChange={event=>{if(Number.isFinite(event.currentTarget.valueAsNumber))set(event.currentTarget.valueAsNumber);}}/></label>;
 return <details className="performance-body-controls" data-performance="physical-edit-controls"><summary>Physical form and material · body {snapshot?.body_revision??'unavailable'}</summary>
  <p>Apply stops output and keeps the body’s motion, pending notes and original score history. Start output to continue.</p>
  <fieldset disabled={!current}><legend>Form</legend>
   {number('Form address',form,setForm,0,63,1)}<button data-performance="physical-form-select" onClick={()=>formEdit({operation:'select-form',address:form})}>Apply form</button>
   {number('Line',line,setLine,1,6,1)}<button data-performance="physical-form-line" onClick={()=>formEdit({operation:'change-line',line:line-1})}>Change line</button>
   {number('Matrix family (complementary 0, moving/resting 1, same quality 2)',matrix,setMatrix,0,2,1)}<button onClick={()=>formEdit({operation:'apply-matrix',family:matrix})}>Apply matrix</button>
   {number('Pose',pose,setPose,0,255,1)}<button data-performance="physical-form-pose" onClick={()=>formEdit({operation:'set-pose',pose})}>Apply pose</button>
   {number('Aperture',aperture,setAperture,0,15,1)}<button onClick={()=>formEdit({operation:'set-aperture',aperture})}>Apply aperture</button><button onClick={()=>formEdit({operation:'reciprocal-aperture'})}>Reciprocal aperture</button>
   {number('Clock steps',steps,setSteps,0,Number.MAX_SAFE_INTEGER,1)}<button onClick={()=>formEdit({operation:'advance-clock',steps})}>Advance form clock</button>
   {number('Spanda tick',tick,setTick,0,11,1)}{number('Cycle',cycle,setCycle,0,Number.MAX_SAFE_INTEGER,1)}<button onClick={()=>formEdit({operation:'spanda-advance',tick12:tick,cycle})}>Apply Spanda position</button>
   <button onClick={()=>formEdit({operation:'transcribe',rna:true})}>Transcribe RNA</button><button onClick={()=>formEdit({operation:'transcribe',rna:false})}>Transcribe DNA</button>
   <details><summary>Creases</summary>{angles.map((value,index)=><React.Fragment key={index}>{number(`Angle ${index+1} (0.1°)`,value,n=>setAngles(old=>old.map((entry,i)=>i===index?n:entry) as [number,number,number]),-2147483648,2147483647,1)}{number(`Velocity ${index+1} (0.1°)`,velocities[index],n=>setVelocities(old=>old.map((entry,i)=>i===index?n:entry) as [number,number,number]),-2147483648,2147483647,1)}</React.Fragment>)}<button onClick={()=>formEdit({operation:'cast-creases',angles_deg10:angles,velocities_deg10:velocities})}>Cast creases</button></details>
  </fieldset>
  {material&&<fieldset disabled={!current}><legend>Material</legend>{(['young_modulus_pa','density_kg_per_m3','damping_alpha_per_second','damping_beta_seconds'] as const).map((key,index)=><React.Fragment key={key}>{number(['Elastic modulus (Pa)','Density (kg/m³)','Rayleigh damping α (1/s)','Rayleigh damping β (s)'][index],material[key],value=>setMaterial(old=>old?{...old,[key]:value}:null))}</React.Fragment>)}<button data-performance="physical-material-apply" onClick={()=>void apply({kind:'material',cause_ref:`physical-material:${crypto.randomUUID()}`,material:{...material,provenance:provenance()}})}>Apply material</button></fieldset>}
  {recipe&&<details><summary>Metric form</summary><fieldset disabled={!current}><label>Body family<select value={recipe.family} onChange={event=>setRecipe(old=>old?{...old,family:event.currentTarget.value as AuthoredMetricRecipe['family']}:null)}><option value="axial_truss">Axial truss</option><option value="prestressed_tension_network">Prestressed tension network</option></select></label>{(['frame_side_metres','site_separation_metres','intersite_section_m2','prestress_newtons'] as const).map((key,index)=><React.Fragment key={key}>{number(['Frame side (m)','Site separation (m)','Intersite section (m²)','Prestress (N)'][index],recipe[key],value=>setRecipe(old=>old?{...old,[key]:value}:null))}</React.Fragment>)}{recipe.section_by_element_m2.map((value,index)=><React.Fragment key={index}>{number(`Element ${index+1} section (m²)`,value,n=>setRecipe(old=>old?{...old,section_by_element_m2:old.section_by_element_m2.map((entry,i)=>i===index?n:entry) as [number,number,number,number]}:null))}</React.Fragment>)}<button data-performance="physical-metric-apply" onClick={()=>void apply({kind:'metric-form',cause_ref:`physical-metric:${crypto.randomUUID()}`,recipe:{...recipe,provenance:provenance()}})}>Apply metric form</button></fieldset></details>}
  {!snapshot&&<p role="status">The actual current body and retained source are unavailable for physical editing.</p>}
 </details>;
}
