import {counter,readPerformance,readTransportAcknowledgement,type NativePerformanceReading} from './protocol.js';
import {temporalKeys} from './temporalCapture.js';
import {sameNativePlaybackJson,requireNativeProgrammeOriginalCohort,type NativeScorePlaybackRange} from './playback.js';
import type {RetainedPerformanceAct} from './retainedAct.js';
import type {NativeRecordingCas} from './sceneRecording.js';
const need=(ok:unknown,reason:string):void=>{if(!ok)throw Error('Native WAV export: '+reason);};
/** Actual C63 Source4 file/restitution consumer. Native C validates the full
 * selected source/Act, every original native callback and WAV f32 bits. */
export function readNativeEditedRender(result:any,reply:any,selected:RetainedPerformanceAct,range:NativeScorePlaybackRange,cas:NativeRecordingCas,id:string,before:NativePerformanceReading){
 counter(id);need(BigInt(id)>0n&&result?.schema==='oi.native-scene-recording-result/v1'&&result.accepted===true&&Object.hasOwn(result.currentness??{},'Ok')&&result.application?.Ok===null,'The current native Document did not qualify its actual render.');
 const native=result.native_reply,r=native?.result,chosen=selected.selection,selection=r?.selection,plan=r?.original_plan;
 const scene=selected.document.scenes.find(s=>s.scene_ref===cas.scene_ref),performance=scene?.performance as any,cut=performance?.checkpoints?.[range.checkpoint_index];
 need(native?.schema==='ql.native-act-owner-result/v1'&&native.available===true&&native.status==='ok'&&native.request_id===id&&native.last_request_id===id&&r?.rendered===true&&r.activity_error===null&&r.score&&typeof r.score==='object','The original native WAV activity is unavailable or incomplete.');
 need(selected.document.expression_ref===cas.expression_ref&&selected.document.revision===cas.document_revision&&scene?.revision===cas.scene_revision&&selection?.native_request_id===id&&selection.act_ref===selected.act_ref&&selection.act_revision===chosen.expected_act_revision&&selection.edition_position===chosen.edition_position&&selection.scene_ref===cas.scene_ref&&selection.scene_revision===cas.scene_revision&&selection.performance_digest===chosen.performance_digest,'The original render selected another Act/current Edition.');
 need(cut?.acknowledged_stopped===true&&plan?.schema==='oi.native-retained-act-playback-plan/v1'&&plan.expression_ref===cas.expression_ref&&plan.scene_ref===cas.scene_ref&&plan.performance_digest===chosen.performance_digest&&plan.from_sample===range.from_sample&&plan.to_sample===range.to_sample&&plan.checkpoint_index===range.checkpoint_index&&plan.checkpoint_ref===cut.checkpoint_ref&&plan.checkpoint_digest===cut.content_digest&&plan.reconstruction_sample===cut.sample,'The actual native rendered range/stopped reconstruction cut changed.');
 const scope=temporalKeys(r.scope,['performance_digest','sample_rate','channels','start_sample','frames','native_audio_contract','native_physical_contract']);counter(scope.start_sample);counter(scope.frames);
 need(scope.performance_digest===chosen.performance_digest&&scope.sample_rate===performance.sample_rate&&scope.channels===1&&scope.start_sample===range.from_sample&&BigInt(scope.frames)===BigInt(range.to_sample)-BigInt(range.from_sample)&&scope.native_audio_contract==='ql.performance-audio/v1'&&scope.native_physical_contract==='ql.physical-body/v1','The WAV is detached from its actual full physical score/range.');
 const host=r.host_receipt,pulse=reply?.native_pulse;
 need(host?.schema==='ql.field-host-receipt/v1'&&host.request_id===id&&host.last_request_id===id&&sameNativePlaybackJson(host.performance,reply)&&reply?.schema==='ql.performance-management-reply/v1'&&reply.operation==='performance-edited-render'&&reply.accepted===true&&pulse?.operation==='selected-source-restitution'&&pulse.accepted===true&&sameNativePlaybackJson(reply.reading,pulse.reading),'The actual native restitution lost its SAME outer acknowledgement.');
 const files=temporalKeys(result.original_render_files,['schema','available','request_id','directory','encoding','files','rendered_wav']),diagnostics=result.diagnostics;
 need(files.schema==='oi.native-recording-render-original-files/v1'&&files.available===true&&files.request_id===id&&typeof files.directory==='string'&&files.directory.length>0&&files.encoding==='serde-json-value-utf8/v1'&&Array.isArray(files.files)&&files.files.length>0&&diagnostics?.schema==='oi.native-act-diagnostic-custody/v1'&&diagnostics.encoding===files.encoding&&Array.isArray(diagnostics.receipts)&&diagnostics.receipts.length===files.files.length,'The full original native render/file cohort is not durable.');
 const descriptors=new Map<string,any>();for(const o of diagnostics.receipts){const d=temporalKeys(o.descriptor,['receipt_ordinal','kind','original_index','bytes','sha256','parts']);for(const k of ['receipt_ordinal','original_index','bytes','parts'])counter(d[k]);need(o.complete===true&&o.received_bytes===d.bytes&&!descriptors.has(d.receipt_ordinal)&&BigInt(d.receipt_ordinal)>0n&&BigInt(d.bytes)>0n&&BigInt(d.parts)>0n&&/^sha256:[0-9a-f]{64}$/.test(d.sha256),'An original native render receipt is incomplete/repeated.');descriptors.set(d.receipt_ordinal,d);}
 const allowed=new Set(['playback.programme.original_request','playback.programme.admission','playback.programme.stopped_prepare','playback.prior_before_resident_restoration','playback.prior_resident_restoration_original_request','playback.prior_resident_restoration','playback.device.start','playback.source_original','playback.source_application','playback.contact_original','playback.contact_admission','playback.contact_pending','playback.event_admission','playback.event_pending','playback.native_callback','playback.selected_checkpoint','playback.resident_restoration','playback.before_resident_restoration','playback.resident_restoration_original_request']);const seen=new Set<string>(),kinds=new Map<string,number>();for(const raw of files.files){const row=temporalKeys(raw,['descriptor','file']),d=row.descriptor;need(sameNativePlaybackJson(d,descriptors.get(d?.receipt_ordinal))&&!seen.has(d.receipt_ordinal)&&allowed.has(d.kind)&&row.file===`original-${d.receipt_ordinal}.json`,'An exported original file lost its exact descriptor.');seen.add(d.receipt_ordinal);kinds.set(d.kind,(kinds.get(d.kind)??0)+1);}
 for(const kind of ['playback.before_resident_restoration','playback.resident_restoration_original_request','playback.resident_restoration'])need(kinds.get(kind)===1&&files.files.filter((row:any)=>row.descriptor.kind===kind)[0].descriptor.original_index==='0','The original before/request/restitution file is missing, repeated or has another native index.');need((kinds.get('playback.native_callback')??0)>0,'The actual native callback originals are absent.');
 requireNativeProgrammeOriginalCohort(files,'edited-render');
 // The prior candidate may genuinely restore another resident source/body.
 // Only the SAME durable native prior original can select that comparison
 // boundary; a label or the old pre-request reading cannot substitute for it.
 const priorKinds=['playback.prior_before_resident_restoration','playback.prior_resident_restoration_original_request','playback.prior_resident_restoration'];
 const hasPrior=priorKinds.some(kind=>kinds.has(kind)),hasBoundary=Object.hasOwn(r,'prior_resident_boundary');
 need(hasPrior===hasBoundary,'The genuine prior resident original and its boundary must be present together.');
 let boundary=before,priorBoundary:any=null;
 if(hasPrior){
  for(const kind of priorKinds)need(kinds.get(kind)===1&&files.files.find((row:any)=>row.descriptor.kind===kind)?.descriptor.original_index==='0','The prior resident original triple is incomplete, repeated or foreign.');
  priorBoundary=temporalKeys(r.prior_resident_boundary,['schema','native_reading','diagnostic_receipt']);
  const actual=files.files.find((row:any)=>row.descriptor.kind==='playback.prior_resident_restoration').descriptor;
  need(priorBoundary.schema==='ql.native-edited-prior-resident-boundary/v1'&&sameNativePlaybackJson(priorBoundary.diagnostic_receipt,actual),'The post-prior boundary differs from its SAME fsynced native original.');
  boundary=readPerformance(priorBoundary.native_reading);
  need(boundary.available&&boundary.session_ref===before.session_ref&&boundary.device.state!=='running'&&BigInt(boundary.transport_epoch)>BigInt(before.transport_epoch)&&boundary.scope.instance_ref===before.scope.instance_ref&&boundary.scope.event_ref===before.scope.event_ref&&boundary.scope.subject_ref===before.scope.subject_ref,'The prior resident boundary belongs to another native owner/work or lacks actual stopped restitution.');
 }
 const restored=temporalKeys(r.restoration,['schema','restored','original_cursor','original_accepted_sequence','previous_transport_epoch','transport_epoch','transaction_ref','checkpoint_ref','receipt_kind','index']);
 const transition=readTransportAcknowledgement(reply.transport_transition);need(transition&&sameNativePlaybackJson(transition,pulse.payload?.transport_ack)&&sameNativePlaybackJson(transition,pulse.payload?.source_restitution?.transport_ack),'The exact native restitution acknowledgement is missing.');
 for(const key of ['original_cursor','original_accepted_sequence','previous_transport_epoch','transport_epoch'])counter(restored[key]);
 need(restored.schema==='ql.native-edited-render-restoration/v1'&&restored.restored===true&&restored.receipt_kind==='playback.resident_restoration'&&restored.index===0&&restored.original_cursor===boundary.samples_elapsed&&restored.original_accepted_sequence===boundary.accepted_sequence&&restored.original_cursor===transition!.target_sample&&restored.original_accepted_sequence===transition!.accepted_sequence&&restored.previous_transport_epoch===transition!.previous_epoch&&restored.transport_epoch===transition!.epoch&&restored.transaction_ref===transition!.transaction_ref&&restored.checkpoint_ref===transition!.checkpoint_ref&&BigInt(transition!.previous_epoch)>=BigInt(boundary.transport_epoch)&&BigInt(transition!.epoch)===BigInt(transition!.previous_epoch)+1n,'The native export did not restitute the actual stopped resident cursor/sequence.');
 // Internal stopped render/restores have their own original epochs. The final
 // closed restitution ACK, never a cross-lifetime guessed baseline, admits it.
 const reading=readPerformance(reply.reading,undefined,transition);
 need(reading.session_ref===boundary.session_ref&&reading.device.state!=='running'&&reading.available&&sameNativePlaybackJson(reading.scope,boundary.scope)&&reading.physical.source_generation===boundary.physical.source_generation&&typeof boundary.physical.eigenbasis_identity==='string'&&boundary.physical.eigenbasis_identity.length>0&&reading.physical.eigenbasis_identity===boundary.physical.eigenbasis_identity&&sameNativePlaybackJson(reading.physical.node_ids,boundary.physical.node_ids)&&sameNativePlaybackJson(reading.physical.positions_metres,boundary.physical.positions_metres)&&Object.is(reading.physical.energy_joules,boundary.physical.energy_joules)&&Object.is(reading.physical.pickup_linear,boundary.physical.pickup_linear)&&sameNativePlaybackJson(reading.parameters,boundary.parameters)&&sameNativePlaybackJson(reading.excitation,boundary.excitation)&&reading.active_touches===boundary.active_touches&&reading.active_voices===boundary.active_voices&&reading.sustain===boundary.sustain,'The complete actual stopped resident body differs after export restitution.');
 const wave=temporalKeys(files.rendered_wav,['file','receipt']),receipt=temporalKeys(wave.receipt,['schema','format','performance_digest','file_sha256','bytes','losses','exact_companion_required']);
 need(wave.file==='native-render.wav'&&receipt.schema==='oi.expression-performance-export/v1'&&receipt.format==='WAV IEEE-float32'&&receipt.performance_digest===chosen.performance_digest&&typeof receipt.file_sha256==='string'&&/^[0-9a-f]{64}$/.test(receipt.file_sha256)&&Number.isSafeInteger(receipt.bytes)&&BigInt(receipt.bytes)===58n+4n*BigInt(scope.frames)&&Array.isArray(receipt.losses)&&receipt.exact_companion_required===true,'The exported WAV lacks its exact native file/size/hash/companion receipt.');
 for(const raw of receipt.losses){const l=temporalKeys(raw,['kind','occurrences','maximum_error','unit','consequence']);need(typeof l.kind==='string'&&Number.isSafeInteger(l.occurrences)&&l.occurrences>=0&&Number.isFinite(l.maximum_error)&&typeof l.unit==='string'&&typeof l.consequence==='string','The native export loss disclosure is malformed.');}
 const restoredSource=readNativeEditedRestoredSource(r,selected.document,cas,reading,transition!.checkpoint_ref);
 return{reading,transition:transition!,files,wav:wave,scope,restoration:restored,boundary,priorBoundary,restoredSource};
}

/** Read-only consumer of the native/C closed restitution return. Complete source
 * evidence must agree with the current selected full Edition and SAME original
 * stopped pulse. This JSON never opens or reconstructs a native source owner. */
function readNativeEditedRestoredSource(returned:any,document:any,cas:NativeRecordingCas,reading:NativePerformanceReading,checkpointRef:string){
 const selector=temporalKeys(returned.restored_source_selection,['schema','expression_ref','scene_ref','checkpoint_ref','source_index','basis_index','basis_digest','identity','source_reading','source_sample']);
 const artifact=returned.restored_source_artifact;
 need(artifact&&typeof artifact==='object'&&!Array.isArray(artifact)&&artifact.schema==='ql.retained-source-performance-fixture/v1','The actual restored native source artifact is absent.');
 const scene=document.scenes.find((row:any)=>row.scene_ref===cas.scene_ref),performance=scene?.performance;
 need(document.expression_ref===cas.expression_ref&&document.revision===cas.document_revision&&scene?.revision===cas.scene_revision&&Array.isArray(performance?.native_sources)&&Array.isArray(performance?.bases),'The restored source belongs to a stale current Document/Scene.');
 need(selector.schema==='ql.native-retained-performance-source-selection/v1'&&selector.expression_ref===cas.expression_ref&&selector.scene_ref===cas.scene_ref&&selector.checkpoint_ref===checkpointRef&&Number.isSafeInteger(selector.source_index)&&selector.source_index>=0&&selector.source_index<=255&&Number.isSafeInteger(selector.basis_index)&&selector.basis_index>=0&&selector.basis_index<=65535,'The restored source lost its actual selected checkpoint/indices.');
 const histories=['native_physical_source_history','native_acoustic_source_history','native_contact_admission_history'];
 const matches=performance.native_sources.flatMap((asset:any,index:number)=>sameNativePlaybackJson(asset.native_bundle,artifact.source_assets)&&histories.every(key=>Object.hasOwn(asset,key)===Object.hasOwn(artifact,key)&&sameNativePlaybackJson(asset[key],artifact[key]))?[{asset,index}]:[]);
 need(matches.length===1&&matches[0].index===selector.source_index,'The restored complete native source/history is absent or ambiguous.');
 const asset=matches[0].asset,bundle=asset.native_bundle,basis=performance.bases[selector.basis_index],raw=artifact.basis;
 need(basis&&basis.content_digest===selector.basis_digest&&asset.basis_digest===selector.basis_digest&&typeof basis.content_digest==='string'&&basis.content_digest.length>0&&performance.bases.filter((b:any)=>b.content_digest===selector.basis_digest).length===1&&sameNativePlaybackJson(basis.identity,asset.identity)&&sameNativePlaybackJson(selector.identity,asset.identity),'The restored source lost its unique full musical basis/identity.');
 // Native Return remains unsealed. Only its content_digest differs from the
 // closed C basis; every other original value, key and signed bit is exact.
 need(raw&&typeof raw==='object'&&!Array.isArray(raw)&&raw.content_digest===''&&Object.keys(raw).length===Object.keys(basis).length&&Object.keys(basis).every(key=>Object.hasOwn(raw,key)&&(key==='content_digest'||sameNativePlaybackJson(raw[key],basis[key]))),'The complete raw native Return differs from its sealed original musical basis.');
 for(const key of histories)if(Object.hasOwn(asset,key))need(Array.isArray(asset[key])&&asset[key].length>0,'Present native histories cannot be empty substitutes for original absence.');
 const sourceReading=temporalKeys(selector.source_reading,['ref','revision','availability']);counter(selector.source_sample);
 need(sourceReading.availability==='available'&&sourceReading.revision==='oi.expression-performance-source-asset/v1'&&/^sha256:[0-9a-f]{64}$/.test(sourceReading.ref)&&selector.source_sample===bundle.current_receiving?.native_admission?.operation?.native_sample&&BigInt(selector.source_sample)<=BigInt(reading.samples_elapsed),'The restored actual source reading/date is unavailable or ahead of the resident.');
 const body=basis.prepared_body,request=body?.request,packet=artifact.native_preparation;
 need(sameNativePlaybackJson(artifact.native_reading,reading)&&packet&&sameNativePlaybackJson(artifact.native_basis,bundle.native_basis)&&sameNativePlaybackJson(packet.physical_body,body)&&sameNativePlaybackJson(packet.native_basis,artifact.native_basis)&&sameNativePlaybackJson(packet.determination,basis.audio_determination),'The restored artifact lost its SAME native pulse/body/M2 determination.');
 need(request?.preparation_ref===reading.scope.preparation_ref&&request.state_ref===reading.scope.state_ref&&String(request.body_revision)===reading.scope.body_revision&&String(body.source_generation)===reading.physical.source_generation&&asset.identity.instance_ref===reading.scope.instance_ref&&asset.identity.event_ref===reading.scope.event_ref&&asset.identity.subject_ref===reading.scope.subject_ref&&asset.identity.m1_revision===reading.scope.m1_revision&&asset.identity.m2_generation===reading.scope.m2_generation&&sameNativePlaybackJson(request.geometry?.nodes?.map((node:any)=>String(node.identity)),reading.physical.node_ids),'The restored renderer source/body descendants differ from the exact native reading.');
 const current=temporalKeys(returned.restored_current_receiving,['schema','source_inputs','source_context','source_payload_context','receiving_definition','native_admission']),admission=current.native_admission,definition=current.receiving_definition,context=current.source_context,payload=current.source_payload_context;
 need(current.schema==='ql.current-performance-receiving/v1'&&sameNativePlaybackJson(current.source_inputs,bundle.current_receiving.source_inputs)&&admission?.schema==='ql.performance-receiving-admission/v1'&&admission.operation?.native_sample===reading.samples_elapsed&&admission.operation.body_revision===reading.scope.body_revision&&admission.operation.preparation?.reference===reading.scope.preparation_ref&&admission.operation.state?.reference===reading.scope.state_ref&&admission.operation.source_instance===reading.scope.instance_ref,'The operative receiving is absent, stale or detached from the restored native cursor/body.');
 need(definition?.schema==='ql.nara-performance-receiving/v1'&&context?.schema==='ql.retained-performance-source-context/v1'&&sameNativePlaybackJson(definition,admission.receiving_definition)&&sameNativePlaybackJson(definition,context.receiving_definition)&&sameNativePlaybackJson(admission.native_basis,artifact.native_basis)&&sameNativePlaybackJson(admission.native_generations,admission.operation.native_generations)&&sameNativePlaybackJson(definition.native_generations,admission.native_generations),'The freshly prepared receiving lost its complete definition/context/current native generations.');
 const preparation=admission.native_preparation,retainedPreparation=bundle.current_receiving.native_admission.native_preparation;
 const hasSparse=Object.hasOwn(packet,'source_key_admission'),sparsePreparation=bundle.source_key_preparation;
 need(Object.hasOwn(bundle,'source_key_preparation')&&Object.hasOwn(bundle.configuration??{},'sparse_condition')&&hasSparse===(sparsePreparation!==null)&&hasSparse===(bundle.configuration.sparse_condition!==null),'The source-key extension is not qualified by the actual retained sparse source owner.');
 need(preparation&&typeof preparation==='object'&&!Array.isArray(preparation)&&sameNativePlaybackJson(preparation,retainedPreparation)&&Object.keys(packet).length===Object.keys(preparation).length+(hasSparse?1:0)&&!Object.hasOwn(preparation,'source_key_admission')&&Object.keys(preparation).every(key=>Object.hasOwn(packet,key)&&sameNativePlaybackJson(preparation[key],packet[key])),'The operative receiving changed its whole original native prepared binding.');
 if(hasSparse){
  const keys=temporalKeys(packet.source_key_admission,['schema','preparation','touch_receipts','physical_standing','audio_octet_source']);
  need(keys.schema==='ql.source-performance-admission/v1'&&sameNativePlaybackJson(keys,retainedPreparation.policy_receipts?.source_keys)&&sameNativePlaybackJson(keys.preparation,sparsePreparation),'The complete source-key admission differs from the actual preserved native producer receipt.');
 }else need(!Object.hasOwn(retainedPreparation.policy_receipts??{},'source_keys'),'A non-sparse source retained an unqualified source-key admission.');
 need(payload?.schema==='ql.native-receiving-source-payload-context/v1'&&payload.private===context.context?.private&&payload.owner?.ref==='crates/ql-mef/src/continuous/performance_receiving.rs'&&payload.owner.availability==='available'&&/^sha256:[0-9a-f]{64}$/.test(payload.owner.revision)&&['source_inputs_sha256','source_context_sha256','native_admission_sha256'].every(key=>/^sha256:[0-9a-f]{64}$/.test(payload[key])),'The fresh receiving lost the actual native producer/context witness.');
 const savedReceiver=Object.hasOwn(bundle,'acoustic_receiving')?bundle.acoustic_receiving:null;
 need(savedReceiver===null||savedReceiver&&typeof savedReceiver==='object'&&savedReceiver.packet,'The retained acoustic epoch lost its original complete packet.');
 return{basis:selector.basis_index,artifact,retainedSource:{asset,selection:selector,current_receiving:current,original_saved_acoustic:savedReceiver===null?null:savedReceiver.packet}};
}
