// Generated by oi contribution compile-registry; review source manifests, never load runtime code.
import {lazy} from "react";
import type {RegisteredHostedSurface} from "./contracts";
export const registeredHostedSurfaces: readonly RegisteredHostedSurface[] = [
  {descriptor:{"contribution_ref":"oi.contribution/core","descriptor_ref":"oi.surface/expressions","kind":"expressions","owner":"oi","region":"canvas","retention":"mounted","revision":1,"title":"Expressions"}, Component:lazy(() => import("./core/descriptor").then(module => ({default:module.ExpressionsHostedSurface})))},
  {descriptor:{"contribution_ref":"oi.contribution/core","descriptor_ref":"oi.surface/techne","kind":"techne","owner":"oi","region":"canvas","retention":"mounted","revision":1,"title":"Technè"}, Component:lazy(() => import("./core/descriptor").then(module => ({default:module.TechneHostedSurface})))},
  {descriptor:{"contribution_ref":"oi.contribution/core","descriptor_ref":"oi.surface/epi-logos","kind":"epi-logos","owner":"oi","region":"canvas","retention":"mounted","revision":1,"title":"Epi-Logos"}, Component:lazy(() => import("./core/descriptor").then(module => ({default:module.EpiLogosHostedSurface})))},
  {descriptor:{"contribution_ref":"oi.contribution/core","descriptor_ref":"oi.surface/system","kind":"system","owner":"oi","region":"canvas","retention":"mounted","revision":1,"title":"Settings"}, Component:lazy(() => import("./core/descriptor").then(module => ({default:module.SystemHostedSurface})))},
  {descriptor:{"contribution_ref":"oi.contribution/factory","descriptor_ref":"oi.surface/factory","kind":"factory","owner":"software-factory","region":"canvas","retention":"mounted","revision":1,"title":"Factory"}, Component:lazy(() => import("./factory/descriptor").then(module => ({default:module.FactoryHostedSurface})))},
  {descriptor:{"contribution_ref":"oi.contribution/automations","descriptor_ref":"oi.surface/automations","kind":"automations","owner":"ai-kit","region":"canvas","retention":"mounted","revision":1,"title":"Automations"}, Component:lazy(() => import("./automations/descriptor").then(module => ({default:module.AutomationsHostedSurface})))}
];
