// Generated by oi contribution compile-registry --metadata; presentation metadata only.
export const hostedSurfaceDescriptors = [
  {
    "contribution_ref": "oi.contribution/core",
    "descriptor_ref": "oi.surface/expressions",
    "kind": "expressions",
    "owner": "oi",
    "region": "canvas",
    "retention": "mounted",
    "revision": 1,
    "title": "Expressions"
  },
  {
    "contribution_ref": "oi.contribution/core",
    "descriptor_ref": "oi.surface/techne",
    "kind": "techne",
    "owner": "oi",
    "region": "canvas",
    "retention": "mounted",
    "revision": 1,
    "title": "Technè"
  },
  {
    "contribution_ref": "oi.contribution/core",
    "descriptor_ref": "oi.surface/epi-logos",
    "kind": "epi-logos",
    "owner": "oi",
    "region": "canvas",
    "retention": "mounted",
    "revision": 1,
    "title": "Epi-Logos"
  },
  {
    "contribution_ref": "oi.contribution/core",
    "descriptor_ref": "oi.surface/system",
    "kind": "system",
    "owner": "oi",
    "region": "canvas",
    "retention": "mounted",
    "revision": 1,
    "title": "Settings"
  },
  {
    "contribution_ref": "oi.contribution/factory",
    "descriptor_ref": "oi.surface/factory",
    "kind": "factory",
    "owner": "software-factory",
    "region": "canvas",
    "retention": "mounted",
    "revision": 1,
    "title": "Factory"
  },
  {
    "contribution_ref": "oi.contribution/automations",
    "descriptor_ref": "oi.surface/automations",
    "kind": "automations",
    "owner": "ai-kit",
    "region": "canvas",
    "retention": "mounted",
    "revision": 1,
    "title": "Automations"
  }
];
