import {open,close,resolveTarget,rows,waitUntil} from './field-lib.ts';
import {projectionStorageKey,relationStorageRef} from '../spacetimedb.mjs';
import {createExploreApplication} from '../explore.mjs';
async function main(){
const resolved=resolveTarget();if(!resolved.bound)throw Error(resolved.reason);const run=process.env.OI_SF3_RUN_REF??`sf3-${Date.now()}`;const bridge=process.env.OI_SF3_BRIDGE_URL??'http://127.0.0.1:4283';const reader=await open(resolved.target,'owner'),publisher=await open(resolved.target,run+'-publisher');const r:any=publisher.conn.reducers,field=`oi:field:${run}`,agentP=`participant:${run}:agent`,humanP=`participant:${run}:human`,ownerP=`participant:${run}:publisher`,expr=`expression:${run}`,agent='agent:sf3';
const created:any=await fetch(`${bridge}/op`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({op:'expression',request:{operation:'create',expression_ref:expr,title:'SF3 shared lesson',actor:'human:world-b'}})}).then(x=>x.json());const native=created.outcome?.data?.document;if(native?.revision!==1)throw Error('native Expression create failed');
const fieldC={schema:'oi.shared-field/v1',field_ref:field,kind:'explore',visibility:'public',title:'SF3 Being encounter',provenance:[{kind:'acceptance',ref:run,source_system:'o-i',revision:'1'}]};await r.putSharedField({fieldRef:field,kind:'explore',visibility:'public',contractJson:JSON.stringify(fieldC)});
const agentC={schema:'oi.participant/v1',participant_ref:agentP,field_ref:field,identity:{kind:'agent',ref:agent},agency:{ref:'agency:sf3',source_system:'actuation'},presentation:{chosen_name:'Epii SF3',summary:'Run-scoped projected Agent.',presence:'available',address:'@sf3-agent'},provenance:{source_system:'ai-kit',source_revision:'rev/1'}};const ownerC={schema:'oi.participant/v1',participant_ref:ownerP,field_ref:field,identity:{kind:'human',ref:'human:publisher'},presentation:{chosen_name:'SF3 publisher'},provenance:{source_system:'central',source_revision:'rev/1'}};const humanC={schema:'oi.participant/v1',participant_ref:humanP,field_ref:field,identity:{kind:'human',ref:'human:world-b'},presentation:{chosen_name:'SF3 reader'},provenance:{source_system:'central',source_revision:'rev/1'}};
for(const p of [ownerC,humanC])await r.putParticipant({participantRef:p.participant_ref,fieldRef:field,identityKind:p.identity.kind,identityRef:p.identity.ref,sourceSystem:p.provenance.source_system,sourceRevision:p.provenance.source_revision,contractJson:JSON.stringify(p)});await r.grantParticipantAuthority({fieldRef:field,participantRef:ownerP,targetIdentity:publisher.identity,role:'contributor',contactable:true,ttlSeconds:0});await waitUntil(()=>rows(publisher.conn.db.myFieldAuthority).some((x:any)=>x.participantRef===ownerP&&!x.revoked),'publisher grant');await r.putParticipant({participantRef:agentC.participant_ref,fieldRef:field,identityKind:agentC.identity.kind,identityRef:agentC.identity.ref,sourceSystem:agentC.provenance.source_system,sourceRevision:agentC.provenance.source_revision,contractJson:JSON.stringify(agentC)});await r.grantParticipantAuthority({fieldRef:field,participantRef:humanP,targetIdentity:reader.identity,role:'observer',contactable:true,ttlSeconds:0});
const comp={schema:'oi.expression-composition/v1',expression_ref:native.expression_ref,revision:native.revision,title:native.title,scenes:native.scenes,entities:native.entities,relations:native.relations,selection:native.selection,provenance:native.provenance,representations:native.representations};
const payload={schema:'oi.world-presentation/v1',presentation_ref:`presentation:${run}:expression`,world_ref:`world:${run}`,revision:1,title:'SF3 shared lesson',summary:'Exact admitted composition',theme:{tokens:{}},regions:[{region_ref:`region:${run}`,label:'Expression',order:0,bindings:[{binding_ref:`binding:${run}`,component_ref:'oi.presentation/expression/v1',props:{expression:{expression_ref:expr,expression_revision:1},composition:comp}}]}],provenance:[{kind:'acceptance',ref:run,source_system:'o-i',revision:'1'}]};
const projection={schema:'oi.projection/v1',projection_ref:`projection:${run}:expression`,projection_revision:1,state:'published',subject:{kind:'expression',ref:expr},source:{system:'o-i',ref:expr,revision:'1'},publisher_participant_ref:ownerP,published_at:new Date().toISOString(),audience:{visibility:'public'},representation:{kind:'oi.world-presentation/v1',payload},provenance:[{kind:'acceptance',ref:run,source_system:'o-i',revision:'1'}]};console.error('STEP projection');await r.putProjection({projectionKey:projectionStorageKey(projection.projection_ref,1),fieldRef:field,projectionRef:projection.projection_ref,projectionRevision:1,sourceRevision:'1',publisherParticipantRef:ownerP,state:'published',contractJson:JSON.stringify(projection)});
for(const e of [{ref:agentP,kind:'being',label:'Epii SF3'},{ref:expr,kind:'expression',label:'SF3 shared lesson'}]){const c={schema:'oi.explore-entry/v1',ref:e.ref,kind:e.kind,world_ref:`world:${run}`,label:e.label,summary:'SF3 acceptance',aliases:[],revision:'1',provenance:[{kind:'acceptance',ref:run,source_system:'o-i',revision:'1'}],locators:[]};console.error('STEP entry');await r.putExploreEntry({semanticRef:e.ref,fieldRef:field,worldRef:c.world_ref,kind:e.kind,label:e.label,revision:'1',entryJson:JSON.stringify(c)});}const rel={relation_ref:`relation:${run}`,from:agentP,to:expr,relation:'oi.agent/refined',origin:'projection',provenance:[{kind:'acceptance',ref:`relation:${run}`,source_system:'o-i',revision:'1'}]};createExploreApplication({entries:[{schema:'oi.explore-entry/v1',ref:agentP,kind:'being',world_ref:`world:${run}`,label:'Epii SF3',summary:'SF3 acceptance',aliases:[],revision:'1',provenance:[{kind:'acceptance',ref:run,source_system:'o-i',revision:'1'}],locators:[]},{schema:'oi.explore-entry/v1',ref:expr,kind:'expression',world_ref:`world:${run}`,label:'SF3 shared lesson',summary:'SF3 acceptance',aliases:[],revision:'1',provenance:[{kind:'acceptance',ref:run,source_system:'o-i',revision:'1'}],locators:[]}],relations:[rel]});const relationRef=relationStorageRef(rel);console.error('STEP relation');await r.putExploreRelation({relationRef,fieldRef:field,fromRef:agentP,toRef:expr,relation:rel.relation,origin:rel.origin,relationJson:JSON.stringify(rel)});await waitUntil(()=>rows(reader.conn.db.exploreEntry).some((x:any)=>x.semanticRef===agentP),'reader sees Agent');console.log(JSON.stringify({run,field,agentP,humanP,expr,reader:reader.identityHex,publisher:publisher.identityHex}));close(reader);close(publisher);
}
main().catch(e=>{console.error(e);process.exit(1)});