/** The shell icon language, generated from icon-cut.html.
 *
 * GENERATED by scripts/sync-icons.mjs — regenerate, never hand-edit
 * (derived-surfaces law; the source of truth is the specimen's icon
 * dictionary and its svg() wrapper, byte-faithful below).
 *
 * The device-SDK icon law: a face uses a NAMED mark from this module
 * (renderIcon / <Icon>), never an inline SVG invention. The mark vocabulary
 * is the owner's cut; extending it means cutting new marks into
 * icon-cut.html and re-running the sync, so the specimen stays the one
 * place the language is readable.
 *
 * Alongside the dictionary this module carries the specimen's other
 * drawings, resolved by the same sync from the same file:
 * - CHEVRON_FOLD / CHEVRON_POP — the device header's fold and pop-out marks.
 * - KIND_SHAPES + renderKindShape — the filled kind marks (facet-shaded
 *   node drawings), each kind's inner markup resolved exactly as the
 *   specimen renders it.
 * - WOOD_MARKS + renderWood — the woodcut marks (skill / skillset / method
 *   / methodology, blade and pen sets), with the specimen's own
 *   size/state/stroke rule reproduced verbatim in renderWood.
 *
 * Pure: no store, no view, no I/O. */

/** Every mark of the cut, verbatim inner-SVG (24×24 grid, currentColor).
 * Some marks set their own fills; the wrapper below supplies the stroke
 * grammar for the rest. */
export const ICON_MARKS = {
  link: `<circle cx="8" cy="12" r="3"/><circle cx="16" cy="12" r="3"/><path d="M11 12h2"/>`,
  linkChain: `<path d="M9.5 14.5l-2 2a3.2 3.2 0 0 1-4.5-4.5l2-2M14.5 9.5l2-2a3.2 3.2 0 0 1 4.5 4.5l-2 2M8.5 15.5l7-7"/>`,
  tap: `<path d="M12 15.5V9"/><path d="M8.2 11.2a5 5 0 0 1 7.6 0"/><circle cx="12" cy="17.2" r="1.15" fill="currentColor" stroke="none"/>`,
  metroDots: `<circle cx="8" cy="12" r="2.2" fill="currentColor" stroke="none"/><circle cx="15.5" cy="12" r="2.2"/>`,
  metro: `<path d="M8.5 19.5h7M12 19.2 8.2 6.2h7.6L12 19.2"/><circle cx="11.2" cy="11.5" r="1.35" fill="currentColor" stroke="none"/>`,
  follow: `<path d="M4 12h9.5M10.5 8l4 4-4 4"/><path d="M18.5 6.5v11"/>`,
  play: `<path d="M8 5.2v13.6l11.2-6.8z" fill="currentColor" stroke="none"/>`,
  stop: `<rect x="6.5" y="6.5" width="11" height="11" fill="currentColor" stroke="none"/>`,
  rec: `<circle cx="12" cy="12" r="5.6" fill="currentColor" stroke="none"/>`,
  plus: `<path d="M12 6v12M6 12h12"/>`,
  od: `<path d="M8 6.2v11.6l8.6-5.8z" fill="currentColor" stroke="none" opacity=".35"/><path d="M14 8v8M10.5 12h7"/>`,
  cmd: `<path d="M8 9.2a2.2 2.2 0 1 1-2.2-2.2H8v2.2zm0 5.6H5.8A2.2 2.2 0 1 0 8 17.2V14.8zM16 9.2V7a2.2 2.2 0 1 1 2.2 2.2H16zM16 14.8h2.2A2.2 2.2 0 1 1 16 17v-2.2zM8 9.2h8M8 14.8h8"/>`,
  arm: `<path d="M7 17.2V7.5h6.4a3.3 3.3 0 0 1 0 6.6H7"/><circle cx="7" cy="17.6" r="1.7" fill="currentColor" stroke="none"/>`,
  back: `<path d="M19 12H8.5M12.2 8.2 8 12.2l4.2 4"/><path d="M5 6.5v11"/>`,
  capEmpty: `<circle cx="12" cy="12" r="6"/>`,
  cap: `<circle cx="12" cy="12" r="6.2"/><circle cx="12" cy="12" r="2.1" fill="currentColor" stroke="none"/>`,
  loop: `<path d="M16.5 4.2 20 7.6l-3.5 3.4M20 7.6H9.2a4.2 4.2 0 0 0-4.2 4.2M7.5 19.8 4 16.4l3.5-3.4M4 16.4h10.8a4.2 4.2 0 0 0 4.2-4.2"/>`,
  punchIn: `<path d="M6 19.5V5.5M6 8h6.2L10.6 11l1.6 3H6"/>`,
  punchOut: `<path d="M18 19.5V5.5M18 8h-6.2L13.4 11 11.8 14H18"/>`,
  draw: `<path d="M13.6 5.2 18.8 10.4 9.2 20H4.2v-5z"/><path d="M12 6.8 17.2 12"/>`,
  keysOld: `<path d="M5 5h5v14H5zM14 5h5v14h-5z"/>`,
  keys: `<rect x="3.2" y="7" width="5" height="10.5" rx=".8"/><rect x="9.5" y="7" width="5" height="10.5" rx=".8"/><rect x="15.8" y="7" width="5" height="10.5" rx=".8"/>`,
  earth: `<circle cx="12" cy="10.5" r="6.6"/><path d="M5.6 10.5h12.8M12 4.1c2 2.1 2 10.6 0 12.8M12 4.1c-2 2.1-2 10.6 0 12.8"/><path d="M12 17.2v3.2M9.2 20.6h5.6"/>`,
  map: `<circle cx="6.5" cy="15" r="2.3"/><circle cx="17.2" cy="7.5" r="2.3"/><path d="M8.6 13.8 15.2 9"/>`,
  browser: `<circle cx="12" cy="12" r="8"/><path d="M4.2 12h15.6M12 4.2c2.5 2.6 2.5 13 0 15.6M12 4.2c-2.5 2.6-2.5 13 0 15.6"/>`,
  detail: `<rect x="3.5" y="3.5" width="17" height="10"/><rect x="3.5" y="15.5" width="17" height="5"/>`,
  dock: `<path d="M8.2 7.2a2.5 2.5 0 1 1 0 5 2.5 2.5 0 0 1 0-5zM3.2 19v-1.6a5 5 0 0 1 10 0V19M15.2 6.4a2.4 2.4 0 0 1 0 5M17.4 13.2a4.2 4.2 0 0 1 2.6 3.6V19"/>`,
  pane: `<rect x="3.5" y="3.5" width="7.2" height="7.2"/><rect x="13.3" y="3.5" width="7.2" height="7.2"/><rect x="3.5" y="13.3" width="7.2" height="7.2"/><rect x="13.3" y="13.3" width="7.2" height="7.2"/>`,
  session: `<path d="M6 3.5v17M12 3.5v17M18 3.5v17"/>`,
  arrangement: `<path d="M3.5 6.5h17M3.5 12h17M3.5 17.5h17"/>`,
  live: `<path d="M2.5 12h3.2l2.4-6.2 3.6 12.4 2.4-6.2H21.5"/>`,
  diamond: `<path d="M12 3.2 20.6 12 12 20.8 3.4 12z"/>`,
  die: `<rect x="7.2" y="2.2" width="4.2" height="3.8" fill="currentColor" fill-opacity=".4" stroke="none"/><rect x="1.2" y="8.2" width="4.2" height="3.8" fill="currentColor" fill-opacity=".4" stroke="none"/><rect x="7.2" y="8.2" width="4.2" height="3.8" fill="currentColor" fill-opacity=".4" stroke="none"/><rect x="13.2" y="8.2" width="4.2" height="3.8" fill="currentColor" stroke="none"/><rect x="19.2" y="8.2" width="4.2" height="3.8" fill="currentColor" fill-opacity=".4" stroke="none"/><rect x="7.2" y="14.2" width="4.2" height="3.8" fill="currentColor" fill-opacity=".4" stroke="none"/>`,
  hex: `<path d="M12 3.2 19.2 7.4v9.2L12 20.8 4.8 16.6V7.4z"/>`,
  chain: `<rect x="2" y="9" width="5.5" height="6" rx="1"/><rect x="9.2" y="9" width="5.5" height="6" rx="1"/><rect x="16.5" y="9" width="5.5" height="6" rx="1"/><path d="M7.5 12h1.7M14.7 12h1.8"/>`,
  expr: `<circle cx="12" cy="12" r="8.2"/><circle cx="12" cy="12" r="3.4"/><path d="M12 8.6v6.8M8.6 12h6.8"/>`,
  techne: `<rect x="3.2" y="3.2" width="5" height="5"/><rect x="15.8" y="3.2" width="5" height="5"/><rect x="3.2" y="15.8" width="5" height="5"/><rect x="15.8" y="15.8" width="5" height="5"/><path d="M8.2 5.7h7.6M5.7 8.2v7.6M8.2 18.3h7.6M18.3 8.2v7.6"/>`,
  search: `<circle cx="10.5" cy="10.5" r="5"/><path d="M14.2 14.2 19 19"/>`,
  trav: `<circle cx="6" cy="16" r="2"/><circle cx="16" cy="7" r="2"/><path d="M8 14.5 14 8.6"/>`,
  direct: `<path d="M5 12h8M12 8l5 4-5 4"/><circle cx="18.5" cy="12" r="1.4" fill="currentColor" stroke="none"/>`,
  journey: `<circle cx="12" cy="12" r="7"/><path d="M8 14.5c2.2-4 5.5-4 8 0"/>`,
  palace: `<path d="M4 19.5V10.5L12 4.5l8 6V19.5z"/><path d="M10 19.5v-5h4v5"/>`,
  contact: `<path d="M7 8h8M12 5l3 3-3 3M17 16H9M12 13l-3 3 3 3"/>`,
  ret: `<path d="M9 8H6.5A3.5 3.5 0 0 0 8 15.2"/><path d="M9 5.5 6 8.2 9 11"/><path d="M10 16.5h8"/>`,
  select: `<path d="M6.5 4.2 6.5 18.2l3.4-3.6 3.2 5.2 2-1.2-3.2-5.2H17z"/>`,
  orbit: `<path d="M16.5 8.2A6.2 6.2 0 1 1 12 5.8"/><path d="M12 3.2v3.2h3"/>`,
  form: `<circle cx="12" cy="12" r="6.5"/><circle cx="12" cy="12" r="1.6" fill="currentColor" stroke="none"/>`,
  bind: `<circle cx="12" cy="12" r="2.4"/><path d="M12 3.5v4M12 16.5v4M3.5 12h4M16.5 12h4"/>`,
  lib: `<rect x="4" y="4" width="6.5" height="6.5"/><rect x="13.5" y="4" width="6.5" height="6.5"/><rect x="4" y="13.5" width="6.5" height="6.5"/><rect x="13.5" y="13.5" width="6.5" height="6.5"/>`,
  placed: `<path d="M12 21s6-5.2 6-10a6 6 0 1 0-12 0c0 4.8 6 10 6 10z"/><circle cx="12" cy="11" r="1.6"/>`,
} as const

/** The union of mark names — the only icons a face may declare. */
export type IconName = keyof typeof ICON_MARKS

export function isIconName(candidate: string): candidate is IconName {
  return Object.prototype.hasOwnProperty.call(ICON_MARKS, candidate)
}

export const ICON_NAMES: readonly IconName[] = Object.keys(ICON_MARKS) as IconName[]

export interface IconOptions {
  /** Stroke width; the specimen's default 1.7. */
  readonly sw?: number
  /** Keep the wrapper from setting fill="none" (marks that paint themselves
   * set their own fills inside; this option is for wrapper-level fills). */
  readonly fill?: boolean
}

/** The specimen's svg() wrapper, exactly: 24×24 viewBox, round caps and
 * joins, currentColor stroke. */
export function renderIcon(name: IconName, size = 16, options: IconOptions = {}): string {
  const sw = options.sw ?? 1.7
  const fill = options.fill ? '' : ' fill="none"'
  return `<svg width="${size}" height="${size}" viewBox="0 0 24 24"${fill} stroke="currentColor" stroke-width="${sw}" stroke-linecap="round" stroke-linejoin="round">${ICON_MARKS[name]}</svg>`
}

// ————————————————————————————————————————————————————————————————————————
// The device header's fold chevron and pop-out mark — the specimen's FOLD
// and POP constants, verbatim (10×10 grid, currentColor stroke).

export const CHEVRON_FOLD = '<svg width="10" height="10" viewBox="0 0 10 10" fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"><path d="M2.4 3.8 5 6.4 7.6 3.8"/></svg>'

export const CHEVRON_POP = '<svg width="10" height="10" viewBox="0 0 10 10" fill="none" stroke="currentColor" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"><path d="M5.8 1.6H8.4V4.2M8.4 1.6 4.6 5.4M7 6.2V8.4H1.6V3H3.8"/></svg>'

// ————————————————————————————————————————————————————————————————————————
// The kind marks — the specimen's kindShape() drawings (filled nodes with
// their darker facet), each kind's inner markup resolved by the sync.

export const KIND_SHAPES = {
  'archetype':
    '<path d="M12 2.4 20.8 12 12 21.6 3.2 12z" fill="var(--mercurius)"/><path d="M12 2.4 3.2 12 12 21.6z" fill="#000" fill-opacity="0.22"/><path d="M12 2.4 16.4 7.2 12 12 7.6 7.2z" fill="#fff" fill-opacity="0.18"/><path d="M12 6.6 16.2 12 12 17.4 7.8 12z" fill="none" stroke="#1d1f22" stroke-opacity=".45" stroke-width=".9"/>',
  'occurrence':
    '<circle cx="12" cy="12" r="8" fill="var(--selfc)"/><path d="M5.2 16.2a8 8 0 0 0 13.6-1.6 9 9 0 0 1-13.6 1.6z" fill="#000" fill-opacity=".22"/><ellipse cx="9.2" cy="8.6" rx="2.8" ry="1.7" transform="rotate(-35 9.2 8.6)" fill="#fff" fill-opacity=".5"/><circle cx="12" cy="12" r="8" fill="none" stroke="#000" stroke-opacity=".25" stroke-width=".8"/>',
  'place':
    '<path d="M2.4 20 9.6 6 13.6 12.6 16 9.4 21.6 20z" fill="var(--tower)"/><path d="M9.6 6 13.6 12.6 14.6 20H10.6z" fill="#000" fill-opacity="0.22"/><path d="M16 9.4 21.6 20H17.8z" fill="#000" fill-opacity="0.22"/><path d="M7.7 9.7 9.6 6 11.6 9.3 10.5 8.6 9.5 10 8.7 8.9z" fill="#fff" fill-opacity=".65"/>',
  'location':
    '<circle cx="12" cy="12" r="8.2" fill="none" stroke="var(--tower)" stroke-width="1.4"/><circle cx="12" cy="12" r="4.4" fill="var(--tower)" fill-opacity=".18" stroke="var(--tower)" stroke-width="1"/><circle cx="12" cy="12" r="1.8" fill="var(--tower)"/><path d="M12 1.4V4.6M12 19.4V22.6M1.4 12H4.6M19.4 12H22.6" stroke="var(--tower)" stroke-width="1.4" stroke-linecap="round"/>',
  'source':
    '<rect x="5.6" y="3.6" width="15" height="13.6" rx="1.3" fill="var(--text-dim)" fill-opacity=".42"/><rect x="3.4" y="6.6" width="15" height="13.6" rx="1.3" fill="var(--text-dim)"/><path d="M6.2 10.4h9.4M6.2 13.3h9.4M6.2 16.2h5.8" stroke="#1d1f22" stroke-opacity=".55" stroke-width="1.2" stroke-linecap="round"/>',
  'palace':
    '<path d="M2.8 9.2 12 3.2 21.2 9.2z" fill="var(--tower)" fill-opacity=".22" stroke="var(--tower)" stroke-width="1.3" stroke-linejoin="round"/><path d="M4.4 10.8h15.2M4.4 20h15.2M3.2 22h17.6" stroke="var(--tower)" stroke-width="1.3" stroke-linecap="round"/><path d="M6.6 12.4v6.2M10.2 12.4v6.2M13.8 12.4v6.2M17.4 12.4v6.2" stroke="var(--tower)" stroke-width="1.6" stroke-linecap="round"/>',
  'journey':
    '<circle cx="12" cy="12" r="8.8" fill="#1d1f22" stroke="var(--tower)" stroke-width="1.3"/><path d="M7.4 16.4c1.4-3.4 4.6-2.2 5.6-4.8.7-1.8 1.6-3 3.6-3.2" fill="none" stroke="var(--tower)" stroke-width="1.3" stroke-dasharray="1.8 1.6" stroke-linecap="round"/><circle cx="7.4" cy="16.4" r="1.5" fill="var(--tower)"/><path d="M14.6 6.6 17.2 8.3 14.8 10" fill="none" stroke="var(--tower)" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>',
  'expression':
    '<path d="M12.00 3.00L14.47 9.20L21.13 9.63L15.99 13.90L17.64 20.37L12.00 16.80L6.36 20.37L8.01 13.90L2.87 9.63L9.53 9.20Z" fill="var(--mercurius)"/><path d="M12 12.6L12.00 3.00L14.47 9.20ZM12 12.6L21.13 9.63L15.99 13.90ZM12 12.6L17.64 20.37L12.00 16.80ZM12 12.6L6.36 20.37L8.01 13.90ZM12 12.6L2.87 9.63L9.53 9.20Z" fill="#000" fill-opacity="0.24"/>',
  'run':
    '<path d="M12.00 2.60L20.14 7.30L20.14 16.70L12.00 21.40L3.86 16.70L3.86 7.30Z" fill="var(--fizz)"/><path d="M12.00 2.60L20.14 7.30L12 12L3.86 7.30Z" fill="#fff" fill-opacity="0.28"/><path d="M3.86 7.30L12 12L12.00 21.40L3.86 16.70Z" fill="#000" fill-opacity="0.24"/>',
  'agent':
    '<circle cx="12" cy="12" r="9.2" fill="none" stroke="var(--honey)" stroke-width="1.1"/><circle cx="12" cy="12" r="5.8" fill="var(--honey)"/><ellipse cx="10.4" cy="10" rx="1.9" ry="1.2" transform="rotate(-35 10.4 10)" fill="#fff" fill-opacity=".45"/><circle cx="18.5" cy="5.5" r="1.9" fill="var(--honey)" stroke="#1d1f22" stroke-width=".9"/>',
  'world':
    '<circle cx="12" cy="12" r="9" fill="var(--accent)" fill-opacity=".28" stroke="var(--accent)" stroke-width="1.3"/><ellipse cx="12" cy="12" rx="3.8" ry="9" fill="none" stroke="var(--accent)" stroke-width=".9"/><path d="M3 12Q12 15 21 12M4.2 7.5Q12 10 19.8 7.5M4.2 16.5Q12 19 19.8 16.5" fill="none" stroke="var(--accent)" stroke-width=".9"/>',
  'contribution':
    '<circle cx="12" cy="12" r="8.8" fill="none" stroke="var(--w-ariadne)" stroke-width="1.2" stroke-dasharray="2.4 1.8"/><path d="M12 5.6v8.6M8.6 11 12 14.4 15.4 11M7.8 17.6h8.4" fill="none" stroke="var(--w-ariadne)" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>',
  'day':
    '<rect x="3.8" y="5.4" width="16.4" height="15.2" rx="1.6" fill="var(--text)" fill-opacity=".1" stroke="var(--text)" stroke-width="1.3"/><path d="M3.8 9.6h16.4" stroke="var(--text)" stroke-width="1.1"/><path d="M8.2 3.2v4M15.8 3.2v4" stroke="var(--text)" stroke-width="1.5" stroke-linecap="round"/><rect x="9.8" y="12" width="4.6" height="4.6" rx=".6" fill="var(--text)"/>',
  'doc':
    '<path d="M5.8 2.6h8.6l4.8 4.8v14H5.8z" fill="var(--paper)" fill-opacity=".14" stroke="var(--paper)" stroke-width="1.2" stroke-linejoin="round"/><path d="M14.4 2.6v4.8h4.8" fill="none" stroke="var(--paper)" stroke-width="1.2" stroke-linejoin="round"/><path d="M8.6 11.4h7.6M8.6 14.3h7.6M8.6 17.2h4.6" stroke="var(--paper)" stroke-width="1" stroke-linecap="round"/>',
  'ghost':
    '<circle cx="12" cy="12" r="8" fill="none" stroke="#9aa0a8" stroke-width="1.2" stroke-dasharray="2.2 1.8"/><circle cx="12" cy="12" r="3.4" fill="none" stroke="#9aa0a8" stroke-width=".9" stroke-dasharray="1.4 1.4"/>',
} as const

/** The union of kind-mark names. */
export type KindShapeName = keyof typeof KIND_SHAPES

export function isKindShape(candidate: string): candidate is KindShapeName {
  return Object.prototype.hasOwnProperty.call(KIND_SHAPES, candidate)
}

export const KIND_SHAPE_NAMES: readonly KindShapeName[] = Object.keys(KIND_SHAPES) as KindShapeName[]

/** The specimen's kindShape wrapper, exactly: 24×24, no stroke grammar of
 * the wrapper's own (the marks paint themselves), round joins. */
export function renderKindShape(kind: KindShapeName, size = 16): string {
  return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke-linejoin="round">${KIND_SHAPES[kind]}</svg>`
}

// ————————————————————————————————————————————————————————————————————————
// The woodcut marks (skill / skillset / method / methodology) in both sets,
// each mark's {tf, line, hatch, small} resolved by the sync from the
// specimen's own templates. renderWood reproduces the specimen's rule:
// the small drawing at 20px and below; hatching from 28px up; the warn
// state draws the same line in the stall colour; denied dims (the .wood.dim
// class the specimen's stylesheet carries).

export const WOOD_MARKS = {
    "blade": {
      "skill": {
        "tf": "rotate(35 32 32)",
        "line": "<circle cx=\"32\" cy=\"7.5\" r=\"3.6\"/><path d=\"M30.2 11.1H33.8L34.2 21.6H29.8Z\"/><path d=\"M19.5 23.6Q21.4 21.2 24 22.4H40Q42.6 21.2 44.5 23.6Q42.6 25.8 40 25H24Q21.4 25.8 19.5 23.6Z\"/><path d=\"M29.4 25V50.5L32 58.5L34.6 50.5V25\"/><path d=\"M32 27.6V49\"/>",
        "hatch": "<circle cx=\"32\" cy=\"7.5\" r=\"1.3\"/><path d=\"M30.1 13.6 33.9 12.4M30 16.2 34 15M29.95 18.8 34.1 17.6M29.9 21.2 34.2 20.1\"/><circle cx=\"32\" cy=\"23.7\" r=\"1.2\"/><path d=\"M33.5 30.5V34M33.5 37.5V41M33.5 44.5V47.5M22.5 23.6H24.5M39.5 23.6H41.5\"/>",
        "small": "<circle cx=\"32\" cy=\"7\" r=\"3.6\"/><path d=\"M32 10.8V58M21 23H43\"/>"
      },
      "skillset": {
        "line": "<circle cx=\"18\" cy=\"9\" r=\"2.6\"/><path d=\"M16.4 11.6H19.6V20H16.4Z\"/><path d=\"M11.5 21.5Q11.5 20 13 20H23Q24.5 20 24.5 21.5Q24.5 23 23 23H13Q11.5 23 11.5 21.5Z\"/><path d=\"M16 23V28M20 23V28M16 32.5V52M20 32.5V52\"/><circle cx=\"32\" cy=\"5\" r=\"2.6\"/><path d=\"M30.4 7.6H33.6V16H30.4Z\"/><path d=\"M25.5 17.5Q25.5 16 27 16H37Q38.5 16 38.5 17.5Q38.5 19 37 19H27Q25.5 19 25.5 17.5Z\"/><path d=\"M30 19V28M34 19V28M30 32.5V52M34 32.5V52\"/><circle cx=\"46\" cy=\"9\" r=\"2.6\"/><path d=\"M44.4 11.6H47.6V20H44.4Z\"/><path d=\"M39.5 21.5Q39.5 20 41 20H51Q52.5 20 52.5 21.5Q52.5 23 51 23H41Q39.5 23 39.5 21.5Z\"/><path d=\"M44 23V28M48 23V28M44 32.5V52M48 32.5V52\"/><path d=\"M6 22V52M10.5 22V52M53.5 22V52M58 22V52M6 22Q8.25 17.5 10.5 22M53.5 22Q55.75 17.5 58 22\"/><path d=\"M10.5 28H53.5M10.5 32.5H53.5\"/><path d=\"M3 52H61V57H3Z\"/><path d=\"M7 57V60.5H15V57M49 57V60.5H57V57\"/>",
        "hatch": "<path d=\"M16.4 14.4L19.6 13.2M16.4 17.4L19.6 16.2M18 35V49\"/><path d=\"M30.4 10.4L33.6 9.2M30.4 13.4L33.6 12.2M32 35V49\"/><path d=\"M44.4 14.4L47.6 13.2M44.4 17.4L47.6 16.2M46 35V49\"/><path d=\"M12.5 30.2H15M23.5 30.2H28.5M35.5 30.2H40.5M49 30.2H51.5M7 54.5H13M20 54.5H28M36 54.5H44M51 54.5H57M8.25 25.5V49\"/>",
        "small": "<circle cx=\"18\" cy=\"10\" r=\"3.4\"/><path d=\"M18 13.6V55M12.5 22H23.5\"/><circle cx=\"32\" cy=\"6\" r=\"3.4\"/><path d=\"M32 9.6V55M26.5 18H37.5\"/><circle cx=\"46\" cy=\"10\" r=\"3.4\"/><path d=\"M46 13.6V55M40.5 22H51.5\"/><path d=\"M6 31H58M3 56H61\"/>"
      },
      "method": {
        "line": "<path d=\"M4 33Q11 30.8 18 30.6H54V37H48.5Q43.5 38.6 42.5 43.5V48H49.5V53.5H14.5V48H21.5V43.5Q20.5 38.6 16.5 37.4Q10 36.8 4 33Z\"/><path d=\"M22 30.6V27.8H42L46 29.2L42 30.6\"/><g transform=\"rotate(-22 34 16)\"><path d=\"M29 9H39V22H29Z\"/><path d=\"M39 13.6H58.5Q61 15.5 58.5 17.4H39\"/></g><path d=\"M27.5 25.4 23.4 22.2M30.4 23.4 29.4 19M39.2 24.4 43.2 21.2\"/>",
        "hatch": "<path d=\"M17.5 33.2H54M37 40.6V46M39.5 39.8V46M17 50.6H47M2 53.5H14.5M49.5 53.5H62M6 53.5l1.2-3 1 3 1.4-2.4.8 2.4M55 53.5l1.2-2.6 1 2.6 1.2-3 .9 3\"/><g transform=\"rotate(-22 34 16)\"><path d=\"M29 11.6H39M29 19.4H39M44 15.5H55\"/></g><circle cx=\"21.6\" cy=\"25.6\" r=\".5\"/><circle cx=\"45\" cy=\"24.2\" r=\".5\"/>",
        "small": "<path d=\"M4 33Q11 31 18 31H54V37H48Q43 38.5 42 44V48H50V54H14V48H22V44Q21 38.5 17 37.5Q10 37 4 33Z\"/><g transform=\"rotate(-22 34 16)\"><path d=\"M28 7H40V22H28Z\"/><path d=\"M40 15.5H60\"/></g>"
      },
      "methodology": {
        "line": "<path d=\"M12 8H44Q46 8 46 10V52Q46 54 44 54H12Z\"/><path d=\"M46 11L52 16V57.5Q52 59.5 50 59.5H18L12.5 54.5\"/><path d=\"M12 16Q9.6 17.5 12 19M12 29Q9.6 30.5 12 32M12 42Q9.6 43.5 12 45\"/><circle cx=\"28.5\" cy=\"30\" r=\"9.5\"/><g transform=\"rotate(26 28.5 28)\"><path d=\"M28.5 22.6V33.6M25.8 25.2H31.2\"/><circle cx=\"28.5\" cy=\"21.4\" r=\"1.1\"/></g><path d=\"M23 37 24.4 33.6 27.6 32.4 31 32.8 33.6 34.6 34.4 37Z\"/><path d=\"M40.5 26.5H46V33.5H40.5Z\"/><path d=\"M46 27L52 32M46 33L52 38\"/>",
        "hatch": "<path d=\"M16 12H42V50H16Z\"/><path d=\"M12 13.5L17.5 8M40.5 8L46 13.5M12 48.5L17.5 54M40.5 54L46 48.5\"/><path d=\"M47.6 13.4V55.6M49.8 15.4V57.4M15.2 56.2H46.4M17 58H48.6\"/><path d=\"M27.4 33 28.4 35 27.6 37M31.2 33.2 30.6 35.2M43.2 28V32\"/>",
        "small": "<path d=\"M12 8H46V54H12Z\"/><path d=\"M46 11L52 16V59.5H18L12 54\"/><circle cx=\"28.5\" cy=\"30\" r=\"9.5\"/><path d=\"M40.5 26H46V34H40.5Z\"/>"
      }
    },
    "pen": {
      "skill": {
        "tf": "rotate(35 32 32)",
        "line": "<path d=\"M30.8 6Q32 3.4 33.2 6L34 35.4H30Z\"/><path d=\"M29.6 35.4H34.4V38.6H29.6Z\"/><path d=\"M30 38.6 30.6 44H33.4L34 38.6\"/><path d=\"M30.6 44Q28.8 50.5 32 58.6Q35.2 50.5 33.4 44Z\"/><path d=\"M32 50.6V57\"/><circle cx=\"32\" cy=\"49.2\" r=\".9\"/>",
        "hatch": "<path d=\"M32.6 9V31M31.2 12V24\"/><path d=\"M29.6 37H34.4\"/><path d=\"M30.3 46.2Q31.2 47.6 31.5 52M33.7 46.2Q32.8 47.6 32.5 52\"/>",
        "small": "<path d=\"M32 4V37M28.4 38H35.6\"/><path d=\"M28.6 42L32 59L35.4 42Z\"/>"
      },
      "skillset": {
        "line": "<path d=\"M17 34H47V37.5H17Z\"/><path d=\"M18.6 37.5H45.4L43.8 57.6Q43.6 59.6 41.6 59.6H22.4Q20.4 59.6 20.2 57.6Z\"/>\n      <path d=\"M30.5 34V16H33.5V34\"/><path d=\"M30.5 16L31.4 5.2L32 4L32.6 5.2L33.5 16\"/><circle cx=\"35.2\" cy=\"11\" r=\"1.3\"/><path d=\"M33 11H33.9\"/>\n      <g transform=\"rotate(-14 24 34)\"><path d=\"M21.8 34V10H26.2V34\"/><path d=\"M21.8 10L24 3.6L26.2 10\"/></g>\n      <g transform=\"rotate(14 40 34)\"><path d=\"M38.4 34L38.2 14H41.8L41.6 34\"/><path d=\"M38.6 14Q38 9 40 3Q42 9 41.4 14Z\"/></g>\n      <path d=\"M4 61.5H60\"/>",
        "hatch": "<path d=\"M19.6 44H44.4M19.9 47H44.1\"/><path d=\"M32 6.6V13.6\"/><g transform=\"rotate(-14 24 34)\"><path d=\"M24 10V34M23.3 5.6 24.7 5.6\"/></g><g transform=\"rotate(14 40 34)\"><path d=\"M40 4.6V11\"/></g><path d=\"M8 61.5V59.6M12 61.5V60.4M16 61.5V60.4M20 61.5V59.6M44 61.5V59.6M48 61.5V60.4M52 61.5V60.4M56 61.5V59.6\"/>",
        "small": "<path d=\"M18 36H46L44 59H20Z\"/><path d=\"M32 36V4M32 6L32 4\"/><g transform=\"rotate(-14 24 36)\"><path d=\"M24 36V5\"/></g><g transform=\"rotate(14 40 36)\"><path d=\"M40 36V5\"/></g>"
      },
      "method": {
        "line": "<path d=\"M4 52H60L56 59H8Z\"/>\n      <circle cx=\"31.6\" cy=\"9.6\" r=\"3.2\"/><path d=\"M30.6 6.6V2.6H32.6V6.6\"/>\n      <path d=\"M29.6 12 32 12.9 20.2 48.6 18.6 52.4 18.4 48.4Z\"/>\n      <path d=\"M33.2 12.4 31.4 13.2 42.4 44H45.4Z\"/><path d=\"M42.2 44H45.6L45 47.8H42.8Z\"/><path d=\"M43.2 47.8 44 51 44.8 47.8\"/>\n      <path d=\"M48 31.5 60 50.5H48Z\"/><path d=\"M50.6 39 55.6 47.8H50.6Z\"/>",
        "hatch": "<path d=\"M44 51Q38.5 56.6 28.6 56.8Q22.6 56.8 18.6 55.4\" stroke-dasharray=\"1.6 1.6\"/><path d=\"M16.2 52.4H21M18.6 50.2V54.6\"/><path d=\"M48 50.5V48.8M51 50.5V49.2M54 50.5V49.2M57 50.5V48.8\"/><path d=\"M8.8 55.5H22M36 55.5H55\"/><path d=\"M27.5 18.5 22.6 36M35 18.5 39.8 33\"/><circle cx=\"31.6\" cy=\"9.6\" r=\".9\"/>",
        "small": "<path d=\"M4 53H60\"/><circle cx=\"32\" cy=\"9\" r=\"3.4\"/><path d=\"M30.6 12 19 52M33.4 12 44 51\"/><path d=\"M48 32 60 51H48Z\"/>"
      },
      "methodology": {
        "line": "<path d=\"M8 10H56V50H8Z\"/><path d=\"M8 50 10 54H58L56 50\"/><path d=\"M58 54V14L56 10\"/><path d=\"M14 54 10.5 62M50 54 53.5 62\"/>\n      <path d=\"M15 14H45V34H15Z\"/><path d=\"M4.5 33H9V45H4.5Z\"/><path d=\"M9 37.6H52.5V41H9\"/>\n      <path d=\"M24 17.4H36V30.6H24Z\"/><circle cx=\"30\" cy=\"24\" r=\"6\"/><path d=\"M24 17.4 36 30.6M36 17.4 24 30.6\"/>",
        "hatch": "<circle cx=\"15\" cy=\"14\" r=\".9\"/><circle cx=\"45\" cy=\"14\" r=\".9\"/><circle cx=\"15\" cy=\"34\" r=\".9\"/><circle cx=\"45\" cy=\"34\" r=\".9\"/><path d=\"M17.6 19H21.4M17.6 22H21.4M38.6 26H42.4M38.6 29H42.4\"/><path d=\"M14 37.6V39M18 37.6V38.6M22 37.6V39M26 37.6V38.6M30 37.6V39M34 37.6V38.6M38 37.6V39M42 37.6V38.6M46 37.6V39\"/><path d=\"M48 14V34M51.5 16V33M11 44H52\"/>",
        "small": "<path d=\"M8 10H56V50H8Z\"/><path d=\"M15 14H45V34H15Z\"/><path d=\"M5 39H52\"/><circle cx=\"30\" cy=\"24\" r=\"6.4\"/>"
      }
    }
  } as const

export type WoodSet = keyof typeof WOOD_MARKS
export type WoodKind = keyof typeof WOOD_MARKS.blade
export type WoodState = 'whole' | 'outline' | 'warn'

/** The two sets' marks differ in shape (some carry a transform, some do
 * not); the WoodMark view makes 'tf' optional so renderWood reads both. */
export interface WoodMark {
  readonly tf?: string
  readonly line: string
  readonly hatch: string
  readonly small: string
}

export function isWoodKind(candidate: string): candidate is WoodKind {
  return Object.prototype.hasOwnProperty.call(WOOD_MARKS.blade, candidate)
}

export function renderWood(kind: WoodKind, size = 16, state: WoodState = 'whole', set: WoodSet = 'blade'): string {
  const g: WoodMark = WOOD_MARKS[set][kind]
  const small = size <= 20
  const sw = size >= 64 ? 1.35 : size >= 32 ? 1.15 : small ? 1.2 : 1.1
  const col = state === 'warn' ? 'var(--stall)' : 'currentColor'
  const body = small ? g.small : g.line + (size >= 28 ? `<g stroke-width="${(sw * .72).toFixed(2)}">${g.hatch}</g>` : '')
  return `<svg class="wood${state === 'outline' ? ' dim' : ''}" width="${size}" height="${size}" viewBox="0 0 64 64" fill="none" stroke="${col}" stroke-width="${sw}" stroke-linecap="round" stroke-linejoin="round"><g${g.tf ? ` transform="${g.tf}"` : ''}>${body}</g></svg>`
}
