import {useEffect,useRef,useState} from 'react';
import {automationLeader,resolvedAutomation,automationGroups} from '../../../../desktop/cradle/expressions-app/field-studies-journeys/src/automationLinks';
import {automationTarget} from '../../../../desktop/cradle/expressions-app/field-studies-journeys/src/nativeParameters';
import type {AutomationLane} from '../../../../desktop/cradle/expressions-app/field-studies-journeys/src/model';
import {sameEditorBasis} from '../../../expressions-boundary/src/editor';
import type {NativeEditorBasis,NativeEditorReading,NativeEditorReply} from '../../../expressions-boundary/src/editor';
import type {InstrumentPresentation} from '../frame/presentation';
import {modulationPreview} from './preview';
import {modulationInputPatch,type ModulationInputs,type ModulationNumber} from './input';
import './modulation.css';
import {TargetRange} from './TargetRange';
export interface ModulationHost {reading:NativeEditorReading;edit:(basis:NativeEditorBasis,laneId:string,values:Partial<AutomationLane>)=>Promise<NativeEditorReply>;command?:(basis:NativeEditorBasis,command:'fire'|'detach'|'remove'|'add-target',laneId:string)=>Promise<NativeEditorReply>}
export interface ModulationEditorProps {host:ModulationHost;laneId:string;depth:'compact'|'full';visible?:boolean;presentation:InstrumentPresentation}
/** Graph is an authored source preview. Effective target values are read from
 * native telemetry, never inferred from the preview or a duplicate clock. */
export function ModulationEditor(props:ModulationEditorProps){
 const target=props.presentation.snapshot().target;
 const held=useRef<NativeEditorReading|null>(null);
 const matches=(basis:NativeEditorBasis)=>Boolean(target.sceneRef)&&basis.expression_ref===target.subjectRef&&basis.scene_ref===target.sceneRef;
 const bound=matches(props.host.reading.basis);
 if(bound)held.current=props.host.reading;
 const reading=held.current&&matches(held.current.basis)?held.current:null;
 if(!reading)return <p role="status">Select the pinned native Scene to open its Modulation editor. This instance remains on {target.sceneRef??target.subjectRef}.</p>;
 const guard=(basis:NativeEditorBasis)=>{if(!matches(basis)||!matches(props.host.reading.basis))throw Error('Select the pinned native Scene before editing this Modulation instance. Pending input remains on its original binding.');};
 const host:ModulationHost={reading,edit:async(basis,id,values)=>{guard(basis);return props.host.edit(basis,id,values);},...(props.host.command?{command:async(basis:NativeEditorBasis,command:'fire'|'detach'|'remove'|'add-target',id:string)=>{guard(basis);return props.host.command!(basis,command,id);}}:{})};
 return <>{!bound&&<p role="status">Select the pinned native Scene to continue this Modulation edit. Pending input remains on {target.sceneRef}.</p>}<fieldset disabled={!bound} style={{border:0,padding:0,margin:0,minWidth:0,pointerEvents:bound?'auto':'none'}}><ModulationBody key={`${target.instanceRef}:${target.subjectRef}:${target.sceneRef}:${props.laneId}`} {...props} host={host}/></fieldset></>;
}
function ModulationBody({host,laneId,depth,visible=true,presentation}:ModulationEditorProps){
 const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const gesture=useRef<'phase'|'min'|'max'>();
 const {reading}=host;const readingBasisKey=JSON.stringify(reading.basis);const lane=reading.scene.automation.find(value=>value.id===laneId);const resolved=lane?resolvedAutomation(reading.scene.automation,lane):undefined;const leader=lane?automationLeader(reading.scene.automation,lane):undefined;
 const initial=presentation.snapshot().view;
 const [inputs,setInputs]=useState<ModulationInputs>((initial.inputs as ModulationInputs)??{});
 const [draft,setDraft]=useState<Partial<AutomationLane>>((initial.draft as Partial<AutomationLane>)??{});const [basis,setBasis]=useState<NativeEditorBasis>((initial.basis as NativeEditorBasis)??reading.basis);const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
 const dirty=Object.keys(draft).length>0||Object.keys(inputs).length>0;
 if(basis.expression_ref!==reading.basis.expression_ref||basis.scene_ref!==reading.basis.scene_ref)throw Error('The retained modulation input belongs to another native Scene.');
 useEffect(()=>{presentation.setDraft(dirty||busy);presentation.updateView({...presentation.snapshot().view,draft,inputs,basis});if(!dirty&&!busy&&!sameEditorBasis(basis,reading.basis))setBasis(reading.basis);},[draft,inputs,basis,readingBasisKey,presentation,busy,dirty]);
 if(lane?.syncWith||!lane||!resolved||!leader)return <section hidden={!visible}><p role="status">{lane?.syncWith?`This target now follows native source ${leader?.id}. Open that source to edit its modulation group.`:`The bound native modulation source ${laneId} is unavailable in this Scene.`}</p>{dirty&&<div><p>Retained source input on {basis.scene_ref}, revision {basis.revision}</p><pre>{JSON.stringify({inputs,draft},null,2)}</pre><button disabled={busy} onClick={()=>{setInputs({});setDraft({});setBasis(reading.basis);presentation.setDraft(false);}}>Cancel input</button></div>}<RetainedTargetInputs presentation={presentation} available={[]}/></section>;
 let displayPatch=draft;let inputError='';try{displayPatch=modulationInputPatch(draft,inputs);}catch(error){inputError=String(error);}
 const source={...resolved,...displayPatch};const target=automationTarget(reading.scene,lane.target);const group=automationGroups(reading.scene.automation).find(group=>group.leader.id===leader.id);
 const set=(key:keyof AutomationLane,value:unknown)=>{if(busy)return;presentation.setDraft(true);setDraft(current=>({...current,[key]:value}));};
 const input=(key:ModulationNumber,value:string)=>{if(busy)return;presentation.setDraft(true);setInputs(current=>({...current,[key]:value}));};
 const number=(key:ModulationNumber,label:string)=><label>{label}<input aria-label={`Modulation ${key}`} inputMode="decimal" disabled={busy} value={inputs[key]??String(source[key])} onChange={event=>input(key,event.target.value)}/></label>;
 const cancel=()=>{if(busy)return;setDraft({});setInputs({});setBasis(reading.basis);presentation.setDraft(false);};
 let preview:ReturnType<typeof modulationPreview>|undefined;let previewError='';try{preview=modulationPreview(reading.scene,laneId,displayPatch);}catch(error){previewError=String(error);}
 const points=preview?.samples.map((point,index)=>`${index/Math.max(1,preview!.samples.length-1)*480},${100-point.normalized*80}`).join(' ')??'';
 const commit=async()=>{if(busy)return;presentation.setDraft(true);setBusy(true);setNotice('');try{const patch=modulationInputPatch(draft,inputs);const reply=await host.edit(basis,laneId,patch);if(!mounted.current)return;if(!reply.ok)throw Error(reply.error);if(reply.reading.basis.expression_ref!==basis.expression_ref||reply.reading.basis.scene_ref!==basis.scene_ref||reply.reading.basis.revision<basis.revision||reply.reading.basis.authored_revision<basis.authored_revision)throw Error('The native reply addressed another or older source. The draft is retained.');const after=reply.reading.scene.automation.find(row=>row.id===laneId);const effective=after?resolvedAutomation(reply.reading.scene.automation,after):undefined;if(!effective||Object.entries(patch).some(([key,value])=>JSON.stringify(effective[key as keyof AutomationLane])!==JSON.stringify(value)))throw Error('The native source differs from this input. The draft is retained for inspection.');setDraft({});setInputs({});setBasis(reply.reading.basis);setNotice('Native modulation source readback confirmed.');}catch(e){if(mounted.current)setNotice(String(e));}finally{if(mounted.current)setBusy(false);}};
 const command=async(action:'fire'|'detach'|'remove'|'add-target')=>{if(!host.command||busy||dirty)return;presentation.setDraft(true);setBusy(true);try{const reply=await host.command(reading.basis,action,laneId);if(!mounted.current)return;if(!reply.ok)throw Error(reply.error);if(reply.reading.basis.expression_ref!==reading.basis.expression_ref||reply.reading.basis.scene_ref!==reading.basis.scene_ref)throw Error('The command reply addressed another native Scene.');}catch(e){if(mounted.current)setNotice(String(e));}finally{if(mounted.current)setBusy(false);}};
 return <section className="instrument-modulation" hidden={!visible} data-depth={depth} aria-label="Modulation editor" aria-busy={busy}>
 <div className="instrument-toolbar"><strong>{source.type==='ramp'?'One-shot':'Modulation'}</strong><span title={lane.target}>{target?.label??lane.target}</span><output>Effective: {reading.observation?.effectiveValues?.[lane.target]??'No native telemetry'}</output>{depth==='compact'&&<button onClick={()=>presentation.setDepth('full')}>Edit source</button>}</div>
 {points?<svg className="modulation-curve" viewBox="0 0 480 120" role="group" aria-label={`${source.wave} authored source preview`} onPointerMove={event=>{if(!gesture.current||busy)return;const box=event.currentTarget.getBoundingClientRect();if(gesture.current==='phase')input('phase',String(Math.max(0,Math.min(1,(event.clientX-box.left)/box.width))));else if(target)input(gesture.current,String(target.min+(1-Math.max(0,Math.min(1,(event.clientY-box.top)/box.height)))*(target.max-target.min)));}} onPointerUp={event=>{gesture.current=undefined;event.currentTarget.releasePointerCapture(event.pointerId);}} onPointerCancel={()=>{gesture.current=undefined;}}><path d="M0 100H480M0 20H480M0 60H480" stroke="#686b71" fill="none"/><polyline points={points} fill="none" stroke="#ffbe00" strokeWidth="2"/>{(['phase','min','max'] as const).filter(key=>key==='phase'||target).map((key,index)=><circle key={key} className="modulation-handle" cx={key==='phase'?((source.phase%1+1)%1)*480:465} cy={key==='phase'?108:index===1?96:24} r={6} tabIndex={0} role="slider" aria-label={`Modulation ${key} handle`} aria-valuenow={source[key]} onPointerDown={event=>{if(busy)return;event.preventDefault();gesture.current=key;event.currentTarget.ownerSVGElement?.setPointerCapture(event.pointerId);}} onKeyDown={event=>{if(!['ArrowLeft','ArrowDown','ArrowRight','ArrowUp'].includes(event.key)||busy)return;event.preventDefault();input(key,String(source[key]+(['ArrowLeft','ArrowDown'].includes(event.key)?-1:1)*(key==='phase'?.01:target?.step??.01)*(event.shiftKey?10:1)));}}/>)}<text x="8" y="115">Authored source · effective values from native telemetry</text></svg>:<div className="modulation-source">{previewError||preview?.reason||'The native preview is unavailable.'}</div>}
 <div className="instrument-toolbar">{number('rate','Rate Hz')}{number('phase','Phase cycles')}<label><input type="checkbox" checked={source.enabled} onChange={event=>set('enabled',event.target.checked)}/>Run</label><button disabled={!dirty||busy} onClick={()=>void commit()}>Apply</button>{dirty&&<button disabled={busy} onClick={cancel}>Cancel input</button>}</div>
 {depth==='full'&&<fieldset disabled={busy} className="modulation-depth"><section><h3>Source</h3><label>Kind<select value={source.type} onChange={event=>set('type',event.target.value)}><option value="lfo">Oscillator</option><option value="ramp">One-shot</option></select></label>{source.type==='lfo'?<label>Wave<select value={source.wave} onChange={event=>set('wave',event.target.value)}>{['sine','triangle','square','saw','steps','smooth','morph'].map(wave=><option key={wave}>{wave}</option>)}</select></label>:<>{number('duration','Duration seconds')}{number('delay','Delay seconds')}<label>Repeat<select value={source.loop} onChange={event=>set('loop',event.target.value)}>{['once','loop','pingpong'].map(loop=><option key={loop}>{loop}</option>)}</select></label><label>Easing<select value={source.easing??'smooth'} onChange={event=>set('easing',event.target.value)}>{['linear','smooth','easeIn','easeOut','elastic','bounce'].map(easing=><option key={easing}>{easing}</option>)}</select></label></>}</section><section><h3>Targets</h3>{group?.targets.map(row=><article key={row.id}><strong>{automationTarget(reading.scene,row.target)?.label??row.target}</strong><code>{row.target}</code><output>{reading.observation?.effectiveValues?.[row.target]??'No native telemetry'}</output>{row.id===laneId&&<>{number('min','Low / From')}{number('max','High / To')}<label>Blend<select value={source.blend} onChange={event=>set('blend',event.target.value)}>{['replace','add','multiply'].map(blend=><option key={blend}>{blend}</option>)}</select></label></>}{row.id!==laneId&&<TargetRange host={host} lane={row} presentation={presentation}/>}</article>)}{host.command&&<div className="instrument-toolbar"><button disabled={dirty||busy} onClick={()=>void command('add-target')}>Add parameter</button>{lane.syncWith&&<button disabled={dirty||busy} onClick={()=>void command('detach')}>Make independent</button>}{source.type==='ramp'&&<button disabled={dirty||busy} onClick={()=>void command('fire')}>Restart</button>}</div>}</section></fieldset>}
 <RetainedTargetInputs presentation={presentation} available={(group?.targets??[]).map(row=>row.id)}/>
 {inputError&&<p role="alert">{inputError}</p>}{notice&&<p role="status">{notice}</p>}
 </section>;
}
/** A removed native target must not strand its retained input or draft guard. */
function RetainedTargetInputs({presentation,available}:{presentation:InstrumentPresentation;available:string[]}){
 const retained=(presentation.snapshot().view.modulationTargets??{}) as Record<string,{basis:NativeEditorBasis;inputs:ModulationInputs;patch:Partial<AutomationLane>}>;
 const orphaned=Object.entries(retained).filter(([id,value])=>!available.includes(id)&&(Object.keys(value.inputs??{}).length||Object.keys(value.patch??{}).length));
 if(!orphaned.length)return null;
 return <section aria-label="Retained target input"><h3>Retained target input</h3>{orphaned.map(([id,value])=><article key={id}><p>The native target {id} is no longer in this modulation group. This input remains on {value.basis.scene_ref}, revision {value.basis.revision}.</p><pre>{JSON.stringify({inputs:value.inputs,patch:value.patch},null,2)}</pre><button onClick={()=>{const view=presentation.snapshot().view,targets={...(view.modulationTargets as typeof retained)};delete targets[id];presentation.setDraft(false,`modulation-target:${id}`);presentation.updateView({...view,modulationTargets:targets});}}>Discard retained range {id}</button></article>)}</section>;
}
