/** Development receiving entrance over the same production authoring owners.
 * Only this lane's controlled native acceptance Expressions are admitted. */
import {kernelOp} from '../../../desktop/cradle/src/kernel/bridge';
import type {KernelOp,KernelTransportStatus} from '../../../desktop/cradle/src/kernel/types';
import {NativeWorking} from '../../../desktop/cradle/expressions-app/field-studies-journeys/src/nativeWorking';
import {DocumentStore} from '../../../desktop/cradle/expressions-app/field-studies-journeys/src/store';
import {createRetainedNativeEditor} from '../../../desktop/cradle/expressions-app/field-studies-journeys/src/hostEditor';
import {sameEditorBasis,type NativeEditorRequest,type NativeEditorReply} from '../../expressions-boundary/src/editor';
import {modulationOwnerPort} from '../src/receiving/modulationOwner';
import {prepareCompositionEdit} from '../../../desktop/cradle/expressions-app/field-studies-journeys/src/kernelComposition';
import {openNativeWorkbench,acknowledgeWorkbenchComposition,nativeWorkbenchJournal} from './nativeRecovery';
export async function nativeWorkbench(transport:KernelTransportStatus,ref:string,publish:()=>void,openSource:(value:unknown)=>void){
 if(!/^expression:(modulation-editor|instrument-editor|instrument-member|research-editor)-[a-f0-9-]+$/.test(ref))throw Error('This entrance admits only this lane’s controlled native test Expressions.');
 const call=async(op:Record<string,unknown>)=>{const result=await kernelOp(transport,op as KernelOp,AbortSignal.timeout(30000));if(result.error||!result.outcome||!('data' in result.outcome))throw Error(result.error??'The owner omitted its native data');return result.outcome.data as any;};
 const expression=(request:Record<string,unknown>)=>call({op:'expression',request});
 const journal=await nativeWorkbenchJournal(ref,request=>call({op:'expression_recovery',request}));
 const work=new NativeWorking({expression,file:request=>call({op:'expression_file',request}),mint:()=>ref,checkpoint:journal.checkpoint});
 const view=await openNativeWorkbench(work,ref,async()=>journal.value,async()=>(await expression({operation:'inspect',expression_ref:ref})).document),store=new DocumentStore(view.journey);
 let receiving:object|null=null;
 const leased=async<T>(operation:()=>Promise<T>):Promise<T>=>{if(receiving||work.busy)throw Error('The native receiver already has an operation awaiting acknowledgement.');const lease={};receiving=lease;publish();try{return await operation();}finally{if(receiving===lease)receiving=null;publish();}};
 const pending=work.state?.pending,submitted=pending&&(pending.kind==='edit'||pending.kind==='create')?pending.submitted:null;
 let sceneId=submitted&&view.bindings[submitted.sceneId]?submitted.sceneId:view.startSceneId;
 const admitted=(id:string|null)=>!!id&&!!sceneId&&view.bindings[sceneId]?.occurrences.some(row=>row.view_entity_id===id)&&store.document.scenes.find(scene=>scene.id===sceneId)?.entities.some(entity=>entity.id===id);
 const nativeSelected=view.document.selection?.scene_ref===view.bindings[sceneId??'']?.scene_ref?view.entity_ids[view.document.selection.entity_ref??'']??null:null;
 let entityId=submitted?(admitted(submitted.entityId)?submitted.entityId:null):(admitted(nativeSelected)?nativeSelected:null),stepId:string|null=null;
 const requireSceneId=()=>{if(!sceneId)throw Error('This native work has no selected Scene. Compose or select a native Scene first.');return sceneId;};
 const snapshot=()=>({journey:store.document,sceneId:requireSceneId(),entityId});
 const owner:Parameters<typeof createRetainedNativeEditor>[0]={store,sceneId:requireSceneId,nativeView:()=>work.state?.view,selection:()=>({entity_ids:entityId?[entityId]:[],step_id:stepId}),
  change:mutate=>{store.change(()=>mutate());publish();},commit:async()=>{await work.commit(snapshot());publish();return true;},standing:()=>({busy:work.busy,notice:null}),telemetry:()=>undefined,fieldPaused:()=>true,
  nativeSelect:async(id,entity)=>{const native=work.state?.view,binding=native?.bindings[id];const ref=Object.entries(native?.entity_ids??{}).find(([,value])=>value===entity)?.[0];if(!binding||(entity!==null&&!ref))throw Error('The native owner has no exact occurrence for this selection.');await work.select({scene_ref:binding.scene_ref,entity_ref:ref??null});publish();return 'applied';},
  selectLocal:(id,index)=>{entityId=id;stepId=store.document.scenes.find(scene=>scene.id===sceneId)?.entities.find(entity=>entity.id===id)?.sequence.steps[index]?.id??null;publish();},
  openEditor:(_kind,id,index)=>{openSource({native_scene:work.state?.view?.bindings[requireSceneId()],entity:store.document.scenes.find(scene=>scene.id===sceneId)?.entities.find(entity=>entity.id===id),step_index:index});},afterHistory:publish};
 const raw=createRetainedNativeEditor(owner),rawEdit=modulationOwnerPort(owner);
 const receiver:typeof raw={...raw,read:()=>{const reading=raw.read();return {...reading,standing:{...reading.standing,pending:reading.standing.pending||!!receiving}};},apply:request=>leased(()=>raw.apply(request)),select:request=>leased(()=>raw.select(request)),selectField:request=>leased(()=>raw.selectField(request)),scene:(request,current)=>leased(()=>raw.scene(request,current)),open:request=>leased(()=>raw.open(request)),history:operation=>leased(()=>raw.history(operation)),save:()=>leased(()=>raw.save()),...(raw.material?{material:(request:Parameters<NonNullable<typeof raw.material>>[0])=>leased(()=>raw.material!(request))}:{})};
 const edit:typeof rawEdit=async(...args)=>{try{return await leased(()=>rawEdit(...args));}catch(error){return {ok:false,error:String(error),reading:receiver.read()};}};
 const request=async(request:NativeEditorRequest):Promise<NativeEditorReply>=>{try{if(request.operation!=='read'){if(!sameEditorBasis(request.basis,receiver.read().basis))throw Error('The captured native editor basis changed.');switch(request.operation){case 'apply':await receiver.apply(request);break;case 'select':await receiver.select(request);break;case 'select-field':await receiver.selectField(request);break;case 'scene':await receiver.scene(request);break;case 'open':await receiver.open(request);break;case 'undo':case 'redo':await receiver.history(request.operation);break;case 'save':await receiver.save();break;case 'material':if(!receiver.material)throw Error('The native owner has no material receiving port.');await receiver.material(request);break;default:throw Error('Unsupported native editor operation.');}}publish();return {ok:true,reading:receiver.read()};}catch(error){return {ok:false,error:String(error),reading:receiver.read()};}};
 const readExpression=async(ref:string)=>(await expression({operation:'inspect',expression_ref:ref})).document;
 return {work,store,receiver,edit,request,readExpression,sceneId:()=>sceneId,selectScene:(ref:string)=>leased(async()=>{const native=work.state?.view,id=Object.keys(native?.bindings??{}).find(id=>native!.bindings[id].scene_ref===ref);if(!id)throw Error('The selected Scene is outside this native work.');if(store.transactionOpen)throw Error('Finish the current native gesture before opening another Scene.');const formation=store.document.scenes.find(scene=>scene.id===id)?.entities.find(entity=>entity.kind==='formation');const occurrence=native!.bindings[id].occurrences.find(row=>row.view_entity_id===formation?.id);await work.select({scene_ref:ref,entity_ref:occurrence?.entity_ref??null});sceneId=id;entityId=occurrence?.view_entity_id??null;stepId=null;publish();}),
  palaceHost:{nativeView:()=>work.state?.view,sceneId:requireSceneId,authoredRevision:()=>store.revision,
   canCompose:()=>{const basis=work.state?.view;if(!basis||receiving||work.busy||store.transactionOpen||work.state?.pending)return false;try{return prepareCompositionEdit(basis,store.document).changes.length===0;}catch{return false;}},readExpression,listExpressions:async()=>{const data=await expression({operation:'list'});return (data.expressions??[]).filter((value:{expression_ref:string})=>/^expression:(modulation-editor|instrument-editor|instrument-member)-/.test(value.expression_ref));},
   composeExpression:(input:any)=>leased(async()=>{const basis=work.state?.view;if(input.expression_ref!==ref||!basis||store.transactionOpen||work.state?.pending||prepareCompositionEdit(basis,store.document).changes.length)throw Error('Finish the retained native work before composing its Palace.');
    const result=await expression({operation:'edit',...input,actor:'agent:instrument-editor-native-test'});if(result.state!=='ready')return {ok:false as const,reason:result.state};const advanced=await acknowledgeWorkbenchComposition(work,store,result.document);if(!sceneId||!advanced.bindings[sceneId]){sceneId=advanced.startSceneId;entityId=null;stepId=null;}return {ok:true as const,document:result.document};}),openExpression:(ref:string)=>{void readExpression(ref).then(openSource,error=>openSource({error:String(error)}));}}};
}
