import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import path from 'node:path';
import {readFileSync,mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {pathToFileURL} from 'node:url';
const root=process.env.OI_STAGE_APP_ROOT??path.resolve(import.meta.dirname,'..'),proposal=process.env.OI_STAGE_STUDIO_PROPOSAL,sourceRoot=process.env.OI_STAGE_SOURCE_ROOT;
const built=await build({absWorkingDir:root,stdin:{contents:`export * from './src/proceduralStageSource';export * from './src/proceduralStageProvider';export {blankScene,entity,clone} from './src/model';export {kernelDocumentToJourney} from './src/kernelDocumentBridge';export {studioBasis,componentAddresses,scopeContains} from './src/proceduralStudio';`,resolveDir:root},plugins:[{name:'actual-qualified-Stage-Studio-source',setup(b){b.onLoad({filter:/[/]procedural(?:Studio|Stage|StageSource|StageProvider)\.ts$/},args=>{const file=path.basename(args.path),replacement=file==='proceduralStudio.ts'?proposal:sourceRoot?path.join(sourceRoot,file):null;return replacement?{contents:readFileSync(replacement,'utf8'),loader:'ts',resolveDir:path.join(root,'src')}:undefined;});}}],bundle:true,write:false,format:'esm',platform:'node',target:'es2022',nodePaths:[path.resolve(root,'../node_modules')]});
const compiledDir=mkdtempSync(path.join(tmpdir(),'oi-stage-domain-')),compiledPath=path.join(compiledDir,'actual-stage-domain.mjs');writeFileSync(compiledPath,built.outputFiles[0].text);const api=await import(pathToFileURL(compiledPath).href);test.after(()=>rmSync(compiledDir,{recursive:true,force:true}));
// Actual authored material, native converter and ParameterRegistry. These
// tests do not replace a native owner port or manufacture source/ACK receipts.
function authoring(){
 const ref='expression:stage-functional',scene=api.blankScene('Source stage');scene.id=ref+':scene:first';const e=api.entity('Force subject','A');e.id=ref+':entity:a';scene.entities=[e];
 const document={schema:'oi.expression/v1',expression_ref:ref,revision:4,title:'Actual authored domain test',scenes:[{scene_ref:scene.id,revision:4,title:scene.name,entity_refs:[e.id],presentation:{schema:'oi.journey-scene/v1',scene,saved:null}}],entities:{[e.id]:{entity_ref:e.id,revision:4,title:e.name,subject:{subject_ref:'subject:continuing',native_owner:'ql',sources:[],readings:[],actions:[],presentation_role:'thing'},parameters:{glyph:{value:e.text},kind:{value:e.kind}}}},relations:{},selection:{scene_ref:scene.id,entity_ref:e.id},provenance:[],representations:[],refinements:[]};
 const view=api.kernelDocumentToJourney(document),journey=api.clone(view.journey);return {view,journey,sceneId:journey.scenes[0].id,selected:[journey.scenes[0].entities[0].id]};
}
// These are the exact supported library domain declarations, independently
// compared to the source-owned native library below. No discovery result or
// availability/compiled producer is pretended to have executed.
const force={recipe:'force_parameters',label:'Selected force parameters',native_operations:['parameter_set'],parameters:[{key:'force_strength',minimum:-20,maximum:20},{key:'force_spin',minimum:-20,maximum:20},{key:'force_radius',minimum:1,maximum:1600}]};
test('actual existing registry converts authored force radius exactly once at the native library boundary',()=>{
 const snapshot=authoring(),scope={kind:'expression'},rows=api.stageForceParameters(snapshot,force,scope),radius=rows.find(row=>row.parameter==='force_radius');assert.ok(radius);assert.equal(radius.factor,400);assert.equal(radius.minimum,.0125,'actual registry hardMin 5 native units remains stricter than recipe minimum 1');assert.equal(radius.maximum,4);assert.equal(radius.address.entity_ref,snapshot.view.bindings[snapshot.sceneId].occurrences[0].entity_ref);assert.equal(radius.units,'stage units');
 const before=api.clone(snapshot),choice=api.stageForceChoice(snapshot,force,scope,radius.target,.5,'retained-radius');assert.deepEqual(choice,{recipe:'force_parameters',writes:[{output_slot:'retained-radius',parameter:'force_radius',value:{value_source:'constant',value:200}}]});assert.deepEqual(snapshot,before);
 const command=api.stageForceCommandTarget(snapshot,force,{kind:'scenes',scene_refs:[radius.address.scene_ref]},radius.target);assert.deepEqual(command.property_keys,['force_radius']);assert.deepEqual(command.scope,{kind:'addresses',addresses:[radius.address]});assert.deepEqual(api.resolvedSourceReadAddresses(snapshot,command.scope),command.scope.addresses,'native read and write retain the same scalar coordinates');assert.equal(api.scopeContains(command.scope,{...radius.address,property:'strength'},snapshot),false);assert.equal(api.scopeContains(command.scope,{...radius.address,component:'entity',property:null},snapshot),false);
});
test('actual force producer refuses wrong native occurrence, out-of-scope field and mismatched registry bounds',()=>{
 const snapshot=authoring(),rows=api.stageForceParameters(snapshot,force,{kind:'expression'}),radius=rows.find(row=>row.parameter==='force_radius');
 const foreign={kind:'addresses',addresses:[{...radius.address,entity_ref:'expression:wrong-prime:entity'}]};assert.equal(api.stageForceParameters(snapshot,force,foreign).length,0);assert.throws(()=>api.stageForceChoice(snapshot,force,foreign,radius.target,.5,'radius'),/scope|registry/);
 const field={kind:'addresses',addresses:[{...radius.address,component:'field',entity_ref:null,property:null}]};assert.equal(api.stageForceParameters(snapshot,force,field).length,0);
 assert.throws(()=>api.stageForceChoice(snapshot,force,{kind:'expression'},radius.target,4.001,'radius'),/registry/);assert.throws(()=>api.stageForceChoice(snapshot,force,{kind:'expression'},radius.target,.001,'radius'),/registry/);assert.throws(()=>api.stageForceChoice(snapshot,force,{kind:'expression'},radius.target,NaN,'radius'),/registry/);assert.throws(()=>api.stageForceChoice(snapshot,force,{kind:'expression'},radius.target,.5,''),/slot/);
});
test('actual whole Expression flow scope cannot be acquired from a selected Scene or constituent',()=>{
 const snapshot=authoring(),basis=api.studioBasis(snapshot),target=api.stageAtlasCommandTarget(snapshot,{kind:'expression'});assert.deepEqual(target.selector,{selector:'occurrences',refs:[basis.expression_ref]});assert.deepEqual(api.resolvedSourceReadAddresses(snapshot,target.scope),target.scope.addresses);assert.throws(()=>api.stageAtlasCommandTarget(snapshot,{kind:'scenes',scene_refs:[basis.scene_ref]}),/whole Expression/);assert.throws(()=>api.stageAtlasCommandTarget(snapshot,{kind:'addresses',addresses:[{...target.scope.addresses[0],component:'scene',scene_ref:basis.scene_ref}]}),/whole Expression/);
});
test('actual shared native Entity force retains every Scene location and refuses partial original authority',()=>{
 const initial=authoring(),document=api.clone(initial.view.document),first=document.scenes[0],second=api.clone(first);second.scene_ref=document.expression_ref+':scene:second';second.presentation.scene.id=second.scene_ref;second.title=second.presentation.scene.name='Second manifestation';document.scenes.push(second);const view=api.kernelDocumentToJourney(document),snapshot={view,journey:api.clone(view.journey),sceneId:view.journey.scenes[0].id,selected:[view.journey.scenes[0].entities[0].id]},radius=api.stageForceParameters(snapshot,force,{kind:'expression'}).find(row=>row.parameter==='force_radius');const before=api.clone(snapshot),command=api.stageForceCommandTarget(snapshot,force,{kind:'expression'},radius.target);assert.equal(command.scope.addresses.length,2);assert.deepEqual(command.scope.addresses.map(address=>address.scene_ref),[first.scene_ref,second.scene_ref]);assert.deepEqual(command.property_keys,['force_radius']);for(const address of command.scope.addresses){assert.equal(address.component,'force');assert.equal(address.property,'radius');assert.equal(api.scopeContains(command.scope,{...address,property:'strength'},snapshot),false);assert.equal(api.scopeContains(command.scope,{...address,component:'entity',property:null},snapshot),false);}assert.deepEqual(api.resolvedSourceReadAddresses(snapshot,command.scope),command.scope.addresses);assert.throws(()=>api.stageForceCommandTarget(snapshot,force,{kind:'scenes',scene_refs:[first.scene_ref]},radius.target),/outside the original force scope/);assert.throws(()=>api.stageForceCommandTarget(snapshot,force,{kind:'addresses',addresses:[command.scope.addresses[0]]},radius.target),/outside the original force scope/);
 const subject={kind:'subject',subject_ref:document.entities[first.entity_refs[0]].subject.subject_ref};assert.deepEqual(api.stageForceCommandTarget(snapshot,force,subject,radius.target),command);const subjectEntities=api.resolvedSourceReadAddresses(snapshot,subject);assert.equal(subjectEntities.length,2);assert.deepEqual(subjectEntities.map(address=>[address.scene_ref,address.entity_ref]),command.scope.addresses.map(address=>[address.scene_ref,address.entity_ref]),'Subject inspection keeps genuine Entity correspondence while the force write scope stays scalar');assert.deepEqual(snapshot,before);
});
test('source request keeps exact base/state parent and available profile, without graph or property defaults',()=>{
 const snapshot=authoring(),ref=snapshot.view.bindings[snapshot.sceneId].occurrences[0].entity_ref,base={expression_ref:snapshot.view.document.expression_ref,scene_ref:api.studioBasis(snapshot).scene_ref,entity_ref:ref,component:'layer',constituent_ref:'continuing-layer',parent_ref:null,property:null},state={...base,parent_ref:'exact-state'};
 const request=api.stageSourceRequest(snapshot,{kind:'addresses',addresses:[base,state]});assert.deepEqual(request.scope.addresses,[base,state]);assert.deepEqual(request.property_keys,[]);assert.equal(request.scene_profile,null);assert.equal(request.expected_revision,4);const omitted={...base};delete omitted.parent_ref;assert.throws(()=>api.stageSourceRequest(snapshot,{kind:'addresses',addresses:[omitted]}),/parent/);assert.throws(()=>api.stageSourceRequest(snapshot,{kind:'addresses',addresses:[{...base,expression_ref:'expression:wrong'}]}),/another Expression/);
 assert.throws(()=>api.stageSourceRequest(snapshot,{kind:'expression'},{ref:"#1-2'-3-4/0'",revision:'source-r1',availability:'stale'}),/available/);assert.throws(()=>api.stageSourceRequest(snapshot,{kind:'expression'},null,['x','x']),/distinct/);
});
test('missing native graph or source library remains refusal, not an admitted source/definition',()=>{
 assert.throws(()=>api.retainedProcedureAuthorship({procedure_ref:'procedure:only-label',revision:'r1'}),/full source-owned/);assert.throws(()=>api.validateProcedureAuthorship({procedure_ref:'procedure:graph-shell',revision:'r1',seed:'seed-explicit',composition:{}}),/full native/);assert.throws(()=>api.validateFullNativeSubject({subject_ref:'subject:label',native_owner:'ql',presentation_role:'being',sources:[],actions:[]}),/full owner/);assert.throws(()=>api.projectStageLibrary({}),/source|reply|compiler/i);
 const snapshot=authoring();assert.throws(()=>api.validateStageSourceReading({schema:'oi.expression-procedural/v1',expression_ref:'expression:foreign',document_revision:4,current_readings:[],scene_sources:[]},snapshot,api.stageSourceRequest(snapshot,{kind:'expression'})),/foreign/);
});
test('actual native Document/scope admission detects dropped rows, wrong occurrence and stale target revision before Source disclosure',()=>{
 const snapshot=authoring(),entity_ref=snapshot.view.bindings[snapshot.sceneId].occurrences[0].entity_ref,address={expression_ref:snapshot.view.document.expression_ref,scene_ref:api.studioBasis(snapshot).scene_ref,entity_ref,component:'entity',constituent_ref:null,property:null},request=api.stageSourceRequest(snapshot,{kind:'addresses',addresses:[address]}),raw={schema:'oi.expression-procedural/v1',expression_ref:address.expression_ref,document_revision:4,current_readings:[],scene_sources:[]};
 assert.deepEqual(api.resolvedSourceReadAddresses(snapshot,request.scope),[address]);assert.throws(()=>api.validateStageSourceReading(raw,snapshot,request),/dropped/);
 const row={address,occurrence_ref:entity_ref+'-other',revision:4,subject:snapshot.view.document.entities[entity_ref].subject,tags:[],properties:{}};assert.throws(()=>api.validateStageSourceReading({...raw,current_readings:[row]},snapshot,request),/occurrence identity/);assert.throws(()=>api.validateStageSourceReading({...raw,current_readings:[{...row,occurrence_ref:entity_ref,revision:3}]},snapshot,request),/target revision/);assert.throws(()=>api.validateStageSourceReading({...raw,current_readings:[row,row]},snapshot,request),/dropped|widened/);
});
test('actual WebCrypto correspondence refuses a constituent hash that names another native address/parent',async()=>{
 const snapshot=authoring(),address={expression_ref:snapshot.view.document.expression_ref,scene_ref:api.studioBasis(snapshot).scene_ref,entity_ref:snapshot.view.bindings[snapshot.sceneId].occurrences[0].entity_ref,component:'layer',constituent_ref:'continuing-layer',parent_ref:'actual-state',property:null};
 await assert.rejects(api.validateStageOccurrenceIdentities({current_readings:[{address,occurrence_ref:address.expression_ref+':target:'+'0'.repeat(64)}]}),/exact address\/parent/);
});
test('actual native library domain source and normal Stage typed path are retained',{skip:!process.env.QL_PROCEDURAL_CONDUCT_SOURCE&&'Native library source must be pinned by the paired owner'},()=>{
 const native=process.env.QL_PROCEDURAL_CONDUCT_SOURCE;
 const text=readFileSync(native,'utf8');for(const p of force.parameters){assert.ok(text.includes(`"key":"${p.key}","minimum":${p.minimum},"maximum":${p.maximum}`),`native library changed ${p.key}`);}
});
const fixturePath=process.env.OI_STAGE_NATIVE_SOURCE_FIXTURE;
test('qualified actual read_source artifact admits exact native scene/principal/place and rejects changed source, subject and revision',{skip:!fixturePath&&'Actual native read_source/candidate artifact has not arrived'},async()=>{
 const actual=JSON.parse(readFileSync(fixturePath,'utf8'));assert.ok(actual.document&&actual.request&&actual.reply&&actual.current_sources,'Use the qualified genuine native source artifact, not a constructed fixture');const view=api.kernelDocumentToJourney(actual.document),snapshot={view,journey:api.clone(view.journey),sceneId:actual.scene_id,selected:actual.selected,currentSources:actual.current_sources};const admitted=api.validateStageSourceReading(actual.reply,snapshot,actual.request);assert.ok(admitted.scene_sources.length>0);const source=admitted.scene_sources[0],profile=actual.request.scene_profile;assert.equal(api.validateNativeSceneSource(source,snapshot,profile).principal.subject_ref,source.principal.subject_ref);
 await api.validateStageOccurrenceIdentities(admitted);for(const mutate of [row=>row.document_revision++,row=>row.principal.subject_ref+='-wrong-prime',row=>row.source_basis.revision+='-stale',row=>row.presentation.scene.name+='-foreign-source',row=>row.locus_ref+="'"]){const changed=api.clone(source);mutate(changed);assert.throws(()=>api.validateNativeSceneSource(changed,snapshot,profile));}assert.deepEqual(actual.reply,JSON.parse(readFileSync(fixturePath,'utf8')).reply);
});
test('actual normal mounted Stage browser reception, retained typing, native preparation/conduct and saved replay',{skip:!process.env.OI_STAGE_BROWSER_RECEIPT&&'Actual native candidate/browser receiving receipt is required'},()=>{
 const receipt=JSON.parse(readFileSync(process.env.OI_STAGE_BROWSER_RECEIPT,'utf8'));assert.equal(receipt.schema,'oi.stage-browser-receipt/v1');for(const gate of ['normal_stage_mount','same_workspace','whole_to_layer_parent','native_source_current','form_retained_native_pulse','library_native_definition','prepared_review_receiver','native_conduct_receipt','saved_reopen_source'])assert.equal(receipt.gates?.[gate]?.state,'pass',gate);assert.ok(receipt.producer_revision&&receipt.app_revision&&receipt.saved_project&&receipt.native_source_sha256);
});
test('actual native prepared Stage artifact fences original retry, cancellation, restoration and foreign activity',{skip:!process.env.OI_STAGE_PREPARED_ARTIFACT&&'Actual native prepared Stage receipt/Document/source intent is required'},()=>{
 const actual=JSON.parse(readFileSync(process.env.OI_STAGE_PREPARED_ARTIFACT,'utf8'));assert.equal(actual.schema,'oi.stage-prepared-artifact/v1');const view=api.kernelDocumentToJourney(actual.document),snapshot={view,journey:api.clone(view.journey),sceneId:actual.scene_id,selected:actual.selected,currentSources:actual.current_sources};const admitted=api.validateStagePreparedReceipt(actual.intent,actual.preview,actual.native_reply,snapshot);assert.deepEqual(admitted.operation,actual.preview.operation);const before=api.clone(actual);
 for(const mutate of [row=>row.native_reply.restored=true,row=>{row.preview.operation.status='cancelled';row.native_reply.operation.status='cancelled';},row=>row.preview.operation.accepted_revision++,row=>row.intent.basis.document_revision++,row=>row.intent.authored.revision+='-edited',row=>row.intent.source.principal.subject_ref+='-wrong-prime',row=>row.intent.scope={kind:'expression'},row=>row.document.revision++]){const changed=api.clone(actual);mutate(changed);const changedView=api.kernelDocumentToJourney(changed.document);assert.throws(()=>api.validateStagePreparedReceipt(changed.intent,changed.preview,changed.native_reply,{...snapshot,view:changedView,journey:changedView.journey}));}if(actual.intent.choice.recipe==='force_parameters'){const altered=api.clone(actual.preview),parameter=actual.intent.choice.writes[0].parameter,sibling=parameter==='force_radius'?'force_strength':'force_radius',entity=actual.intent.scope.addresses[0].entity_ref;altered.operation.envelope.changes.push({change:'parameter_set',entity_ref:entity,parameter:sibling,value:1});assert.throws(()=>api.validateStagePreparedReceipt(actual.intent,altered,actual.native_reply,snapshot),/sibling|undeclared/,'even a prepared native-looking preview cannot acquire sibling scalar authority');}assert.deepEqual(actual,before);
});
