import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {modules} from './nara-personal-modules.mjs';
import {record,source,parent,target,consent,nativeOwner,reply,kinds} from './nara-personal-fixtures.mjs';
const {mod:m,dispose}=await modules();after(dispose);
const clone=structuredClone;
const template=await readFile(new URL('../documents/ql-dialogue-flow.html',import.meta.url),'utf8');
const parse=html=>JSON.parse(html.match(/<script type="application\/json" id="ql-doc">([\s\S]*?)<\/script>/)[1].replace(/<\\\/script/gi,'</script'));
function flow(){const doc=parse(template);doc.meta.documentId='flow:retained';doc.meta.revision=5;doc.entries=[{id:'human1',author:'F',at:'2026-09-20',html:'<p>Original human words</p>',replyTo:null,touched:true}];doc.journal=[{id:'page1',at:'2026-09-19',html:'<p>Journal with <img src="local-photo.png"></p>'}];doc.notes=[{text:'keep note'}];doc.media=[{ref:'native-image:test'}];doc.packet=[{unfamiliar:'extension retained'}];const html=template.replace(/(<script type="application\/json" id="ql-doc">)[\s\S]*?(<\/script>)/,(_s,a,b)=>a+JSON.stringify(doc)+b);return {html,doc,revision:'source:r5',location:{...source.location,path:'Control/user/flows/f.html',ref:'central:path:/test:Control/user/flows/f.html'}};}
const returned={delivery_ref:'delivery:1',agent_session_ref:'agent-session/1',actor_ref:'agent:nara',role:'nara',subject_ref:'subject:one',text:'A real returned text with <script>not executable</script> & symbols',complete:true};

test('no native operation, model or microphone runs when a personal controller is constructed',()=>{const calls=[];new m.PersonalController(async r=>calls.push(r),consent);assert.deepEqual(calls,[]);});
test('private read refuses another native person and does not replace the current record',async()=>{const c=new m.PersonalController(async()=>reply({record:{...record(),target:{...target,subject_ref:'other'}}}),consent);await assert.rejects(c.read(target),/personal/);assert.equal(c.snapshot.record,null);});
test('consent cannot be asserted by an agent or omitted',()=>{assert.throws(()=>new m.PersonalController(async()=>{}, {...consent,actor_kind:'agent'}));assert.throws(()=>new m.PersonalController(async()=>{}, {...consent,personal_data:false}));});
test('identity layer stays optional and source provenance is retained, without synthesized birth facts',()=>{const present=m.identitySource('birthdate-name',source),absent=m.identitySource('natal-chart',null,'I do not know my birth time');assert.equal(present.slot.protected_value_ref.ref_id,source.location.ref);assert.equal(present.slot.source.revision,source.revision);assert.equal(absent.slot.source,null);assert.equal(absent.slot.standing,'unavailable');assert.equal(absent.slot.absence_reason,'I do not know my birth time');assert.ok(!JSON.stringify(present).includes(source.content));});
test('native mutation is revision-bound and only its actual matching receipt confirms success',async()=>{const owner=nativeOwner(),c=new m.PersonalController(owner.call,consent);await c.read(target);const before=clone(c.snapshot.record);const result=await c.apply(m.identitySource(kinds[1],source));assert.equal(result.revision,2);assert.deepEqual(before.domain.identity.slots[1].source,null);assert.equal(owner.calls[1].expected_revision,1);assert.equal(c.snapshot.pending,null);});
test('lost native acknowledgement retains exact request and idempotent recovery never recasts',async()=>{const owner=nativeOwner();let lose=true;const c=new m.PersonalController(async req=>{const out=await owner.call(req);if(req.operation==='apply'&&lose){lose=false;throw new Error('lost ack');}return out;},consent);await c.read(target);await assert.rejects(c.apply({kind:'centre_feedback',ordinal:2,feedback_ref:'source:feedback'}));const pending=c.snapshot.pending;await assert.rejects(c.apply({kind:'centre_feedback'}));await c.recover();assert.equal(c.snapshot.record.revision,2);assert.deepEqual(owner.calls[1],owner.calls[2]);assert.equal(owner.calls[2].request_id,pending.request_id);});
test('a definite native revision refusal never becomes an accepted change',async()=>{const c=new m.PersonalController(async req=>req.operation==='read'?reply({record:record()}):{schema:m.PERSONAL_CONTRACT,ok:false,private:true,error:{reason:'revision conflict'}},consent);await c.read(target);await assert.rejects(c.apply({kind:'centre_feedback'}),/revision conflict/);assert.equal(c.snapshot.record.revision,1);assert.equal(c.snapshot.pending,null);});
test('forged success receipt cannot clear the pending native operation',async()=>{const c=new m.PersonalController(async req=>req.operation==='read'?reply({record:record()}):reply({record:{...record(),revision:2},receipt:{request_id:'other',revision:2,previous_revision:1}}),consent);await c.read(target);await assert.rejects(c.apply({kind:'centre_feedback'}),/exact/);assert.ok(c.snapshot.pending);});
test('a pending native write blocks read/rebind and duplicate apply across presentations',async()=>{let release;const owner=nativeOwner(),c=new m.PersonalController(async req=>{if(req.operation==='apply')await new Promise(r=>release=r);return owner.call(req);},consent);await c.read(target);const writing=c.apply({kind:'centre_feedback',ordinal:0,feedback_ref:'source:one'});await assert.rejects(c.read({...target,nara_ref:'other'}));await assert.rejects(c.apply({kind:'centre_feedback'}));release();await writing;});
test('context branch boundaries refuse adjacent but prefix-similar coordinates',()=>{assert.throws(()=>m.contextSource('jungian-depth','M4.4.30',source,''));assert.throws(()=>m.contextSource('jungian-depth','M4.4.4.3',source,''));assert.equal(m.contextSource('jungian-depth','M4.4.3.4',source,'').reading.coordinate_ref,'M4.4.3.4');});
test('practice requires deliberate review and a closed predecessor, not an identity-hash guess',()=>{assert.throws(()=>m.nextPractice(record(),source,false));const r=record();r.domain.transformation.phase_history.phases=[{storey:0,decan:0,stroke:2,closed_at_unix_ms:null}];assert.throws(()=>m.nextPractice(r,source,true));r.domain.transformation.phase_history.phases[0].closed_at_unix_ms=1;assert.equal(m.nextPractice(r,source,true,2).phase.stroke,3);});
test('ordinary note creation is exclusive, preserves exact prose and resolves the native owner address',async()=>{const calls=[];const content='My own words\n\nBirth time unknown.\n';const result=await m.createHumanNote(parent,'my own words.md',content,{write:async(location,revision,text)=>{calls.push({location,revision,text});return {outcome:'created',revision:'r2'};},read:async location=>({...source,location,content,revision:'r2'})});assert.equal(calls[0].revision,'');assert.equal(result.content,content);assert.equal(result.location.ref,'central:path:/test:Control/user/my%20own%20words.md');});
test('existing notes and unsafe paths are never overwritten or silently renamed',async()=>{for(const name of ['../who.md','x/y.md','x\\y.md','.hidden.md','x.md '])assert.throws(()=>m.noteLocation(parent,name));assert.throws(()=>m.noteLocation({...parent,entries:[{name:'about-me.md'}]},'about-me.md'),/already exists/);assert.throws(()=>m.noteLocation({...parent,location:{...parent.location,path:'Work/demo'}},'about-me.md'));});
test('racing note create and uncertain readback retain the human draft as failure',async()=>{await assert.rejects(m.createHumanNote(parent,'about-me.md','words',{write:async()=>({outcome:'conflict'}),read:async()=>{throw Error('must not read');}}),/Another writer/);await assert.rejects(m.createHumanNote(parent,'about-me.md','words',{write:async()=>({outcome:'created',revision:'r2'}),read:async()=>({...source,revision:'r2',content:'changed'})}),/readback/);});
test('Flow preview preserves the original HTML shell, human entries, Journal, notes, media and unknown packet data',async()=>{const original=flow(),preview=await m.previewDialogueReturn(original,returned,new Date('2026-09-21T00:00:00Z')),after=parse(preview.html);assert.equal(after.entries.length,2);assert.equal(after.entries[1].author,'H');assert.equal(after.meta.revision,6);assert.deepEqual(after.entries[0],original.doc.entries[0]);for(const field of ['journal','notes','media','packet'])assert.deepEqual(after[field],original.doc[field]);const shell=s=>s.replace(/(<script type="application\/json" id="ql-doc">)[\s\S]*?(<\/script>)/,'$1$2');assert.equal(shell(preview.html),shell(original.html));assert.match(after.entries[1].html,/&lt;script&gt;/);assert.match(after.entries[1].html,/AgentSession: agent-session\/1/);});
test('a returned native delivery is idempotent in the same Flow, not duplicated or allowed to change after return',async()=>{const one=await m.previewDialogueReturn(flow(),returned),saved={...flow(),html:one.html,doc:parse(one.html),revision:'r6'};const two=await m.previewDialogueReturn(saved,returned);assert.equal(two.unchanged,true);assert.equal(two.html,one.html);await assert.rejects(m.previewDialogueReturn(saved,{...returned,text:'changed reply'}),/different content/);});
test('Flow accept refuses stale review and native CAS conflicts before any overwrite',async()=>{const original=flow(),preview=await m.previewDialogueReturn(original,returned);let writes=0;await assert.rejects(m.acceptDialogueReturn(preview,{read:async()=>({...original,revision:'r-new'}),write:async()=>{writes++;}}),/changed after review/);assert.equal(writes,0);await assert.rejects(m.acceptDialogueReturn(preview,{read:async()=>original,write:async()=>{writes++;return {outcome:'conflict'};}}),/stale Flow write/);assert.equal(writes,1);});
test('Flow success requires the actual reviewed byte content and returned source revision',async()=>{let original=flow();const preview=await m.previewDialogueReturn(original,returned);await m.acceptDialogueReturn(preview,{read:async()=>original,write:async(_l,_r,html)=>{original={...original,html,doc:parse(html),revision:'r6'};return {outcome:'written',revision:'r6'};}});assert.equal(original.doc.entries[1].author,'H');});
test('unfinished, unbound or person-authored dialogue cannot be relabelled as Nara',async()=>{for(const bad of [{complete:false},{delivery_ref:''},{role:'person'},{actor_ref:''}])await assert.rejects(m.previewDialogueReturn(flow(),{...returned,...bad}));});
test('identity fingerprint is stable across JSON order and native orientation but changes with actual source revision',async()=>{const r=record(),a=await m.identityPattern(r,'cymatic');const q=record();q.domain.q_composed={w:0,x:0,y:0,z:1};q.domain.identity.slots.reverse();const b=await m.identityPattern(q,'yantra');assert.equal(a.fingerprint.value,b.fingerprint.value);r.domain.identity.slots[0].source.revision='new-source';assert.notEqual((await m.identityPattern(r,'cymatic')).fingerprint.value,a.fingerprint.value);assert.ok(!JSON.stringify(a).includes('Control/user'));assert.ok(!JSON.stringify(a).includes('subject:one'));});
test('an empty identity stack, personal payload or invalid orientation never becomes a made-up pattern',async()=>{const r=record();r.domain.identity.slots=r.domain.identity.slots.map(s=>({...s,source:null,protected_value_ref:null}));await assert.rejects(m.identityPattern(r,'yantra'),/at least one/);const good=await m.identityPattern(record(),'cymatic');assert.throws(()=>m.validateIdentityPattern({...good,notes:'must-not-leak'}));assert.throws(()=>m.validateIdentityPattern({...good,orientation:{w:0,x:0,y:0,z:0}}));});
test('the identity uses all seven native chakral cymatic forms, no receiver-to-station mapping, and retains orientation separately',async()=>{const p=await m.identityPattern(record(),'cymatic'),a=m.identityScene(p),b=m.identityScene(p);assert.deepEqual(a.entities,b.entities);assert.equal(a.entities.length,7);assert.ok(a.entities.every(e=>e.shape==='cymatic'&&e.station===null));assert.equal(a.engine.resonanceEnabled,false);assert.equal(a.composition.carryStation,false);assert.equal(new Set(a.entities.map(e=>e.templateFrequency)).size,7);assert.ok(!JSON.stringify(a).includes(p.fingerprint.value));const flipped=m.identityScene({...p,orientation:{w:0,x:0,y:0,z:1}});assert.ok(Math.abs(a.entities[0].position.y+flipped.entities[0].position.y)<1e-12);});
test('one existing engine presents privately without altering the ordinary scene; capture, export and diagnostics cannot read it',async()=>{const frames=[],publicScene={id:'ordinary',entities:[]},engine={canvas:{},capabilities:{kind:'production'},render:f=>frames.push(clone(f)),resize(){},capture:()=>({}),telemetry:()=>({public:true}),inspect:()=>({public:true}),transportState:()=>({ordinary:true}),dispose(){}};const port=m.privateIdentityEngine(engine,{canPresent:()=>true,requestFrame(){}});const frame={scene:publicScene,camera:{},delta:0,params:{},selectedIds:[],pointer:{active:false},simTime:0};port.engine.render(frame);port.begin(await m.identityPattern(record(),'cymatic'));port.engine.render(frame);assert.equal(frames[1].scene.entities.length,7);assert.deepEqual(publicScene,{id:'ordinary',entities:[]});assert.throws(()=>port.engine.capture());assert.throws(()=>port.engine.transportState());assert.deepEqual(port.engine.inspect(),{private:true,standing:'private-presentation; native source not disclosed'});port.end();assert.equal(frames.at(-1).scene.id,'ordinary');assert.deepEqual(port.engine.telemetry(),{public:true});});
test('recording or an active native field lease refuses identity presentation rather than replacing another owner',async()=>{const port=m.privateIdentityEngine({canvas:{},render(){},dispose(){}},{canPresent:()=>false,requestFrame(){}});assert.throws(()=>port.begin({}),/Finish recording/);assert.equal(port.active,false);});

test('Flow script markers in comments and exporter code are not duplicate document elements',async()=>{
 const f=flow();f.html='<!-- <script type="application/json" id="ql-doc">not JSON</script> -->'+f.html;
 const result=await m.previewDialogueReturn(f,returned);assert.ok(result.html.startsWith('<!-- <script'));
 const twice={...flow(),html:flow().html+'<script type="application/json" id="ql-doc">{}</script>'};await assert.rejects(m.previewDialogueReturn(twice,returned),/exactly one/);
});
test('existing literal comments and closing tags inside Flow prose remain valid JSON and identical authored strings',async()=>{
 const f=flow();f.doc.entries[0].html='<p>Keep <!-- user note --> literal data</p>';
 f.html=f.html.replace(/(<script type="application\/json" id="ql-doc">)[\s\S]*?(<\/script>)/,(_all,a,b)=>a+JSON.stringify(f.doc)+b);
 const p=await m.previewDialogueReturn(f,returned);assert.equal(parse(p.html).entries[0].html,f.doc.entries[0].html);
});
test('private telemetry does not masquerade as the normal material reading used by the real app loop',async()=>{
 const port=m.privateIdentityEngine({render(){},dispose(){},telemetry:()=>({simTime:42}),stations:()=>[{frequencyHz:1}]},{canPresent:()=>true,requestFrame(){}});
 port.begin(await m.identityPattern(record(),'cymatic'));assert.equal(port.engine.telemetry(),null);assert.deepEqual(port.engine.stations(),[]);port.end();assert.equal(port.engine.telemetry().simTime,42);
});
test('oracle interpretation retains the original packet and optional model without claiming source authority',()=>{
 const r=m.interpretOracle('packet:original',source,'',23);assert.equal(r.packet_ref,'packet:original');assert.equal(r.interpretation.packet_ref,'packet:original');assert.equal(r.interpretation.model_ref,null);assert.equal(r.interpretation.output_ref.revision,source.revision);assert.equal(r.interpretation.standing,'reported');
});
