import {test} from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {PAGE_PROFILE,blankPage,validatePage,readPage,renderPage,availableForms,pageDate,allowedLink} from "../src/personal/page.mjs";
import {pageExpressionBinding} from "../src/personal/page-expression.mjs";
const roster=JSON.parse(await readFile(new URL("../documents/forms.json",import.meta.url),"utf8"));
for(const family of ["beings","things"]){
 test(`${family}: passive render does not mint or invoke`,()=>{const doc=blankPage(family);const before=structuredClone(doc);const html=renderPage(doc);assert.deepEqual(doc,before);assert.deepEqual(readPage(html),doc);assert.equal(doc.meta.documentId,null);assert.equal(doc.meta.created,null);assert.ok(!/fetch\(|localStorage|postMessage|__TAURI__|https?:\/\/[^<]/.test(html));});
 test(`${family}: exact source and unknown data survive a full copy`,()=>{const doc=blankPage(family);doc.meta.title="A particular subject";doc.meta.documentId="authored-document";doc.bindings={worldRef:"world:private",subjectRef:"subject:7",categories:["C1","C4"],expressionRef:"projection:private:2",sources:[{ref:"source:7",revision:"revision:12",extension:{keep:true}}]};doc.notes=[{text:"PRIVATE_SENTINEL",id:"note:1"}];doc.extensions={future:[{name:"retain me"}]};assert.deepEqual(readPage(renderPage(doc)),doc);});
 test(`${family}: text cannot close the JSON script or create markup`,()=>{const doc=blankPage(family);doc.meta.title='</script><script>globalThis.compromised=1</script><!--';doc.page.sections[0].text='<img src=x onerror="globalThis.compromised=2">';const html=renderPage(doc);assert.deepEqual(readPage(html),doc);assert.ok(!html.includes('<script>globalThis.compromised'));assert.ok(html.includes('\\u003c/script>'));});
 test(`${family}: appearance leaves subject/category/source unchanged`,()=>{const doc=blankPage(family);doc.bindings.subjectRef="subject:7";const old=structuredClone(doc.bindings);doc.appearance={layout:"editorial",tone:"ink"};assert.deepEqual(readPage(renderPage(doc)).bindings,old);});
 test(`${family}: built reference carrier is exactly reproducible`,async()=>{assert.equal(await readFile(new URL(`../documents/oi-${family}.html`,import.meta.url),"utf8"),renderPage(blankPage(family)));});
}
test("six core families, with plural canonical Beings and Things",()=>{assert.equal(roster.forms.length,6);assert.equal(roster.forms[2].label,"Beings");assert.equal(roster.forms[3].label,"Things");assert.equal(roster.cProfile.source,"C0");assert.equal(roster.cProfile.expression,"C5");assert.equal(roster.cProfile.audienceIndependent,true);assert.equal(roster.cProfile.requiresLiveQl,false);});
test("legacy Day index and files remain intact; absent forms aren't fabricated",()=>{const forms=availableForms(roster);assert.equal(forms.length,4);assert.equal(forms[0].file,"ql-dialogue-flow.html");assert.equal(forms[1].file,"ql-daily-die.html");assert.ok(!forms.some(f=>/cube|card/.test(f.file)));});
test("a seventh user descriptor is not rejected by a closed family enum",()=>{const copy=structuredClone(roster);copy.forms.push({kind:"document-garden",label:"Garden",hint:"A custom reading",templateRef:"user.template/garden",file:"garden.html"});assert.equal(availableForms(copy).at(-1).label,"Garden");assert.equal(roster.forms.length,6);});
test("duplicate descriptors and path escape are rejected before file resolution",()=>{const copy=structuredClone(roster);copy.forms.push(copy.forms[0]);assert.throws(()=>availableForms(copy),/duplicate/);copy.forms.pop();copy.forms[2].file="../private.html";assert.throws(()=>availableForms(copy),/owner-resolved/);});
for(const categories of [["C0"],["C5"],["C9"],["C2","C2"],[]])test(`reject category conflation ${JSON.stringify(categories)}`,()=>{const d=blankPage("things");d.bindings.categories=categories;assert.throws(()=>validatePage(d),/C1–C4/);});
test("C0/C5 source-expression exists independently of an optional audience",()=>{const d=blankPage("things");d.bindings.worldRef="world:public-source";d.bindings.expressionRef="projection:private-reading";d.extensions.audience="private";assert.equal(readPage(renderPage(d)).bindings.expressionRef,d.bindings.expressionRef);});
test("calendar uses declared occurrence; a revision cannot move the page",()=>{const d=blankPage("things");d.meta.occurredOn="2026-09-10";d.meta.createdOn="2026-09-13";d.meta.revision=23;assert.deepEqual(pageDate(d),{date:"2026-09-10",basis:"occurrence"});});
test("no UTC guessing when civil creation date is absent",()=>{const d=blankPage("beings");d.meta.created="2026-09-13T23:30:00Z";assert.equal(pageDate(d),null);d.meta.createdOn="2026-09-14";assert.deepEqual(pageDate(d),{date:"2026-09-14",basis:"creation"});});
test("impossible occurrence dates fail rather than normalize",()=>{const d=blankPage("things");d.meta.occurredOn="2026-02-30";assert.throws(()=>pageDate(d));});
test("unknown profiles, corrupt state and duplicate state refuse conversion",()=>{assert.throws(()=>readPage('<script type="application/json" id="ql-doc">{}</script>'));assert.throws(()=>readPage('not a carrier'));const h=renderPage(blankPage("things"));assert.throws(()=>readPage(h+h),/one embedded/);const d=blankPage("things");d.profile=PAGE_PROFILE+"-future";assert.throws(()=>renderPage(d),/no lossy/);});
for(const href of ["javascript:alert(1)","data:text/html,yes","file:///etc/passwd","//example.test/x","https:\\example.test","java\nscript:alert(1)"])test(`reject active or ambiguous link ${JSON.stringify(href)}`,()=>{assert.equal(allowedLink(href),false);const d=blankPage("things");d.page.links=[{id:"a",label:"x",relation:"mentioned",href}];assert.throws(()=>renderPage(d),/unsupported link/);});
test("normal locators preserve relation labels instead of inferring ownership",()=>{const d=blankPage("things");d.page.links=[{id:"a",label:"Another page",relation:"interested in",href:"./interest.html#section-1"}];assert.equal(readPage(renderPage(d)).page.links[0].relation,"interested in");assert.ok(allowedLink("https://example.test/a"));});
test("invalid revision and duplicated content identities are rejected",()=>{const d=blankPage("things");d.meta.revision=-1;assert.throws(()=>renderPage(d));d.meta.revision=0;d.page.sections.push(d.page.sections[0]);assert.throws(()=>renderPage(d),/duplicate/);});
test("Being page carries a first-class Expression body with exact file and subject revisions",()=>{const d=blankPage("beings");d.meta.documentId="ada";d.meta.title="Ada";d.bindings.worldRef="world:personal";d.bindings.subjectRef="central:being:ada";d.page.expression={schema:"oi.expression-presentation/v1",expression_ref:"expression:ada",expression_revision:4,scene_ref:"expression:ada:scene:welcome",live_renderer_ref:"renderer:oi:expression-stage",live_availability:"available",subjects:[{ref:"central:being:ada",revision:"subject@9",availability:"available",sources:[]}],representations:[{kind:"image",representation:{ref:"capture:ada:4",revision:"capture@1",availability:"available"},provenance:[{ref:"expression:ada",revision:"4",availability:"available"}],href:"./ada-expression.png",media_type:"image/png"}]};const html=renderPage(d);const restored=readPage(html);assert.equal(restored.page.expression.expression_ref,"expression:ada");assert.match(html,/capture:ada:4/);assert.match(html,/ada-expression\.png/);const binding=pageExpressionBinding(restored,"file@17");assert.equal(binding.subject_ref,"central:being:ada");assert.equal(binding.props.expression.expression_revision,4);assert.equal(binding.provenance[0].revision,"file@17");});
test("page Expression refuses mismatched native subject and missing file revision",()=>{const d=blankPage("things");d.bindings.subjectRef="central:thing:other";d.page.expression={schema:"oi.expression-presentation/v1",expression_ref:"expression:one",expression_revision:1,live_renderer_ref:"renderer:oi:expression-stage",live_availability:"available",subjects:[{ref:"central:thing:one",revision:"r1",availability:"available",sources:[]}],representations:[]};assert.throws(()=>pageExpressionBinding(d,"file@1"),/do not match/);d.bindings.subjectRef="central:thing:one";assert.throws(()=>pageExpressionBinding(d,""),/exact file revision/);});
