/** Production Wiki surface over a controlled kernel boundary. Source reading
 * payloads are generated by the real native CLI, never re-parsed in this host. */
import {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {KernelProvider} from '../src/kernel/KernelProvider';
import {VisualsProvider} from '../src/visuals/ParticleExpression';
import {ExpressionStageProvider} from '../src/stage/ExpressionStage';
import {KnowledgeSurface} from '../src/knowledge/KnowledgeSurface';
import '@epilogos/oi-design-system/tokens.css';
window.__OI_KERNEL_BRIDGE__=`${location.origin}/__wiki_fixture`;
const observed:{context:unknown[];opened:unknown[]}={context:[],opened:[]};
window.addEventListener('oi:context-candidate',event=>observed.context.push((event as CustomEvent).detail));
Object.assign(window,{__WIKI_TEST__:observed});
function App(){
 const [graph,setGraph]=useState(false);
 return <main style={{height:'95vh',display:'flex',flexDirection:'column',fontFamily:'var(--oi-font-sans)',color:'var(--oi-foreground)',background:'var(--oi-canvas-ground)'}}>
  <header><button onClick={()=>setGraph(false)}>Read corpus</button><button onClick={()=>setGraph(true)}>Graph corpus</button></header>
  <div style={{minHeight:0,flex:1,display:'flex'}}><KnowledgeSurface key={graph?'graph':'page'} binding={{id:graph?'wiki-test-graph':'wiki-test-page',kind:'knowledge',title:'Alpha',address:graph?{kind:'wiki',value:'wiki:root'}:{kind:'source',value:'source:a'},view:{knowledgePlane:graph?'graph':'page'}}} onOpen={async(address,title,project)=>{observed.opened.push({address,title,project});}}/></div>
 </main>;
}
createRoot(document.getElementById('root')!).render(<KernelProvider><VisualsProvider><ExpressionStageProvider><App/></ExpressionStageProvider></VisualsProvider></KernelProvider>);
