/** Real native construction/source and native Expression roundtrip; no source
 * model extension, inference from traversal, mocked owner, or RC persistence. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn,execFileSync} from 'node:child_process';
import {once} from 'node:events';
import {mkdtemp,mkdir,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {kernelOp} from '../src/kernel/bridge.ts';
import {listFiles} from '../src/files/client.ts';
import {knowledge} from '../src/knowledge/client.ts';
import {verifyInsertionSource} from '../src/expressions/sourceInsertion.ts';
import {resolveHostedSource} from '../src/expressions/sourceHandoff.ts';
import {readRegister} from '../src/knowledge/construction.ts';
import {projectConstruction} from '../src/knowledge/constructionProjection.ts';
import {wikiSceneRelationReadings} from '../src/techne/wikiSceneRelationReadings.ts';
import {readWikiSceneTechne} from '../src/techne/wikiReadingProvider.ts';
import {publishWikiNativeRegisters} from '../src/techne/wikiNativeExpression.ts';
import {build} from 'esbuild';
import {fileURLToPath} from 'node:url';

test('native authored directions resolve by exact relation revision and participation, without changing the native document',{skip:process.env.OI_NATIVE_AUTHORED_SCENE!=='1',timeout:120000},async()=>{
 for(const key of ['OI_KERNEL_BIN','OI_BIN','OI_AIKIT_BIN','OI_CENTRAL_CTRL_BIN'])assert.ok(process.env[key],key+' required');
 const scratch=await mkdtemp(join(tmpdir(),'oi-scene-direction-')),root=join(scratch,'Central'),home=join(scratch,'oi-home');let child,stderr='';
 const env={...process.env,OI_HOME:home,AIKIT_HOME:join(scratch,'aikit-home'),OI_CENTRAL_ROOT:root,OI_CENTRAL_PROJECT_QUERY:''};
 try{
  await mkdir(root);await mkdir(home);
  assert.equal(JSON.parse(execFileSync(process.env.OI_CENTRAL_CTRL_BIN,['--root',root,'--json','action','run','central.init','{}'],{env,encoding:'utf8',timeout:30000})).ok,true);
  await mkdir(join(root,'Work','Notes'),{recursive:true});
  const projectInit=JSON.parse(execFileSync(env.OI_CENTRAL_CTRL_BIN,['--root',root,'--json','action','run','projectcentral.init',JSON.stringify({project:'Notes',project_id:'source-return-notes'})],{env,encoding:'utf8',timeout:30000}));assert.equal(projectInit.ok,true,JSON.stringify(projectInit));
  child=spawn(process.env.OI_KERNEL_BIN,['127.0.0.1:0'],{env,detached:true,stdio:['ignore','pipe','pipe']});child.stderr.on('data',chunk=>stderr+=chunk);
  const url=await new Promise((resolve,reject)=>{let output='';const timer=setTimeout(()=>reject(Error(stderr||'Native startup timed out')),30000);child.once('error',error=>{clearTimeout(timer);reject(error);});child.once('exit',code=>{clearTimeout(timer);reject(Error('Native exited '+code+stderr));});child.stdout.on('data',chunk=>{output+=chunk;const match=/listening on (http:\/\/[^ ]+)/.exec(output);if(match){clearTimeout(timer);resolve(match[1]);}});});
  const transport={kind:'bridge',url},before=await readRegister(transport),subject=before.spaces[0].ref,frameRef='wiki:frame:native-direction';
  const parts=['participation:wiki:direction-a','participation:wiki:direction-b'];
  const directions=['directed','undirected','bidirectional'];
  const request={schema:'aikit.constellation-action/v1',frame_ref:frameRef,expected_revision:0,actor_ref:'human:native-direction-regression',operation_ref:'operation:wiki:native-direction',changes:[{change:'create',anchor_ref:'wiki:anchor:native-direction',title:'Native direction parity',inquiry:{question:'Does source direction survive a transient reading?'},space_refs:[subject],frame:null},...parts.map(part=>({change:'member_add',member:{subject_ref:subject,participation:{participation_ref:part,role_ref:null,sources:[],note:'Same source, distinct native occurrence'}}})),...directions.map(direction=>({change:'relation_put',relation:{relation_ref:'wiki:edge:native-'+direction,expected_revision:null,from_participation_ref:parts[0],to_participation_ref:parts[1],relation:'supports',direction,standing:'asserted',evidence:[]}}))]};
  const apply=JSON.parse(execFileSync(process.env.OI_AIKIT_BIN,['--json','-C',root,'wiki-construct','apply','--file',join(root,before.file.location.path)],{env,input:JSON.stringify({basis_content:before.file.content,request}),encoding:'utf8',timeout:30000}));assert.ok(apply.ok,JSON.stringify(apply));
  const current=await readRegister(transport),frame=current.frames.find(row=>row.ref===frameRef);assert.ok(frame);
  const opened=await projectConstruction(transport,undefined,frame,current.relations,current);assert.equal(opened.state,'ready',JSON.stringify(opened));
  const document=opened.document,scene=document.scenes.find(row=>row.scene_ref===document.selection.scene_ref),bytes=JSON.stringify(document);
  const selectedReading=await knowledge(transport,undefined,{action:'read',address:{kind:'wiki',value:subject}});
  const librarySource={kind:'projected-object',ref:subject,title:'Actual native Wiki source',owner:'display label is not binding authority',scope:'local',provider:'wiki',address:{kind:'wiki',value:subject},revision:selectedReading.revision};
  const admitted=await verifyInsertionSource(transport,librarySource);
  assert.equal(admitted.binding.subject_ref,subject);
  assert.equal(admitted.binding.native_owner,selectedReading.provider);
  assert.deepEqual(admitted.binding.readings,[{ref:subject,revision:selectedReading.revision,availability:'available'},{ref:`wiki:${current.file.location.path}`,revision:current.file.revision,availability:'available'}]);
  assert.ok(admitted.binding.sources.some(row=>row.ref===current.source_ref&&row.revision===current.file.revision),'actual owner register provenance retained');
  assert.ok(!('content'in admitted),'native source payload is not copied into the Scene request');
  const fileItem={kind:'page',ref:current.file.location.ref,title:'Actual register file',owner:'display label',scope:'local',provider:'central',sourceLocation:current.file.location,revision:current.file.revision};
  const fileAdmission=await verifyInsertionSource(transport,fileItem);
  assert.equal(fileAdmission.binding.subject_ref,current.file.location.ref);
  assert.equal(fileAdmission.binding.readings[0].revision,current.file.revision);
  await assert.rejects(verifyInsertionSource(transport,{...fileItem,revision:'changed-before-insertion'}),/selected source changed/);
  await assert.rejects(verifyInsertionSource(transport,{...fileItem,ref:'redirected-ref'}),/exact source location/);
  const cancelled=new AbortController();cancelled.abort();
  await assert.rejects(verifyInsertionSource(transport,librarySource,cancelled.signal),/abort/i);
  const projectRegister=await readRegister(transport,'Notes'),projectSubject=projectRegister.spaces[0]?.ref;assert.ok(projectSubject,'native Project register discloses its source space');assert.notEqual(projectSubject,subject,'native root and Project source identities differ');
  const projectReading=await knowledge(transport,'Notes',{action:'read',address:{kind:'wiki',value:projectSubject}});
  const projectAdmission=await verifyInsertionSource(transport,{...librarySource,ref:projectSubject,project:'Notes',address:{kind:'wiki',value:projectSubject},revision:projectReading.revision});
  // Ordinary authored Scene, with an actual unadopted file selected through
  // Central. No Wiki provenance or persisted location is needed to reopen it.
  await mkdir(join(root,'Work','Bare'),{recursive:true});
  const ordinaryPath=join(root,'Work','Bare','note é.txt');
  await writeFile(ordinaryPath,'Actual ordinary file source\n');
  const listed=await listFiles(transport,'Work/Bare',true),ordinary=listed.entries.find(row=>row.name==='note é.txt');assert.ok(ordinary);
  const choice=await verifyInsertionSource(transport,{kind:'page',ref:ordinary.location.ref,title:'Ordinary note',owner:'display',scope:'local',provider:'central',sourceLocation:ordinary.location});
  const expr=async request=>{const result=await kernelOp(transport,{op:'expression',request});assert.ok(!result.error,JSON.stringify(result));assert.equal(result.outcome?.result,'expression');return result.outcome.data.document;};
  const plain=await expr({operation:'create',expression_ref:'expression:ordinary-file-return',title:'Ordinary authored Scene',actor:'human:native-source-return'});
  const plainScene=plain.scenes[0].scene_ref,entityRef=plain.expression_ref+':entity:ordinary-file';
  const inserted=await expr({operation:'edit',expression_ref:plain.expression_ref,expected_revision:plain.revision,actor:'human:native-source-return',changes:[{change:'entity_add',scene_ref:plainScene,entity_ref:entityRef,title:choice.title},{change:'subject_bind',entity_ref:entityRef,binding:choice.binding},{change:'entity_add',scene_ref:plainScene,entity_ref:entityRef+'-wiki',title:admitted.title},{change:'subject_bind',entity_ref:entityRef+'-wiki',binding:admitted.binding},{change:'entity_add',scene_ref:plainScene,entity_ref:entityRef+'-project',title:projectAdmission.title},{change:'subject_bind',entity_ref:entityRef+'-project',binding:projectAdmission.binding}]});
  const ordinaryRequest={ref:choice.binding.subject_ref,subject:{ref:inserted.expression_ref,revision:inserted.revision,sceneRef:plainScene}};
  publishWikiNativeRegisters([{name:'Notes',path:'Work/Notes'}]);
  const reopenedProject=await resolveHostedSource(transport,{...ordinaryRequest,ref:projectSubject});assert.equal(reopenedProject.project,'Notes');assert.deepEqual(reopenedProject.address,{kind:'wiki',value:projectSubject});
  const reopenedWiki=await resolveHostedSource(transport,{...ordinaryRequest,ref:subject});
  assert.deepEqual(reopenedWiki.address,{kind:'wiki',value:subject},'Wiki inserted into an ordinary Scene retains its actual owner register');
  assert.equal(reopenedWiki.returnTo.passageId,plainScene);
  const reopened=await resolveHostedSource(transport,ordinaryRequest);
  assert.deepEqual(reopened.location,ordinary.location,'source ref resolves through owner to exact file without frontend parsing');
  assert.equal(reopened.address,undefined,'ordinary file does not enter Wiki navigation');
  assert.equal(reopened.returnTo.passageId,plainScene);
  assert.deepEqual(await expr({operation:'inspect',expression_ref:inserted.expression_ref}),inserted,'opening source leaves native authored Scene untouched');
  await writeFile(ordinaryPath,'Changed after occurrence insertion\n');
  await assert.rejects(resolveHostedSource(transport,ordinaryRequest),/file source changed/);
  await assert.rejects(resolveHostedSource(transport,{...ordinaryRequest,ref:'outside-scene'}),/no single source/);
  publishWikiNativeRegisters([]);
  const nativeSubject={ref:document.expression_ref,revision:document.revision,sceneRef:scene.scene_ref};
  const source=await resolveHostedSource(transport,{ref:subject,subject:nativeSubject});
  assert.deepEqual(source.address,{kind:'wiki',value:subject});
  assert.equal(source.project,undefined);
  assert.deepEqual(source.returnTo,{place:{ref:document.expression_ref,title:scene.title},passageId:scene.scene_ref});
  const edgeRef='wiki:edge:native-directed',alias='timeline:dated-native-edge';
  const edgeSource=await resolveHostedSource(transport,{ref:alias,subject:nativeSubject,context:{node:{graphNodeId:alias,sourceCoordinates:[edgeRef]},relationField:{subjectGraphNodeId:alias,contextualNodes:[],relationships:[]}}});
  assert.deepEqual(edgeSource.address,{kind:'wiki',value:edgeRef},'Timeline alias opens actual source relation, never derived anchor');
  const destination=await knowledge(transport,edgeSource.project,{action:'read',address:edgeSource.address});
  assert.equal(destination.resource,edgeRef,'destination reads the exact native source rather than transported Timeline metadata');
  await assert.rejects(resolveHostedSource(transport,{ref:alias,subject:nativeSubject,context:{node:{graphNodeId:alias,sourceCoordinates:[edgeRef,subject]}}}),/no single source/);
  await assert.rejects(resolveHostedSource(transport,{ref:alias,subject:nativeSubject,context:{node:{graphNodeId:'another-event',sourceCoordinates:[edgeRef]}}}),/selection changed/);
  await assert.rejects(resolveHostedSource(transport,{ref:'outside-scene',subject:nativeSubject}),/no single source/);
  await assert.rejects(resolveHostedSource(transport,{ref:subject,subject:{...nativeSubject,revision:document.revision+1}}),/revision|changed/i);
  const reading=await wikiSceneRelationReadings({document,scene,current});
  assert.deepEqual(reading.map(row=>row.direction).sort(),[...directions].sort());
  for(const row of reading){assert.equal(row.from_participation_ref,parts[0]);assert.equal(row.to_participation_ref,parts[1]);assert.equal(row.frame_ref,frameRef);assert.equal(document.relations[row.binding_ref].relation.ref,row.relation_ref);}
  publishWikiNativeRegisters([]);
  const resolved=await readWikiSceneTechne(transport,{expression_ref:document.expression_ref,revision:document.revision,scene_ref:scene.scene_ref,facet:'relation-semantics'});
  assert.equal(resolved.schema,'oi.scene-relation-readings/v1');assert.equal(resolved.expression_ref,document.expression_ref);assert.equal(resolved.revision,document.revision);assert.equal(resolved.scene_ref,scene.scene_ref);assert.deepEqual(resolved.relation_readings,reading);
  const compiled=await build({stdin:{contents:"export {nativeInstrumentCanvas} from './researchInstrumentsData.ts';export {kernelDocumentToJourney} from './kernelDocumentBridge.ts';",resolveDir:fileURLToPath(new URL('../expressions-app/field-studies-journeys/src/',import.meta.url)),loader:'ts'},tsconfig:fileURLToPath(new URL('../expressions-app/field-studies-journeys/tsconfig.json',import.meta.url)),bundle:true,platform:'node',format:'esm',write:false,logLevel:'silent'});
  const api=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
  const converted=api.kernelDocumentToJourney(document),sceneId=converted.startSceneId;
  const canvas=api.nativeInstrumentCanvas(converted,sceneId,resolved.relation_readings);
  assert.equal(canvas.edges.length,3);
  for(const row of reading){const shown=canvas.edges.find(edge=>edge.id===row.binding_ref);assert.ok(shown);assert.equal(shown.directionality,{directed:'forward',undirected:'none',bidirectional:'bidirectional'}[row.direction]);assert.equal(shown.style.dashed,false);}
  const unknown=api.nativeInstrumentCanvas(converted,sceneId);assert.ok(unknown.edges.every(edge=>edge.directionality==='none'&&edge.style.dashed),'unresolved source direction is disclosed, not defaulted forward');
  assert.equal(JSON.stringify(document),bytes,'reading changes no native state');
  assert.ok(Object.values(document.relations).every(row=>!('direction'in row)&&!('semantic_direction'in row)),'native binding schema unchanged');
  const stale=structuredClone(current);stale.relations[0].revision++;
  await assert.rejects(wikiSceneRelationReadings({document,scene,current:stale}),/source relation changed/);
  const redirected=structuredClone(document),binding=Object.values(redirected.relations)[0];binding.from_entity_ref=binding.to_entity_ref;
  await assert.rejects(wikiSceneRelationReadings({document:redirected,scene:redirected.scenes.find(row=>row.scene_ref===scene.scene_ref),current}),/another occurrence/,'equal source subjects do not erase participation identity');
  const malformed=structuredClone(current);malformed.relations[0]['aikit.constellation-relation/v1'].direction='incoming';
  await assert.rejects(wikiSceneRelationReadings({document,scene,current:malformed}),/no current supported direction/,'traversal direction is never source semantics');
 }finally{if(child){const stopped=child.exitCode===null?once(child,'exit'):null;try{process.kill(-child.pid,'SIGTERM');}catch{}if(stopped)await stopped;}await rm(scratch,{recursive:true,force:true});}
});
