#!/usr/bin/env python3
"""Capture and verify the real release CLI build inputs; never build in self-test."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import unittest
from datetime import datetime, timezone

REPO = Path(__file__).resolve().parents[2]
ENV_KEYS = ('PATH', 'CARGO_HOME', 'RUSTUP_HOME', 'RUSTUP_TOOLCHAIN', 'CARGO_TARGET_DIR',
            'CARGO_BUILD_JOBS', 'CARGO_INCREMENTAL', 'CARGO_ENCODED_RUSTFLAGS', 'RUSTFLAGS',
            'RUSTC', 'RUSTC_WRAPPER', 'RUSTC_WORKSPACE_WRAPPER', 'RUSTDOCFLAGS', 'CC', 'CXX',
            'AR', 'CFLAGS', 'CXXFLAGS', 'SDKROOT', 'MACOSX_DEPLOYMENT_TARGET',
            'SOURCE_DATE_EPOCH', 'SUITE_BUILD_REVISION')


def require(condition, message):
    if not condition:
        raise ValueError(message)


def canonical(value):
    return json.dumps(value, sort_keys=True, separators=(',', ':'), ensure_ascii=False).encode()


def sha(path):
    with Path(path).open('rb') as stream:
        return hashlib.file_digest(stream, 'sha256').hexdigest()


def file_record(path):
    path = Path(path).absolute()
    require(path.is_file(), f'Source input absent: {path}')
    before = path.stat()
    record = {'path': str(path), 'size_bytes': before.st_size, 'sha256': sha(path)}
    after = path.stat()
    require((before.st_size, before.st_mtime_ns, before.st_ino) ==
            (after.st_size, after.st_mtime_ns, after.st_ino), f'Source raced during capture: {path}')
    if path.is_symlink():
        record['symlink'] = os.readlink(path)
        record['resolved_path'] = str(path.resolve())
    return record


def verify_records(records):
    for record in records:
        require(file_record(record['path']) == record, f'Source bytes changed: {record["path"]}')


def package_inputs(root, require_includes=True):
    """Rust modules/build source and literal include! inputs, without unrelated docs.

    Registry native/build assets are additionally verified from Cargo's complete
    checksum manifest. OUT_DIR includes are generated by the recorded build.
    """
    root = Path(root).absolute()
    inputs = {root / 'Cargo.toml'}
    rust = set((root / 'src').rglob('*.rs')) if (root / 'src').is_dir() else set()
    rust.update(root.glob('*.rs'))
    pending = list(rust)
    seen = set()
    while pending:
        source = pending.pop()
        if source in seen:
            continue
        seen.add(source)
        inputs.add(source)
        text = source.read_text()
        for match in re.finditer(r'\binclude(?:_str|_bytes)?!\s*\(\s*"((?:[^"\\]|\\.)*)"', text):
            value = json.loads('"' + match.group(1) + '"')
            included = (source.parent / value).resolve()
            if not included.is_file() and not require_includes:
                # Published registry archives omit some cfg(test)-only fixtures.
                # Every shipped registry file is independently checked against
                # the locked archive/checksum manifest; an active missing include
                # still fails the real Cargo build, which is required for a basis.
                continue
            require(included.is_file(), f'Literal Rust include absent: {source}: {value}')
            inputs.add(included)
            if included.suffix == '.rs':
                pending.append(included)
        # The manifest-directory form names source input rather than generated output.
        for match in re.finditer(r'include(?:_str|_bytes)?!\s*\(\s*concat!\s*\(\s*env!\s*\(\s*"CARGO_MANIFEST_DIR"\s*\)\s*,\s*"([^"]+)"\s*\)', text):
            included = Path(str(root) + match.group(1)).resolve()
            if not included.is_file() and not require_includes:
                continue
            require(included.is_file(), f'Manifest-relative Rust include absent: {included}')
            inputs.add(included)
    return inputs


def locked_packages(path):
    # Read the small authoritative identity subset without a third-party TOML parser.
    result = []
    for block in Path(path).read_text().split('[[package]]')[1:]:
        item = dict(re.findall(r'^(name|version|source|checksum) = "([^"]+)"$', block, re.M))
        require('name' in item and 'version' in item, 'Malformed Cargo.lock package identity')
        result.append(item)
    require(result, 'Cargo.lock package set is empty')
    return result


def run_read(argv, cwd, env=None):
    result = subprocess.run(argv, cwd=cwd, env=env, check=True, stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE, text=True)
    return result.stdout.strip()


def flag(argv, name, default=None):
    values = []
    for index, token in enumerate(argv):
        if token == name:
            require(index + 1 < len(argv), f'Missing command value: {name}')
            values.append(argv[index + 1])
        elif token.startswith(name + '='):
            values.append(token[len(name) + 1:])
    require(len(values) <= 1, f'Duplicate build option: {name}')
    return values[0] if values else default


def validate_command(command, cwd, artifact):
    require(isinstance(command, list) and all(isinstance(p, str) and p for p in command), 'Build command must be explicit argv')
    require(command[:2] == ['cargo', 'build'] and '--release' in command, 'Only explicit cargo build --release is admitted')
    require('--profile' not in command and not any(p.startswith('--profile=') for p in command), 'Custom Cargo profile is not release evidence')
    manifest = (cwd / flag(command, '--manifest-path', 'Cargo.toml')).resolve()
    require(manifest == (REPO / 'cli/Cargo.toml').resolve(), 'Build must target the actual O:I CLI manifest')
    require(not flag(command, '--target'), 'This receipt records the native Darwin release, not a cross build')
    target = flag(command, '--target-dir')
    require(target is not None, 'Explicit --target-dir is required')
    expected = (cwd / target / 'release/oi').absolute()
    require(expected.resolve() == artifact.resolve() and 'debug' not in artifact.parts, 'Release artifact/target directory mismatch')
    require(not any(p in command for p in ('--tests', '--examples', '--benches', '--all-targets')), 'Only actual release CLI/library compilation is admitted')
    require(not any(p in command for p in ('--lib', '--workspace', '--exclude', '--example', '--test', '--bench')), 'Build may not select another target')
    require(flag(command, '--package', flag(command, '-p', 'oi-cli')) == 'oi-cli', 'Build package must be oi-cli')
    require(flag(command, '--bin', 'oi') == 'oi', 'Build binary must be oi')
    allowed_values = {'--manifest-path', '--target-dir', '--jobs', '-j', '--features', '--package', '-p', '--bin', '--color'}
    allowed_flags = {'--release', '--locked', '--offline', '--frozen', '--all-features', '--no-default-features',
                     '--verbose', '-v', '-vv', '--quiet', '-q'}
    index = 2
    while index < len(command):
        token = command[index]
        if token in allowed_values:
            require(index + 1 < len(command), f'Missing build option value: {token}')
            index += 2
        else:
            require(token in allowed_flags or any(token.startswith(p + '=') for p in allowed_values) or
                    (token.startswith('-j') and token[2:].isdigit()), f'Unsupported release build option: {token}')
            index += 1
    return manifest


def narrow_clean_commands(receipt):
    commands = []
    for git in receipt['git_dependencies']:
        if not git['source_dirty']:
            continue
        owners = [p for p in receipt['dependency_packages'] if
                  (p['source'] or '').startswith('git+') and Path(p['manifest_path']).is_relative_to(git['path'])]
        for package in owners:
            require(package['name'] == 'aikit-core', 'Dirty Git dependency requires a separately reviewed clean aperture')
            commands.append(['cargo', 'clean', '--release', '-p', package['name'],
                             '--manifest-path', flag(receipt['build_command'], '--manifest-path', 'cli/Cargo.toml'),
                             '--target-dir', flag(receipt['build_command'], '--target-dir')])
    return commands


def verify_registry(record):
    root = Path(record['root'])
    checksum_path = root / '.cargo-checksum.json'
    if record['checksum_manifest_sha256'] is not None:
        require(sha(checksum_path) == record['checksum_manifest_sha256'], f'Registry checksum manifest changed: {root}')
        checksum = json.loads(checksum_path.read_bytes())
        require(checksum.get('package') == record['package_checksum'], f'Registry package differs from Cargo.lock: {root}')
        for relative, expected in checksum['files'].items():
            path = root / relative
            require(path.resolve().is_relative_to(root.resolve()) and sha(path) == expected,
                    f'Registry source checksum mismatch: {path}')
    else:
        require(not checksum_path.exists(), f'Registry checksum manifest appeared after capture: {root}')
        archive = Path(record['source_archive'])
        require(sha(archive) == record['package_checksum'], f'Registry archive differs from Cargo.lock: {archive}')
        with tarfile.open(archive, 'r:gz') as stream:
            count = 0
            for member in stream:
                require(member.isdir() or member.isfile(), f'Unsupported registry archive member: {member.name}')
                if not member.isfile():
                    continue
                parts = Path(member.name).parts
                require(parts[0] == root.name and '..' not in parts, f'Uncontained registry archive member: {member.name}')
                path = root.joinpath(*parts[1:])
                require(path.resolve().is_relative_to(root.resolve()) and path.is_file() and path.stat().st_size == member.size,
                        f'Registry source file absent/size changed: {path}')
                with stream.extractfile(member) as content:
                    expected = hashlib.file_digest(content, 'sha256').hexdigest()
                require(sha(path) == expected, f'Registry source differs from locked archive: {path}')
                count += 1
            require(count > 0, f'Registry source archive empty: {archive}')


def source_snapshot(metadata, lock_path, env=None, require_aikit=True):
    packages = locked_packages(lock_path)
    selected = {metadata['resolve']['root']}
    nodes = {n['id']: n for n in metadata['resolve']['nodes']}
    pending = list(selected)
    while pending:
        for dep in nodes[pending.pop()]['deps']:
            # Tests/dev-only dependencies are not part of cargo build --release.
            if any(kind['kind'] in (None, 'build') for kind in dep['dep_kinds']) and dep['pkg'] not in selected:
                selected.add(dep['pkg'])
                pending.append(dep['pkg'])
    paths = {lock_path}
    dependencies, registries, git_roots = [], [], {}
    for package in metadata['packages']:
        if package['id'] not in selected:
            continue
        manifest = Path(package['manifest_path'])
        root = manifest.parent
        paths.update(package_inputs(root, require_includes=not (package['source'] or '').startswith('registry+')))
        for ancestor in root.parents:
            inherited_manifest = ancestor / 'Cargo.toml'
            if inherited_manifest.is_file():
                paths.add(inherited_manifest)
            if (ancestor / '.git').exists():
                break
        # Nonstandard native target roots, if an actual owner declares them.
        for target in package['targets']:
            if set(target['kind']) & {'bin', 'lib', 'rlib', 'proc-macro', 'custom-build'}:
                source = Path(target['src_path'])
                paths.add(source)
                if source.parent != root:
                    paths.update(source.parent.rglob('*.rs'))
        identity = {'name': package['name'], 'version': package['version'], 'source': package['source'],
                    'manifest_path': str(manifest), 'features': nodes[package['id']]['features']}
        locked = next((p for p in packages if p['name'] == package['name'] and
                       p['version'] == package['version'] and p.get('source') == package['source']), None)
        require(locked is not None, f'Resolved package absent from actual Cargo.lock: {package["id"]}')
        identity['lock_identity'] = locked
        source = package['source'] or ''
        if source.startswith('registry+'):
            checksum = root / '.cargo-checksum.json'
            registry = {'root': str(root), 'package_checksum': locked['checksum'],
                        'checksum_manifest_sha256': sha(checksum) if checksum.is_file() else None}
            if not checksum.is_file():
                archive = root.parents[2] / 'cache' / root.parent.name / (root.name + '.crate')
                require(archive.is_file(), f'Registry checksum manifest and locked source archive both absent: {root}')
                registry['source_archive'] = str(archive)
                paths.add(archive)
            verify_registry(registry)
            registries.append(registry)
            if checksum.is_file():
                paths.add(checksum)
        elif source.startswith('git+'):
            revision = source.rsplit('#', 1)[-1]
            actual = run_read(['git', 'rev-parse', 'HEAD'], root)
            require(actual == revision, f'Git dependency checkout differs from lock: {root}')
            git_root = run_read(['git', 'rev-parse', '--show-toplevel'], root)
            git_roots[git_root] = {'path': git_root, 'source_revision': actual,
                                   'source_dirty': bool(run_read(['git', 'status', '--porcelain'], root))}
        dependencies.append(identity)
    require(any(d['name'] == 'oi-cradle-kernel' for d in dependencies), 'Actual CLI kernel dependency absent')
    if require_aikit:
        require(any(d['name'] == 'aikit-core' and (d['source'] or '').startswith('git+') for d in dependencies), 'Actual pinned AIKit dependency absent')
    # Config/toolchain files can alter compilation without editing Rust sources.
    for directory in [REPO, *REPO.parents]:
        for name in ('.cargo/config', '.cargo/config.toml', 'rust-toolchain', 'rust-toolchain.toml'):
            path = directory / name
            if path.is_file():
                paths.add(path)
    for name in ('config', 'config.toml'):
        path = Path((env or os.environ).get('CARGO_HOME', Path.home() / '.cargo')) / name
        if path.is_file():
            paths.add(path)
    records = [file_record(path) for path in sorted(paths)]
    return {'source_files': records, 'source_tree_sha256': hashlib.sha256(canonical(records)).hexdigest(),
            'dependency_packages': sorted(dependencies, key=lambda p: (p['name'], p['version'], p['source'] or '')),
            'registry_sources': sorted(registries, key=lambda p: p['root']),
            'git_dependencies': sorted(git_roots.values(), key=lambda p: p['path'])}


def write_new(path, value):
    with Path(path).open('x') as stream:
        json.dump(value, stream, indent=2, sort_keys=True, ensure_ascii=False)
        stream.write('\n')


def build_environment(overrides):
    env = os.environ.copy()
    for entry in overrides:
        key, separator, value = entry.partition('=')
        require(separator and key in ENV_KEYS, f'Unsupported explicit build environment: {key}')
        env[key] = value
    return env, {key: env.get(key) for key in ENV_KEYS}


def capture(args):
    command = json.loads(args.command_json)
    cwd, artifact = Path(args.cwd).absolute(), Path(args.artifact).absolute()
    manifest = validate_command(command, cwd, artifact)
    env, recorded_env = build_environment(args.env)
    tools = {}
    for tool in ('cargo', 'rustc'):
        path = Path(shutil.which(tool, path=env.get('PATH')) or '')
        require(path.is_file(), f'Actual build tool absent: {tool}')
        tools[tool] = {'path': str(path), 'sha256': sha(path),
                       'version': run_read([str(path), '-vV'], cwd, env)}
        selected = Path(run_read(['rustup', 'which', tool], cwd, env))
        require(selected.is_file(), f'Selected native build tool absent: {tool}')
        require(not (tool == 'rustc' and env.get('RUSTC')), 'Custom RUSTC needs a recorded selected-tool adapter')
        selected_version = run_read([str(selected), '-vV'], cwd, env)
        require(selected_version == tools[tool]['version'], f'Dispatched and selected build tools differ: {tool}')
        tools[tool]['selected_executable'] = file_record(selected)
    host = next(line.removeprefix('host: ') for line in tools['rustc']['version'].splitlines() if line.startswith('host: '))
    metadata_command = ['cargo', 'metadata', '--locked', '--offline', '--format-version', '1',
                        '--filter-platform', host, '--manifest-path', str(manifest)]
    for option in ('--all-features', '--no-default-features'):
        if option in command:
            metadata_command.append(option)
    features = flag(command, '--features')
    if features:
        metadata_command += ['--features', features]
    raw_metadata = run_read(metadata_command, cwd, env)
    metadata = json.loads(raw_metadata)
    require(metadata['resolve']['root'] is not None, 'CLI dependency resolution has no root')
    lock = Path(metadata['workspace_root']) / 'Cargo.lock'
    snapshot = source_snapshot(metadata, lock, env)
    result = {'schema': 'oi.cli-build-capture/v1', 'captured_at': datetime.now(timezone.utc).isoformat(),
              'source_root': str(REPO), 'source_revision': run_read(['git', 'rev-parse', 'HEAD'], REPO),
              'source_dirty': bool(run_read(['git', 'status', '--porcelain'], REPO)),
              'cwd': str(cwd), 'artifact_path': str(artifact), 'build_command': command,
              'build_environment': recorded_env, 'build_environment_overrides': args.env, 'tools': tools,
              'producer': file_record(__file__),
              'cargo_metadata_encoding': 'canonical-json/v1',
              'cargo_metadata_sha256': hashlib.sha256(canonical(metadata)).hexdigest(),
              'cargo_metadata': metadata, 'cargo_lock_path': str(lock), **snapshot}
    result['required_narrow_clean_commands'] = narrow_clean_commands(result)
    write_new(args.capture, result)
    print(json.dumps({'capture': str(Path(args.capture).absolute()), 'sha256': sha(args.capture),
                      'source_tree_sha256': result['source_tree_sha256'], 'source_files': len(result['source_files'])}))


def verify_capture(receipt, env):
    require(receipt['schema'] == 'oi.cli-build-capture/v1', 'Expected actual CLI pre-build capture')
    require({key: env.get(key) for key in ENV_KEYS} == receipt['build_environment'], 'Build environment changed since capture')
    require(run_read(['git', 'rev-parse', 'HEAD'], REPO) == receipt['source_revision'], 'CLI source revision changed since capture')
    require(hashlib.sha256(canonical(receipt['cargo_metadata'])).hexdigest() == receipt['cargo_metadata_sha256'], 'Recorded Cargo metadata changed')
    require(file_record(__file__) == receipt['producer'], 'Build receipt producer changed since capture')
    require(narrow_clean_commands(receipt) == receipt['required_narrow_clean_commands'], 'Dirty dependency clean command changed')
    for tool, record in receipt['tools'].items():
        require(shutil.which(tool, path=env.get('PATH')) == record['path'] and sha(record['path']) == record['sha256'] and
                run_read([record['path'], '-vV'], receipt['cwd'], env) == record['version'], f'Build tool changed: {tool}')
        selected = Path(run_read(['rustup', 'which', tool], receipt['cwd'], env))
        require(file_record(selected) == record['selected_executable'] and run_read([str(selected), '-vV'], receipt['cwd'], env) == record['version'], f'Selected build tool changed: {tool}')
    actual = source_snapshot(receipt['cargo_metadata'], Path(receipt['cargo_lock_path']), env)
    for key in ('source_files', 'source_tree_sha256', 'dependency_packages', 'registry_sources', 'git_dependencies'):
        require(actual[key] == receipt[key], f'CLI compile inputs changed since capture: {key}')


def build(args):
    capture_path = Path(args.capture).absolute()
    require(not Path(args.output).exists(), 'Refusing to overwrite a build basis')
    receipt = json.loads(capture_path.read_bytes())
    capture_sha = sha(capture_path)
    env, _ = build_environment(receipt['build_environment_overrides'])
    artifact, cwd = Path(receipt['artifact_path']), Path(receipt['cwd'])
    validate_command(receipt['build_command'], cwd, artifact)
    verify_capture(receipt, env)
    started = datetime.now(timezone.utc).isoformat()
    clean_results = []
    # Only the approved dirty pinned AIKit package, in this exact release target.
    # Invoke build only after the other release build has exited; capture/verify
    # never clean anything and never start a build.
    for command in receipt['required_narrow_clean_commands']:
        cleaned = subprocess.run(command, cwd=cwd, env=env)
        clean_results.append({'command': command, 'cwd': str(cwd), 'exit_code': cleaned.returncode})
        require(cleaned.returncode == 0, f'Narrow dependency clean failed: exit {cleaned.returncode}')
    # This is the only build call. Never reached by capture, verify, or self-test.
    result = subprocess.run(receipt['build_command'], cwd=cwd, env=env)
    require(result.returncode == 0, f'Recorded release build failed: exit {result.returncode}')
    verify_capture(receipt, env)
    require(sha(capture_path) == capture_sha, 'Pre-build capture changed during the build')
    with artifact.open('rb') as stream:
        header = stream.read(8)
    require(header[:4] == bytes.fromhex('cffaedfe') and header[4:8] == bytes.fromhex('0c000001') and
            os.access(artifact, os.X_OK), 'Actual release artifact is not executable Darwin arm64 Mach-O')
    basis = {key: receipt[key] for key in ('source_root', 'source_revision', 'source_dirty', 'source_tree_sha256',
                                         'source_files', 'dependency_packages', 'registry_sources', 'git_dependencies', 'tools', 'build_environment')}
    basis.update({'schema': 'oi.cli-build-basis/v1', 'producer': receipt['producer'], 'capture': {'path': str(capture_path), 'sha256': capture_sha},
                  'narrow_dependency_clean': clean_results,
                  'verification': {'source_inputs_unchanged_before_and_after': True, 'build_exit_code': result.returncode,
                                   'started_at': started, 'completed_at': datetime.now(timezone.utc).isoformat()},
                  'artifact': {'path': str(artifact), 'sha256': sha(artifact), 'size_bytes': artifact.stat().st_size,
                               'profile': 'release', 'build_command': receipt['build_command'], 'cwd': str(cwd)}})
    write_new(args.output, basis)
    print(json.dumps({'basis': str(Path(args.output).absolute()), 'sha256': sha(args.output), 'artifact': basis['artifact']}))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest='operation', required=True)
    before = sub.add_parser('capture', help='Read inputs before the final release build; does not build')
    before.add_argument('--command-json', required=True)
    before.add_argument('--artifact', required=True)
    before.add_argument('--cwd', default=str(REPO))
    before.add_argument('--env', action='append', default=[])
    before.add_argument('--capture', required=True)
    after = sub.add_parser('build', help='Verify capture, execute its exact release argv, verify again, emit basis')
    after.add_argument('--capture', required=True)
    after.add_argument('--output', required=True)
    check = sub.add_parser('verify', help='Verify captured bytes/environment without building')
    check.add_argument('--capture', required=True)
    sub.add_parser('self-test', help='Real source/include/lock/filesystem checks; never builds')
    args = parser.parse_args()
    if args.operation == 'self-test':
        unittest.main(argv=[__file__])
    elif args.operation == 'capture':
        capture(args)
    elif args.operation == 'build':
        build(args)
    else:
        receipt = json.loads(Path(args.capture).read_bytes())
        env, _ = build_environment(receipt['build_environment_overrides'])
        verify_capture(receipt, env)
        print(json.dumps({'verified': str(Path(args.capture).absolute()), 'source_tree_sha256': receipt['source_tree_sha256']}))


class RealInputTests(unittest.TestCase):
    def test_actual_cli_includes_are_captured(self):
        inputs = package_inputs(REPO / 'cli')
        self.assertIn(REPO / 'cli/src/main.rs', inputs)
        self.assertIn(REPO / 'cli/build.rs', inputs)
        self.assertIn(REPO / 'surfaces.json', inputs)
        self.assertIn(REPO / 'desktop/install-footprint.json', inputs)
        self.assertNotIn(REPO / 'packages/live-shell/src/runtime.rs', inputs)

    def test_actual_kernel_json_include_is_captured(self):
        self.assertIn(REPO / 'desktop/cradle/kernel/src/decision_sites.json',
                      package_inputs(REPO / 'desktop/cradle/kernel'))

    def test_changed_actual_source_copy_is_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / 'main.rs'
            shutil.copyfile(REPO / 'cli/src/main.rs', path)
            before = file_record(path)
            self.assertEqual(before, file_record(path))
            path.write_bytes(path.read_bytes() + b'\n// changed input\n')
            with self.assertRaisesRegex(ValueError, 'Source bytes changed'):
                verify_records([before])

    def test_actual_lock_retains_exact_aikit_pin(self):
        packages = locked_packages(REPO / 'cli/Cargo.lock')
        package = next(p for p in packages if p['name'] == 'aikit-core')
        self.assertEqual(package['source'], 'git+https://github.com/EpiLogos/ai-kit?rev=e53801d#e53801d86cf4b3eec3d1b3c28528f779180efa3a')

    def test_debug_or_unrelated_build_command_rejected(self):
        artifact = Path('/tmp/oi-receipt-check/release/oi')
        with self.assertRaises(ValueError):
            validate_command(['cargo', 'build', '--manifest-path', 'cli/Cargo.toml'], REPO, artifact)
        with self.assertRaises(ValueError):
            validate_command(['/bin/true', '--release'], REPO, artifact)

    def test_actual_manifest_cannot_select_another_binary(self):
        command = ['cargo', 'build', '--release', '--manifest-path', 'cli/Cargo.toml',
                   '--target-dir', '/tmp/oi-receipt-check', '--package', 'oi-conformance']
        with self.assertRaises(ValueError):
            validate_command(command, REPO, Path('/tmp/oi-receipt-check/release/oi'))

    def test_locked_registry_source_mutation_is_rejected(self):
        package = next(p for p in locked_packages(REPO / 'cli/Cargo.lock') if p['name'] == 'ahash')
        original = Path.home() / '.cargo/registry/src/index.crates.io-1949cf8c6b5b557f' / ('ahash-' + package['version'])
        archive = original.parents[2] / 'cache' / original.parent.name / (original.name + '.crate')
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory) / original.name
            shutil.copytree(original, root)
            record = {'root': str(root), 'package_checksum': package['checksum'],
                      'checksum_manifest_sha256': None, 'source_archive': str(archive)}
            verify_registry(record)
            source = root / 'src/lib.rs'
            source.write_bytes(source.read_bytes() + b'\n// changed installed source\n')
            with self.assertRaisesRegex(ValueError, 'Registry source'):
                verify_registry(record)


if __name__ == '__main__':
    try:
        main()
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        print(str(error), file=sys.stderr)
        sys.exit(1)
