/** Generated by scripts/build-themes.mjs from themes/upstream/ — do not edit; rerun the script. */
/** The theme library index: what Settings → Visuals renders. Each entry
 * carries its preview colours; the values themselves live in themes.css. */
/** @typedef {{id: string, name: string, appearance: "light" | "dark",
 *             preview: {ground: string, ink: string, accent: string, strip: string[]},
 *             source: {name: string, repo: string, license: string}}} ThemeIndexEntry */
/** @type {ThemeIndexEntry[]} */
export const THEMES = [
  {
    "id": "catppuccin-mocha",
    "name": "Catppuccin Mocha",
    "appearance": "dark",
    "preview": {
      "ground": "#1e1e2e",
      "ink": "#cdd6f4",
      "accent": "#cba6f7",
      "strip": [
        "#cba6f7",
        "#a6e3a1",
        "#89b4fa"
      ]
    },
    "source": {
      "name": "Catppuccin Mocha",
      "repo": "catppuccin/vscode",
      "license": "MIT"
    }
  },
  {
    "id": "dracula-dark",
    "name": "Dracula",
    "appearance": "dark",
    "preview": {
      "ground": "#282a36",
      "ink": "#f8f8f2",
      "accent": "#6272a4",
      "strip": [
        "#ff79c6",
        "#f8f8f2",
        "#ffb86c"
      ]
    },
    "source": {
      "name": "Dracula",
      "repo": "dracula/visual-studio-code",
      "license": "MIT"
    }
  },
  {
    "id": "night-owl-dark",
    "name": "Night Owl",
    "appearance": "dark",
    "preview": {
      "ground": "#011627",
      "ink": "#d6deeb",
      "accent": "#122d42",
      "strip": [
        "#c792ea",
        "#ecc48d",
        "#5f7e97"
      ]
    },
    "source": {
      "name": "Night Owl",
      "repo": "sdras/night-owl-vscode-theme",
      "license": "MIT"
    }
  },
  {
    "id": "nord-dark",
    "name": "Nord",
    "appearance": "dark",
    "preview": {
      "ground": "#2e3440",
      "ink": "#d8dee9",
      "accent": "#3b4252",
      "strip": [
        "#81a1c1",
        "#a3be8c",
        "#8fbcbb"
      ]
    },
    "source": {
      "name": "Nord",
      "repo": "arcticicestudio/nord-visual-studio-code",
      "license": "MIT"
    }
  },
  {
    "id": "one-dark-pro",
    "name": "One Dark Pro",
    "appearance": "dark",
    "preview": {
      "ground": "#282c34",
      "ink": "#abb2bf",
      "accent": "#3e4452",
      "strip": [
        "#c678dd",
        "#98c379",
        "#e06c75"
      ]
    },
    "source": {
      "name": "One Dark Pro",
      "repo": "Binaryify/OneDark-Pro",
      "license": "MIT"
    }
  },
  {
    "id": "tokyo-night-dark",
    "name": "Tokyo Night",
    "appearance": "dark",
    "preview": {
      "ground": "#1a1b26",
      "ink": "#a9b1d6",
      "accent": "#262838",
      "strip": [
        "#bb9af7",
        "#9ece6a",
        "#de5971"
      ]
    },
    "source": {
      "name": "Tokyo Night",
      "repo": "tokyo-night/tokyo-night-vscode-theme",
      "license": "MIT"
    }
  },
  {
    "id": "light-plus",
    "name": "Light Plus",
    "appearance": "light",
    "preview": {
      "ground": "#ffffff",
      "ink": "#000000",
      "accent": "#1f1f1f",
      "strip": [
        "#0000ff",
        "#a31515",
        "#267f99"
      ]
    },
    "source": {
      "name": "Light Plus",
      "repo": "microsoft/vscode",
      "license": "MIT"
    }
  },
  {
    "id": "quiet-light",
    "name": "Quiet Light",
    "appearance": "light",
    "preview": {
      "ground": "#f5f5f5",
      "ink": "#3b3b3b",
      "accent": "#9769dc",
      "strip": [
        "#4b69c6",
        "#aaaaaa",
        "#4b69c6"
      ]
    },
    "source": {
      "name": "Quiet Light",
      "repo": "microsoft/vscode",
      "license": "MIT"
    }
  },
  {
    "id": "solarized-light",
    "name": "Solarized Light",
    "appearance": "light",
    "preview": {
      "ground": "#fdf6e3",
      "ink": "#657b83",
      "accent": "#b49471",
      "strip": [
        "#586e75",
        "#2aa198",
        "#268bd2"
      ]
    },
    "source": {
      "name": "Solarized Light",
      "repo": "microsoft/vscode",
      "license": "MIT"
    }
  }
];
